### ISSUE TITLE
Log format no longer compatible with filebeat coredns plugin (timestamp missing)

### ISSUE THREAD

**Issue by DatanoiseTV** [miekg/coredns#4883]
Unfortunately with the commit 5ef59595ddda59b9401cc6e25e9540d0464ccd1b the timestamp from the log file is removed. Therefore the filebeat coredns plugin cannot parse the loglines.

**Comment by chrisohaver** [comment]
See https://github.com/coredns/coredns/issues/3211#issuecomment-645890663

**Comment by DatanoiseTV** [comment]
How am I supposed to log to Kibana in that situation? The plugin is still included with Kibana but fails silently. I think it should be an optional starup flag that allows to use timestamps in log files. Otherwise there is not much of a benefit "log" logging to a file.

**Comment by yongtang** [comment]
> Therefore the filebeat coredns plugin cannot parse the loglines.

@DatanoiseTV From the above I think that means filebeat itself will need to be updated? Can you open an issue with filebeat instead?
