### ISSUE TITLE
when endpoints pod ip changed, the cache of coredns will refresh actively?

### ISSUE THREAD

**Issue by beastpu** [miekg/coredns#4885]
i know coredns watch apiserver to monitor changes of resources, such as endpoints, service....
Coredns cache ttl is 30s, If the pod ip changes , coredns may get old ip address. i want to knows if coredns can refresh cache actively?

my project use coredns as service discovery by headless service, How can I ensure data consistency  when pod is updated?

**Comment by chrisohaver** [comment]
> Coredns caches 30s records by default.

In the default _Kubernetes_ deployment of CoreDNS, CoreDNS is configured to cache for a _maximum_ of 30s.  If the TTL of a record to be cached is < 30s, then it will cache it for the length of the shorter TTL.  The TTL for Kubernetes DNS records defaults to 5, but can be configured.  Therefore Kubernetes dns records are cached for 5 seconds by default.

> If the pod ip changes during caching, crondns will watch apiserver to refresh the content in the cache.

No. The kubernetes plugin watches the API server for changes and updates, but the prior record will remain in the cache plugin's response cache until the TTL expires.  That said, there is no performance need for the cache plugin to cache the Kubernetes records. The kubernetes plugin already maintains a separate API controller cache of services and endpoints objects, so the responses can be synthesized very quickly.  If you don't want the cache plugin to cache Kubernetes records, the are a few different options, each with unique drawbacks (which prevent adopting them as the k8s default)...
* You can disable the cache plugin.  This would also disable caching upstream responses.
* You can set TTL to 0 for Kubernetes records.  This should prevent Kubernetes records ever being retrieved from cache, but could cause problems for caching resolvers.
* You can disable the cache plugin for just Kubernetes by breaking the kubernetes plugin out into a separate server block in the Corefile, authoritative for the Kubernetes cluster's zones.  To do this properly, you need to know the subnet ranges for your services and pods to you can properly declare the cluster's reverse zones - which means they need to be static.
* You can disable the cache plugin for just Kubernetes by creating a new server block with cache and forward to upstreams, listening to a different port (e.g. 5300). In the original server block, remove cache, and alter forward to point to the new server (e.g. 127.0.0.1:5300).  This has the disadvantage of adding an extra hop to each upstream query (more work).

**Comment by beastpu** [comment]
Thank you for your answer
