### ISSUE TITLE
k8s_external returning pod IPs for ns1.dns AAAA records instead of service IP

### ISSUE THREAD

**Issue by baconwaifu** [miekg/coredns#4887]
**What happened**:
k8s_external returns pod IPs for ns1.dns when no Load balancer IP is available

**What you expected to happen**:
k8s_external returns the service's (in this config, routable) service IP address when no LB IP exists

**How to reproduce it (as minimally and precisely as possible)**:
`dig ns1.dns.<k8s_external zone> @<kube-dns service> AAAA` with service type set to ClusterIP (in an IPv6 cluster?)

**Anything else we need to know?**:
Untested on IPv4 as cluster in question is IPv6 only.  
Behavior resolved as soon as type was changed to LoadBalancer to allocate an LB IP

**Environment**:

- the version of CoreDNS: `coredns:1.8.4`
- Corefile: one that uses `k8s_external`
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Debian buster under kubeadm-k8s
- Others: kube-dns configured without a LoadBalancer IP address (now fixed, but this is about the unexpected behavior of `externalAddrFunc` when no Ingress or LB exists)

**Comment by chrisohaver** [comment]
> **What happened**: _k8s_external_ returns pod IPs for ns1.dns when no Load balancer IP is available

This part is a bug. The most correct result would be to return an empty answer when there is no external IP (empty additional section).

> **What you expected to happen**: _k8s_external_ returns the service's (in this config, routable) service IP address when no LB IP exists

This expectation is not correct. _k8s_external_ intentionally does not return ClusterIPs, because in these IPs _typically_ are not routable outside the cluster, and would be meaningless to return to an external resolver.

**Comment by chrisohaver** [comment]
Not stale: open PR to close this #4891.
