### ISSUE TITLE
plugin/route53 blocking reload/restart

### ISSUE THREAD

**Issue by rnsc** [miekg/coredns#4894]
**What happened**:

Health and readiness endpoints are unresponsive when reloading a config with a few hundreds AWS Route53 zones.
It takes 5 minutes for CoreDNS to start (after a stop), all the while no health checks are responding, nor prometheus endpoints, and nothing can be served until all the AWS Route53 zones are fully loaded.

So, I have more than 500 AWS Route 53 hosted zones configured into CoreDNS.
The config also has a `.` default with a forward config to external DNS.
Each zone is configured with `ready` and `prometheus`.

My AWS hosted zones definition is not in the Corefile, but is imported with a simple `import`.

A start, or reload of the config always takes around 5 minutes.

Start:
```bash
Sep 28 11:20:27 systemd[1]: Started CoreDNS DNS server.
Sep 28 11:25:22 coredns[3734616]: .:53
```

Reload:
```bash
Sep 28 11:50:56 systemd[1]: Reloading CoreDNS DNS server.
Sep 28 11:50:56 coredns[3734616]: [INFO] SIGUSR1: Reloading
Sep 28 11:50:56 coredns[3734616]: [INFO] Reloading
Sep 28 11:50:56 systemd[1]: Reloaded CoreDNS DNS server.
Sep 28 11:55:44 coredns[3734616]: [INFO] Reloading complete
```

**What you expected to happen**:

I would at least expect the health/ready endpoints to answer something rather than not listening at all.
I understand that the DNS server itself is not available until all zones are loaded. Upon reload, the DNS server is still up and replies to requests properly, even if the health/ready endpoints are dead.
I guess it's also related, if I do a `systemctl reload coredns` while a start/reload is happening, systemd just times out on waiting and kills the process. So there's a thread locking the main process?

**How to reproduce it (as minimally and precisely as possible)**:

I pasted my Corefile below, the imported config is just 570 zones with the route53 plugin defined in each of them.
I'm provisioning them with Ansible and have a randomised refresh to avoid throttling on the AWS API.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: `CoreDNS-1.8.4`
- Corefile: 
```
. {
  errors
  health
  ready
  prometheus :9153
  cache 600
  minimal
  forward . 8.8.8.8 8.8.4.4
}

import aws-zones.config
```
- logs, if applicable: (see above)
- OS (e.g: `cat /etc/os-release`): 
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Others:

**Comment by chrisohaver** [comment]
I think the main issue here is that _route53_ establishes a connection in line during setup.  This is similar to the concern raised in #4601, where the _azure_ plugin does the same.  If establishing the connection is done in a go routine, the server can start serving other plugins more immediately.  Some plugins connect to outside resources in this way (e.g. _kubernetes_), although I think most do not.

**Comment by rnsc** [comment]
Hey @chrisohaver , thanks for linking that other issues, I would have thought it was in the "core" of the CoreDNS rather than in the plugin itself.
Are all the plugins using the same logic then? I'll check out the route53 plugin's code (contributing is probably out of my league though)!

**Comment by rnsc** [comment]
@chrisohaver I also noticed that during start, if there's throttling on the AWS Route 53 API, CoreDNS just exits. Should I open another issue for that? Or would fixing the above solve that issue too?

**Comment by chrisohaver** [comment]
> @chrisohaver I also noticed that during start, if there's throttling on the AWS Route 53 API, CoreDNS just exits. Should I open another issue for that? Or would fixing the above solve that issue too?

Sounds like maybe coredns is timing out connecting to route53. There would be an error message in the log if so.  This is also close to the issue raised in #4601, in that a connection failure causes coredns not to start. Putting the connection attempt in a retry loop in a go routine would address that.

**Comment by rnsc** [comment]
> > @chrisohaver I also noticed that during start, if there's throttling on the AWS Route 53 API, CoreDNS just exits. Should I open another issue for that? Or would fixing the above solve that issue too?
> 
> Sounds like maybe coredns is timing out connecting to route53. There would be an error message in the log if so. This is also close to the issue raised in #4601, in that a connection failure causes coredns not to start. Putting the connection attempt in a retry loop in a go routine would address that.

I detailed the issue here: https://github.com/coredns/coredns/issues/4899
It's not a timeout issue, but a throttling issue in my case when running more than one instance with a heavy config, I have an updated code locally for that specific issue though

**Comment by chrisohaver** [comment]
OK, then it sounds like #4899 is another symptom of the same underlying cause, that the connections are made inline with setup.  i.e. Putting the connection attempt in a retry loop in a go routine would address both issues.
