### ISSUE TITLE
1.8.6 Release Tracking Issue

### ISSUE THREAD

**Issue by chrisohaver** [miekg/coredns#4896]
Issue for tracking 1.8.6 release.

- #4895
- #4884

**Comment by chrisohaver** [comment]
@miekg, @yongtang

I think we should do a quick release to fix #4881. 
WDYT?  Or would you prefer to let the current release soak a little longer to see if any other bugs shake out?

**Comment by miekg** [comment]
No, it's fine to release. We can just push one out. Should have some time
this weekend.

**Comment by justindavies** [comment]
Hi, is there an update on the 1.8.6 release?

**Comment by yongtang** [comment]
Updated the release note in #4909 to prepare for a release.

**Comment by chrisohaver** [comment]
OK to release today?

**Comment by yongtang** [comment]
Let's give it a try.

**Comment by chrisohaver** [comment]
lovely - drone appears to have docker issues again, related to the recent docker `--platform` change #4897.

**Comment by chrisohaver** [comment]
So - I guess we need to revert that and release 1.8.7 ?

**Comment by chrisohaver** [comment]
> So - I guess we need to revert that and release 1.8.7 ?

Actually - it looks like the [docker release](https://github.com/coredns/release/blob/master/docker-coredns) always uses latest master Makefiles/Dockerfile... so we don't need to release 1.8.7.

**Comment by miekg** [comment]
Yeah!
I'll tweet and update coredns.io tomorrow
