### ISSUE TITLE
continuous benchmarking for CoreDNS

### ISSUE THREAD

**Issue by odeke-em** [miekg/coredns#4906]
**What would you like to be added**:
Kindly presenting to y'all "Bencher"  https://bencher.orijtech.com/ which is available from the GitHub marketplace per https://github.com/marketplace/gobencher

 
**Why is this needed**:
CoreDNS is a critical and core infrastructure that needs to always be performant; Performance issues can turn out to be security issues. Just like running tests on every single commit/PR, performance benchmarking is an important practice. Unfortunately for Go, benchmarking is very cumbersome and requires:
* setting up quiet machines with nothing running on them -- provisioning these by every single contributor is unrealistic
* running benchmarks and collecting results before and after a change -- ergonomically cumbersome and a huge time sink
* running each benchmark at least 10 times or so with -count=10 to get stable results -- time consuming and not known by many people
* summarize and interpret the results -- hard to do

Bencher does all that heavy lifting for you, and runs just as fast or even faster than the CI tests. We provide a GitHub check that'll inform you if it regressed or not, and then a detailed view if you need to examine benchmarks like at https://dashboard.github.orijtech.com/ or say https://dashboard.github.orijtech.com/graphs?repo=https%3A%2F%2Fgithub.com%2Fent%2Fent.git or https://dashboard.github.orijtech.com/benchmark/28adf5649e194532b2401f7a4547f7ff

Thank you! Kindly cc-ing my colleagues @kirbyquerby @cuonglm

Please try it out and let us know what you think.

**Comment by miekg** [comment]
Looks nice. It executes Benchmark functions? Does it use a VM? 

Real-world DNS benchmarking would require at least 3 bare-metal machines (sender, receivers, measurer) and good networking, to actually say something sane

**Comment by odeke-em** [comment]
> Looks nice. It executes Benchmark functions? Does it use a VM? 
> 
> 
> 
> Real-world DNS benchmarking would require at least 3 bare-metal machines (sender, receivers, measurer) and good networking, to actually say something sane

Thank you @miekg! Yes it executes Benchmark* functions as Go's testing package provides. Yes, it uses VMs but quiet machines running exactly only the target benchmarks, and with CPU scaling turned off as well as performance locks on, and we run them multiple times (-count=10) to reduce variance. We plan on using physical machines in the near future, and we can then dedicate resources to help in this thorough benchmarking. However, for now the current setup can bring y'all good utility in performance changes per code commit.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns] continuous be..." ]
>Thank you @miekg! Yes, it uses VMs but quiet machines running exactly only the
>target benchmarks, and with CPU scaling turned off as well as performance locks
>on, and we run them multiple times (-count=10) to reduce variance. We plan on
>using physical machines in the near future, and we can then dedicate resources
>to help in this thorough benchmarking. However, for now the current setup can
>bring y'all good utility in performance changes per code commit.

thanks, yes very useful. I tried building something simular years back with prometheus
metrics, but setting it up to work per pull request was too hard.

Even benchmark tests are usually micro benching a thing, this is still useful.

**Comment by odeke-em** [comment]
> [ Quoting ***@***.***> in "Re: [coredns/coredns] continuous be..." ]
> >Thank you @miekg! Yes, it uses VMs but quiet machines running exactly only the
> >target benchmarks, and with CPU scaling turned off as well as performance locks
> >on, and we run them multiple times (-count=10) to reduce variance. We plan on
> >using physical machines in the near future, and we can then dedicate resources
> >to help in this thorough benchmarking. However, for now the current setup can
> >bring y'all good utility in performance changes per code commit.
> 
> thanks, yes very useful. I tried building something simular years back with prometheus
> metrics, but setting it up to work per pull request was too hard.
> 
> Even benchmark tests are usually micro benching a thing, this is still useful.
> 


Great @miekg, you can get benchmarks up and running in less than 1 minute by visiting https://github.com/marketplace/gobencher and after you've added it, any subsequent Go related commits and PRs will automatically be benchmarked and with time you'll see progressions. It'll also have a GitHub check in which we'll determine for you what regressed or not, so you don't have to sweat with interpreting. If you need to tweak configurations for judging regressions or improvements, please see https://bencher.orijtech.com/configuration/

We look forward to serving CoreDNS and we shall work on helping y'all identify flakes or even help with improving performance. Thank you @miekg!

**Comment by miekg** [comment]
I tried installing, but I don't understand why it needs 'Read and write access to checks and pull requests', so I stopped the install

**Comment by odeke-em** [comment]
> I tried installing, but I don't understand why it needs 'Read and write access to checks and pull requests', so I stopped the install

@miekg it uses those permissions so that it can run per PR and set the status of the result if are no changes, improvements or regressions as a GitHub check for example per ![](https://bencher.orijtech.com/images/gohugo-checks.png)
For an end to end walk through see https://bencher.orijtech.com/perfclinic/sliceupdate/

Otherwise there wouldn't be a non-invasive way to show you the result of the benchmark run, we don't want to comment on every PR as that would spam and annoy users, yet we want to provide a link to get the status of each benchmark. The remedy to this is using the GitHub checks API.

**Comment by chrisohaver** [comment]
At a glance, that doesn't seem like it should need _write_ access to PRs.

**Comment by kirbyquerby** [comment]
As some background, bencher originally used the pull request write access to comment a link to the dashboard, eg:
![image](https://user-images.githubusercontent.com/6455350/137204746-286b7a70-6242-4913-8aec-58f82f6e0e1b.png)

As we now use the checks API for this, I've decreased the permission to read-only access (so we can get events for new PRs). Thanks @chrisohaver and @miekg for catching this!

**Comment by miekg** [comment]
thanks for the prompt replies. I'll take another look

**Comment by miekg** [comment]
bit of a noob question, but do I need to do more than what I did? I looked in the faq, and just enabling it should be enough, but I don't see anything showing up in the test PR I made.

**Comment by cuonglm** [comment]
> bit of a noob question, but do I need to do more than what I did? I looked in the faq, and just enabling it should be enough, but I don't see anything showing up in the test PR I made.

You need to make a change related to go files. The bencher does not trigger benchmark for changes that don't modify the actual code, e.g change to documents, .github, ...

**Comment by miekg** [comment]
ha thanks @cuonglm, thought I did that, but it's not showing, made one in another commit

*and* I see gobencher showing up, as it should. Perfect.

**Comment by cuonglm** [comment]
> ha thanks @cuonglm, thought I did that, but it's not showing, made one in another commit
> 
> 
> 
> *and* I see gobencher showing up, as it should. Perfect.

The benchmark is done: https://dashboard.github.orijtech.com

Also see the bencher badge in your Checks now😎

**Comment by odeke-em** [comment]
Thank you everyone for chiming in, and thanks @miekg for adding Bencher. We aim to satisfy CoreDNS to the best of our abilities so that your project can always be performant. You shall see lots of upcoming features for Bencher and perhaps even some bugs filed when we see where performance can be improved for CoreDNS. I shall close this issue and thank you again.
