### ISSUE TITLE
SERVFAIL when querying web.whatsapp.com

### ISSUE THREAD

**Issue by yrro** [miekg/coredns#4907]
**What happened**:

I've got CoreDNS configured to forward queries to NextDNS via DNS-overTLS.

I've found that queries for `web.whatsapp.com` fail:

```
$ dig @192.168.0.4 web.whatsapp.com

; <<>> DiG 9.16.15-Debian <<>> +multi @192.168.0.4 web.whatsapp.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 17324
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: c776ca9170f0ff50 (echoed)
;; QUESTION SECTION:
;web.whatsapp.com.	IN A

;; Query time: 35 msec
;; SERVER: 192.168.0.4#53(192.168.0.4)
;; WHEN: Mon Oct 04 19:31:13 BST 2021
;; MSG SIZE  rcvd: 57

```

**What you expected to happen**:

Queries for `web.whatsapp.com` should be successful.

**How to reproduce it (as minimally and precisely as possible)**:

I can reproduce this by querying CoreDNS with the `Corefile` below.

**Anything else we need to know?**:

I haven't noticed any other queries resulting in `SERVFAIL`.

If I modify the `Corefile` to not use DNS-over-TLS, queries succeed.

If I query NextDNS directly with `dig` (well, via `socat` to wrap the connection in TLS) then I don't see the failure.

So it seems to be a combination of `web.whatsapp.com` + `CoreDNS` + NextDNS's DNS-over-TLS endpoint that are required to trigger the problem.

For reference, here's how I used `socat` to provide a DNS-over-TLS wrapper:

```
# socat  -d  TCP4-LISTEN:53,bind=127.0.0.1,reuseaddr,fork OPENSSL:45.90.28.0:853,snihost=xoanon-3baadc.dns1.nextdns.io,verify=0
```

And the test is performed with:

```
$ dig +vc @127.0.0.1 web.whatsapp.com

; <<>> DiG 9.16.15-Debian <<>> +multi +vc @127.0.0.1 web.whatsapp.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61892
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; PAD: (26 bytes)
;; QUESTION SECTION:
;web.whatsapp.com.	IN A

;; ANSWER SECTION:
web.whatsapp.com.	30 IN CNAME mmx-ds.cdn.whatsapp.net.
mmx-ds.cdn.whatsapp.net. 30 IN A 157.240.240.60

;; Query time: 79 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Oct 04 19:36:02 BST 2021
;; MSG SIZE  rcvd: 128

```

**Environment**:

- the version of CoreDNS: `CoreDNS-1.8.5`
- Corefile:
```
.:53 {
  bind 192.168.0.4
  prometheus 0.0.0.0:9153
  errors
  log
  local
  cache
  forward . tls://45.90.28.0 tls://45.90.30.0 {
  }
}
```
- logs, if applicable:
```
[INFO] 192.168.0.13:59963 - 45581 "A IN web.whatsapp.com. udp 34 false 512" SERVFAIL qr,rd,ra 34 0.073893455s
[INFO] 192.168.0.13:60542 - 27080 "A IN web.whatsapp.com. udp 34 false 512" SERVFAIL qr,rd,ra 34 0.104795023s
[INFO] 192.168.0.13:60542 - 27080 "A IN web.whatsapp.com. udp 34 false 512" SERVFAIL qr,rd,ra 34 0.104762179s
[INFO] 192.168.0.13:64348 - 21044 "A IN web.whatsapp.com. udp 34 false 512" SERVFAIL qr,rd,ra 34 0.03564958s
[INFO] 192.168.0.13:64348 - 21044 "A IN web.whatsapp.com. udp 34 false 512" SERVFAIL qr,rd,ra 34 0.022196212s
[INFO] 192.168.0.13:57805 - 52978 "A IN web.whatsapp.com. udp 34 false 512" SERVFAIL qr,rd,ra 34 0.07165171s
[INFO] 192.168.0.13:57805 - 52978 "A IN web.whatsapp.com. udp 34 false 512" SERVFAIL qr,rd,ra 34 0.075214437s
```
- OS: RHEL 8.4
- Others: I'm running the `docker.io/coredns/coredns` container image inside podman

**Comment by yrro** [comment]
I can also reproduce this with DNS-over-TLS to `9.9.9.10` and `1.1.1.1`, so it's not NextDNS in particular that's required, just any DNS-over-TLS endpoint.

**Comment by rajansandeep** [comment]
Is it possible you're getting a `SERVFAIL` due to the ongoing FB(Facebook, WhatsApp, Instagram) outage?

**Comment by yrro** [comment]
Looks like it! 🤦

**Comment by yrro** [comment]
Confirmed. What really confused me is why I was getting query results when hitting my ISP's resolver (and Cloudflare etc) via cleartext DNS...
