### ISSUE TITLE
Modified zone is not re-signed

### ISSUE THREAD

**Issue by ohreally** [miekg/coredns#4916]
**What happened**:

I'm using CoreDNS with the _file_ and _sign_ plugins.
When I modify a zone file (add/delete a record), and then restart CoreDNS, the modified zone is not signed. And since CoreDNS serves the zone from the signed file, the modified zone is not served.

**What you expected to happen**:

I expect CoreDNS (or more precisely the _sign_ plugin) to notice that the unsigned file is newer than the signed file, and to understand that this means that the zone must be re-signed.

**How to reproduce it (as minimally and precisely as possible)**:

- Configure CoreDNS to use the _file_ and _sign_ plugins.
- Create a zone file.
- Start CoreDNS.
- Modify the zone file.
- Restart CoreDNS.
- Signed zone file (_db.example.com.signed_) is unchanged.

**Anything else we need to know?**:

No, I think that's about it...

**Environment**:

- the version of CoreDNS: _1.8.6_
- Corefile: _yes_
- logs, if applicable: _none_
- OS (e.g: `cat /etc/os-release`): _FreeBSD 12.2-RELEASE_
- Others: _-_

**Comment by ohreally** [comment]
Oops, my bad...
I think I should be using the _auto_ plugin in this case, right?
If that is true, then please close this issue.
Sorry to have wasted your time.

**Comment by miekg** [comment]
did you change the SOA serial? I see that's not really described in the sign plugins docs

**Comment by ohreally** [comment]
Yes, I changed the serial.
