### ISSUE TITLE
Can coredns deployed in k8s default namesapce ? 

### ISSUE THREAD

**Issue by rayliu419** [miekg/coredns#4922]
Hi, 

We're running an application which use Service type in k8s and our Ops team create a k8s cluster without a DNS for us. Becasue our application use DNS to do something we found we have to install a coredns in the cluster. 
We followed this wiki https://github.com/coredns/deployment/tree/master/kubernetes to run coredns in a pod. The coredns pod is running but we found some error logs like:

[ERROR] plugin/errors: 2 example-pulsarcluster-zookeeper-service. A: read udp 110.0.26.162:43423->->xx.xx.xx.xx:53: i/o timeout

I aksed our Ops team and they said this is because "example-pulsarcluster-zookeeper-service" mapping can't be found in coredns and it's redirect the request to xx.xx.xx.xx(outside network DNS). This is strange because I think when k8s create a service, it will tell coredns to create a new entry for mapping(pls correct me if I'm wrong), but in this case, it seems fails. 
Due to some constrains, we deploy the coredns pod in namespace "default", I guess maybe we must deploy it in "kube-system" namespace(to get service creation notification)? 

Our settings;
k8s version - 1.19 stable
coredns version - 1.7.0 

Thanks !

**Comment by chrisohaver** [comment]
Can you deploy k8s DNS service discovery in an alternate namespace?  Yes probably, if you must.

Identifying the cause of lookup failure: It could be several things. e.g. if the pod making the dns request is in a separate namespace from the service it is trying to look up, must also specify the namespace (e.g. `example-pulsarcluster-zookeeper-service.zookeeper-namespace`).

If you have not already done so, please run through https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/.  It's pretty thorough, the results should help better understand what's causing the issue.

**Comment by rayliu419** [comment]
chrisohaver, thanks for your reply!  

Finally, I've found the root cause. The problem is our ops team doesn't configure the k8s cluster in right way. When the pod starts, their /etc/resolv.conf file doesn't contain the search directive, which blocks the extension of DNS query. 
The FQDS of service name example-pulsarcluster-zookeeper-service  should be example-pulsarcluster-zookeeper-service.default.svc.cluster.local, but in our case, the query is just example-pulsarcluster-zookeeper-service. 

Some follow up questions:
1. I've read some source code of coredns, it seems it will monitor all the namespaces of k8s(not just kube-system), is it right? 
2. It is said the file /etc/resolv.conf of pod is copied from the node's config, but our /etc/resolv.conf seems not come from it. Does coredns override the /etc/resolv.conf file in some way? (E.g., it register itself as internal DNS and tells k8s when starting pods, modify the nameserver to its CLUSTER_IP)? 

Thansk!

**Comment by chrisohaver** [comment]
> The problem is our ops team doesn't configure the k8s cluster in right way.

Agreed.  The DNS service discovery is a critical part of the k8s control plane. Not including one renders the cluster somewhat blind. 

> When the pod starts, their /etc/resolv.conf file doesn't contain the search directive ...

This could be due to kubelet misconfiguration and/or that the Pod has the dnsPolicy = "default". See below.

> I've read some source code of coredns, it seems it will monitor all the namespaces of k8s(not just kube-system), is it right?

Yes. It monitors ip addresses for services and endpoints in all namespaces by default.

> It is said the file /etc/resolv.conf of pod is copied from the node's config, but our /etc/resolv.conf seems not come from it.

That is only true for Pods that have dnsPolicy = "default".  However, the dnsPolicy that most Pods use is "clusterFirst", for which kubelet constructs a synthesized resolv.conf containing the static cluster IP of the coredns service as the nameserver, and with search domains designed to search services in the kubernetes cluster domain.  The is an example in https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/.

>  Does coredns override the /etc/resolv.conf file in some way? (E.g., it register itself as internal DNS and tells k8s when starting pods, modify the nameserver to its CLUSTER_IP)?

No. kubelet must be configured manually with the static IP address of the dns service and cluster domain (e.g. `cluster.local`).

IOW, if adding a dns service to a cluster that doesn't have one, you need to at least add the service AND you need to update the kubelet configuration with DNS clusterIP and cluster domain.

**Comment by rayliu419** [comment]
chrisohaver, thanks for your clear explanation.
By the way, do you know the performance limitation when we use coredns as k8s internal DNS server? I am worried about the coredns performance because our cluster may have huge flow in the future.   Our ops has a plan to use their own DNS as an external DNS of k8s, I don't know whether it's a right choice. Acutally, I don't agree to use an external DNS at the moment since it seems no obvious advantage to use external DNS instead of coredns.

**Comment by chrisohaver** [comment]
Being a k8s deployment, it can be scaled horizontally to handle larger load.  Also, deploying [node-local dns-cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) will reduce load on the CoreDNS deployment for external lookups.

**Comment by rayliu419** [comment]
Thanks, I'll close the issue.
