### ISSUE TITLE
plugin/route53 allow configuring of endpoint URL

### ISSUE THREAD

**Issue by 56KBs** [miekg/coredns#4943]
**What would you like to be added**:
The ability to configure the `endpoint` in the Route53 plugin AWS client.

**Why is this needed**:
We are making use of the Route53 plugin in order to aid our integration tests, using a mocked version of Route53 served via [localstack](https://github.com/localstack/localstack), sadly, localstack does not provide for free the ability to serve the Route53, when combining it with coredns it does allow this. I have currently locally modified the `setup.go` for the Route53 plugin to support this in order to allow us to use the locally hosted Route53 instead of the true Route53.

**Comment by Aut0R3V** [comment]
I'd like to work on this ,can someone provide a little bit of guidance on how to get this done?

**Comment by chrisohaver** [comment]
> can someone provide a little bit of guidance on how to get this done?

@Aut0R3V, Add a new option (e.g. `endpoint`) to parsing in `setup.go`, and assign it to (probably) `Endpoint` in the `aws.Config`. Also add unit tests, and update README.

**Comment by Aut0R3V** [comment]
Thank you!
