### ISSUE TITLE
plugin/etcd :  Can it support to config two ip value in A records ?

### ISSUE THREAD

**Issue by victory460** [miekg/coredns#4958]
Can it support to config two ip value in A records ? Want to use loadbalance.
In zone file，can config it as following: 
```
$ORIGIN example.org.
@	3600 IN	SOA sns.dns.icann.org. noc.dns.icann.org. (
				2017042745 ; serial
				7200       ; refresh (2 hours)
				3600       ; retry (1 hour)
				1209600    ; expire (2 weeks)
				3600       ; minimum (1 hour)
				)

	3600 IN NS a.iana-servers.net.
	3600 IN NS b.iana-servers.net.

server1  IN  A  10.0.1.3
         IN  A  10.0.1.5

```
I found a example in etcd:
```
etcdctl put /skydns/local/skydns/ '{"host":"1.1.1.1","ttl":60}'
```
 Can it support to config two ip value in A records ?
 How to config it?
Thanks.

**Comment by chrisohaver** [comment]
> Can it support to config two ip value in A records ?

Yes - more or less.  etcd/skydns (contrary to normal DNS behavior) will return all answers from all subdomains of the domain queried. So, if you add records for `abc.server1.example.com.` and `xyz.server1.example.com.`, a query for `server1.example.com.` will return the answers for `abc.server1.example.com.` and `xyz.server1.example.com.`.

**Comment by victory460** [comment]
> > Can it support to config two ip value in A records ?
> 
> Yes - more or less. etcd/skydns (contrary to normal DNS behavior) will return all answers from all subdomains of the domain queried. So, if you add records for `abc.server1.example.com.` and `xyz.server1.example.com.`, a query for `server1.example.com.` will return the answers for `abc.server1.example.com.` and `xyz.server1.example.com.`.

Sorry, maybe I didn't make it clear. I mean  when I `dig -t A server1.example.com `  that  it can answer :
_server1.example.com.    3600    IN      A       10.0.1.3
server1.example.com.    3600    IN      A       10.0.1.5_
How to config it in etcd plugin?

**Comment by chrisohaver** [comment]
Yes, as explained above.  Try it.

**Comment by chrisohaver** [comment]
For an example see the following test case...

https://github.com/coredns/coredns/blob/f60fabc87523a7241cb517756017d5fb281076d3/plugin/etcd/lookup_test.go#L261-L267

and test data...

https://github.com/coredns/coredns/blob/f60fabc87523a7241cb517756017d5fb281076d3/plugin/etcd/lookup_test.go#L50-L52

**Comment by victory460** [comment]
> Yes, as explained above. Try it.

I know what you mean now. This is a bit different from the way the zone file described:
```
$ORIGIN example.org.
@	3600 IN	SOA sns.dns.icann.org. noc.dns.icann.org. (
				2017042745 ; serial
				7200       ; refresh (2 hours)
				3600       ; retry (1 hour)
				1209600    ; expire (2 weeks)
				3600       ; minimum (1 hour)
				)

	3600 IN NS a.iana-servers.net.
	3600 IN NS b.iana-servers.net.
server1  IN  A  10.0.1.3
         IN  A  10.0.1.5
```
Thank you very much.

**Comment by victory460** [comment]
> For an example see the following test case...
> 
> https://github.com/coredns/coredns/blob/f60fabc87523a7241cb517756017d5fb281076d3/plugin/etcd/lookup_test.go#L261-L267
> 
> and test data...
> 
> https://github.com/coredns/coredns/blob/f60fabc87523a7241cb517756017d5fb281076d3/plugin/etcd/lookup_test.go#L50-L52

Thanks!
