### ISSUE TITLE
If there are many service pods on the headless backend, the results of DNS lookup for a headless service will not be balanced

### ISSUE THREAD

**Issue by runner112** [miekg/coredns#4960]
coredns has enabled loadbalance，the version is v1.8. If there are many service pods on the headless backend, the results of DNS lookup for a headless service will not be balanced.

For example, if 5 pods are mounted on the headless backend, the analysis results are balanced. If headless mounts 15 pods, the resolution result of dns will always be about 2 times higher than the other pods.

test method：
for i  in {1..10000};do  curl -vI  xxxx.svc.cluster.local cluster.local  >> /tmp/abc  2>&1  ;done
The analysis results of 5 pods in the backend：
 sh-4.2# cat /tmp/abc  | grep "Trying" |  egrep -o   '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | sort | uniq -c | sort -nr
   2128 172.20.8.54
   2037 172.20.8.55
   1957 172.20.8.53
   1943 172.20.5.33
   1935 172.20.5.32

The analysis results of 15 pods in the backend：
sh-4.2# cat /tmp/efg  | grep "Trying" |  egrep -o   '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | sort | uniq -c | sort -nr
   1338 172.20.8.54
    659 172.20.8.53
    654 172.20.3.100
    653 172.20.3.99
    648 172.20.3.102
    637 172.20.3.103
    628 172.20.3.95
    622 172.20.5.33
    613 172.20.3.94
    612 172.20.3.97
    611 172.20.3.101
    596 172.20.3.98
    595 172.20.3.96
    569 172.20.8.55
    565 172.20.5.32

172.20.8.54 response is much higher than other requested ip

**Comment by chrisohaver** [comment]
Thanks @runner112, see #4961 for a proposed improvement.
