### ISSUE TITLE
Add ability to add new server transport protocols

### ISSUE THREAD

**Issue by jdamick** [miekg/coredns#4973]
**What would you like to be added**:

The ability to add new server implementations for either existing transports (dns, https, etc.) and add new server transport (quic, or other experimental servers).

**Why is this needed**:

Currently it is not possible to add or override server transports without patching existing source.

**Comment by chrisohaver** [comment]
Closing this issue, as a PR was opened at the same time.  I think it makes sense to have the discussion in one place, not split between an issue and a PR.

**Comment by jdamick** [comment]
Ok, I didn't want to just submit an unsolicited PR with no context.

**Comment by chrisohaver** [comment]
No problem. The context can go in the PR description.

IMO, The idea of raising an issue is to have a discussion and gather input from the community about it before agreeing upon and submitting a solution.  If you already have a solution built, there is little purpose to opening a separate issue.

**Comment by chrisohaver** [comment]
I have copied the description here to the PR description.
