### ISSUE TITLE
plugin/loadbalance: add a loadbalance strategy based on ip hash for session retention

### ISSUE THREAD

**Issue by victory460** [miekg/coredns#4979]
**What would you like to be added**:
Currently ,there is only a roundRobin loadbalance strategy. Is such a feature necessary that to develop a load balancing strategy based on ip hash for session retention?
**Why is this needed**:
This loadbalance strategy can support the function of session retention, that is, the domain name resolution records resolved by the client of the same source IP will not change.
If necessary, I am willing to develop it.

**Comment by johnbelamaric** [comment]
I don't think that makes sense for DNS. Why should a DNS server manage session state? The client should locally cache the IP after the first lookup.

**Comment by chrisohaver** [comment]
I _think_ what is being suggested is that we randomize based on a hash of the client ip, such that a given client IP would always produce the same result.  This could be done without maintaining any state on the server.  One major caveat however is that if the answer set changes (e.g. an extra answer is added), then the answers for all clients would change. i.e. 
1. query for `example.com`
2. answer has 5 records
3. _loadbalance_ selects one record based on IP: e.g.  `int(client_ip) % 5`
4. write only the selected record to client

It's doable ... but it's unusual. I don't immediately see how this would be useful or why this would be needed.

@victory460, can you describe your use case?  How do you plan to use this feature?

**Comment by chrisohaver** [comment]
> I don't immediately see how this would be useful or why this would be needed.

I suppose if the client does _not_ locally retain the IP for its session, and making the client do so is not possible.

**Comment by johnbelamaric** [comment]
Load balance doesn't select a single record. It shuffles records under the assumption that naive clients use the first value returned. It's also limited by some resolvers that [sort](https://tools.ietf.org/html/rfc8305#section-4) the answers anyway. We do have a demo plugin that selects a single record that I did for the _Learning CoreDNS_ book: https://github.com/coredns/learning-coredns/tree/master/plugins/onlyone that might work more like you describe. But yes, even with a hash it wouldn't really be deterministically "sticky".

**Comment by chrisohaver** [comment]
@victory460 IOW, We think what you are describing is not appropriate to add to _loadbalance_ plugin.  If you need this, you can create an external plugin.  You could use @johnbelamaric's https://github.com/coredns/learning-coredns/tree/master/plugins/onlyone as a starting point.

**Comment by victory460** [comment]
Thanks for the discussion.
Steps as you said:
> * query for `example.com`
> * answer has 5 records
> * _loadbalance_ selects one record based on IP: e.g.  `int(client_ip) % 5`
> * write only the selected record to client

[ Wide area persistence—To ensure user connections persist across apps and data centers, BIG-IP GTM synchronizes data, propagates local DNS, and maintains session integrity.](https://www.f5.com/pdf/products/big-ip-global-traffic-manager-ds.pdf)

Before, we wanted to make a similar function as above , but now it seems to be a bit problematic.

**Comment by miekg** [comment]
yes, let's not pretend DNS LB is any good.
