### ISSUE TITLE
bind doesn't seem to work properly

### ISSUE THREAD

**Issue by rany2** [miekg/coredns#4993]
**What happened**:

Using `bind` doesn't have the intended result of binding to only the addresses provided.

**What you expected to happen**:

`bind` option still causes coredns to listen on `*:53`

**How to reproduce it (as minimally and precisely as possible)**:

1. Add the following the config:
```
. {
  bind 127.0.0.1
  bind ::1
}
```
2. Start CoreDNS
3. Verify that `*:53` is still being listened to:
```
# ss -tupln|grep coredns
udp   UNCONN 0      0                              127.0.0.1:53         0.0.0.0:*    users:(("coredns",pid=62722,fd=9))     
udp   UNCONN 0      0                                      *:53               *:*    users:(("coredns",pid=62722,fd=7))     
udp   UNCONN 0      0                                  [::1]:53            [::]:*    users:(("coredns",pid=62722,fd=11))    
tcp   LISTEN 0      4096                           127.0.0.1:53         0.0.0.0:*    users:(("coredns",pid=62722,fd=8))     
tcp   LISTEN 0      4096                                   *:53               *:*    users:(("coredns",pid=62722,fd=3))     
tcp   LISTEN 0      4096                               [::1]:53            [::]:*    users:(("coredns",pid=62722,fd=10))
```

**Anything else we need to know?**: N/A

**Environment**:

- the version of CoreDNS: CoreDNS-1.8.6 linux/amd64, go1.17.3, 13a9191-dirty
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Arch Linux
- Others:

**Comment by miekg** [comment]
can't reproduce:

~~~
% ./coredns -p 1053
example.net.:1053 on 127.0.0.1
example.net.:1053 on ::1
CoreDNS-1.8.6
linux/amd64, go1.17.3,

% ss -tupln|grep coredns
udp     UNCONN   0        0              127.0.0.1:1053           0.0.0.0:*      users:(("coredns",pid=10325,fd=8))
udp     UNCONN   0        0                  [::1]:1053              [::]:*      users:(("coredns",pid=10325,fd=10))
tcp     LISTEN   0        4096           127.0.0.1:1053           0.0.0.0:*      users:(("coredns",pid=10325,fd=7))
tcp     LISTEN   0        4096               [::1]:1053              [::]:*      users:(("coredns",pid=10325,fd=9))
~~~

Are you on Mac? Probably hit by this https://github.com/miekg/dns/issues/724

**Comment by rany2** [comment]
This issue turned out to be a misunderstanding of coredns. I thought that if I only specified it `bind` in the `.` section then it would apply to all the other zones. After adding `bind` to all the zones in my config it worked out.
