### ISSUE TITLE
How to reload DoH certificate

### ISSUE THREAD

**Issue by Tantalor93** [miekg/coredns#4994]
Hello, in the previous versions of CoreDNS (before 1.8.0) it was possible to run CoreDNS as DoH server where we were terminating TLS before CoreDNS instance (in my case on Traefik, which then forwarded DoH traffic via plain HTTP to CoreDNS), but that is no longer possible due to https://github.com/coredns/coredns/commit/5235b35e3f321fc1e273c39e19eae71bd0df7fcc

I am now trying to run CoreDNS as DoH server with TLS plugin enabled,
```Corefile
https://example.org {
    whoami
    tls mycert mykey
}
```

where certificates are issued and renewed by Cert-manager in kubernetes, but it seems it that when certificate is renewed(reissued) then CoreDNS will not reload the new certificate. Can CoreDNS be somehow configured to gracefully reload the certificate?

I think it was partially discussed here https://github.com/coredns/coredns/issues/3460#issuecomment-765321708 , but it seems there is no conclusion to the discussion.

**Comment by Tantalor93** [comment]
Imho it could be solved quite easily by `reload` plugin (https://github.com/coredns/coredns/tree/master/plugin/reload) if it could be configured to watch any file (like cert) and gracefully reload whole CoreDNS on cert change

**Comment by miekg** [comment]
does it make sense to revert 5235b35e3f321fc1e273c39e19eae71bd0df7fcc ?

Regarding that discussion what I think that should happen is:
* make it possible for plugins to submit files for reload to watch (and maybe unwatch)
* make *hosts* also do this? (or not, would be cool though, but reloading the *entire* server might be a bit much.

Making *reload* smarter should not be that hard and there is prior art in e.g. *health* and *ready* plugins.

**Comment by Tantalor93** [comment]
I would be 100% for reverting the  https://github.com/coredns/coredns/commit/5235b35e3f321fc1e273c39e19eae71bd0df7fcc if you agree @miekg , I can prepare the revert.

as for reloading whole server, yea I agree that might be too much. Might be better to do it somehow more clever.

**Comment by miekg** [comment]
yes revert makes sense, although was some comment in the tls plugin on running with TLS and then fronted by a TLS terminating proxy make sense.
