### ISSUE TITLE
Release tracking: 1.8.7

### ISSUE THREAD

**Issue by miekg** [miekg/coredns#4996]
Let's release 1.8.7, bunch of things got merged, nothing earth shattering.

**Comment by yongtang** [comment]
Will try to release 1.8.7 today. /cc @miekg  @chrisohaver

**Comment by yongtang** [comment]
From the error looks like the golang download link should be updated.

/cc @miekg  @chrisohaver do you know where the script should be updated?

**Comment by chrisohaver** [comment]
Fixed here I think ... https://github.com/coredns/release/blob/master/release-coredns.
And then I think needs to be pushed to drone by @miekg.

... or maybe another drone script pulls this? I don't know.

**Comment by mrueg** [comment]
Are there any plans to continue on this release?

**Comment by yongtang** [comment]
coredns 1.8.7 has been released successfully 👍 🎉 !
