### ISSUE TITLE
Coredns stops resolving random domains after some time

### ISSUE THREAD

**Issue by fliespl** [miekg/coredns#5005]
**What happened**:

After a few minutes CoreDNS fails to resolve random queries with following errors.

[ERROR] plugin/errors: 2 crl.globalsign.net. A: read udp 192.168.88.2:61369->192.168.88.1:53: wsarecv: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

[ERROR] plugin/errors: 2 teams.events.data.microsoft.com. A: read udp 192.168.88.2:61446->192.168.88.1:53: wsarecv: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

192.168.88.1 - is Mikrotik HAP Ac2

**What you expected to happen**:

Keep resolving dns queries.

**How to reproduce it (as minimally and precisely as possible)**:
```
. {
	bind 127.0.0.1 192.168.50.88 
	
	log
	errors
	
	forward . 192.168.75.1 192.168.88.1 {
		policy sequential
		health_check 2s
	}
}
```

**Anything else we need to know?**:

**Environment**:

.:53 on 127.0.0.1
.:53 on 192.168.50.88
CoreDNS-1.8.6
windows/amd64, go1.17.1, 13a9191

Windows 11

**Comment by chrisohaver** [comment]
Intitial thoughts...
1. That's a long error string.
2. Per googling, the error is (mostly) discussed in the context of Windows - so this may be a Windows specific issue.

As a workaround  - try adding `force_tcp` to the _forward_ plugin.
