### ISSUE TITLE
Unable to resolve POD_NAME.SERVICE_NAME.cluster.default.svc with operator spawned pod

### ISSUE THREAD

**Issue by xcompass** [miekg/coredns#5008]
**What happened**:
After upgrade to CoreDNS 1.8.4 (or above), my etcd operator spawned pod is unable to start up.
```
gp-etcd-cluster-tnk55vjnwt                                        0/1     Init:0/1            0          13m
```
And the log for init container:
```
▶ k logs gp-etcd-cluster-tnk55vjnwt -c check-dns
Server:    10.3.0.10
Address 1: 10.3.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'gp-etcd-cluster-tnk55vjnwt.gp-etcd-cluster.default.svc'
```
All other DNS resolutions seem working fine.

**What you expected to happen**:
DNS name should be resolved to IP

**How to reproduce it (as minimally and precisely as possible)**:
* Update to CoreDNS 1.8.4+
* Install Etcd Operator with https://github.com/coreos/etcd-operator/blob/master/example/deployment.yaml
* Add a etcd cluster with the following yaml
```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "gp-etcd-cluster"
spec:
  size: 5
  version: "3.2.29"
```
* Run `kubectl get pods` and etcd pod is stuck in the init stage.

**Anything else we need to know?**:
* It works fine with 1.8.3 or below
* I tried to isolate the issue with simple service and pod (to generate a endpoint) and it resolved correctly. I can only replicate this issue with etcd operator generated pods.
* When I switch to 1.8.3 and create a new etcd cluster and all 5 pods were up, I then upgrade to 1.8.4 and delete one of the pod. The new pod failed to start up. When I tried to nslookup the `SERVICE.default.svc`, I only get 4 endpoints

```
kubectl exec -it dnsutils -- nslookup gp-etcd-cluster.default.svc
Server:         10.3.0.10
Address:        10.3.0.10#53

Name:   gp-etcd-cluster.default.svc.cluster.local
Address: 10.2.36.12
Name:   gp-etcd-cluster.default.svc.cluster.local
Address: 10.2.99.37
Name:   gp-etcd-cluster.default.svc.cluster.local
Address: 10.2.10.30
Name:   gp-etcd-cluster.default.svc.cluster.local
Address: 10.2.112.16

```
But when I check the endpoints with command `k get ep gp-etcd-cluster -o yaml`. I got 5. The new one, which is stuck in the init status was there as well. So it seems that CoreDNS is not watching the new endpoint being added. However, this works with a simple service and pod.

**Environment**:

- the version of CoreDNS: 1.8.4+
- Corefile: 
```
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          endpoint_pod_names
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
```
- logs, if applicable: No logs from CoreDNS
- OS (e.g: `cat /etc/os-release`): Flatcar 2983.2.0
- Others: K8S 1.19.7

**Comment by chrisohaver** [comment]
If a headless service defines `Service.spec.publishNotReadyAddresses: true`, then CoreDNS will publish unready endpoints for that service.

Without that defined, CoreDNS _intentionally_ only publishes records for _ready_ endpoints.  There were a couple of releases after migrating from Endpoint to EndpointSlice monitoring in 1.8.1, where CoreDNS was _errantly_ publishing unready endpoints.  This was _fixed_ in 1.8.4 with https://github.com/coredns/coredns/pull/4580.

**Comment by xcompass** [comment]
Ah, that make sense. Thanks!
