### ISSUE TITLE
Reloading blocked when number of zone files is more than 1500

### ISSUE THREAD

**Issue by mscbg** [miekg/coredns#5010]
Hi, all:
I have configured Corefile like this:
. {
    hosts /opt/tiger/data/ti/etc/coredns/hosts.conf {
        fallthrough
        reload 2s
    }
    import /opt/tiger/data/ti/etc/coredns/contents.conf
    acl byted.org {
        block net 0.0.0.0/0
    }
    chaos CoreDNS-001 info@coredns.io
    forward . 10.8.8.8 10.8.8.9 {
        except 10.in-addr.arpa d.b.d.f.ip6.arpa
    }
    reload 10s
    loadbalance
    log
}

And contents.conf is like this:
file /opt/tiger/data/ti/etc/coredns/f4bd5b5c-auto-test.com./f4bd5b5c-auto-test.com..zone f4bd5b5c-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/5824635c-auto-test.com./5824635c-auto-test.com..zone 5824635c-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/982ff514-auto-test.com./982ff514-auto-test.com..zone 982ff514-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/415ca908-auto-test.com./415ca908-auto-test.com..zone 415ca908-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/09c982bd-auto-test.com./09c982bd-auto-test.com..zone 09c982bd-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/aacf871c-auto-test.com./aacf871c-auto-test.com..zone aacf871c-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/80ab06d6-auto-test.com./80ab06d6-auto-test.com..zone 80ab06d6-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/cffac8d3-auto-test.com./cffac8d3-auto-test.com..zone cffac8d3-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/51de698a-auto-test.com./51de698a-auto-test.com..zone 51de698a-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/092fc8f9-auto-test.com./092fc8f9-auto-test.com..zone 092fc8f9-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/856dafe7-auto-test.com./856dafe7-auto-test.com..zone 856dafe7-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/c1c76dc3-auto-test.com./c1c76dc3-auto-test.com..zone c1c76dc3-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/aa-test.com./aa-test.com..zone aa-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/05d2bfa4-auto-test.com./05d2bfa4-auto-test.com..zone 05d2bfa4-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/9620d3eb-auto-test.com./9620d3eb-auto-test.com..zone 9620d3eb-auto-test.com. {
    reload 2s
}
file /opt/tiger/data/ti/etc/coredns/795fd2a8-auto-test.com./795fd2a8-auto-test.com..zone 795fd2a8-auto-test.com. {
    reload 2s
}
.....
There are more than 1500 files. Then I find if I changed contents.conf or Corefile. CoreDNS will reload failed.
Log is just like:
![image](https://user-images.githubusercontent.com/20103281/143373921-6ddf44b7-dcaa-4a99-89ec-b4c774b01105.png)
There is no more log even if I wait for a long while. If I send SIGUSR1, CoreDNS can still not reload success.
![image](https://user-images.githubusercontent.com/20103281/143374213-20351da7-2989-4bb5-b921-29eb2098c909.png)

If the number of zone files is about 100, CoreDNS will reload success:
![image](https://user-images.githubusercontent.com/20103281/143374154-b393af17-2285-4c57-acaa-ce18b39f0823.png)

By the way, zone file wil reload success any time if I changed zone file.
![image](https://user-images.githubusercontent.com/20103281/143374633-7fd57302-a676-4231-b015-442b93471e2d.png)

**Environment**:
CoreDNS 1.8.5
Linux debian 9.13, Kernel 5.4.56.bsk.1-amd64
I have set LimitNOFILE=65535

**Comment by mscbg** [comment]
It seems reload is blocked by "_, err := instance.Restart(corefile)" which is in reload.go

**Comment by mscbg** [comment]
I have found my problem. That is because I have configured two the same zones and zonefiles. But I think CoreDNS should show some log like "domain is already configured, conflict" instead of block reloading.

**Comment by miekg** [comment]
> I have found my problem. That is because I have configured two the same zones and zonefiles. But I think CoreDNS should show some log like "domain is already configured, conflict" instead of block reloading.

what's the conflict here? Re-using a generic zonefile for different zones is perfectly valid to do, provided `@` is used in the file instead of the actual domain names.
