### ISSUE TITLE
Using etcd with forward

### ISSUE THREAD

**Issue by Mutantt** [miekg/coredns#5012]
we use below config in our k8s and forwarding doesn't work when I use it with etcd plugin.when I remove etcd plugin,forwarding starts to work. please advise if I have missed anything.

.:53 {
        log
        errors
        etcd {
         path /skydns
         endpoint https://172.29.2.11:2379 https://172.29.2.12:2379 https://172.29.2.13:2379
         tls /etcd/cert.pem /etcd/key.pem /etcd/ca.crt
        } 
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 10.233.23.36 {
          prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }

**Comment by chrisohaver** [comment]
The etcd plugin is grabbing and answering all queries before forward gets them. To fix, either specify the zone for which etcd is authoritative in the etcd plugin definition, or add fallthrough to etcd plugin options.

**Comment by Mutantt** [comment]
@chrisohaver  Thank you,it worked.
