### ISSUE TITLE
HINFO: read udp 10.1.81.29:58070->10.1.162.250:53: i/o timeout

### ISSUE THREAD

**Issue by Sam-Sundar** [miekg/coredns#5015]
Hi CoreDNS Team,

We have an offline environment where Microk8s is deployed with Calico node and CoreDNS as DNS.

We could see DNS is not resolving endpoints and are getting i/o timeout. We have followed [this article](https://github.com/ubuntu/microk8s/files/7587411/redhat.txt) to remove NFTABLE and use iptable instead, and also added below env in caliconode daemonset
```yaml
- name: FELIX_IPTABLESBACKEND
  value: "NFT"
  ```
When i check iptables, below is the output with no rule even though we run `iptables -P FORWARD ACCEPT && iptables -P INPUT ACCEPT && iptables -P OUTPUT ACCEPT`

![image](https://user-images.githubusercontent.com/83000807/143888899-8a331724-1e57-4e49-be1c-e6a8edecf8d2.png)
![image](https://user-images.githubusercontent.com/83000807/143888963-3fef30f6-5044-4261-b069-4511c2d14521.png)

We get this error in coredns logs
![image](https://user-images.githubusercontent.com/83000807/143889680-9d808ddf-aae5-4092-9a20-f57082d44cfc.png)

Also when we nslookup a service from another pod, we get this below error
![image](https://user-images.githubusercontent.com/83000807/143890919-e82a5b9d-7c7a-423c-b815-838f2d7309a2.png)

Also firewalld is not running and we followed [this](https://github.com/coredns/coredns/issues/4666#issuecomment-856153464) too and removed all the hardening restrictions.
Can you please let us know if we are missing something and how to solve this issue.

**Environment**: 

- the version of CoreDNS: coredns/coredns:1.8.0, quay.io/calico/node:v3.13.2
- Corefile: `forward . /etc/resolv.conf`
- logs, if applicable: 
- [coredns_NFT.log](https://github.com/coredns/coredns/files/7618875/coredns_NFT.log)
- [calico_NFT.log](https://github.com/coredns/coredns/files/7618880/calico_NFT.log)
- OS (e.g: `cat /etc/os-release`) - RHEL 8.4

- Others:

**Comment by chrisohaver** [comment]
From what I can actually read, it seems like a networking issue, probably better asked in Calico channels.

**Comment by chrisohaver** [comment]
From a CoreDNS perspective, the coredns pods are timing out waiting for a response from the upstream dns (10.1.162.250), and timing out trying to connect to Kubernetes API (10.152.183.1).

**Comment by chrisohaver** [comment]
> probably better asked in Calico channels 

Actually - rather than Calico, the question is probably best asked to the MicroK8s community.

Closing here.
