### ISSUE TITLE
Support DSCP marking in forward plugin

### ISSUE THREAD

**Issue by nearbyfly** [miekg/coredns#5016]
**What would you like to be added**:
Currently forward plugin doesn't support DSCP marking. To support QoS, DSCP marking is required.

**Why is this needed**:
To ensure DNS traffic QoS, DSCP marking is expected, especially for forwarding query to external DNS servers. 
Other DNS forwarder, like bind9, can support DSCP marking.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[coredns/coredns] Support DSCP mark..." ]
>What would you like to be added:
>Currently forward plugin doesn't support DSCP marking. To support QoS, DSCP
>marking is required.
>
>Why is this needed:
>To ensure DNS traffic QoS, DSCP marking is expected, especially for forwarding
>query to external DNS servers.
>Other DNS forwarder, like bind9, can support DSCP marking.

unlikely to be implemented. You can also easily detect these pkt because they run over
port 53.

/close
