### ISSUE TITLE
Configure custom DNS forwarding, occasionally inaccessible

### ISSUE THREAD

**Issue by chj9** [miekg/coredns#5018]
**What happened**:
Configure custom DNS forwarding, occasionally inaccessible
**What you expected to happen**:
Addressing successfully every time
**How to reproduce it (as minimally and precisely as possible)**:
`
kubectl -n kube-system edit configmap coredns
`
My config
```
.:53 {
    log
    errors
    health {
       lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    prometheus :9153
    forward .  172.17.20.111:53  /etc/resolv.conf  {
       max_concurrent 1000
    }
    cache 30
    loop
    reload
    loadbalance
}
```
172.17.20.111:53 is my custom bind9 dns server
![image](https://user-images.githubusercontent.com/16426260/144205005-caa2e257-2815-41c5-baed-5b24e9ec3246.png)

- the version of CoreDNS: 1.8.0
- the version of k8s: 1.21.6
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Others:

**Comment by chrisohaver** [comment]
The forward plugin uses a `random` policy by default, each forwarded message goes to a randomly selected upstream from the list of upstreams in forward and the resolv.conf files listed. But even if you select a `sequential` policy, it will not act the way I suspect you want it to. 

If `172.17.20.111` serves a private/local domain, the proper way to forward is to create a server block for that domain, and forward to that upstream.  e.g. if 172.17.20.111 is used to serve the zone `mydomain`...

```
.:53 {
    [...]
    forward .  /etc/resolv.conf  {
       max_concurrent 1000
    }
    [...]
}

mydomain:53 {
    forward .  172.17.20.111:53
    cache 30
}
```

**Comment by chj9** [comment]
> The forward plugin uses a `random` policy by default, each forwarded message goes to a randomly selected upstream from the list of upstreams in forward and the resolv.conf files listed. But even if you select a `sequential` policy, it will not act the way I suspect you want it to.
> 
> If `172.17.20.111` serves a private/local domain, the proper way to forward is to create a server block for that domain, and forward to that upstream. e.g. if 172.17.20.111 is used to serve the zone `mydomain`...
> 
> ```
> .:53 {
>     [...]
>     forward .  /etc/resolv.conf  {
>        max_concurrent 1000
>     }
>     [...]
> }
> 
> mydomain:53 {
>     forward .  172.17.20.111:53
>     cache 30
> }
> ```

I set it up and restart coredns, but the problem still exists
this is my config
```
.:53 {
    log
    errors
    health {
       lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    hosts {
      47.92.255.92   atai-gateway-0
      fallthrough
    }
    prometheus :9153
    forward .  /etc/resolv.conf  {
       max_concurrent 1000
    }
    cache 30
    loop
    reload
    loadbalance
}
.test:53 {
    forward .  172.17.20.111:53
    cache 30
}
.qa:53 {
    forward .  172.17.20.111:53
    cache 30
}
```
I have found a rule, that is, if my domain is not accessed for a long time, this problem will occur when I access it suddenly。
of course, this problem is occasional, and sometimes a sudden access is successful
![image](https://user-images.githubusercontent.com/16426260/144342761-bbf70be5-c18b-4b01-9a91-01a87a60cb82.png)

**Comment by chrisohaver** [comment]
Your queries are still being routed through the `.:53` block. Remove the leading dot from the `test` and `qa` domains...

```
test:53 {
    forward .  172.17.20.111:53
    cache 30
}
qa:53 {
    forward .  172.17.20.111:53
    cache 30
}
```
