### ISSUE TITLE
Add external plugin version specification in plugin.cfg

### ISSUE THREAD

**Issue by chrisohaver** [miekg/coredns#5025]
For CoreDNS build reproducibility, I think it would be useful to add an extra optional parameter per plugin to plugin.cfg, that specifies the tag/commit to build with for external plugins.

A step added to the Makefile could then check plugin.cfg for these and `go get` the configured version.

**Comment by yongtang** [comment]
I think we may want to default to `master` if it is not specified.

**Comment by chrisohaver** [comment]
> I think we may want to default to `master` if it is not specified.

I think we'd want to leave it at the current behavior if a version is not specified - that is use default version selection behavior of go modules.

**Comment by chrisohaver** [comment]
Hmm, after playing this through more in my head.  From a practicality standpoint, this is redundant with `go.mod`.

Currently when a user forks CoreDNS as they would when "maintaining" a build of CoreDNS with external plugins, they can manually `go get` the external plugins at the versions they need, and then commit the resulting `go.mod`.  Then any user checking out the project to build would automatically build with the versions set in `go.mod` when making.

So, I think this is not needed, and it doesn't really reduce steps for the user.
