### ISSUE TITLE
forward Plugin performs health check even if `max_fails` is `0`

### ISSUE THREAD

**Issue by tiwood** [miekg/coredns#5028]
**What happened**:

We have the following errors reported by CoreDNS:

```
[ERROR] plugin/errors: 2 . NS: read udp 10.245.6.73:56152->168.63.129.16:53: i/o timeout
```

We assume this is the `forward` plugins's health check, but that should be disabled by our config:

```
.:53 {
    forward . 168.63.129.16 {
      max_fails 0
    }
    log
    errors
    reload
    nsid

    ready :8181
    health :8080
    prometheus :9153

    #// cache for 5 min
    cache 300 {
      denial 0
      serve_stale 5m
    }
}
```

**What you expected to happen**:

No health checks should be performed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.8.6
- Corefile: see above
- logs, if applicable:
```
[ERROR] plugin/errors: 2 . NS: read udp 10.245.6.73:56152->168.63.129.16:53: i/o timeout
```
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Others:

**Comment by chrisohaver** [comment]
Looking at the code, I can't see the code path where this can happen.
I don't believe CoreDNS will actually log the health check queries coming from itself (forward).
I cannot replicate this issue. 

To verify, is `10.245.6.73` the IP address of your CoreDNS instance?

**Comment by chrisohaver** [comment]
> To verify, is `10.245.6.73` the IP address of your CoreDNS instance?

Hmm, It must be.  A better question: In the logs do you see `[INFO]` NS queries for  `.` ? If so, it would mean the queries are coming from somewhere else.

**Comment by tiwood** [comment]
Thanks @chrisohaver, you're actually right and my assumption was wrong. It turns out there is an external client that issues these queries.

```
[INFO] 10.250.206.10:11962 - 6 "NS IN . udp 17 false 512" - - 0 6.002242672s
[ERROR] plugin/errors: 2 . NS: read udp 10.245.6.73:59259->168.63.129.16:53: i/o timeout
```
