### ISSUE TITLE
Response alternate from file

### ISSUE THREAD

**Issue by sphlvn3** [miekg/coredns#5029]
**What you expected to happen:**
If forward response (can't find) than response from file
**How to reproduce it (as minimally and precisely as possible):**

This is my coredns conf. I want to forward query to file, if abc.example.com can't find any record on consul. Is there any way to make that.

```
(global_config) {
    prometheus 10.170.16.14:9253
    reload 2s
    log
    errors
}

example.com:53 {
    import global_config
    file /etc/coredns/db-example.com {
      reload 5s
    }
}

abc.example.com:53 {
    import global_config
    forward . 10.170.16.11:8600
    ...?...
}
```

**Comment by chrisohaver** [comment]
There isn't a built in solution.  But you can build CoreDNS with the [_alternate_](https://github.com/coredns/alternate) external plugin which enables thins kind of thing.  It allows coredns to discard answers with certain response codes, e.g. NXDOMAIN, and forward the query to another DNS server (which can be another port CoreDNS is listening to if needed).
