### ISSUE TITLE
Why are internal service names forwarded to the external DNS server first?

### ISSUE THREAD

**Issue by SamDecrock** [miekg/coredns#5031]
Say I have a Kubernetes Service called `mysql`.

When I want to connect to it from another pod I simply use the name `mysql` (not the fqdn). I would expect coredns to see this and resolve it directly to the IP of that service. But it's not. For some reason it wants to forward that name to the DNS server set in my hosts `/etc/resolv.conf` only to get a `NXDOMAIN` and then eventually resolve it. 

This all works well unless your machine is not connected to the internet, then it takes ages for the name to resolve because it first waits for a timeout of the non-existing external DNS server.

Why doesn't resolve that service name directly?

**Comment by chrisohaver** [comment]
Some possible reasons that fit the info provided...

1. Your pod making the query could have `dnsPolicy: default`.  If so, it won't send dns queries to CoreDNS at all, just straight to the node's upstreams.
2. You could be using a dns look up tool that doesn't append search domains by default (like `dig`).
3. mysql could be in a different namespace from the pod, in which case you'd need to search for `mysql.mysqlns` where mysqlns is the name of the mysql namespace.

For 3, The NXDOMAIN would be originated from CoreDNS, not the upstream.

**Comment by SamDecrock** [comment]
Ok, I'm beginning to understand how this DNS resolving works.

1. `dnsPolicy` is not set so it defaults to `dnsPolicy: ClusterFirst`.
2. The python code is using the mysql connector to connect to the database. I'm not sure who is doing the resolving here. https://www.w3schools.com/python/python_mysql_getstarted.asp
3. It's in the same namespace.

**Comment by chrisohaver** [comment]
Another possibility is if the mysql endpoints are not ready (In which case, the NXDOMAIN would be originated from CoreDNS, not the upstream.)

**Comment by johnbelamaric** [comment]
If it's sending "mysql" to CoreDNS, then it's a broken client side resolver
(not using domain/search from resolv.conf).

**Comment by chrisohaver** [comment]
> If it's sending "mysql" to CoreDNS, then it's a broken client side resolver
(not using domain/search from resolv.conf).

@SamDecrock, you can determine what query coredns receives by enabling logging in coredns (add `log` plugin to Corefile).  See https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#are-dns-queries-being-received-processed

**Comment by chrisohaver** [comment]
Another unlikely possibility is if CoreDNS and kubelet are configured to use different cluster domains (the default being `cluster.local.`).

**Comment by SamDecrock** [comment]
I did this test again with dnsmasq as the main DNS server running on the machine itself. I can clearly see incoming service names like `mysql`.

I guess the pods are using a client that doesn't add the search domains like `mysql.<namespace>.svc.cluster.local`. Therefor, some of our components of our software end up being forwarded to the upstream DNS servers.

We can solve this in 4 ways:
- fix the client libraries not respecting the search domains (would be the best solution).
- set `ndots` to `1`. Explained here https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html
- excluding the erroneous non-fqdn in the CoreDNS config.
- remove the upstream DNS servers as the machine isn't connected to the internet anyway.
- add `domain-needed` to the DNSMasq config. It makes sure these plain names like `mysql` are not forwarded upstream (the best solution for my case).
