### ISSUE TITLE
use kube-apiserver proxy endpoint cause: starting server with unsynced Kubernetes API

### ISSUE THREAD

**Issue by Poorunga** [miekg/coredns#5034]
**What happened**:
I opened kube-apiserver proxy, and added the endpoint configuration item of kubernetes in Corefile. Then when I restart coredns, it will prompt "starting server with unsynced Kubernetes API", and coredns cannot resolve the domain name normally like: "kubernetes.default.svc.cluster.local".
I debugged coredns and I found that nsController is not working properly.

**What you expected to happen**:
When I use kube-apiserver proxy as kubernetes endpoint, I hope coredns can work normally.

**How to reproduce it (as minimally and precisely as possible)**:
1. use `kubectl proxy --address=0.0.0.0 --port=8001` to open kube-apiserver proxy
2. add kubernetes.endpoint arg then restart coredns
3. try some dns request:
  - use `dig @127.0.0.1 -p 1053 www.google.com`  ---> success
  - use `dig @127.0.0.1 -p 1053 kubernetes.default.svc.cluster.local`  ---> failed

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 
v1.8.6

- Corefile:
```
.:1053 {
    errors
    health {
       lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       endpoint http://119.8.111.84:8001
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```

- logs, if applicable:
```
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
.:1053
[INFO] plugin/reload: Running configuration MD5 = a480734fafaa7475024387f40ebee5e6
CoreDNS-1.8.6
linux/amd64, go1.16.2,
```

- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Others:

**Comment by Poorunga** [comment]
After my continuous debugging, I found that the code would get stuck at `ok, v := k.endpointSliceSupported(kubeClient)`, making it unable to reach `k.APIConn.Run()`.

https://github.com/coredns/coredns/blob/master/plugin/kubernetes/kubernetes.go#L258-L273:
```
	onStart = func() error {
		go func() {
			if initEndpointWatch {
				// Revert to watching Endpoints for incompatible K8s.
				// This can be removed when all supported k8s versions support endpointslices.
				ok, v := k.endpointSliceSupported(kubeClient)
				if !ok {
					k.APIConn.(*dnsControl).WatchEndpoints(ctx)
				}
				// Revert to EndpointSlice v1beta1 if v1 is not supported
				if ok && v == discoveryV1beta1.SchemeGroupVersion.String() {
					k.APIConn.(*dnsControl).WatchEndpointSliceV1beta1(ctx)
				}
			}
			k.APIConn.Run()    <------  code cannot reach here!!!
		}()

		timeout := time.After(5 * time.Second)
		ticker := time.NewTicker(100 * time.Millisecond)
		defer ticker.Stop()
		for {
			select {
			case <-ticker.C:
				if k.APIConn.HasSynced() {
					return nil
				}
			case <-timeout:
				log.Warning("starting server with unsynced Kubernetes API")
				return nil
			}
		}
	}

```

**Comment by chrisohaver** [comment]
What version of kubernetes are you using?

**Comment by Poorunga** [comment]
@chrisohaver  My k8s version is 1.18.20

**Comment by chrisohaver** [comment]
This is expected behavior if CoreDNS cannot connect to the API at start up.

Can you verify that the API proxy is reachable? e.g. can you connect to the API with kubectl from the same system you are running CoreDNS on?

**Comment by Poorunga** [comment]
When I configure accept-hosts(e.g. kubectl proxy --address='0.0.0.0' --accept-hosts='^*$'), everything is normal, coredns is running very well.

Thank you very much. @chrisohaver
