### ISSUE TITLE
The endpointSliceSupported function adds retries to prevent endless loops

### ISSUE THREAD

**Issue by Poorunga** [miekg/coredns#5036]
endpointSliceSupported will continuously call kubeClient.ServerVersion()

https://github.com/coredns/coredns/blob/0b6356adc5fae139c9a04b154b0a4f2646456e06/plugin/kubernetes/kubernetes.go#L305-L314

This will cause the code to fail to reach k.APIConn.Run()

https://github.com/coredns/coredns/blob/0b6356adc5fae139c9a04b154b0a4f2646456e06/plugin/kubernetes/kubernetes.go#L263-L273

Is it better to increase the number of retries in the code here?

**Comment by chrisohaver** [comment]
> Is it better to increase the number of retries in the code here?

It retries forever since if we can’t connect to the api, then Run will fail. 

Relating to this, this week I plan on adding some throttled logging here so connection errors can be known.

**Comment by Poorunga** [comment]
> Relating to this, this week I plan on adding some throttled logging here so connection errors can be known.

Thank you, I got it.
