### ISSUE TITLE
coredns rewrite in Kubernetes plugin sometimes broken

### ISSUE THREAD

**Issue by szuecs** [miekg/coredns#5063]
**What happened**:
Queries with rewrite in kubernetes plugin seems to fail from time to time.

```
root@zmon-appliance-worker-764bb8bbf4-7xr7d:/app# for i in {0..10}; do dig +short +tcp tracing.platform-infrastructure.example.com; sleep 1; done
10.3.56.205
10.3.56.205
10.3.56.205
10.3.56.205
10.3.56.205
10.3.56.205
10.3.56.205
18.193.175.138
3.121.255.186
18.156.75.37
18.156.75.37
18.193.175.138
3.121.255.186
3.121.255.186
18.156.75.37
18.193.175.138
3.121.255.186
18.156.75.37
18.193.175.138
```

While checking these queries and running tcpdump I observed that if coredns is not hit via TCP 9054, but UDP 9054 it will query upstream resolvers via UDP and not respond with the rewrite. It's not a proof that's true, but an observation that was weird and maybe actually is the issue.

I am sure that coredns is the one querying the upstream resolver as I could track down the client port from which it was sent to coredns client port.
tcpdump who queries 172.31.0.2:53  (upstream)?
```
20:30:50.546957 IP 172.31.0.2.53 > 172.31.10.209.60405: 12983 4/0/1 CNAME tracing.platform-infrastructure.example.com., A 18.156.75.37, A 3.121.255.186, A 18.193.175.138 (145)
```
netstat who is port 60405?
```
root@ip-172-31-10-209:~# netstat -tuapen | grep 60405
udp        0      0 172.31.10.209:60405     172.31.0.2:53           ESTABLISHED 0          5398406    3843/coredns   
```

**What you expected to happen**: response with 10.3.56.205 and no call to upstream resolver

**How to reproduce it (as minimally and precisely as possible)**: unknown

**Anything else we need to know?**:
- 10.3/16 is the Kubernetes service IP range
- All pods are ready, no restart, no other issues like endpoints not ready, pods are in all AZs available, ...
- we have dnsmasq caching in front of coredns (similar to local-dns with conntrack bypass) 

```
root@ip-172-31-10-209:~# iptables-save | grep NOTRACK
-A PREROUTING -s 127.0.0.1/32 -d 127.0.0.1/32 -p udp -m udp --sport 9254 -j NOTRACK
-A PREROUTING -s 127.0.0.1/32 -d 127.0.0.1/32 -p udp -m udp --dport 9254 -j NOTRACK
-A PREROUTING -d 172.31.10.209/32 -p udp -m udp --dport 53 -j NOTRACK
-A PREROUTING -s 127.0.0.1/32 -d 127.0.0.1/32 -p tcp -m tcp --sport 9254 -j NOTRACK
-A PREROUTING -s 127.0.0.1/32 -d 127.0.0.1/32 -p tcp -m tcp --dport 9254 -j NOTRACK
-A PREROUTING -d 172.31.10.209/32 -p tcp -m tcp --dport 53 -j NOTRACK
-A OUTPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -p udp -m udp --sport 9254 -j NOTRACK
-A OUTPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -p udp -m udp --dport 9254 -j NOTRACK
-A OUTPUT -s 172.31.10.209/32 -p udp -m udp --sport 53 -j NOTRACK
-A OUTPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -p tcp -m tcp --sport 9254 -j NOTRACK
-A OUTPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -p tcp -m tcp --dport 9254 -j NOTRACK
-A OUTPUT -s 172.31.10.209/32 -p tcp -m tcp --sport 53 -j NOTRACK
```

**Environment**:  Kubernetes

- the version of CoreDNS: v1.8.4
- Corefile:
```
ingress.cluster.local:9254 {

    template IN A {
        match "^.*[.]ingress[.]cluster[.]local"
        answer "{{ .Name }} 60 IN A 10.3.99.99"
        fallthrough
    }
    template IN AAAA {
        rcode NOERROR
    }
    prometheus :9153
    ready :9155
}


# 10.2.0.0/16, 10.3.0.0/16 defines that this server is authority for revese
# lookups for these ranges.
cluster.local:9254 10.2.0.0/16:9254 10.3.0.0/16:9254 tracing.platform-infrastructure.example.com:9254 {
    errors

    rewrite name exact tracing.platform-infrastructure.example.com trace-collector-{$ZONE}.tracing.svc.cluster.local

    kubernetes {
        pods insecure
    }
    cache 30

    log svc.svc.cluster.local.

    prometheus :9153
    ready :9155
}

.:9254 {
    errors
    health :9154 # this is global for all servers
    ready :9155
    prometheus :9153

    forward . /etc/resolv.conf {
      max_concurrent 2000
    }

    pprof 127.0.0.1:9156
    cache 30
    reload
}
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by chrisohaver** [comment]
> **How to reproduce it (as minimally and precisely as possible):** unknown

By this do you mean that you have not tried to reproduce this minimally, or that you have tried, and have not been able to reproduce the issue?  If you have tried, can you describe what you have tried?

**Comment by chrisohaver** [comment]
What type of k8s Service is `trace-collector-{$ZONE}.tracing.svc.cluster.local`?

https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

**Comment by szuecs** [comment]
> What type of k8s Service is `trace-collector-{$ZONE}.tracing.svc.cluster.local`?
> 
> https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

ClusterIP

Look like this:

```
% kubectl -n tracing get svc
trace-collector-eu-central-1a       ClusterIP   10.3.56.205  <none>        8443/TCP,8444/TCP,8445/TCP   19d
trace-collector-eu-central-1b       ClusterIP   10.3.226.240   <none>        8443/TCP,8444/TCP,8445/TCP   19d
trace-collector-eu-central-1c       ClusterIP   10.3.4.32      <none>        8443/TCP,8444/TCP,8445/TCP   19d
```

> > **How to reproduce it (as minimally and precisely as possible):** unknown
> 
> By this do you mean that you have not tried to reproduce this minimally, or that you have tried, and have not been able to reproduce the issue? If you have tried, can you describe what you have tried?

I did not test other setups, yet. I can see the same error happens in different clusters with the same configuration.

**Comment by chrisohaver** [comment]
The symptoms described imply a failure to route the initial incoming query to the correct server block.  That is, if coredns answers with something from an upstream dns, it means the query must have been routed to the `.:9254` block because it's the only block with a _forward_ plugin defined.

I think though that this is pretty unlikely, and that something else is probably at play (e.g. suspect queries not passed through CoreDNS).  There _is_ an unusual case where use of the *bind* plugin can cause multiple blocks to listen to the same zone+port, and result in unpredictable query routing.  But _bind_ is not used here. 

What do CoreDNS logs show when the wrong answer is returned? (would need to add logging in `.:9254` block).

**Comment by szuecs** [comment]
@chrisohaver thanks, logging enabled showed the issue, an interesting one so I document it here. No coredns issue!

Suppose you have a `tracing.bar.example.org` and a rewrite:
```
rewrite name exact tracing.bar.example.org trace-collector-{$ZONE}.tracing.svc.cluster.local
```

Log after that the query changed the results to the non rewrite A records of `tracing.bar.example.org.`:
```
[INFO] 127.0.0.1:61716 - 28658 "A IN tracing.foo.example.org. udp 63 false 4096" NOERROR qr,rd,ra 284 0.001297499s
```

The issue was a CNAME:
```
tracing.foo.example.org. 30      IN      CNAME    tracing.bar.example.org.
```
The trailing dot is not matched in the rewrite config, so the cache has now the upstream result so all resolutions of `tracing.bar.example.org` (without trailing dot) are cached and resolved to the upstream and not to the rewrite.
