### ISSUE TITLE
Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout

### ISSUE THREAD

**Issue by xyc2019** [miekg/coredns#5072]
I added a new Node on k8s cluster, but the coredns pod can not running because of the error as below:

Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
-------------------
When I entered into a pod on new Node and execute Ping command:
ping: www.google.com: Temporary failure in name resolution

**Comment by chrisohaver** [comment]
Looks like the network isn’t set up properly on the new node.
