### ISSUE TITLE
The kind of HTTP Redirect function ,  have any plans to do it ?

### ISSUE THREAD

**Issue by victory460** [miekg/coredns#5073]
We found many cloud service vendor contain the HTTP Redirect function in their dns product. For example: [oracle-dns](https://docs.oracle.com/en-us/iaas/Content/DNS/Tasks/httpredirect.htm)
Beside, this feature does have some demand. 
Does coredns team have a plan to do the kind of function?  if so, I would like to join it.

**Comment by chrisohaver** [comment]
CoreDNS already has the _rewrite_ plugin, which can map zones to alternate zones.  However this is a DNS server, so it effectively applies to all protocols.   An HTTP redirect applies to only the HTTP protocol.   A DNS server cannot know what protocol a resolver is going to use after it gets an IP address for a requested name.

**Comment by chrisohaver** [comment]
I think it's odd that Oracle includes this configuration under its "DNS" section.  I presume it's because it also allows optional configuration of a DNS "alias" for the moved zone (which can be accomplished with the _rewrite_ plugin in CoreDNS). The primary function of the feature is about redirecting HTTP traffic, so it seems misplaced.

**Comment by victory460** [comment]
> I think it's odd that Oracle includes this configuration under its "DNS" section. I presume it's because it also allows optional configuration of a DNS "alias" for the moved zone (which can be accomplished with the _rewrite_ plugin in CoreDNS). The primary function of the feature is about redirecting HTTP traffic, so it seems misplaced.

Thanks your answer.

**Comment by victory460** [comment]
> CoreDNS already has the _rewrite_ plugin, which can map zones to alternate zones. However this is a DNS server, so it effectively applies to all protocols. An HTTP redirect applies to only the HTTP protocol. A DNS server cannot know what protocol a resolver is going to use after it gets an IP address for a requested name.

Thanks. But use the the _rewrite_ plugin can not process this scenes:

`github.com` redirect to  `google.com/test/a`

**Comment by chrisohaver** [comment]
> Thanks. But use the the _rewrite_ plugin can not process this scenes:
> 
> `github.com` redirect to `google.com/test/a`

That is impossible to do with DNS.

**Comment by victory460** [comment]
> > Thanks. But use the the _rewrite_ plugin can not process this scenes:
> > `github.com` redirect to `google.com/test/a`
> 
> That is impossible to do with DNS.

👍 Thank you for your patient explanation it.

**Comment by chrisohaver** [comment]
IOW, the feature you are requesting isn’t feasible to implement using DNS.
