### ISSUE TITLE
Allow caching upstreams’ SERVFAIL to be turned off

### ISSUE THREAD

**Issue by xh4n3** [miekg/coredns#5074]
Hi guys, I need some thoughts about caching upstreams’ SERVFAIL error.

In my case, we have applications queries domains on the internet, the path is like：

```
app -> coredns -> multiple local dns-servers -> authoritative dns servers on the internet
```

The local dns-servers sometime cannot talk to/from authoritative dns servers due to a lot reasons, upstream rate limiting or a sudden network error. In such cases, a SERVFAIL response will be sent to coredns.

The current behavior of coredns is always caching SERVFAIL for minTTL, i.e. 5 seconds. When this cache goes in, any following queries will be responded with a cached SERVFAIL within 5 seconds, instead of trying again or trying different local dns-server.

So if this is the case, the attempts in resolv.conf at client side doesn't make any sense at all. Should we consider make this SERVFAIL caching TTL configurable via minnttl? Setting minnttl to zero will let app to retry on SERVFAIL. 

Code is here https://github.com/coredns/coredns/blob/master/plugin/cache/cache.go#L157

Related: #3927 #2720

Thanks!

**Comment by chrisohaver** [comment]
> Can caching upstreams’ SERVFAIL turned off?

It cannot. (Not without disabling cache entirely)

> So if this is the case, the attempts in resolv.conf at client side doesn't make any sense at all.

I think the resolv.conf system resolver behavior only does a retry if there is a timeout.  A SERVFAIL answer, from cache or not, would satisfy the resolver, and it will not retry.

An _application_ might separately implement a retry itself (presumably with a considerate delay between retries).  In which case it should get an updated answer once the cache entry expires.

Possible solutions:
* Adding an option to the _cache_ plugin, to disable negative cache (which includes SERVFAIL). This has been proposed before, but rejected.

* Adding an option to the _cache_ plugin, to disable caching of SERVFAIL responses.

* Write a new plugin that rewrites SERVFAIL response codes to some other error response code that is not cached (one categorized as `OtherError` by `response.Typify`). This solution is kind of off-the-wall, but it's a way of stepping around the issue without making changes to CoreDNS's current plugins.

**Comment by xh4n3** [comment]
Hi @chrisohaver , thanks for you reply!

> * Adding an option to the _cache_ plugin, to disable negative cache (which includes SERVFAIL). This has been proposed before, but rejected.

May I know why this was rejected? Sorry, I haven't found the issue or pr you're referring to.

> * Adding an option to the _cache_ plugin, to disable caching of SERVFAIL responses.

I do not know why we were caching SERVFAIL for 5 seconds, just a personal decision I guess? IMHO, both a configurable SERVFAIL caching TTL and a new boolean option to switch it off are good ideas. We can keep 5 seconds caching as a default, so no one will be surprised.

I can submit an PR regarding this shortly, how do you think? @chrisohaver

**Comment by chrisohaver** [comment]
> May I know why this was rejected? Sorry, I haven't found the issue or pr you're referring to.

https://github.com/coredns/coredns/pull/2883

> I can submit an PR regarding this shortly, how do you think? @chrisohaver

I recommend getting a green light from @miekg before proceeding that way.

**Comment by xh4n3** [comment]
Hi @miekg,
I'm requesting this feature because we sometimes come across some random SERVFAIL responses from our local dns-servers, due to the network or single server performance, etc. Those SERVFAILs are very rare, and often the records returns NOERROR in a second try.
We have some apps use coredns as dns server, some apps use local dns-servers directly. Now apps do not use coredns faces much less failures. I guess this 5 seconds SERVFAIL cache is the cause.

**Comment by chrisohaver** [comment]
I think it's reasonable to add this as an option.  The DNS negative cache RFC 2308 says that a negative cache MAY cache a SERVFAIL response (which means it may also _not_ cache them). There are valid arguments for both caching and not caching SERVFAIL responses, so it's reasonable to make this configurable.
