### ISSUE TITLE
plugin/secondary: Support retrying configuration for retrieval of failed `secondary` records 

### ISSUE THREAD

**Issue by Seelengrab** [miekg/coredns#5089]
**What would you like to be added**:

An option/setting for configuring a "retry" of retrieving records specified in `secondary`/`transfer` blocks, either with a longer timeout, periodically or until successful (since after that point, the secondary will notify the primary).

**Why is this needed**:

This supports setups where a name server acts as a DNS entry point who's retrieving records of subdomains in order to minimize latency by requiring fewer network hops. When retrieving records from a primary name server at startup and the network is not available for an extended amount of time, the records are never tried to be retrieved at a later date (after 10s, if I read the source correctly), even if the network in question does come back up.

**Comment by chrisohaver** [comment]
I believe the request here is to make the initial retrieval timeout and retry period configurable in `/plugin/secondary/setup.go`, currently hard coded to 10s, and 0.25s respectively.

https://github.com/coredns/coredns/blob/83021637b35b0ef0ba09640e6f3d902cad8cdfb7/plugin/secondary/setup.go#L32-L49

**Comment by Seelengrab** [comment]
Yes, precisely. Having both "how long until the next retry" and "how often should it be retried (or forever)" available would be nice. The latter in particular would be helpful, as network outages that prevent synchronization may be much longer than 10s e.g. due to a power outage.

**Comment by moolitayer** [comment]
> **What would you like to be added**:
> 
> An option/setting for configuring a "retry" of retrieving records specified in `secondary`/`transfer` blocks, either with a longer timeout, periodically or until successful (since after that point, the secondary will notify the primary).
> 
> **Why is this needed**:
> 
> This supports setups where a name server acts as a DNS entry point who's retrieving records of subdomains in order to minimize latency by requiring fewer network hops. When retrieving records from a primary name server at startup and the network is not available for an extended amount of time, the records are never tried to be retrieved at a later date (after 10s, if I read the source correctly), even if the network in question does come back up.

Not exactly. The refresh does not stop after 10 seconds. In `coredns/plugin/secondary/README.md` we have

~~~
If the primary server(s) don't respond when CoreDNS is starting up, the AXFR will be retried
indefinitely every 10s.
~~~

See this from my local run:
~~~
example.org.:50000
CoreDNS-1.9.1
linux/amd64, go1.18.1, 0622a6c6
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.0.1.1:53"': dial tcp 10.0.1.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.1.2.1:53"': dial tcp 10.1.2.1:53: i/o timeout
[WARNING] plugin/secondary: All 'example.org.' masters failed to transfer, retrying in 250ms: dial tcp 10.1.2.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.0.1.1:53"': dial tcp 10.0.1.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.1.2.1:53"': dial tcp 10.1.2.1:53: i/o timeout
[WARNING] plugin/secondary: All 'example.org.' masters failed to transfer, retrying in 500ms: dial tcp 10.1.2.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.0.1.1:53"': dial tcp 10.0.1.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.1.2.1:53"': dial tcp 10.1.2.1:53: i/o timeout
[WARNING] plugin/secondary: All 'example.org.' masters failed to transfer, retrying in 1s: dial tcp 10.1.2.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.0.1.1:53"': dial tcp 10.0.1.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.1.2.1:53"': dial tcp 10.1.2.1:53: i/o timeout
[WARNING] plugin/secondary: All 'example.org.' masters failed to transfer, retrying in 2s: dial tcp 10.1.2.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.0.1.1:53"': dial tcp 10.0.1.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.1.2.1:53"': dial tcp 10.1.2.1:53: i/o timeout
[WARNING] plugin/secondary: All 'example.org.' masters failed to transfer, retrying in 4s: dial tcp 10.1.2.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.0.1.1:53"': dial tcp 10.0.1.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.1.2.1:53"': dial tcp 10.1.2.1:53: i/o timeout
[WARNING] plugin/secondary: All 'example.org.' masters failed to transfer, retrying in 8s: dial tcp 10.1.2.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.0.1.1:53"': dial tcp 10.0.1.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.1.2.1:53"': dial tcp 10.1.2.1:53: i/o timeout
[WARNING] plugin/secondary: All 'example.org.' masters failed to transfer, retrying in 10s: dial tcp 10.1.2.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.0.1.1:53"': dial tcp 10.0.1.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.1.2.1:53"': dial tcp 10.1.2.1:53: i/o timeout
[WARNING] plugin/secondary: All 'example.org.' masters failed to transfer, retrying in 10s: dial tcp 10.1.2.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.0.1.1:53"': dial tcp 10.0.1.1:53: i/o timeout
[ERROR] plugin/file: Failed to setup transfer `example.org.' with `"10.1.2.1:53"': dial tcp 10.1.2.1:53: i/o timeout
[WARNING] plugin/secondary: All 'example.org.' masters failed to transfer, retrying in 10s: dial tcp 10.1.2.1:53: i/o timeout
~~~

The first retry happens after 250ms. Then 500ms, then 1s and then 2s. Doubling each time until the maximum of 10s is reached. From that point on there is a retry every 10 sec forever.

@chrisohaver I can add the configuration you mentioned if that's desireable, but I beleive the behaviour @Seelengrab is interested in is already in place. I beleive this issue can be closed.

**Comment by chrisohaver** [comment]
@moolitayer, yes that's right, I didn't look at the code carefully.  

 Thanks for testing it!

Since the the feature is already in place, there is no need to make the values configurable.

@Seelengrab, there must be something else wrong with your configuration or environment if the transfer is never successful.

**Comment by Seelengrab** [comment]
The case we observed was quite some time ago (I may be able to figure out which version it was on), but I don't think I saw the behavior you describe in my logs (there never was a retry after some tries). It may be that we initially had a successful initial transfer, which then didn't happen again after a network outage & subsequent update on the primary server. I'd have to check the logs, but since this happened in production I'd say the case of "initial transfer successful, then failures after a network outage" is likely. Could it be that there's some connection caching going in that doesn't reestablish after an outage?

I'll see if I can check logs soon-ish.

**Comment by chrisohaver** [comment]
> "initial transfer successful, then failures after a network outage" is likely.

OK, it could be that. A failed transfer as a result of a NOTIFY is _not_ re-tried.  So the zone would not be updated until the next time the zone is updated based on the SOA refresh timer (which can be a long interval).

It may be that we aren't handling receiving a NOTIFY correctly.  The RFC describes the secondary entering a zone refresh state when a NOTIFY is received.  In this case it should be retrying on the interval defined by the SOA retry.  IOW - When receiving a NOTIFY, we should signal to the secondary zone's update go routine that it's time to do another refresh.  As currently implemented, receiving a NOTIFY results in a single ad hoc zone transfer attempt done asynchronously with the zone update process.  Having the update go routine do the actual transfer would also avoid doubling up transfer requests when a notify comes in at the same time the zone is due to be refreshed. (I'm relying on fuzzy memory and code skimming - so I could be wrong here)

Logs would help identify the precise nature of the failure.

**Comment by Seelengrab** [comment]
Well, sorry for only getting back to this late, but I sadly can't provide logs showing the behavior.. I'll keep an eye out and if it happens again, I'll see if I can catch it.
