### ISSUE TITLE
how to make CoreDNS conditional resolve depending on the domain name

### ISSUE THREAD

**Issue by zffocussss** [miekg/coredns#5094]
Hi team:
    I have a question below.
    Provided, there is a domain abc.com,which all of its subdomains are private in local DNS(in a file zone),except a particular one which is external.abc.com,it is a public internet host.
   can coredns resovle them in a corefile config.
   I have try forward plugin ,but it failed.
  
   a1.abc.com a2.abc.com in local private dns
   external.abc.com is registered in other place.

**Comment by chrisohaver** [comment]
One way to do it is to set up two server blocks …

```
external.abc.com {
  forward …
}

abc.com {
  file …
}

```

**Comment by zffocussss** [comment]
> 
I am not sure if it can work,as external.abc.com is a single domain,not a subdomain..

in other side,Can I use forward/except to route them?

**Comment by chrisohaver** [comment]
Give an example query and desired behavior that you think won’t work.

**Comment by chrisohaver** [comment]
Not quite sure what you want - description is short and a bit loose - could fit several meanings. Concrete examples would help.

**Comment by zffocussss** [comment]
@chrisohaver , I saw that forward plugin have a keyword "except",I expect it can forward all the subdomain except a single one domain,and make it resovled by other plugins.

**Comment by chrisohaver** [comment]
Still unclear what you want to do. Again, examples would help.

Do you require external.abc.com to be resolved by an upstream dns, but foo.external.abc.com to be resolved internally?

**Comment by chrisohaver** [comment]
> Do you require external.abc.com to be resolved by an upstream dns, but foo.external.abc.com to be resolved internally?

Assuming yes.

> I saw that forward plugin have a keyword "except",I expect it can forward all the subdomain except a single one domain,and make it resovled by other plugins.

Yes, it does, but it's can't be used like you say, since _forward_ is the last plugin in the plugin chain (`plugin.cfg`) that is capable of responding.  That is, if you use `except`, then a query for that name will always result in a SERVFAIL, and a "no next plugin" error will be logged.

Barring custom compiled versions of CoreDNS, I'm not sure what the practical use case for `except` is.  If _forward_ allowed more than one declaration per server block, it could come in handy if it the query was passed through to the next _forward_ declaration.  But only one _forward_ plugin is permitted per server block.  It's possible that external plugins could be added to `plugin.cfg` after _forward_, in which case it could be useful.

**Comment by chrisohaver** [comment]
> forward is the last plugin in the plugin chain (plugin.cfg) that is capable of responding. 

Actually, there is _grpc_, which gets executed after _forward_, and is much like _forward_ itself, except that it send queries upstream via GRPC.  So there is a use case there.  _forward_ and _grpc_ could be chained together with self forwarding to a local grpc listener to get the desired effect.  But IMO it's too much of a hack to be seriously considered.

**Comment by zffocussss** [comment]
thanks

**Comment by zffocussss** [comment]
> 

yes

**Comment by zffocussss** [comment]
> Still unclear what you want to do. Again, examples would help.
> 
> Do you require external.abc.com to be resolved by an upstream dns, but foo.external.abc.com to be resolved internally?

yes

**Comment by m1iktea** [comment]
> Still unclear what you want to do. Again, examples would help.
> 
> Do you require external.abc.com to be resolved by an upstream dns, but foo.external.abc.com to be resolved internally?

hi , I have the same problem now,
I want to require out1.abc.com out2.abc.com outn.abc.com to be resolved by an upstream dns, but inside1.abc.com inside2.abc.com insiden.abc.com to be resolved internally 
This is my configfile, but not work
`corefile`
```
abc.com {
   file /etc/coredns/db.abc.com
   reload 30s
   log
   forward . 8.8.8.8
}
```
`db.abc.com`
```
$ORIGIN abc.com.
@	3600 IN	SOA sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600
	3600 IN NS a.iana-servers.net.
	3600 IN NS b.iana-servers.net.

@                      IN  NS    ns1
ns1                    IN  A     192.168.1.22
@                      IN  A     192.168.1.22
inside1                IN  A     192.168.1.22
inside2                IN  A     192.168.1.22
inside3                IN  A     192.168.1.22
inside4                IN  A     192.168.1.22
...
```
