### ISSUE TITLE
v1.8.7 build fail with go1.16 

### ISSUE THREAD

**Issue by uucloud** [miekg/coredns#5095]
**What happened**:
```
➜  coredns git:(master) make
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=a9adfd56" -o coredns
sigs.k8s.io/json/internal/golang/encoding/json
# sigs.k8s.io/json/internal/golang/encoding/json
../../pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
../../pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
make: *** [coredns] Error 2
```

**What you expected to happen**:
Get a coredns.

**How to reproduce it (as minimally and precisely as possible)**:
build v1.8.7 with go1.16

**Anything else we need to know?**:
I've solved this problem by upgrading Go to v1.17.5 but I don't know why.

**Environment**:

- the version of CoreDNS: v1.8.7
- Corefile: N/A
- logs, if applicable: N/A
- OS (e.g: `cat /etc/os-release`):  macOS Big Sur 11.6.2
- Others:

**Comment by yuvalta** [comment]
Hi, 
I've encountered the same issue. `sigs.k8s.io/json` min go version is `1.17`.
See this issue from `kubernetes-sigs/json` repo: [sf.Exported undefined](https://github.com/kubernetes-sigs/json/issues/11).
