### ISSUE TITLE
Unable to resolve CNAMEs which point to hosts in cluster.local

### ISSUE THREAD

**Issue by rmoe** [miekg/coredns#5105]
**What happened**:
I'm not able to resolve CNAMEs that point to hosts in `cluster.local`. I have a DNS record `service-local.mydomain.com` which is a CNAME with a value of `service.service-ns.svc.cluster.local`. From any pod inside the cluster when I try to resolve `service-local.mydomain.com` I don't get the A record for `service.service-ns.svc.cluster.local`. E.g., from a test pod in my cluster:

```
root@test:/# dig service-local.mydomain.com  

; <<>> DiG 9.9.5-9+deb8u19-Debian <<>> service-local.mydomain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 58505
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;service-local.mydomain.com. IN A

;; ANSWER SECTION:
service-local.mydomain.com. 30 IN CNAME	service.service-ns.svc.cluster.local.

;; AUTHORITY SECTION:
.			30	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2022011900 1800 900 604800 86400

;; Query time: 7 msec
;; SERVER: 172.21.0.10#53(172.21.0.10)
;; WHEN: Wed Jan 19 19:49:24 UTC 2022
;; MSG SIZE  rcvd: 240
```
I only get one answer which isn't the case for any other CNAME whose value is a domain other than `cluster.local`.

```
root@test:/# dig dl-cdn.alpinelinux.org

; <<>> DiG 9.9.5-9+deb8u19-Debian <<>> dl-cdn.alpinelinux.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28823
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dl-cdn.alpinelinux.org.		IN	A

;; ANSWER SECTION:
dl-cdn.alpinelinux.org.	30	IN	CNAME	dualstack.d.sni.global.fastly.net.
dualstack.d.sni.global.fastly.net. 30 IN A	146.75.30.133

;; Query time: 37 msec
;; SERVER: 172.21.0.10#53(172.21.0.10)
;; WHEN: Wed Jan 19 20:21:10 UTC 2022
;; MSG SIZE  rcvd: 169
```

and I'm able to resolve `service.service-ns.svc.cluster.local` from the same host.

```
root@test:/# dig service.service-ns.svc.cluster.local

; <<>> DiG 9.9.5-9+deb8u19-Debian <<>> service.service-ns.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6304
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;service.service-ns.svc.cluster.local.	IN A

;; ANSWER SECTION:
service.service-ns.svc.cluster.local.	24 IN A	172.21.243.207

;; Query time: 2 msec
;; SERVER: 172.21.0.10#53(172.21.0.10)
;; WHEN: Wed Jan 19 20:00:25 UTC 2022
;; MSG SIZE  rcvd: 121

```
**What you expected to happen**:
When resolving `service-local.mydomain.com` I expect a second answer with the A record for `service.service-ns.svc.cluster.local`.

**How to reproduce it (as minimally and precisely as possible)**:
Create a CNAME record which points to some host in `cluster.local` and attempt to resolve that hostname from inside the cluster.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.8.6
- Corefile:
```
    .:53 {
        errors
        health {
            lameduck 10s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
This is expected.  The upstream name server doesn't know how to handle the `cluster.local.` zone, and configuring that would be somewhat complicated and problematic.

Another approach that _doesn't_ involve the upstream nameserver, is to add a `rewrite` rule in in CoreDNS that rewrites `service-local.mydomain.com.` to	`service.service-ns.svc.cluster.local.`.  This can be added to the CoreDNS corefile. See https://github.com/coredns/coredns/blob/master/plugin/rewrite/README.md

Note if you have node-local dns deployed, the rewrite rule has to go in the node local configs, not the cluster deployment config.

**Comment by rmoe** [comment]
Thanks for the quick response. We'll look for alternative solutions. I'm far from a DNS expert so maybe you can help me understand what's happening here. Is the issue that the second lookup to get the A record happens on the server upstream from coredns?

**Comment by chrisohaver** [comment]
> Thanks for the quick response. We'll look for alternative solutions. I'm far from a DNS expert so maybe you can help me understand what's happening here. Is the issue that the second lookup to get the A record happens on the server upstream from coredns?

Yes. The rewrite solution I described should work for you.

**Comment by rmoe** [comment]
> Yes. The rewrite solution I described should work for you.

Great, thank you for the help.
