### ISSUE TITLE
error information appears when configure an ipv6 address in config file

### ISSUE THREAD

**Issue by aa51513** [miekg/coredns#5106]
**What happened**:
when configure an ipv6 address in configuration file , it tells an error

**What you expected to happen**:
work  normally

**How to reproduce it (as minimally and precisely as possible)**:
use my configuration file (below)

**Anything else we need to know?**:
Nothing else

**Environment**:
linux/amd64

- the version of CoreDNS:  CoreDNS-1.8.7
- Corefile:
.:53 {
    bind 127.0.0.1
    forward . tls://[2001:4860:4860::8888] tls://[2001:4860:4860::8844] {
        tls_servername dns.google
		force_tcp
		max_fails 3
    }
    cache 1
}
- logs, if applicable:
2022-01-20T12:49:28.115953000Z plugin/forward: not an IP address or file: "[2001:4860:4860::8888]"
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
- Others:

**Comment by chrisohaver** [comment]
Brackets are only used when specifying a port for an ipv6 address. The following should work:

`forward . tls://2001:4860:4860::8888 tls://2001:4860:4860::8844`

**Comment by aa51513** [comment]
> Brackets are only used when specifying a port for an ipv6 address. The following should work:
> 
> `forward . tls://2001:4860:4860::8888 tls://2001:4860:4860::8844`

thank you，it works
