### ISSUE TITLE
A few questions...

### ISSUE THREAD

**Issue by cyrillpetroff** [miekg/coredns#5112]
Have a good day! I have two questions. Firstly, is there an option or how to make coredns only process the A-record for my zones (does not respond to other requests like TXT, MX, etc.)
And the second question is how to do this correctly:
```
.:53 {
bind eth0
    rewrite name regex (.*)\.track\.evada\.gun\.vn {1} answer auto
    forward . dns://208.67.222.222 {
    prefer_udp
    }
    cache 30
    log
    errors
}
```
This workss, but there is a lot of junk traffic. the idea is to make requests like google.com.track.evada.gun.vn coreds redirect requests to google.com.

And this is not working anymore:
```
.track.evada.gun.vn:53 {
    bind eth0
    rewrite name regex (.*)\.track\.evada\.gun\.vn {1} answer auto
    forward . dns://208.67.222.222 {
    prefer_udp
    }
    cache 30
    log
    errors
}
```

**Comment by chrisohaver** [comment]
> Firstly, is there an option or how to make coredns only process the A-record for my zones (does not respond to other requests like TXT, MX, etc.)

Depends on what you mean by "do not respond." 

If you mean to respond negatively, then you could use the _template_ plugin to return NXDOMAIN or NOERROR with empty answer for specific types, but you'd need to create a rule for each type (no way to say "not A" in templates).

Not responding at all for certain types, leaving the client to time out, is not possible with built in plugins.  It is possible with the firewall external plugin: https://github.com/coredns/policy.

> And the second question is ...  this is not working anymore:
> `.track.evada.gun.vn:53 { `

The leading dot here will prevent routing your queries to that server block. i.e. `track.evada.gun.vn:53 {` should work.

**Comment by cyrillpetroff** [comment]
> If you mean to respond negatively, then you could use the template plugin to return NXDOMAIN or NOERROR with empty answer for specific types, but you'd need to create a rule for each type (no way to say "not A" in templates).

Now I understand. Thank you.

> The leading dot here will prevent routing your queries to that server block. i.e. track.evada.gun.vn:53 { should work.

`track.evada.gun.vn:53 {`
If you do this, then some.domain.track.evada.gun.vn will not work with regex rewrite

**Comment by chrisohaver** [comment]
> If you do this, then `some.domain.track.evada.gun.vn` will not work with regex rewrite

It will. Try it.

**Comment by cyrillpetroff** [comment]
> It will. Try it.

Wow, it really works. Problem solved. The topic can be closed.
