### ISSUE TITLE
i/o timeout inside the logs kubernetes coredns

### ISSUE THREAD

**Issue by walter-heestermans-toyota** [miekg/coredns#5179]
I we see the following message inside logs coredns pod

[ERROR] plugin/errors: 2 svc-datadog-agent-dogstatsd.datadog-agent.toyota-europe.com. SRV: read udp 192.168.86.18:56917->150.45.86.241:53: i/o timeout

What are possible causes?

**Comment by chrisohaver** [comment]
A dns response was not received from 150.45.86.241. This could be because one of the following:
1. the request never reached 150.45.86.241 (e.g. dropped by firewall)
2. 150.45.86.241 ignored the request
3. the response never reached coredns (e.g. dropped by firewall)
