### ISSUE TITLE
Coredns's kubernetes plugin is not automatically reloading certificates.

### ISSUE THREAD

**Issue by mplzik** [miekg/coredns#5190]
**What happened**:

After kubernetes certificate rotation (i.e. https://docs.microsoft.com/en-us/azure/aks/certificate-rotation#rotate-your-cluster-certificates), coredns's kubernetes plugin stopped answering queries, failing with errors like:

```
E0215 10:17:40.406501       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get [https://hidden.hcp.centralus.azmk8s.io:443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0](https://hidden.hcp.centralus.azmk8s.io/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0): x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
```
instead.

**What you expected to happen**:

After certificates are rotated, `coredns` should pick up the change in certificates mounted as TLS secrets and update the k8s connection parameters accordinglt

**How to reproduce it (as minimally and precisely as possible)**:

1. Spin up a kubernetes cluster
2. Launch `coredns` in the cluster, with k8s secrets mounted to the pod and actively used to access the k8s API
3. Rotate k8s cluster certificates
4. `coredns`'s kubernetes plugin should be failing to access the kubernetes API
5. Restart the `coredns` pod
6. `coredns`'s kubernetes plugin should successfully resolving domain names.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.6.2
- Corefile:

```
...
    hidden.local:53 {
        errors
        cache 30
        loop
        reload
        loadbalance
        kubernetes hidden.local {
          endpoint https://hidden.hcp.centralus.azmk8s.io:443
          kubeconfig /etc/coredns/kubeconfig hidden
          pods verified
        }
    }
...
```
- logs, if applicable:
```
2022-02-15 10:27:50 | E0215 10:27:50.660450       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://hidden.hcp.centralus.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
-- | --
  |   | 2022-02-15 10:27:50 | E0215 10:27:50.660450       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://hidden.hcp.centralus.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
  |   | 2022-02-15 10:27:50 | E0215 10:27:50.660450       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://hidden.hcp.centralus.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
  |   | 2022-02-15 10:27:51 | [INFO] SIGTERM: Shutting down servers then terminating
...
  |   | 2022-02-15 10:27:59 | hidden.local.:53
  |   | 2022-02-15 10:27:59 | dev-us-east-0.local.:53
  |   | 2022-02-15 10:27:59 | .:53
...
  |   | 2022-02-15 10:27:59 | 2022-02-15T10:27:59.556Z [ERROR] plugin/errors: 2 4397468498566913564.2394199031892779446. HINFO: plugin/loop: no next plugin found
  |   | 2022-02-15 10:27:59 | 2022-02-15T10:27:59.557Z [INFO] plugin/reload: Running configuration MD5 = 5e36cdb189fe3c2aa49f7d97569ea366
  |   | 2022-02-15 10:27:59 | 2022-02-15T10:27:59.557Z [INFO] CoreDNS-1.6.2
  |   | 2022-02-15 10:27:59 | 2022-02-15T10:27:59.557Z [INFO] linux/amd64, go1.12.8, 795a3eb
  |   | 2022-02-15 10:27:59 | CoreDNS-1.6.2
  |   | 2022-02-15 10:27:59 | linux/amd64, go1.12.8, 795a3eb

```

- OS (e.g: `cat /etc/os-release`): `coredns` docker image: coredns/coredns:1.6.2
- Others: Despite of this being an older version of coredns, I couldn't find any code that would refresh the credentials in neither coredns nor client-go codebase.

**Comment by chrisohaver** [comment]
Please clean up the description formatting. It's hard to read: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.

**Comment by chrisohaver** [comment]
Try removing the `endpoint` and `kubeconfig` options, these should only be used when coredns is not running in the API endpoint's cluster. Specifying them will supersede the environment variables client-go uses by default.

> I couldn't find any code that would refresh the credentials in neither coredns nor client-go codebase.

IIUC, the mechanism is that client-go watches will fail when the certs are no longer valid, and attempt to re-establish the watches.  Once the mounted certs are valid, the re-attempts will succeed.

**Comment by mplzik** [comment]
Apologies for the delay. I cleaned up the logs to make them a bit more readable. As for removing `endpoints` and `kubeconfig`, that's not something we can do -- the use-case for coredns in this case is to provide cross-cluster DNS resolution, where we provide it with a secret (and kubeconfig) that allows coredns to reach external kube apiservers.

**Comment by chrisohaver** [comment]
Is your expectation that after rotating certs in the "external" cluster, a kubeconfig file with the previous certs used by a pod "local" cluster will be updated automatically?  by CoreDNS?

**edit:** I think I incorrectly interpreted the steps in the description as "expectations" due to the use of word "should".  I think the expectation is that that the API connection will be re-loaded when the certs in the kubeconfig change (the kubeconfig itself being updated by some other cert rotation process, not CoreDNS).

**Comment by chrisohaver** [comment]
Does the latest release of CoreDNS solve this?  

There was an update to client-go that seems closely related: https://github.com/kubernetes/kubernetes/pull/79083

CoreDNS 1.6.2 (3 years ago) was released before that merged (2 years ago).

**Comment by mplzik** [comment]
This has now been verified to work correctly with coredns 1.9.1 . Closing this issue.
