### ISSUE TITLE
CoreDNS not resolving API gateway domain from pods 

### ISSUE THREAD

**Issue by Hassnain-Alvi** [miekg/coredns#5192]
I am using coredns in EKS and I am able to fix Route 53 domain resolution issue using route 53 plugin. 
CoreDNS is still not able to resolve one domain and it's API Gateway domain. My API Gateway is linked with lambda and accessible on the internet using Amazon link. When pods try to call their lambda they get name or host not known error.

In CoreDNS logs I saw that on each query it return NXDOMAIN error. How can I fix it ?
I tried creating an alias to resolve it through route 53 plugin but still problem is same 

All other domains internet plus route 53 are working fine but not the API Gateway one.

**Comment by chrisohaver** [comment]
Can you share your Corefile, and the API Gateway domain?
