### ISSUE TITLE
coredns getting errors on all reloads

### ISSUE THREAD

**Issue by sphlvn3** [miekg/coredns#5203]
Hi all,

When I make a change to the imported file, I get the following error and my changes are not applied

```
coredns[1116]: [ERROR] plugin/reload: Corefile changed but reload failed: starting with listener file descriptors: getting old listener file: file tcp [::]:54: use of closed network connection
coredns[1116]: [ERROR] Restart failed: getting old listener file: file tcp [::]:54: use of closed network connection
```

I can't always catch this error. I get an error on all changes(imported files) after getting an error on reload once until restart the service.

While the service is in this state, if I make changes to the corefile, it crashes and restarts. 
```
coredns[1115]: [INFO] Reloading
coredns[1115]: panic: sync: negative WaitGroup counter
coredns[1115]: goroutine 1632782787 [running]:
coredns[1115]: sync.(*WaitGroup).Add(0xc000fdaff0, 0xffffffffffffffff)
coredns[1115]: /tmp/tmp.yM3x7N1L0w/go/src/sync/waitgroup.go:74 +0x147
coredns[1115]: sync.(*WaitGroup).Done(...)
coredns[1115]: /tmp/tmp.yM3x7N1L0w/go/src/sync/waitgroup.go:99
coredns[1115]: github.com/coredns/coredns/core/dnsserver.(*Server).Stop.func1(0xc000fdafc0, 0xc00220a1e0)
systemd[1]: coredns-asya.service: main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: Unit coredns-asya.service entered failed state.
systemd[1]: coredns-asya.service failed.
systemd[1]: coredns-asya.service holdoff time over, scheduling restart.

```

I couldn't identify what triggered it.

I caught this problem for the first time in the test environment and I didn't care much. But today I faced the same problem in production environment.

By the way when I reload the service with systemctl it successfully reloads

coredns version: 1.8.0 linux/amd64, go1.15.3,
os: centos7

Corefile:
```
(global_config) {
    health :8054
    prometheus 0.0.0.0:9254
    reload 2s
    log
    errors
}

.:54 {
    import global_config
    forward . 8.8.8.8 8.8.4.4
}

hep.io:54 {
    import global_config
    file /etc/coredns/asya/zones/db-asya.hep.io {
      reload 5s
    }
}

import /usr/others.conf
```

others.conf:
```
yusuf.hep.io:54 {
    import global_config
    forward . 10.10.166.171:8600 10.10.166.172:8600 10.10.166.173:8600 10.10.166.174:8600 10.10.166.175:8600
    rewrite stop {
        name regex (.*) {1}query.consul
        answer name (.*)\.query\.consul {1}
    }
}

techopsportal.hep.io:54 {
    import global_config
    forward . 10.10.166.171:8600 10.10.166.172:8600 10.10.166.173:8600 10.10.166.174:8600 10.10.166.175:8600
    rewrite stop {
        name regex (.*) {1}query.consul
        answer name (.*)\.query\.consul {1}
    }
}
```

**Comment by yongtang** [comment]
@sefaphlvn coredns 1.8.0 was released more than a year ago and a lot of enhancements have been added since then. Have you tried the latest version of coredns?

**Comment by chrisohaver** [comment]
@sefaphlvn, Is the following a correct summary of the sequence of events you are reporting? (i.e. required sequence of events to trigger the panic)

1. Change a file imported by the Corefile
2. Observe that reload fails with "use of closed network connection" error.
3. Change the Corefile again
4. Observe that CoreDNS panics with "negative WaitGroup counter"

**Comment by sphlvn3** [comment]
> @sefaphlvn, Is the following a correct summary of the sequence of events you are reporting? (i.e. required sequence of events to trigger the panic)
> 
> 1. Change a file imported by the Corefile
> 2. Observe that reload fails with "use of closed network connection" error.
> 3. Change the Corefile again
> 4. Observe that CoreDNS panics with "negative WaitGroup counter"

yes exactly like that. but sometimes error occurs, not always

**Comment by chrisohaver** [comment]
> yes exactly like that. but sometimes error occurs, not always

To clarify: Sometimes error in step 2 occurs? But error in step 4 always occurs if error in step 2 occurred?

**Comment by sphlvn3** [comment]
> > yes exactly like that. but sometimes error occurs, not always
> 
> To clarify: Sometimes error in step 2 occurs? But error in step 4 always occurs if error in step 2 occurred?

Yes thats right.

We observed this on 3 different machines.  After restart everything works fine

**Comment by chrisohaver** [comment]
@sefaphlvn, can you recall a specific change to the Corefile you made that resulted in the first error?

**Comment by sphlvn3** [comment]
I add new record like below to other.conf file. if I get `use of closed network connection` error.  Any change to corefile results in an error

If you want specific one thing. If I delete prometheus conf from corefile thats happen

```
yusuf.hep.io:54 {
    import global_config
    forward . 10.10.166.171:8600 10.10.166.172:8600 10.10.166.173:8600 10.10.166.174:8600 10.10.166.175:8600
    rewrite stop {
        name regex (.*) {1}query.consul
        answer name (.*)\.query\.consul {1}
    }
}
```

**Comment by sphlvn3** [comment]
> @sefaphlvn coredns 1.8.0 was released more than a year ago and a lot of enhancements have been added since then. Have you tried the latest version of coredns?

I upgraded coredns version to 1.9.0.
If I get an error, I will let you know here.
