### ISSUE TITLE
use template and hosts plugin,but some hosts not work

### ISSUE THREAD

**Issue by zj452008181** [miekg/coredns#5204]
coredns version :1.6.9
config:
```
.:53 {
    errors
    health {
       lameduck 5s
    }
    ready
    template IN A example.com {
      match .*\.example\.com
      answer "{{ .Name }} 60 IN A 192.168.2.1"
      fallthrough
    }
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    hosts {
        10.0.0.1 a.example.int
        192.168.0.11 aaa.example.com
        192.168.0.12 bbb.example.com
            fallthrough
    }
    prometheus :9153
    forward . /etc/resolv.conf {
       max_concurrent 1000
    }
    cache 30
    log
    reload
    loadbalance
}
```

use this config:
 a.example.int resolve to 10.0.0.1
it's ok.
but aaa.example.com and bbb.example.com domains also reslove to 192.168.2.1,what's wrong?

**Comment by zj452008181** [comment]
.:53 {
    errors
    health {
       lameduck 5s
    }
    ready
    template IN A foxconn.com {
      match .*\.foxconn\.com
      answer "{{ .Name }} 60 IN A 116.6.66.29"
      fallthrough
    }
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    hosts {
        10.0.3.10 jira.jusda.int
        116.6.233.52 vpn1.cn.foxconn.com
        116.6.233.46 esvpn.foxconn.com
        116.6.233.46 esvpn.globalredir.foxconn.com
            fallthrough
    }
    prometheus :9153
    forward . /etc/resolv.conf {
       max_concurrent 1000
    }
    cache 30
    log
    reload
    loadbalance
}

**Comment by chrisohaver** [comment]
Nothing wrong, those match the _template_ in the Corefile ...

`aaa.example.com` and `bbb.example.com` both match `.*\.example\.com`

**Comment by chrisohaver** [comment]
Regarding the second unscrubbed Corefile... 

`vpn1.cn.foxconn.com`,  `esvpn.foxconn.com` and `esvpn.globalredir.foxconn.com` all match the template `.*.foxconn.com`, so their answers will be `116.6.66.29`.
