### ISSUE TITLE
seems that log plugin format not correct

### ISSUE THREAD

**Issue by hingbong** [miekg/coredns#5223]
```
log . {combined} {/forward/upstream} {
        class denial error
    }
```
i set this in Corefile, but i only get `[INFO] 8.8.4.4:853`.
another is that the `log_dir` is not working, always logs to stdout

**Comment by chrisohaver** [comment]
The log format needs to be one ~token~ argument. e.g. If there are spaces in it, it needs to be wrapped in quotes...

```
log . "{combined} {/forward/upstream}" {
        class denial error
    }
```

Otherwise I think it only uses the last ~token~ argument on the line.

**Comment by hingbong** [comment]
> The log format needs to be one ~token~ argument. e.g. If there are spaces in it, it needs to be wrapped in quotes...
> 
> ```
> log . "{combined} {/forward/upstream}" {
>         class denial error
>     }
> ```
> 
> Otherwise I think it only uses the last ~token~ argument on the line.

now i get `[INFO] {combined} 8.8.4.4:853`

**Comment by chrisohaver** [comment]
Looking at the code, looks like `{combined}` and `{common}` cannot be combined with any other placeholders.

This is not documented.  The documentation suggests that these act like other placeholders, but they do not (they are kind of "fake" placeholders).

**Comment by chrisohaver** [comment]
The following should be the equivalent of what you want ...

```
log . "{remote}:{port} - {>id} \"{type} {class} {name} {proto} {size} {>do} {>bufsize}\" {rcode} {>rflags} {rsize} {duration}  \"{>opcode}\" {/forward/upstream}"
```

**Comment by chrisohaver** [comment]
IMO - _log_ should be fixed to treat `{common}` and `{combined}` as normal placeholders that can be used in conjunction with other placeholders.

**Comment by hingbong** [comment]
only keep two quotation marks, `"{remote}:{port} - {>id} {type} {class} {name} {proto} {size} {>do} {>bufsize} {rcode} {>rflags} {rsize} {duration} {>opcode} {/forward/upstream}"` and works

**Comment by chrisohaver** [comment]
> only keep two quotation marks ...

I neglected to escape two of the double-quotes... fixed in post above.

**Comment by hingbong** [comment]
and the log_dir is not working, always logs to stdout
![image](https://user-images.githubusercontent.com/26398240/156862759-fe2526a4-920d-42d6-95db-9ccaf3bcafba.png)
do i need to open a new issue

**Comment by yongtang** [comment]
The `log_dir` was never meant to be available in coredns. Instead it was caused by third-party libraries that implicitly invoked global "flag". Created a PR #5229 for the fix.

**Comment by yongtang** [comment]
The issue with format was that `{common}` should be expanded (not exactly replace) before feed into rules. Created a PR #5230 for the fix.
