### ISSUE TITLE
Split utils like dnstest in a separate package

### ISSUE THREAD

**Issue by mfuentesg** [miekg/coredns#5245]
**What would you like to be added**:
Hi, I was looking your code base to get inspired on dns testing for my personal project, and I found `dnstest` under `plugin/pkg` folder. But, I didn't find any simple way to use it without including the whole project in my dependency list.

That's because I decided to `clone` just that part for my own use [https://github.com/mfuentesg/dnstest](https://github.com/mfuentesg/dnstest) and it works perfectly.

**Why is this needed**:
Becuase it can be useful for others developers like me, who are building their own dns but are worried about the quality of the code.

This is not a requeriment at all, but would be great if you can do it :)

**Comment by chrisohaver** [comment]
It's already a separate package.  I think perhaps you are asking us to split it out into a separate _project_.

> But, I didn't find any simple way to use it without including the whole project in my dependency list.

What specific problems does this cause you?

**Comment by mfuentesg** [comment]
Hey @chrisohaver thanks for replying. My bad, I was trying to say that, a different project.

I just wanted to use dnstest package, but being a embedded package in coredns project, I am unable to do it. So, having a different repository me and lot of people could use this smart package in their own projects like me.

i.e I had split coredns's `dnstest` package in a diferent repo https://github.com/mfuentesg/dnstest, and using like follows 

https://github.com/mfuentesg/localdns/blob/17b5fbd22c72d5dfa9bfbb2f3e38d3ec80f5833c/handler/handler_test.go?plain=1#L82-L109

**Comment by chrisohaver** [comment]
> I just wanted to use dnstest package, but being a embedded package in coredns project, I am unable to do it.

Why are you unable to do it?

What specific problem does including the coredns/coredns module cause you?

**Comment by mfuentesg** [comment]
Forget it, now I was able to use it, importing the whole project as a dependency.
