### ISSUE TITLE
pingcap/coredns is not ARM supported

### ISSUE THREAD

**Issue by Gearheads** [miekg/coredns#5248]
Hello, I am new here, and I was wondering if anyone knew where this image comes from?
https://hub.docker.com/r/pingcap/coredns/tags

My team is looking to leverage this image within ARM64 architecture, but this image does not support it. Is there another image we should use, or would someone be able to help point me as to where this image gets created?

Also, I am more than happy to help contribute to get this image updated to support ARM64 if need be. 😃

**Comment by yongtang** [comment]
@Gearheads  Our docker image is located on: https://hub.docker.com/r/coredns/coredns/tags

I believe it is already available for arm64. You can give it a try.

**Comment by Gearheads** [comment]
Ok thanks @yongtang. I will try that image instead.

**Comment by Gearheads** [comment]
hi @yongtang, just as an update, I tried using those images, but unfortunately they fail with the following error:
```
/etc/chaos-dns/Corefile:7 - Error during parsing: Unknown directive 'k8s_dns_chaos'
```
After doing some research it looks like a custom plugin from the `chaos-mesh` team.
- https://github.com/chaos-mesh/k8s_dns_chaos

I will close this ticket, and apologies for the confusion. Thank you again for your response, and help.

**Comment by johnbelamaric** [comment]
No clue. But you can build from the source here :)

FYI, it's really, really unsafe to use an image if you don't know the
source. Especially something like a DNS server that may run with elevated
privileges (or could be corrupted to return bogus DNS entries). I highly
recommend you build your own.
