### ISSUE TITLE
plugins/forward: default value of max_concurrent option

### ISSUE THREAD

**Issue by yilas** [miekg/coredns#5267]
Hi,

I wanted to change the coredns configmap and I was wondering what the value of `max_concurrent` is. I can't find this information in the documentation or the source code (or I searched incorrectly... it's also possible :-) )

Regards

**Comment by chrisohaver** [comment]
The option adds a limit to the number of concurrent forwarded queries. Without it, there is no limit.

**Comment by yilas** [comment]
> The option adds a limit to the number of concurrent forwarded queries. Without it, there is no limit.

Thank you for the reply.
Have a nice day
