### ISSUE TITLE
plugin/route53: Corefile:xx - Error during parsing: failed to create route53 plugin: NoCredentialProviders: no valid providers in chain. Deprecated.

### ISSUE THREAD

**Issue by lcurtis-datto** [miekg/coredns#5273]
**What happened**: When using route53 plugin and profile other than the default in AWS credentials file, this error occurs. I am able to use aws cli and assume roles and list zones from other accounts. I have configured multiple profiles as per https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-cli.html

**What you expected to happen**:
Normal coredns operation works fine using the default AWS profile. I am new to golang, so not sure how to further debug. That error appears to be related to not finding the proper credentials. To note, if I switch the credentials line to 'credentials default', I get an error stating access is denied for that zone, which I would expect. Does the route53 plugin not support switching roles?

**How to reproduce it (as minimally and precisely as possible)**:

in Corefile, add a route 53 stanza using an AWS credentials profile other than default

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: CoreDNS-1.9.1
- Corefile:

myzone.com {
    route53 myzone.com.:Z12345678 {
    credentials otherprofile
    }
}

- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Others:
~/.aws/config file

[profile otherprofile]
role_arn=arn:aws:iam::12345678901:role/xxx-route53-readonly
region=us-west-2
source_profile=default

**Comment by chrisohaver** [comment]
Pinging _route53_ plugin owners: @yongtang @dilyevsky

**Comment by dilyevsky** [comment]
@lcurtis-datto thanks for report! Yeah I looked at the sdk code and don't think it actually resolves sts profile with our current setup. https://github.com/coredns/coredns/pull/5268 should address this, i'll review/ping it tonight.
