### ISSUE TITLE
plugin/kubernetes: Coredns starts with unsynced kubernetes API

### ISSUE THREAD

**Issue by vicky1999s** [miekg/coredns#5274]
**What happened**
Coredns starting with unsynced kubernetes API  and goes to crashedLoopFallback state after the node VM was restarted.

**What you expected to happen**:
Coredns server to sync with kubernetes API after the node VM was restarted.

**How to reproduce it (as minimally and precisely as possible)**:
create a cluster in a VM in azure and use Azure CNI for networking.

**Anything else we need to know?**:
No

**Environment**:

- the version of CoreDNS: 1.8.6
- Corefile:

           Corefile: |
              .:53 {
                  errors
                  health {
                     lameduck 5s
                  }
                  ready
                  kubernetes cluster.local in-addr.arpa ip6.arpa {
                     pods insecure
                     fallthrough in-addr.arpa ip6.arpa
                     ttl 30
                  }
                  prometheus :9153
                  forward . /etc/resolv.conf {
                     max_concurrent 1000
                  }
                  cache 30
                  loop
                  reload
                  loadbalance
              }

- logs, if applicable:

          [WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
          .:53
          [INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
          CoreDNS-1.8.6
          linux/amd64, go1.17.1, 13a9191
          [ERROR] plugin/errors: 2 8640993315538981573.6174799016948003349. HINFO: read udp 10.30.0.13:36945->168.63.129.16:53: i/o timeout
Note: I can able to access the upstream server (168.63.129.16:53) from the pod.

- OS (e.g: `cat /etc/os-release`):

ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"

- Others:
k8s version:
      Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
      Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

However, it works well with other CNIs such as calico and weavenet.

**Comment by chrisohaver** [comment]
Does this work better with the latest release?  There have been some fixes/improvements in this area.

**Comment by vicky1999s** [comment]
No, I am using the latest release and still the same issue.

**Comment by chrisohaver** [comment]
> No, I am using the latest release and still the same issue.

Have the logs changed?  1.9.1 has improved logging for API connection failures.

> However, it works well with other CNIs such as calico and weavenet.

This strongly suggests a problem with your CNI (Azure CNI).

The CoreDNS log does not show a fatal error.  The error in the log says that 168.63.129.16 is not responding to the HINFO request.  This could be a CNI networking failure, or that 168.63.129.16 drops HINFO requests.  But that is not a fatal error in either case.

Despite no fatal error in the coredns log, you say coredns is in a crash loop back off state.  That seems to be contradictory, unless perhaps there is some other kubernetes infrastructure reason for failing _before_ CoreDNS is started, and the log is from before the node was rebooted?

What is the state of the coredns Deployment?
