### ISSUE TITLE
Windows 10 Network Connection Status Indicator icon report a false "No Internet" status

### ISSUE THREAD

**Issue by Elger9** [miekg/coredns#5290]
**What happened**: 
CoreDNS running locally. Windows 10 Network Connection Status Indicator icon report a false "No Internet" status. Internet connection is available and can be used normally, but some programs don't work, such as Spotify (maybe they are checking the indicator?)

**What you expected to happen**: 
The indicator should show a valid internet connection.

**How to reproduce it (as minimally and precisely as possible)**:

Corefile:
```
.:53 {
    forward . 8.8.8.8:53
    log
}
```

Run CoreDNS
```
.\coredns.exe
.:53
CoreDNS-1.9.1
windows/amd64, go1.17.8, 4b597f8
```
```
Set Windows DNS to 127.0.0.1
```

**Environment**:

- the version of CoreDNS: CoreDNS-1.9.1
- Corefile: as above
- Windows 10 Pro 21H2

**Comment by chrisohaver** [comment]
OK, per https://docs.microsoft.com/en-us/troubleshoot/windows-client/networking/internet-explorer-edge-open-connect-corporate-public-network#ncsi-active-probes-and-the-network-status-alert,  Network Connection Status Indicator (NCSI), tests internet by ...
1. Downloading a text file `http://www.msftconnecttest.com/connecttest.txt`
2. Doing a dns look up for `dns.msftncsi.com` (doesn't say what type of query is done)

@Elger9, can you manually perform both of those actions?  i.e.
1. Can you get `http://www.msftconnecttest.com/connecttest.txt`  in your web browser?
2. Can you do a dns lookup for `dns.msftncsi.com` (type A)?

The CoreDNS log you provided do not show any NCSI DNS lookups ever reaching CoreDNS.  There should be at least two, `www.msftconnecttest.com ` and `dns.msftncsi.com`.

**Comment by Elger9** [comment]
Yes, without a problem:
```
C:\>curl http://www.msftconnecttest.com/connecttest.txt
Microsoft Connect Test
C:\>nslookup dns.msftncsi.com
Server:  UnKnown
Address:  127.0.0.1

Non-authoritative answer:
Name:    dns.msftncsi.com
Addresses:  fd3e:4f5a:5b81::1
          131.107.255.255
```

Then the correct entry appears in the log

```
C:\Users\user\coredns>.\coredns.exe
.:53
CoreDNS-1.9.1
windows/amd64, go1.17.8, 4b597f8
[INFO] 127.0.0.1:49952 - 12503 "A IN www.msftconnecttest.com. udp 41 false 512" NOERROR qr,rd,ra 318 0.0165791s
[INFO] 127.0.0.1:49954 - 1 "PTR IN 1.0.0.127.in-addr.arpa. udp 40 false 512" NXDOMAIN qr,rd,ra 124 0.0136414s
[INFO] 127.0.0.1:49955 - 2 "A IN dns.msftncsi.com. udp 34 false 512" NOERROR qr,rd,ra 66 0.0098633s
[INFO] 127.0.0.1:49956 - 3 "AAAA IN dns.msftncsi.com. udp 34 false 512" NOERROR qr,rd,ra 78 0.0093076s
```

However, according to the log, the "Network Connection Status Indicator" never attempts to connect to the above domains. These domains only appear in the log when I query them manually from the command line.

Perhaps this is a similar problem to that found in Acrylic DNS https://mayakron.altervista.org/support/acrylic/FAQ.htm#817f2a2c28fb43acb9b840622f002513

**Comment by chrisohaver** [comment]
In that case, CoreDns is working fine, and there is some issue with NCSI - perhaps it is querying some other DNS server.

**Comment by Elger9** [comment]
Thanks for the suggestion that it's a Windows problem. Exactly right. NCSI does not like 127.0.0.1 as a DNS server. I changed it to a local address of 192.168.x.x and it works in both cases (CoreDNS and Acrylic DNS).
