### ISSUE TITLE
Having a option to exposing ingress service?

### ISSUE THREAD

**Issue by vincent5753** [miekg/coredns#5295]
**What would you like to be added**:
Ability to expose ingress service to pod as a setup option

**Why is this needed**:
I got folks asking that it's possible to expose ingress service to pod and node(without hosting a external dns).
So I came up with the solution in the my [repo](https://github.com/vincent5753/corednssync)
I think it would be nice for some people to see such option while setting up their cluster.

**Comment by chrisohaver** [comment]
The external plugin, https://coredns.io/explugins/k8s_gateway/ also exposes K8s Ingress.

**Comment by chrisohaver** [comment]
Closing, since an external plugin that does this is available.
