### ISSUE TITLE
Does coredns v1.5.2 supports IPv6

### ISSUE THREAD

**Issue by goshreyas** [miekg/coredns#5307]
Hi Team, I want to know whether [CoreDNS v1.5.2](https://github.com/coredns/coredns/pull/2969) supports IPv6.
 If CoreDNS v1.5.2 supports IPv6, then what needs to be done to make it enable?
 If CoreDNS v1.5.2 does not support IPv6, then starting from which release version IPv6 supported?

**Comment by chrisohaver** [comment]
It probably does. 1.5 is really old. It kind of sounds like you want to use the oldest version possible. Why is that?
