### ISSUE TITLE
CoreDNS in azure PrivateDNS

### ISSUE THREAD

**Issue by calberts** [miekg/coredns#5309]
I have a question in relation to coredns in combination with azure private DNS zone in the azure cloud.
As know the Azure DNS has shortcomings. it cant act as part of recursive resolving in an internal root environment.
Always an extra caching server needs to be implemented with forwards to the so-called magic azure  DNS IP address.
This can make resolving complex in an enterprise network

The question is how can we use coredns in a way that the coredns server will act as an authoritative server for the Private azure DNS zones. 

Did someone already solved this issue how to deal with this, what is your advise

Chris

**Comment by chrisohaver** [comment]
> The question is how can we use coredns in a way that the coredns server will act as an authoritative server for the Private azure DNS zones.

Does the _azure_ plugin fit your needs? https://github.com/coredns/coredns/tree/master/plugin/azure

**Comment by calberts** [comment]
i will check this, thanks for the information.
question how will core DNS azure plugin retrieve the data from the azure private zones

**Comment by chrisohaver** [comment]
> question how will core DNS azure plugin retrieve the data from the azure private zones

It uses the Azure DNS REST API.

**Comment by calberts** [comment]
The question is, will this work when there is no access to the internet, the vnet will be a kind of extended internal network. If I am correct  I am not able to use this API (security), are there another method available with coredns.

The aim is that we like to have the private zone like to ba act as real authoritative server

Thanks for your quick response.

Chris

**Comment by chrisohaver** [comment]
You can export your private zone as a zone file, and use the _file_ plugin to serve the zone file.  Of course, if after that you make any changes to the private zone in Azure, the changes would not be reflected in CoreDNS until you re-export and update the CoreDNS zone file.
