### ISSUE TITLE
Why not get server's ip from udp packet with destination ip?

### ISSUE THREAD

**Issue by victory460** [miekg/coredns#5310]
https://github.com/coredns/coredns/blob/275c014c5c9bc4d4469811b252a27f3dc7dca74c/request/request.go#L32

I find the server's ip get from local addr,such as 127.0.0.1. Why not get server's ip from udp packet with destination ip?  
How to get destination ip from udp packet? I not find the function in net pkg.
Thanks a lot!

**Comment by chrisohaver** [comment]
> I find the server's ip get from local addr, such as 127.0.0.1.

If CoreDNS actually receives an IPv4 request on the local interface, then that will be the localIP.

> Why not get server's ip from udp packet with destination ip?

It already does this.

**Comment by victory460** [comment]
> > I find the server's ip get from local addr, such as 127.0.0.1.
> 
> If CoreDNS actually receives an IPv4 request on the local interface, then that will be the localIP.
> 
> > Why not get server's ip from udp packet with destination ip?
> 
> It already does this.

Thanks a lot for your reply.
https://github.com/coredns/coredns/blob/275c014c5c9bc4d4469811b252a27f3dc7dca74c/request/request.go#L67
I find the server's ip get from localIP, but not from udp packet with destination ip.

My test case  :

1. `dig @192.168.1.11  a1.example.com`
2. print `state.LocalIP()`
3. find the print ip not match 192.168.1.11 (the ip is one of localIP)

So, I confuse it.
> Why not get server's ip from udp packet with destination ip?
> How to get destination ip from udp packet? 

Thanks a lot !

**Comment by chrisohaver** [comment]
I _think_ this is a side effect of binding on "all ports" on a single listener. The local ip in the udp connection is not necessarily the actual ip the request really came in on.  If you bind on addresses explicitly (with the bind plugin), the localIP should be correct, since a separate listener is created for each address.

Perhaps we could infer the address it came in on, by looking at the remote IP address and comparing to the local interface subnets.  But would add a significant amount of extra processing per each request.

**Comment by victory460** [comment]
> I _think_ this is a side effect of binding on "all ports" on a single listener. The local ip in the udp connection is not necessarily the actual ip the request really came in on. If you bind on addresses explicitly (with the bind plugin), the localIP should be correct, since a separate listener is created for each address.
> 
> Perhaps we could infer the address it came in on, by looking at the remote IP address and comparing to the local interface subnets. But would add a significant amount of extra processing per each request.

Thank you for your patient answer. The background of this question is that we want to get the destination ip from udp packet and set it in `Request struct`. Now I try to do it. Thanks!

**Comment by chrisohaver** [comment]
> this is a side effect of binding on "all ports" on a single listener 

More specifically, this is a limitation of Go's `net` package.  The local IP just returns what the listener was created with.  If the listener is listening on all ports (i.e. `0.0.0.0` `::0` aka `*` in other contexts), then the value returned defaults to localhost.

I did find one workaround out there involving socket options, but it has platform specific exceptions.

IMO, if this is an important issue to you, use the _bind_ plugin workaround per my earlier comment.

**Comment by victory460** [comment]
> > this is a side effect of binding on "all ports" on a single listener
> 
> More specifically, this is a limitation of Go's `net` package. The local IP just returns what the listener was created with. If the listener is listening on all ports (i.e. `0.0.0.0` `::0` aka `*` in other contexts), then the value returned defaults to localhost.
> 
> I did find one workaround out there involving socket options, but it has platform specific exceptions.
> 
> IMO, if this is an important issue to you, use the _bind_ plugin workaround per my earlier comment.

Thanks a lot.
