### ISSUE TITLE
forward plugin takes priority

### ISSUE THREAD

**Issue by myaspm** [miekg/coredns#5312]
Hi everyone, 

I'm trying to use grpc and forward plugins together. DNS queries should be first sent to my grpc backend and only if an error happens then they should be sent to forward plugin. But forward takes top priority and answers every query (same also happens with redis plugin).  'fallthrough' directive doesnt work for grpc plugin.

Sample Corefile:

```
. {
    grpc . 127.0.0.1:50051 {
    }
    forward . 8.8.8.8 {
    }
    debug
    log
}
```

Is there a way to use grpc with fallthrought to forward plugin?

Thanks in advance.

**Comment by chrisohaver** [comment]
The execution order of plugins is governed by the order in `/plugin.cfg` at build time - _not the order in the Corefile_.
To change the order, you can alter `/plugin.cfg` and re-build your own version of CoreDNS.

Also be aware that `fallthrough` only falls through when the response is `NXDOMAIN`. Other errors, such as a `SERVFAIL` will not fall through.  The intent is to fall through to the next plugin when the queried name does not exist, not when there is an error.

Some external plugins that may help, depending on what precisely you are trying to achieve: https://coredns.io/explugins/alternate/ and  https://coredns.io/explugins/fanout/.

**Comment by myaspm** [comment]
Yeah thanks i altered plugin.cfg and now at least request first go to grpc server. I'm returning NXDOMAIN but queries are not recevied by neither alternate nor forward plugin. I'm thinking my grpc server is the problem. Any help is appreciated, thanks in advance.

**Comment by myaspm** [comment]
Alright, i managed to implement a simple fallthrough in grpc plugin. This issue can be closed. Thanks @chrisohaver for your help.

**Comment by ferranbt** [comment]
Hi @myaspm. Could you share a gist of your solution? I am stuck on the same problem. I compiled `coredns`, change the order of `grpc` and `forward` on `plugin.cfg` and used this `Corefile`:

```
.:5354 {
    grpc . 172.17.0.1:5566
    forward . 8.8.8.8
    log
    errors
}
```

My `grpc` server looks like this:

```
...
func (s *service) Query(ctx context.Context, req *pb.DnsPacket) (*pb.DnsPacket, error) {
	pkt := new(dns.Msg)
	if err := pkt.Unpack(req.Msg); err != nil {
		return nil, err
	}
	fmt.Println(pkt)

	return nil, status.Error(codes.NotFound, "service id was not found")
...
```
However, when making a DNS query, there is no fallthrough, only `grpc` process the query. And from the logs of it, it is returning a `nxdomain` error.

```
➜  coredns git:(master) ✗ ./coredns --conf Corefile
.:5354
CoreDNS-1.10.0
linux/amd64, go1.19.1, 78da65d8-dirty
[INFO] 127.0.0.1:55941 - 16849 "A IN example.com. udp 52 false 4096" NXDOMAIN qr,rd 29 0.000898991s
[INFO] 127.0.0.1:50618 - 40868 "A IN example.com. udp 52 false 4096" NXDOMAIN qr,rd 29 0.000663235s
[INFO] 127.0.0.1:39737 - 31795 "A IN example.com. udp 52 false 4096" NXDOMAIN qr,rd 29 0.000583715s
```

**Comment by ferranbt** [comment]
From what I am reading in the code (please correct me If I am wrong), the "fallthrough" behavior is only enabled if the plugin calls `plugin.NextOrFailure`. It is a per-plugin feature, not a `coredns` feature. `Grpc` does not have that functionality.
