### ISSUE TITLE
Coredns all queries upstream only go through the same UDP session.Can this working mode be modified?

### ISSUE THREAD

**Issue by wuchuwei** [miekg/coredns#5318]
Coredns all queries upstream only go through the same UDP session.Can this working mode be modified?

**Comment by chrisohaver** [comment]
What problems does the current working mode cause for you?

**Comment by wuchuwei** [comment]
> 当前的工作模式给您带来了哪些问题？
DNS transparent proxy is enabled on our network gateway.We have a domain forwarding profile on the gateway.For example, amazon.co.jp forwards to Opendns.Transparent proxy is implemented using DNAT (change destination IP address), so the DNS client DNAT opendns IP address only when the first query is amazon.co.jp.So I want each query to be a new UDP session.
The following coreDNS configuration addresses my needs.But we've been using DNS transparent proxy for a long time and we still want everything configured here.
amazon.co.jp:53 {
  errors
  cache 30
  forward . 208.67.222.222
}

**Comment by wuchuwei** [comment]
> What problems does the current working mode cause for you?

DNS transparent proxy is enabled on our network gateway.We have a domain forwarding profile on the gateway.For example, amazon.co.jp forwards to Opendns.Transparent proxy is implemented using DNAT (change destination IP address), so the DNS client DNAT opendns IP address only when the first query is amazon.co.jp.So I want each query to be a new UDP session.
The following coreDNS configuration addresses my needs.But we've been using DNS transparent proxy for a long time and we still want everything configured here.
amazon.co.jp:53 {
errors
cache 30
forward . 208.67.222.222
}

**Comment by chrisohaver** [comment]
Thanks. 

> we've been using DNS transparent proxy for a long time  

What is the change that occurred when this started to become a problem for you?  Sounds like things were fine for you, and now they are not.

**Comment by wuchuwei** [comment]
> Thanks.
> 
> > we've been using DNS transparent proxy for a long time
> 
> What is the change that occurred when this started to become a problem for you? Sounds like things were fine for you, and now they are not.

This is a real problem with coreDNS.Just because our domestic network environment is a little special.The DNS public server we used recently returned records for the amazon.co.jp domain name that were unavailable (possibly DNS contamination).We did not investigate specific problems before because the returned records had no impact on business.Now, due to the influence, we conducted an in-depth check on the DNS query process and found that the function of forwarding the transparent proxy specified domain name to the specified DNS server configured is invalid.

**Comment by chrisohaver** [comment]
Can you describe in detail your special environment?  What full path does a dns request and response take?
