### ISSUE TITLE
How does dnssec validation works in default coredns provided by kubernetes

### ISSUE THREAD

**Issue by shruthidharani-4313** [miekg/coredns#5331]
I am exploring [plugin options][1] available in kubernetes coredns especially on dnssec validation. 
1) Default [Corefile][2] of coredns does not have dnssec plugin. Will the default coredns do dnssec validation or not?
2) Can someone give an example to generate a key using dnssec-keygen and use it in dnssec plugin. what are all arguments needs to be passed? What should be given in place of ECDSAP256SHA256 and zonename(see below).  

> key file indicates that KEY file(s) should be read from disk. When multiple keys are specified, RRsets will be signed with all keys. Generating a key can be done with dnssec-keygen: dnssec-keygen -a ECDSAP256SHA256 zonename.

I want to do dnssec validation for this server block.
```
example.com:53 {
cache 30
log
errors
forward . IP1
}
```
As I am new to coredns configuration [dnssec][3], it would be really helpful if someone can explain about this. Thanks in advance!!

  [1]: https://coredns.io/
  [2]: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
  [3]: https://coredns.io/plugins/dnssec/

**Comment by chrisohaver** [comment]
Will CoreDNS do DNSSEC _validation_? No, it does not.

To be clear, the _dnssec_ plugin does on the fly _signing_ of unsigned replies - it does not do validation.  Any validation would happen downstream (e.g. on the client).

Similarly, the _sign_ plugin will sign a zone file served by the _file_ plugin.

> I want to do dnssec validation for this server block.

CoreDNS is not able to do proxy DNSSEC signature validation. E.g. the _forward_ plugin cannot be configured to request DNSSEC when forwarding a query upstream, and verify the response has a valid DNSSEC signature.

**Comment by WestFarmer** [comment]
> Can someone give an example to generate a key using dnssec-keygen and use it in dnssec plugin. what are all arguments needs to be passed? What should be given in place of ECDSAP256SHA256 and zonename(see below).

still want answer of this
