### ISSUE TITLE
Does coredns use ipv4 or ipv6 to answer queries by default

### ISSUE THREAD

**Issue by shruthidharani-4313** [miekg/coredns#5332]
I am exploring on how coredns replies to dns queries either via ipv4 or ipv6 by default. 

1. Coredns replies to ip6, ip4 or both ip6 and ip4 queries by default? 

2. By default, will coredns answer to dns queries over ipv4 or ipv6? Can we configure this to use ipv6 or ipv4?

It would be really helpful if someone helps me to clarify this. Thanks in advance!

**Comment by chrisohaver** [comment]
> ... how coredns replies to dns queries either via ipv4 or ipv6 by default

If a request is received over ipv6, the response will naturally be ipv6, and if a request is received over ipv4, the response will naturally be ipv4.

By default, the CoreDNS listener binds to all local addresses (i.e. it listens for requests coming in to any address).  You can use the _bind_ plugin to make CoreDNS just listen to the address(es) you want.

**Comment by shruthidharani-4313** [comment]
@chrisohaver Thanks for your reply, I will check it out how it suits for coredns. Because in https://coredns.io/plugins/bind/ I see when we use for bind in more than one server block, this will produce issues. There is an open bug when we need to bind more than one server block to the same address(localhost) and port. When we define two server block, one with bind and otehr without bind, or all server with bind to same IP, this will collide with another server if it’s using bind to listen to an interface on the same port. Hope my understanding on this plugin is correct. Correct me if I'm wrong.

**Comment by chrisohaver** [comment]
> Because in https://coredns.io/plugins/bind/ I see we use for bind in more than one server block, this will produce issues

That warning needs to be rephrased.  AFAIK the issue only occurs when binding one server block to all addresses (default behavior without using bind), and at the same time another server block bound to an address (with bind plugin).  IOW, when you use the bind plugin in one server block, and don't use it in another.  In effect, if you use the bind plugin, you _must_ use it in all server blocks of a common port.

**Comment by shruthidharani-4313** [comment]
@chrisohaver Thanks for your valuable and clear response. I'll try it in action and check.

**Comment by chrisohaver** [comment]
Kudos for reading the docs, and thanks for catching that! #5349 fixes the explanation.  I also added a TL;DR to it, since the explanation was getting lengthy.
