### ISSUE TITLE
"Name or service not known" error while domain name is surely existing

### ISSUE THREAD

**Issue by tjbnde** [miekg/coredns#5348]
We are using CoreDNS in our clusters and are experiencing the "Name or service not known" error in some clusters, even-though the domain name is existent. This issue seems to appear only under higher load and scaling up the number of CoreDNS replicas fixes the problem temporarily. We are currently trying to reproduce this issue on other clusters by creating load to CoreDNS manually and simulating high usages of our own services, but weren't able to get there yet.

Has this issue been seen by other users in the past, and how could the load in our cluster lead to an error like this, which seems totally unrelated to load?
Do you have ideas on how we could reproduce this in other clusters?

Thank you very much in advance!

**Comment by chrisohaver** [comment]
Need more info. CoreDNS version? CoreDNS logs when a look up fails?
You have used the term "clusters", is this in a Kubernetes cluster? If so what version? And is Node Local DNS deployed?

**Comment by chrisohaver** [comment]
If there are no errors in the CoreDNS log, and assuming this deployed in Kubernetes, and you don't have Node Local DNS deployed: what you describe could be the result of a well known linux conntrack issue that affects Kubernetes.  


[Node local cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) was, AFAIK, primarily built to address the linux conntrack issue that causes occasional packet drops in Kubernetes.  Node local cache mitigates this by acting as a TCP proxy DNS forwarder deployed on each node - TCP being more robust to packet drops that DNS's default UDP. Node local cache also helps by offloading upstream dns queries from the cluster service discovery deployment of coredns, and reduced latency a bit for those requests too.

**Comment by tjbnde** [comment]
Thank you for your input! We are using CoreDNS version 1.8.6 and Kubernetes v1.21.10. We weren't able to find any associated logs to this issue. Actually we aren't using Node Local DNS and will evaluate this option. But doesn't the error message "Name or service not known" imply that the connection to CoreDNS itself was successful, but CoreDNS wasn't able to resolve the domain name? And wouldn't we just get high latencies if we were facing the linux conntrack issue, because requests would automatically be resent?

**Comment by chrisohaver** [comment]
> But doesn't the error message "Name or service not known" imply that the connection to CoreDNS itself was successful, but CoreDNS wasn't able to resolve the domain name?

Perhaps, but I can't say for sure.  I don't know what is constructing the actual message.  It's not a CoreDNS error string.

> And wouldn't we just get high latencies if we were facing the linux conntrack issue, because requests would automatically be resent?

True, it typically manifests that way.

Turn on response logging in CoreDNS to help diagnose. https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution

What types of names are affected ...
* in-cluster services? e.g. `myservice.default.svc.cluster.local`
* names served by an upstream DNS? e.g. `something.mydomain.org.`

Are the services you are looking up transient in any way? E.g. if they are queried while they do not exist, the negative response will be cached for however long the record TTL is, but not higher than the _cache_ plugin's max TTL.

Without a way for you to reliably reproduce the issue, this will be difficult to track down.

**Comment by tjbnde** [comment]
> Turn on response logging in CoreDNS to help diagnose. https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution

We already tried getting more logs, but unfortunately it seems as if when turning on all logs ("log"-parameter in our Corefile), our system can't handle this anymore. In two of our big clusters, this lead to crashes of many important pods, so enabling all logs isn't an option for our prod-clusters. We have therefore limited it to error-logs only. I will keep track of the logs and check again if I can find something when this issue occurs again. We mainly see the issue when running our automated tests.


> What types of names are affected ...

We have only seen this for names served by an upstream DNS.


> Are the services you are looking up transient in any way? E.g. if they are queried while they do not exist, the negative response will be cached for however long the record TTL is, but not higher than the _cache_ plugin's max TTL.

No they aren't, and this issue occurs for different services and domain names.


> Without a way for you to reliably reproduce the issue, this will be difficult to track down.

Yes, that's what we are experiencing. Reproducing the issue by just putting load on CoreDNS artificially by running some DNS-performance-tests doesn't work. And we are experiencing this on prod-clusters with higher loads only. But as increasing the number of CoreDNS replicas solves the problem, we are guessing that this is some kind of a performance issue.

Do you have a guess on things we could try to reproduce this issue?

**Comment by chrisohaver** [comment]
> We have only seen this for names served by an upstream DNS.

Is the upstream DNS returning NXDOMAIN in these cases?  Is it private or public?

**Comment by tjbnde** [comment]
Those are public domain names (and I can resolve them from my local machine). I didn't see error logs the last time I checked, but I will investigate our logs again, the next time this issue occurs in our cluster (I expect it to happen latest on Monday again).

**Comment by chrisohaver** [comment]
That you only see this for names served by an upstream DNS, and there are no errors in CoreDNS's log, likely means that the upstream DNS is sporadically returning a negative response, and CoreDNS is just forwarding that answer along to the client.

**Comment by tjbnde** [comment]
Yes, this assumption seems likely, but how could it be that scaling up the number of CoreDNS pods solves the issue, if this wouldn't be on our end? Somehow this looks like a performance issue.

A colleague reported that he has seen this issue for internal domains too, maybe this helps us to break it down too.

**Comment by chrisohaver** [comment]
> A colleague reported that he has seen this issue for internal domains too, maybe this helps us to break it down too.

By "internal domain" what do you mean specifically? If you are referring to a `cluster.local` domain, this _expands_ the scope, since previously we had narrowed it down to only queries forwarded to other servers.  Do you have CoreDNS logs/response codes, etc for this case?

Going over the reported details again, can you fill in some gaps?

CoreDNS sometimes returns "Name or service not known".
* We are assuming this is the result of a negative response from CoreDNS, not a timeout or other connection issue to CoreDNS.
* How frequently does this occur?
* Knowing the actual form of negative response would help, e.g. response code (NXDOMAIN, SERVFAIL, REFUSED).
* There are no errors in CoreDNS's log during these failures?

The issue seems to appear only under higher load.
* How high is the load, and for how long is it high?
* Do you see an increase of the `coredns_health_request_duration_seconds` during this time?

Scaling up CoreDNS seems to temporarily resolve the issue.
* Scaling up by how much?  
* Temporarily for how long?  After a set amount of time?  Until load goes higher? After you scale back down?

Can you share your CoreDNS Corefile?

One possibility: If the issue affects lookups in the `cluster.local` domain, then the following does not apply. Nevertheless, In default Kubernetes deployments of CoreDNS, each CoreDNS instance limits the number of concurrent queries to upstream servers, requests are refused if that limit would be exceeded.  This lines up with "scaling up seems to help", but not with the only temporary effect that scaling up apparently has.  Although, the number of concurrent queries in flight isn't only related to CoreDNS load, but equally related to the latency of the upstream server. So if latency from the the upstream server fluctuates, perhaps this could inconsistently related to load.

**Comment by chrisohaver** [comment]
> ...  requests are refused if that limit would be exceeded. ...

If this is happening, the `coredns_forward_max_concurrent_rejects_total` metric should reflect it.

**Comment by tjbnde** [comment]
> By "internal domain" what do you mean specifically? If you are referring to a `cluster.local` domain, this _expands_ the scope, since previously we had narrowed it down to only queries forwarded to other servers. Do you have CoreDNS logs/response codes, etc for this case?

Yes, a colleague confirmed that he saw this for cluster.local domains too. I saw it for external domains too, so we can't narrow it down there. Unfortunately there was no occurrence in our clusters over the last few days, and I'm still waiting for the issue to occur again, so I can check the logs again.

> * How frequently does this occur?

Usually we saw this multiple times a week, sometimes multiple times a day.


> * There are no errors in CoreDNS's log during these failures?

I will investigate this, once we see the issue in our system again. Unfortunately we can't reproduce this yet, so we need to wait for it to happen in our affected cluster.

> * How high is the load, and for how long is it high?

Usually we have about 129.000 requests to CoreDNS per minute in our cluster. We are running 5 replicas of coreDNS, so it comes down to 430 requests per second per pod. In general the traffic seems to be pretty consistent without extreme changes to the load (over an interval of 1 hour). But these findings aren't 100 % reliable because enabling the logs in the cluster led to some problems.
We can't say at which load the issue occurs exactly. To test this, we would need to reproduce the issue in another cluster.


> * Do you see an increase of the `coredns_health_request_duration_seconds` during this time?

To investigate this, we would need to reproduce the issue in another cluster, because on the productive systems we can't keep track of this, because we don't know when the issue will happen again.


> * Scaling up by how much?

In one customer-facing cluster where we had this issue, we increased the replica count of CoreDNS from 5 to 16. This solved the problems.


> * Temporarily for how long?  After a set amount of time?  Until load goes higher? After you scale back down?

After scaling up, the issues are solved until the load gets higher again. We don't scale down the replicas afterwards.



> Can you share your CoreDNS Corefile?

This is our Corefile:

```.:8053 {
  errors
  log . {
      class error
  }
  health {
      lameduck 15s
  }
  ready
  kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
      ttl 30
  }
  prometheus 0.0.0.0:9153
  forward . /etc/resolv.conf
  cache 30
  loop
  reload
  loadbalance round_robin
  import custom/*.override
}
import custom/*.server
```

**Comment by chrisohaver** [comment]
>> How high is the load,

> 430 requests per second per pod

430 QPS doesn't seem like a high load for this configuration, even with limited compute resources.

> But these findings aren't 100 % reliable because enabling the logs in the cluster led to some problems.

You should not need to enable logs to determine how many queries per second coredns is processing.  Are you collecting prometheus metrics?  Do you still have data from the time of the failures?

>>Do you see an increase of in `coredns_health_request_duration_seconds` during this time?

> To investigate this, we would need to reproduce the issue in another cluster, because on the productive systems we can't keep track of this, because we don't know when the issue will happen again.

OK - so, I guess you do not still have prometheus data from the time of the failures.

**Comment by tjbnde** [comment]
Last week, we have scaled up the number of replicas of CoreDNS (from 5 to 13), and have experienced the issue once since then. I checked the CoreDNS logs afterwards and wasn't able to find any logs regarding the URL that was failing in the given timeframe. So this either needs to be an issue with our logging configuration, or the error isn't thrown by CoreDNS itself.


> 430 QPS doesn't seem like a high load for this configuration, even with limited compute resources.
> 
> >

Yes, but our tests have shown that this is about the capacity we can get.



> You should not need to enable logs to determine how many queries per second coredns is processing. Are you collecting prometheus metrics? Do you still have data from the time of the failures?
> 
> > >

Yes, we are collecting prometheus metrics. I have checked them and they seem to be matching with our prior findings.


> OK - so, I guess you do not still have prometheus data from the time of the failures.

yes, we don't.

**Comment by chrisohaver** [comment]
> ... experienced the issue once since then.

Was the failing name in `cluster.local`, or upstream?

> I checked the CoreDNS logs afterwards and wasn't able to find any logs regarding the URL that was failing in the given timeframe.

Assuming it was an upstream domain, this means that CoreDNS is able to reach upstream name servers, and not timing out waiting for a response.

>  ... an issue with our logging configuration ...

I don't know that the response is an _error_ from CoreDNS, it could be a non-error negative response (denial of existence), or a timeout.  IOW, I don't know for sure what kind of DNS responses/conditions will cause the client application to throw the "Name or service not known" error.  To log errors _and_ non-error negative responses,  add `denial` to the class of responses to log. e.g. 

```
 log . {
      class error denial
  }
```

Note: Due to the way domain searching works in Kubernetes, this will significantly increase the amount of logging (Kubernetes pods typically send a lot of queries for non-existent services).

**Comment by tjbnde** [comment]
> Was the failing name in `cluster.local`, or upstream?
> 
> >

it was upstream.



> Note: Due to the way domain searching works in Kubernetes, this will significantly increase the amount of logging

Unfortunately we can't enable this in our prod cluster (where we are facing the issues), as we had problems with this before.


We will now wait a few more days and see, how scaling up the number of CoreDNS replicas impacts this issue. Maybe this helps us to make sure, this is a performance issue.

**Comment by dankirkpatrick** [comment]
I'm having a similar issue.  We have an on-prem k8s cluster.  A service is configured to call out to an internal-only DNS name, let's say "fubar.example.com".  "example.com" is a valid domain with an authoritative name server, but "fubar.example.com" is internal-only, with a DNS entry only on our internal DNS server, not on the authoritative name server.  About 50% of my requests fail with "name or server not known", while the other 50% of requests succeed with the internal IP address.  This is on a cluster with little-to-no traffic, so it's not a result of high load.

I'm running a DNSUtils pod where I can make DNS requests directly.  Using dig, nslookup, and host apps, the behavior is the same, with 50% of requests failing.  I run a shell script to repeatedly call dig/nslookup/host every 35 seconds (less than 30 seconds seems to cache the DNS server, so all requests either succeed or fail).  Based upon these symptoms, I presume that 1 of my 2 CoreDNS pods is failing, and depending upon which pod my requests get routed to they succeed or fail.  However, from my logs I can get a success then a failure with both requests being serviced by the same CoreDNS pod.

My CoreDNS config looks like:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
    }
```
Logs in CoreDNS of a successful then a failing request, using nslookup:

```
2022-07-19T09:29:56.263793400-07:00 [INFO] 10.233.64.0:41956 - 2212 "A IN fubar.example.com.default.svc.cluster.local. tcp 67 false 65535" NXDOMAIN qr,aa,rd 160 0.0001617s
2022-07-19T09:29:56.265911500-07:00 [INFO] 10.233.64.0:41956 - 38936 "A IN fubar.example.com.svc.cluster.local. tcp 59 false 65535" NXDOMAIN qr,aa,rd 152 0.0001502s
2022-07-19T09:29:56.267069800-07:00 [INFO] 10.233.64.0:41956 - 61309 "A IN fubar.example.com.cluster.local. tcp 55 false 65535" NXDOMAIN qr,aa,rd 148 0.0001048s
2022-07-19T09:30:12.678203100-07:00 [INFO] 10.233.64.0:44030 - 41709 "A IN fubar.example.com.default.svc.cluster.local. tcp 67 false 65535" NXDOMAIN qr,aa,rd 160 0.0001805s
2022-07-19T09:30:12.679498300-07:00 [INFO] 10.233.64.0:44030 - 15851 "A IN fubar.example.com.svc.cluster.local. tcp 59 false 65535" NXDOMAIN qr,aa,rd 152 0.0001183s
2022-07-19T09:30:12.680276400-07:00 [INFO] 10.233.64.0:44030 - 35506 "A IN fubar.example.com.cluster.local. tcp 55 false 65535" NXDOMAIN qr,aa,rd 148 0.0001047s
```

And here is the output from my DNSUtils client:
```
root@dnsutils:/# nslookup fubar.example.com
Server:         10.233.0.10
Address:        10.233.0.10#53

Name:   fubar.example.com
Address: 10.211.80.251


root@dnsutils:/# nslookup fubar.example.com
Server:         10.233.0.10
Address:        10.233.0.10#53

** server can't find fubar.example.com: NXDOMAIN
```

Here is a dig request that fails:
```
root@dnsutils:/# dig fubar.example.com

; <<>> DiG 9.9.5-9+deb8u19-Debian <<>> fubar.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 16635
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;fubar.example.com.       IN      A

;; AUTHORITY SECTION:
example.com.         30      IN      SOA     ns1-01.azure-dns.com. azuredns-hostmaster.microsoft.com. 1 3600 300 2419200 300

;; Query time: 40 msec
;; SERVER: 10.233.0.10#53(10.233.0.10)
;; WHEN: Tue Jul 19 16:52:19 UTC 2022
;; MSG SIZE  rcvd: 155
```

and here is the dig output on a successful request:

```
root@dnsutils:/# dig fubar.example.com

; <<>> DiG 9.9.5-9+deb8u19-Debian <<>> fubar.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15652
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;fubar.example.com.       IN      A

;; ANSWER SECTION:
fubar.example.com. 30     IN      A       10.211.80.251

;; Query time: 2 msec
;; SERVER: 10.233.0.10#53(10.233.0.10)
;; WHEN: Tue Jul 19 16:54:01 UTC 2022
;; MSG SIZE  rcvd: 91
```

(Note: I've replaced my actual DNS names with fubar.example.com in my copy/pastes above)
(Note: This is on a Kubespray/kubeadm-installed cluster, v1.21.9, with CoreDNS v1.8.0)

**Comment by chrisohaver** [comment]
@dankirkpatrick , 

This seems like a different issue.  The symptoms you give suggest you may have two upstream dns servers configured in CoreDNS Pod's `/etc/resolv.conf`, one of them able to answer the query, and the other returning NXDOMAIN.  By default, the _forward_ plugin uses a random policy selecting an upstream at random to forward to. This would result in a 50% NXDOMAIN rate if only one of two upstreams can provide an answer.  All upstream entries in a resolv.conf file should be able to answer the same set of domains.  It should never contain a mix of recursive public servers and private domain dns servers.  This is in general, not just in the context of CoreDNS.

To configure private stub domains in coredns, see: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns
