### ISSUE TITLE
coredns arm64 container image have the wrong architecture in their manifests

### ISSUE THREAD

**Issue by opskumu** [miekg/coredns#5365]
**What happened**:

coredns arm64 container image have the wrong architecture in their manifests

```
➜  ~ docker pull --platform linux/arm64 coredns/coredns:1.8.7
1.8.7: Pulling from coredns/coredns
Digest: sha256:58508c172b14716350dc5185baefd78265a703514281d309d1d54aa1b721ad68
Status: Image is up to date for coredns/coredns:1.8.7
docker.io/coredns/coredns:1.8.7
➜  ~ docker inspect coredns/coredns:1.8.7 | grep -i arch
        "Architecture": "amd64",  
➜  ~
```

right  Architecture should `arm64`

**What you expected to happen**:

I found https://github.com/coredns/coredns/pull/4779 solve the problem, but now is wrong

**How to reproduce it (as minimally and precisely as possible)**:

None

**Anything else we need to know?**:

None

**Comment by zouyee** [comment]
duplicate https://github.com/coredns/coredns/issues/5363
