### ISSUE TITLE
How to resolve external CNAME without forward plugin

### ISSUE THREAD

**Issue by Dakyne** [miekg/coredns#5369]
Hi,
I setup two instances in a Corefile, one is listening on private interface and is answering everything and forward to public resolver when needed. The second one is listening onto public interface, and should only answer my own domains (let's say it's example.com).

The issue I face is with a CNAME resolving an external domain, it fails to resolve if I don't have forward plugin enabled (it would turn my resolver into an open one and I don't want this) or a record specifying the NS of this domain (it is not suitable because of scalability).

Example: 
`mycname.example.com. IN CNAME public.domain.com` <- this fails to resolve

I already read the issues about this, but no solution works for me.

Thanks!

**Comment by chrisohaver** [comment]
Can you share your Corefile?

**Comment by chrisohaver** [comment]
> The issue I face is with a CNAME resolving an external domain, it fails to resolve if I don't have forward plugin enabled (it would turn my resolver into an open one and I don't want this)

One kludgey way to have your cake and eat it too would be to forward to a private/local instance ...

```
.:5399 {
  bind 127.0.0.1
  file ./Zonefile/example.com.db example.com
  forward . 8.8.8.8
}

example.com {
  bind <public-addr>
  forward . 127.0.0.1:5399
}
```

**Comment by Dakyne** [comment]
Yes sorry, I thought it was enough without. N.B: ports are fake and I plan to use a common configuration once everything works as expected.

My instance runs in docker

LAN:53 → 0.0.0.0:54
WAN:53 → 0.0.0.0:53
Everything else is only exposed to localhost.

```yaml
# Internal zones reachable from LAN only
.:54 {
    auto  {
        directory /root/zones
        reload 30s
    }
    reload 5s
    cache 300
    cancel
    loadbalance round_robin
    local
    loop
    metadata
    minimal
    log
    errors
    health 0.0.0.0:1234
    ready  0.0.0.0:5678
    prometheus 0.0.0.0:9012
    warnlist {
        url https://hosts.oisd.nl/nsfw/ hostfile
        reload 1440m
    }
    forward . 1.1.1.1 # I want this line here
    debug
}
# External zones reachable from anywhere
.:53 {
    auto  {
        directory /root/zones db\.(.*((0)|(ca)|(com)|(eu)|(fr)|(info)|(net)|(org)|(ru)|(tn)|(vn))) {1}
        reload 30s
    }
    reload 5s
    cache 300
    cancel
    loadbalance round_robin
    local
    metadata
    minimal
    log
    errors
    health 0.0.0.0:3456
    ready  0.0.0.0:7890
    prometheus 0.0.0.0:1345
    warnlist {
        url https://hosts.oisd.nl/nsfw/ hostfile
        reload 1440m
    }
    forward . 1.1.1.1 # I don't want this line here
    debug
}
```

Sorry for the delay, I'm trying not to work on weekends!

**Comment by chrisohaver** [comment]
Applying the [example above](https://github.com/coredns/coredns/issues/5369#issuecomment-1119980460) to your configuration ...

```
(common) {
    reload 5s
    cache 300
    cancel
    local
    minimal
    log
    errors
    debug
}

# Internal zones reachable from LAN only
.:54 {
    auto  {
        directory /root/zones
        reload 30s
    }

    import common

    warnlist {
        url https://hosts.oisd.nl/nsfw/ hostfile
        reload 1440m
    }
    metadata
    loadbalance round_robin

    health 0.0.0.0:1234
    ready  0.0.0.0:5678
    prometheus 0.0.0.0:9012

    forward . 1.1.1.1
}

# External zones reachable from anywhere
ca com eu fr info net org ru tn vn {
    import common
    forward . 127.0.0.1:54
}



```

**Comment by Dakyne** [comment]
Thanks!

But with this configuration, the dns is still an open one for the specified tlds. It is "less open" than before.
Is it doable without a hacky method ?

**Comment by chrisohaver** [comment]
I assume the tlds listed have zones defined by auto, in which case they are not open.

**Comment by Dakyne** [comment]
I do have zones defined in auto. Let me try with examples:

1. private.lan1 IN A 1.2.3.4   <- Only reachable from private network (WORKING)
2. my-public-zone.com   IN A 2.3.4.5   <- Reachable from anywhere (WORKING)
3. google.com <- Should resolve only from private network (and other public DNS such as 1.1.1.1) (NOT WORKING : resolve from anywhere)
4. my-public-cname.com IN CNAME somethingpublic.com <- should resolve the final address from anywhere (WORKING)

The issue I face is with 3. and 4. the external server forwards everything and my dns is still an open one.

I found a way that works, but it makes me write 150+ domains...

```
example.ca example.com example.eu ... {
    import common
    forward . 127.0.0.1:54
}
```

**Comment by chrisohaver** [comment]
> I do have zones defined in auto.

I suspect you have some _sub_ domains defined, but not those exact TLDs.
For example, you may have a zonefile for `example.com` but not `com`.
Each authoritative zone (e.g. domain with a zonefile served by auto) must be listed for my example to work.

> ... but it makes me write 150+ domains.

If there is a pattern to the subdomains shared by the TLDs, you might be able to use *template* to block ones that don't fit the pattern.  But if there is no pattern, you'd have to list them all.

**Comment by Dakyne** [comment]
Thanks for your answers, there is no pattern except `[-a-z0-9]+\.(ca|com|eu|fr|info|net|org|ru|tn|vn)$` to grep the names.
I close the ticket.
