### ISSUE TITLE
health plugin: Frequent calls to http://:8080/health forwarded to http_proxy

### ISSUE THREAD

**Issue by tdihp** [miekg/coredns#5390]
**What happened**:

We configure http_proxy environment variable for CoreDNS, found http proxy receives frequent calls to `http://:8080/health`

**What you expected to happen**:

It shouldn't connect to proxy even if http_proxy is configured.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
export http_proxy=http://127.0.0.1:8000
cat <<EOT > Corefile
. {
  health
}
EOT
./coredns
```

Outcome:

```
.:53
CoreDNS-1.9.2
linux/amd64, go1.18.1, 092c144
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": proxyconnect tcp: dial tcp 127.0.0.1:8000: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": proxyconnect tcp: dial tcp 127.0.0.1:8000: connect: connection refused
[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": proxyconnect tcp: dial tcp 127.0.0.1:8000: connect: connection refused
```

**Anything else we need to know?**:

It works fine if using this Corefile instead:

```
. {
  health 127.0.0.1:8080
}
```

We've opened https://github.com/golang/go/issues/52988 during investigation of this issue, for tracking golang net/http behavior where transport connects to proxy when not specifying hostname, but works fine if specifying hostname as localhost/loopback.

Note that the behavior of `overloaded.go` which tries to visit /health itself is not documented and was the element of surprise for this investigation. Further documentation of this behavior is also a plus outcome for this issue. 

**Environment**:

- the version of CoreDNS: tested on v1.8.6 and v1.9.2
- Corefile:
  . {
    health
  }
- logs, if applicable: `[WARNING] plugin/health: Local health request to "http://:8080/health" failed: Get "http://:8080/health": proxyconnect tcp: dial tcp 127.0.0.1:8000: connect: connection refused`
- OS (e.g: `cat /etc/os-release`): Both with official CoreDNS Linux image/pod and in Ubuntu 20.04
- Others:

**Comment by chrisohaver** [comment]
> Note that the behavior of overloaded.go which tries to visit /health itself is not documented and was the element of surprise for this investigation. Further documentation of this behavior is also a plus outcome for this issue.

It is documented, but it is in the [Metrics](https://github.com/coredns/coredns/tree/master/plugin/health#metrics) section,  deep in TL;DR territory.

**Comment by chrisohaver** [comment]
IMO the self check should be modified to always bypass the proxy.

**Comment by tdihp** [comment]
> It is documented, but it is in the [Metrics](https://github.com/coredns/coredns/tree/master/plugin/health#metrics) section, deep in TL;DR territory.

True, also the mention of local access is subtle and rather implicit:

> duration to process a HTTP query to the local /health endpoint. As this a local operation it should be fast.

It doesn't explicitly explain on what is the trigger or frequency of this local operation. What I'd expect to be a clearer doc would be to append in description that: "When enabled, this plugin periodically sends HTTP query to the local /health endpoint in order to collect metrics."
