### ISSUE TITLE
Meaning of "fresh" stale responses (cache plugin)

### ISSUE THREAD

**Issue by FelixRTU** [miekg/coredns#5393]
Hi, can someone please explain a sentence from the [readme](https://github.com/coredns/coredns/blob/5b9b079dabc7f71463cea3f0c6a92f338935039d/notes/coredns-002.md) of the cache plugin? I don't understand what "fresh" means in the last sentence i posted below. Why are or should stale responses considered fresh again? So is there a difference in behavior if i set it to "0" or "2h"?
Thanks

> `serve_stale`, when serve_stale is set, cache always will serve an expired entry to a client if there is one available. When this happens, cache will attempt to refresh the cache entry after sending the expired cache entry to the client. The responses have a TTL of 0. DURATION is how far back to consider stale responses as **fresh**. [...]

**Comment by chrisohaver** [comment]
A cache entry that has been expired for longer than DURATION will not be sent to the client. A cache entry that has been expired for less than DURATION will be sent to the client.
