### ISSUE TITLE
how to configure CoreDNS act as full resolver , where to define internal root-hints

### ISSUE THREAD

**Issue by calberts** [miekg/coredns#5402]

**Comment by chrisohaver** [comment]
Without external plugins, CoreDNS is not a recursive resolver. You can use forward to forward requests to a recursive resolver, but it cannot do the resolution itself. 

There is the external plugin “unbound” which uses the unbound library to do recursive queries. Should be able to configure root hints in that plugin via `options` https://coredns.io/explugins/unbound/

**Comment by owenthereal** [comment]
I'm curious if it's possible to build a recursive resolver with something like https://github.com/domainr/dnsr. The unbound makes use of the libunbound wrapper which seems to have some issues compiling: https://github.com/coredns/unbound/issues/31

**Comment by chrisohaver** [comment]
> I'm curious if it's possible to build a recursive resolver with something like https://github.com/domainr/dnsr. 

Yeah, should be possible to wrap dnsr in an plugin. At a glance, it looks like it would be pretty straight forward.
