### ISSUE TITLE
coredns is stuck at  ContainerCreating

### ISSUE THREAD

**Issue by phyljh** [miekg/coredns#5424]
Hello~
I have an issue that coredns is stuck at ContainerCreating status.
I need solution for this issue.

$ kubectl get pods -n kube-system -o wide
NAME                                    READY   STATUS              RESTARTS   AGE   IP              NODE            NOMINATED NODE   READINESS GATES
coredns-6d4b75cb6d-2425h                0/1     ContainerCreating   0          41m   <none>          alienware-m15   <none>           <none>
coredns-6d4b75cb6d-j2wjf                0/1     ContainerCreating   0          41m   <none>          alienware-m15   <none>           <none>
etcd-alienware-m15                      1/1     Running             4          42m   192.168.0.121   alienware-m15   <none>           <none>
kube-apiserver-alienware-m15            1/1     Running             4          41m   192.168.0.121   alienware-m15   <none>           <none>
kube-controller-manager-alienware-m15   1/1     Running             4          42m   192.168.0.121   alienware-m15   <none>           <none>
kube-proxy-dmnp8                        1/1     Running             0          41m   192.168.0.121   alienware-m15   <none>           <none>
kube-scheduler-alienware-m15            1/1     Running             4          42m   192.168.0.121   alienware-m15   <none>           <none>
weave-net-k4xgx                         2/2     Running             0          37m   192.168.0.121   alienware-m15   <none>           <none>

--------------------------------------------------------------------------------------------

$ kubectl describe pods -n kube-system coredns-6d4b75cb6d-2425h
Name:                 coredns-6d4b75cb6d-2425h
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 alienware-m15/192.168.0.121
Start Time:           Fri, 03 Jun 2022 19:14:43 +0900
Labels:               k8s-app=kube-dns
                      pod-template-hash=6d4b75cb6d
Annotations:          <none>
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        ReplicaSet/coredns-6d4b75cb6d
Containers:
  coredns:
    Container ID:  
    Image:         k8s.gcr.io/coredns/coredns:v1.8.6
    Image ID:      
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kz9nc (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  kube-api-access-kz9nc:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly op=Exists
                             node-role.kubernetes.io/control-plane:NoSchedule
                             node-role.kubernetes.io/master:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                   From               Message
  ----     ------                  ----                  ----               -------
  Normal   Scheduled               43m                   default-scheduler  Successfully assigned kube-system/coredns-6d4b75cb6d-2425h to alienware-m15
  Warning  FailedCreatePodSandBox  43m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "81723f7d3c7a33a1d9e192d464df354408d48aa8143903c171147eed7c245aec": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
  Warning  FailedCreatePodSandBox  42m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1c83322f918932ff785bad15aff301299f573a1323d98a394de2d11c246ff491": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
  Warning  FailedCreatePodSandBox  42m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f63578b8ee08995181f43e8e78f8648834336b99c5bf65e1d12850663d4d6ca6": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
  Warning  FailedCreatePodSandBox  42m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "e1b4b42151c0be2c7d5ca09546a131e36092afd2738881ed184c75c79f3622e5": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
  Warning  FailedCreatePodSandBox  42m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3a61f5d12c2436aa5cc88d41103fc940a4125537bcc18d21408aa25a3ff48240": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
  Warning  FailedCreatePodSandBox  41m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "761d7a2040b0f93b27733e4efe5418da32c8abe15031a156159aaf66ba64cf13": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
  Warning  FailedCreatePodSandBox  41m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9658c9cff660cc93eb6faebb257a8b33a1b73d6c6b523b4fd8702a9737805fa2": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
  Warning  FailedCreatePodSandBox  41m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "b71263a1873d85c48391598c103012bf045f48425d6b625a99949424a35f2be1": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
  Warning  FailedCreatePodSandBox  41m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "fa0607cf56bc50f006b6db5de09fdf18e1f5b2d2c2f8d2e76b5638cadf2f5b50": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
  Warning  FailedCreatePodSandBox  3m5s (x175 over 41m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "708bf53ab6bcdcd9e2947a3770f843568b7322d301a77f33e00e4d789b309021": error getting ClusterInformation: Get "https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")

**Comment by chrisohaver** [comment]
Looks like a problem with your k8s cluster certs. Not a CoreDNS issue.

**Comment by chrisohaver** [comment]
Closing this since it's a problem with other Kubernetes infrastructure, not CoreDNS.
