### ISSUE TITLE
[Q] Can I use coredns to map my own purchased domain to my IP(s)?

### ISSUE THREAD

**Issue by NightMachinery** [miekg/coredns#5432]
I previously used sites like https://www.namecheap.com/ to set up the DNS records for my own domain names. Can I do this by self-hosting CoreDNS? How so?

Say I have a domain, `my_domain.com`. I like to set up IP addresses (A records) for `a1.my_domain.com`, `a2.my_domain.com`. How can I do so with CoreDNS?

**Comment by chrisohaver** [comment]
> Can I do this by self-hosting CoreDNS? How so?

Yes, it's possible. In a nutshell, host CoreDNS and expose it to the world on a public IP, register the IP as a nameserver for your domain.

>  I like to set up IP addresses (A records) for a1.my_domain.com, a2.my_domain.com. How can I do so with CoreDNS?

By using the [file plugin](https://github.com/coredns/coredns/tree/master/plugin/file#readme).
