### ISSUE TITLE
Enhancement: add k8s_event plugin

### ISSUE THREAD

**Issue by xh4n3** [miekg/coredns#5437]
**What would you like to be added**
k8s_event, a plugin that would send events to k8s.

**Why is this needed**
- Noticeable: Many CoreDNS users don’t setup CoreDNS metrics alerting before they had DNS breakdowns. If we push events like upstream DNS server timeout, Corefile reload failure to k8s, they should have notice some potential risk in the first place.
- Lasting & Precise: Metrics do not always provide enough information for finding root causes for DNS breakdowns. Container log are mostly mixed with access logs, and prone to get rotated. K8s events can provide slightly more lasting and more precise information.

**Consideration & Goals**
- Customizable:
  - event type: what kind (or level) of event should be reported
  - target k8s: which k8s apiserver endpoint to report events to
    - or are we gonna support other types of eventing in the future, e.g. cloud events?
- Less code: we better not to change every plugin's code to intergrate with this eventing plugin
- Avoid overloading k8s: include events from control plane, exclude events from each dns request

**Design** 
As Chris suggested, CoreDNS's logger package is responsible for the logging of all plugins, and is suitable for such a feature to be implement in. Besides, the k8s_event plugin could be the user interface to change the behaviors of this feature. Let me demonstrate below:

![image](https://user-images.githubusercontent.com/4469022/173582029-19afcc95-6b05-4045-951b-90745af081fa.png)

What k8s_event plugin does:
1. initiate a event recorder with k8s apiserver
2. wrap event recording logic in callback functions
3. call the logger's SetCallback with its callback functions

```go
func onStart() {
    kubeClient := getKubeClient()
    ref := getRef()
    recorder := getRecorder(kubeClient)
    log.SetCallback(logFunc, logfFunc)
}

func logfFunc(ref *corev1.ObjectReference, record record.EventRecorder, classes []Class) func(level, format string, v ...interface{}) {
	return func(level, format string, v ...interface{}) {
            if matchClass(level, classes) {
                record.Eventf(ref, corev1.EventTypeWarning, levelToReason(level), fmt.Sprintf(format, v))
            }
	}
}
```

What logger package does:
1. initiate a singleton variable to store callback functions, allow k8s_event to set
2. when its printer functions get called, it checks whether callback functions have been set
  a. if set, call the callback functions first, then call the Golang's log to print
  b. if not set, simply call the Golang's log to print
```go
// this is almost identical to the D singleton for Debug
var E = &e{}

type e struct {
	logfFunc func(level, format string, v ...interface{})
	logFunc  func(level string, v ...interface{})
	sync.RWMutex
}

func (e *e) SetCallback(logfFunc func(level, format string, v ...interface{}),
	logFunc func(level string, v ...interface{})) {
	e.Lock()
	e.logfFunc = logfFunc
	e.logFunc = logFunc
	e.Unlock()
}

// in the printer functions, we first call the callbacks if they exists
func (p P) Error(v ...interface{}) {
	if f := E.LogFunc(); f != nil {
		f(err, v)
	}
	p.log(err, v...)
}
```

**User Interface**
The k8s_event plugin take following options:
```
k8s_event {
    endpoint URL
    tls CERT KEY CACERT
    kubeconfig KUBECONFIG [CONTEXT]
    class CLASSES...
    rate [QPS] [Burst] [LRUCacheSize]
}
```
CLASSES is a space-separated list of classes of logs that should be reported as kubernetes events. The class of log will be reflected on the Reasonfield of event, e.g. k8s_event will use CoreDNSWarning as Reason for a warning log.
The classes of responses are:
- WARNING
- ERROR
- FATAL
If no class is specified, it defaults to all of above.

The option `rate` is used to control the throttling of events, which is passed to kubernetes client, see https://github.com/kubernetes/client-go/blob/master/tools/record/event.go#L55 for details.

**Example**
When user triggered a reload error, the event would be like:
```bash
# kubectl get ev -w -n kube-system
LAST SEEN   TYPE      REASON         OBJECT                         MESSAGE
0s          Warning   CoreDNSError   pod/coredns-65f6b5565d-4gjvg   Corefile changed but reload failed: [[starting with listener file descriptors: Corefile:7 - Error during parsing: Unknown directive 'proxy']]
```

**Alternative Design**
The above design reuses the existing logging everywhere in the CoreDNS, it may output some unnecessary logs to k8s.
Alternative idea is to implement the eventing logic like a first-class citizen in the CoreDNS, and kubernetes event would be one of the many event sink kind. Describe below:
- add a new `event` package, which is same level as logger package
- keep k8s_event as user interface to setup the event sink
- add event reporting logic to the plugins that needs

![image](https://user-images.githubusercontent.com/4469022/173582155-a77b276b-a6ca-46ec-8c70-cc1c73ad0a85.png)

This design may requires additional work like injecting ReportEvent logic to all plugins, but the upsides of it are:
- we may have clearer description for Events
- thanks to separation of event and logs, we can have some logs aggregated, e.g., if forward plugin found ten Servfails in one minute, report as a event. 

**Discussion**
- Which design suits better?
- Should this k8s_event plugin be built-in or external?
  - Should we use coredns/kubeapi, but kubeapi is currently an external plugin. 
     - And how do we differentiate the kubeapi client used by k8s_events and the one used by kubenodes?
- What `runtime.Object` should be used in the k8s event?
  - When k8s_event push events to the same cluster where CoreDNS is running, we can use CoreDNS pod as runtime object, perhaps we need downward api.
   - When k8s_event push events to other cluster, we should let user specify which runtime object should be used.

Please leave some feedback on this, thanks! :p

**Comment by chrisohaver** [comment]
Thanks for an excellent write up! 

I'm not familiar with K8s Events, so I want understand in what contexts is it appropriate for an application such as CoreDNS to create Events.  IOW, are Events reserved for actionable events that intend to trigger other workflows, or can it be treated like an anything-goes log. I suspect more the former, therefore ...

> Which design suits better?

I think a generic events framework would work better.  Once that is in place, separate plugins could be written that adapt those generic events to other backends, like Kubernetes.  I think this might be what you are suggesting too, but I'm not sure.

> Should this _k8s_event_ plugin be built-in or external?

The events framework would have to be built in, but the adaptors could be external.

> Should we use coredns/kubeapi, but kubeapi is currently an external plugin.

It would simplify things a little to use _kubeapi_.  Doing so would also virtually require _k8s_event_ to be external (it would be awkward for an internal plugin to require an external plugin to function).

> And how do we differentiate the kubeapi client used by k8s_events and the one used by kubenodes?

They would have to use the same client.  I think it would be extremely unusual to want connect them each to a different cluster.  Or would it ...

> When k8s_event push events to other cluster ...

Can you describe a specific use case for pushing events to different/multiple clusters?  If this is needed, and fits the intended design of K8s Events, then _k8s_event_ would need to establish its own client, and perhaps also permit multiple _k8s_event_ plugin instances that can connect to different clusters.

Looking forward to see other maintainers thoughts on this.

**Comment by xh4n3** [comment]
> what contexts is it appropriate for an application such as CoreDNS to create Events.

IMHO, Events are structured logs to convey an explicit message, they are often used to inform on-calls about the system status. Some examples:
- kube-proxy acts as a network proxy that runs on each k8s node, it pushes a birthCry event after initialization. https://github.com/kubernetes/kubernetes/blob/v1.24.2-rc.0/cmd/kube-proxy/app/server.go#L789-L799
- node-problem-detector uses Event to report any abnormals on the nodes https://github.com/kubernetes/node-problem-detector#problem-api

Indeed, there is a trend that people use these events to automatically trigger some actions, to repair things automatically. 

No matter in which contexts, event messages must be clean and explicit. So separating events with cumbersome logs will be good.

> I think a generic events framework would work better.

Yeah, I think we can consider these actions to be nailed down:
- implement a generic events framework on the same level as the logger package
- implement k8s_event as an external plugin that relies on kubeapi
  - or implement k8s_event as an internal plugin, simply copies the apiserver client code from the kubernetes plugin

> They would have to use the same client. I think it would be extremely unusual to want connect them each to a different cluster. Or would it ...
> Can you describe a specific use case for pushing events to different/multiple clusters?

I was trying to be as customizable as possible, but I think you're right. Let's forget about these unusual cases, keep it simple for now.

BTW, how do you think about the User Interface part? And the UML diagram part in the Alternative Design part?

**Comment by chrisohaver** [comment]
> BTW, how do you think about the User Interface part?

IIUC, `class` is not needed if we aren't trying to latch on to the existing logs structure.
The first three options go away if it's made to use the _kubeapi_ plugin.
`rate` should be optional, with sensible defaults.

I think all user configuration would be at the adapter side (e.g. in _k8s_event_).  I can't think of any general event package configuration that would be needed.

>  And the UML diagram part in the Alternative Design part?

It makes sense to me.  The diagram essentially says:
* The events package receives events from other plugins (such as _kubernetes_ and _reload_ in the diagram).
* The events package reflects the events to other plugins that register to receive them  (_k8s_event_ in the diagram).

**Comment by johnbelamaric** [comment]
> Indeed, there is a trend that people use these events to automatically trigger some actions, to repair things automatically.

Speaking with my SIG Architecture hat on, these people are making a mistake. Events are explicitly *not* an API. There are no deprecation or other guarantees with events. They are intended for human consumption.

Instead, they should be using a watch on objects of interest and looking for the conditions they are interested in to determine when to react.

**Comment by johnbelamaric** [comment]
That said there I no issues with CoreDNS sending events. Just wanted to clear up the intended use of events in Kubernetes.

**Comment by chrisohaver** [comment]
>>  ... people use these events to automatically trigger some actions ...

> Speaking with my SIG Architecture hat on, these people are making a mistake.

Perhaps the initial design fits better then.  It does have the benefit of not needing to modify other plugins to send events.

**Comment by xh4n3** [comment]
> They are intended for human consumption.

@johnbelamaric Thanks for clarifying this. Maybe they do not have a choice when metrics/object status are not exported, anyway, they are on their own to adapt the version changes.

@chrisohaver Thanks, I'll draft a version of code with the initial design.

**Comment by chrisohaver** [comment]
Adding link to @xh4n3's implementation of the plugin: https://github.com/xh4n3/k8s_event

@xh4n3 has requested we transfer ownership of this plugin to the coredns project as a CoreDNS-maintained external plugin (i.e. to live in `coredns/k8s_event`).

**Comment by chrisohaver** [comment]
@xh4n3 , The plugin looks good to me.  Only thing I see missing is unit tests.

**Comment by xh4n3** [comment]
Thanks @chrisohaver for following this.
I've added the unit test part in https://github.com/xh4n3/k8s_event/pull/3 . Please let me know if that's okay to merge.

**Comment by xh4n3** [comment]
@chrisohaver Thanks for reviewing the pr, the unit test part is merged now.
Next we should begin transferring the ownership, what should I do?

**Comment by yongtang** [comment]
@xh4n3  Let me help you with that. I will create a repo named `k8s_event` within the org and add you to the repo.

**Comment by yongtang** [comment]
@xh4n3  I have created the repo https://github.com/coredns/k8s_event and added you with write access. Can you push the code into the repo (ideally with commit history)?

**Comment by chrisohaver** [comment]
It should be easier to just transfer the repo...

I have done this before without a problem.

i.e. @xh4n3, from your repo, go to settings, and find the transfer option.
We should get notified and be able to accept the transfer.  Then we can add you as a maintainer with write access.

**Comment by xh4n3** [comment]
Thank you @yongtang for creating the repo 😃 

> It should be easier to just transfer the repo...

The transfering failed with `coredns/k8s_event already exists` so I guess I have to push the code then.

**Comment by chrisohaver** [comment]
> > It should be easier to just transfer the repo...
> 
> The transfering failed with `coredns/k8s_event already exists` so I guess I have to push the code then.

Unless we delete the repo, then transfer.

**Comment by chrisohaver** [comment]
Sorry I didn’t catch this before the repo got created. I don’t know if GitHub will reserve the name of a deleted repo for some period of time. May be safer to manually commit to the new repo now.

fwiw, IMO, retaining commit history is not important since its a first commit, and only you have worked on it.

**Comment by xh4n3** [comment]
Yeah, the new repo looks good now. Thank you @chrisohaver 
So the next thing to do would be updating the coredns/coredns.io, right?

**Comment by chrisohaver** [comment]
Just open a PR to add the external plugin.

**Comment by xh4n3** [comment]
@chrisohaver I opened two PR, [one](https://github.com/coredns/coredns.io/pull/272) adds the plugin documentation, [one](https://github.com/coredns/k8s_event/pull/1) fixes the repo path in the new repo. Please help me review them, thanks!
