### ISSUE TITLE
Cache-Plugin serve_stale unexpected behavior

### ISSUE THREAD

**Issue by FelixRTU** [miekg/coredns#5440]
**What happened**:

Using the cache-plugin and setting the `serve_stale` mode results in a parsing error: `Error during parsing: Wrong argument count or unexpected line ending after 'verify'`

---
**What you expected to happen**:

I excpected the config to be parsed and the "verify" mode to be selected for the cache-plugins serve_stale option. 

---
**How to reproduce it (as minimally and precisely as possible)**:

add the following to the concerning configmap 

```
cache {
            serve_stale 1h verify
 }
```
---

**Anything else we need to know?**:

- The readme is inconsistent with the actual code as the readme calls the mode "[verified](https://github.com/coredns/coredns/tree/master/plugin/cache#readme)" and in the code its "[verify](https://github.com/coredns/coredns/blob/66f2ac7568ccb0178cc9ce6dbd7320bcd3428d64/plugin/cache/setup.go#L186)" 

- The setup_test tests invalid values as in some successfull tests no time units are set (see [line 130](https://github.com/coredns/coredns/blob/66f2ac7568ccb0178cc9ce6dbd7320bcd3428d64/plugin/cache/setup_test.go#L130), [line 131](https://github.com/coredns/coredns/blob/66f2ac7568ccb0178cc9ce6dbd7320bcd3428d64/plugin/cache/setup_test.go#L131) and [line 132](https://github.com/coredns/coredns/blob/66f2ac7568ccb0178cc9ce6dbd7320bcd3428d64/plugin/cache/setup_test.go#L132))
- Using the configurations from the successful tests results in the stated parsing error.

---
**Environment**:

- the version of CoreDNS: 
  - registry.k8s.io/dns/k8s-dns-node-cache:1.21.1   (1.22.2 issue still persisting)
  - k8s.gcr.io/coredns/coredns:v1.8.6
- Corefile:  [Corefile.txt](https://github.com/coredns/coredns/files/8928689/Corefile.txt)
- logs, if applicable: [node-local-dns-8djrj_node-cache.log](https://github.com/coredns/coredns/files/8928788/node-local-dns-8djrj_node-cache.log)

- OS: kubernetes v1.23.6 on linux vms with 3 nodes total
- Others: The 1.22.2 image seems to be the newest one. If there are other images i could try, please let me know.

**Comment by chrisohaver** [comment]
The option was not present in 1.8.6.  Added recently in 1.9.2 I think.
And `k8s-dns-node-cache:1.21.1`/`1.22.2` are probably not compiled with a version of coredns that has the option.

The option name in the README is wrong though, thanks for the catch.

**Comment by chrisohaver** [comment]
> And k8s-dns-node-cache:1.21.1/1.22.2 are probably not compiled with a version of coredns that has the option.

Per go.mod, they are using 1.7.0: https://github.com/kubernetes/dns/blob/master/go.mod#L7

**Comment by chrisohaver** [comment]
> no time units are set 

I don’t think units are required for zero length duration.

**Comment by FelixRTU** [comment]
Thank you for looking up the version. I will try to follow their "release process" to update the coredns dependency.

Concerning the the missing units. I just tested it and if i use `serve_stale 90` i get `plugin/cache: time: missing unit in duration "90"`. Thats why i think that these tests are incorrect

**Comment by FelixRTU** [comment]
Afaik only TTL values have no unit

**Comment by chrisohaver** [comment]
> if i use `serve_stale 90` i get `plugin/cache: time: missing unit in duration "90"`

90 isn’t a zero value.

**Comment by FelixRTU** [comment]
You are right. `0` does indeed work so the test should as well
