### ISSUE TITLE
How kubernetes handles unhealthy coredns pod?

### ISSUE THREAD

**Issue by shruthidharani-4313** [miekg/coredns#5442]
The below snippet is taken from default Corefile of coredns. 
```
data:  
  Corefile: |    
  .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
```
In this snippet, health plugin is used to report health status to http://localhost:8080/health. If 200 OK is reported means healthy coredns pod. But I have few queries, 
If anything other than 200 OK is reported as health status of coredns pod, will kubernetes destroy and recreate the coredns pod ?  Or how it will be handled by kubernetes?

If coredns pod is unhealthy, how is it handled to make it healthy? will kubernetes automatically take care of ensuring a healthy coredns pod ? What is the advised lameduck duration? Based on what parameters, we can come to a appropriate lameduck duration.

It would be really helpful if anyone can comment on this. Thanks in advance!

**Comment by chrisohaver** [comment]
It depends on the liveness probe defined in the coredns Deployment. It defines a number of allowed failures before the Pod is replaced.

**Comment by shruthidharani-4313** [comment]
Because i am using the default coredns deployment. How to check whether what is defined in liveness probe by default?

**Comment by chrisohaver** [comment]
Technically there isn’t a singular default deployment of coredns.  Each provider defines the default independently.

You can see the value in your cluster using `kubectl -n kube-system get deployment coredns -o yaml`.  This is the best way to know.

**Comment by shruthidharani-4313** [comment]
@chrisohaver Thanks, i could see failurethreshold: 5. Can you help me to clarify this query => What is the advised lameduck duration? Based on what parameters, we can come to a appropriate lameduck duration.

**Comment by chrisohaver** [comment]
5s is fine. It’s based on the typical client dns timeout.
