### ISSUE TITLE
How to restart coredns pod without downtime in kubernetes

### ISSUE THREAD

**Issue by shruthidharani-4313** [miekg/coredns#5443]
I have a coredns pod running in kube-system namespace. I need to restart the coredns pod without downtime. I am aware that we can do delete coredns pod using below command and new coredns pod will spin up automatically.
`kubectl delete pods -n kube-system -l k8s-app=kube-dns`

But it is creating downtime. So I am expecting to do a restart of this coredns pod without downtime.
 
Usecase: I have set TTL as 1hr i.e, `cache 3600`. I have an external dns server where I will forward any requests to that external dns server using forward plugin. And whenever I need to get recent changes in external dns entries before TTL gets expired, I think we need to restart the coredns pod. Is there any other way to get the changes on external dns into effect immediately? If restart is the only way, how can I do it without downtime? It would be really helpful when someone helps me on this. Thanks in advance!

**Comment by chrisohaver** [comment]
kubectl can do a rolling restart of a deployment, which should work better than deleting the pods.

**Comment by shruthidharani-4313** [comment]
@chrisohaver Can you help me with the command to do rolling restart of coredns?

**Comment by chrisohaver** [comment]
`kubectl rollout restart <deployment-name>`

(I've never actually done one - I just googled it.)

**Comment by dougludlow** [comment]
```
kubectl -n <namespace> rollout restart deployment coredns
```

To be exact.
