### ISSUE TITLE
go run   coredns\coredns.go  出现error

### ISSUE THREAD

**Issue by Webster-Yang** [miekg/coredns#5474]
[Running] go run "d:\workspace\other\coredns\coredns.go"
go: finding module for package github.com/Azure/azure-sdk-for-go/profiles/latest/dns/mgmt/dns
go: finding module for package github.com/Azure/azure-sdk-for-go/profiles/latest/privatedns/mgmt/privatedns
go: found github.com/Azure/azure-sdk-for-go/profiles/latest/dns/mgmt/dns in github.com/Azure/azure-sdk-for-go v66.0.0+incompatible
..\..\gopath\pkg\mod\k8s.io\client-go@v0.24.1\plugin\pkg\client\auth\exec\metrics.go:21:2: package io/fs is not in GOROOT (D:\install\go\go1.14.2.windows-amd64\go\src\io\fs)

[Done] exited with code=1 in 4.201 seconds

**Comment by Webster-Yang** [comment]
PS D:\workspace\other\coredns>
PS D:\workspace\other\coredns>
PS D:\workspace\other\coredns> go get -u
go: google.golang.org/genproto upgrade => v0.0.0-20220628213854-d9e0b6570c03
go: github.com/prometheus/common upgrade => v0.35.0
go: golang.org/x/net upgrade => v0.0.0-20220624214902-1bab6f366d9e
go: github.com/Azure/go-autorest/autorest/to upgrade => v0.4.0
go: golang.org/x/sys upgrade => v0.0.0-20220627191245-f75cf1eec38b
go: golang.org/x/tools upgrade => v0.1.11
go: github.com/golang/protobuf upgrade => v1.5.2
go: cloud.google.com/go/compute upgrade => v1.7.0
go: github.com/cespare/xxhash/v2 upgrade => v2.1.2
go: google.golang.org/protobuf upgrade => v1.28.0
go: github.com/go-openapi/jsonreference upgrade => v0.20.0
go: golang.org/x/mod upgrade => v0.5.1
go: github.com/prometheus/client_golang upgrade => v1.12.2
go: golang.org/x/crypto upgrade => v0.0.0-20220622213112-05595931fe9d
go: k8s.io/klog/v2 upgrade => v2.70.0
go: github.com/DataDog/sketches-go upgrade => v1.4.1
go: github.com/google/go-cmp upgrade => v0.5.8
go: github.com/googleapis/gax-go/v2 upgrade => v2.4.0
go: golang.org/x/oauth2 upgrade => v0.0.0-20220628200809-02e64fa58f26
go: github.com/davecgh/go-spew upgrade => v1.1.1
go: gopkg.in/yaml.v3 upgrade => v3.0.1
go: k8s.io/api upgrade => v0.24.2
go: go.opencensus.io upgrade => v0.23.0
go: google.golang.org/grpc upgrade => v1.47.0
go: github.com/pkg/errors upgrade => v0.9.1
go: go.uber.org/zap upgrade => v1.21.0
go: sigs.k8s.io/yaml upgrade => v1.3.0
go: sigs.k8s.io/json upgrade => v0.0.0-20220525155127-227cbc7cc124
go: google.golang.org/api upgrade => v0.86.0
go: github.com/emicklei/go-restful upgrade => v2.15.0+incompatible
go: golang.org/x/xerrors upgrade => v0.0.0-20220609144429-65e65417b02f
go: github.com/go-logr/logr upgrade => v1.2.3
go: go.uber.org/atomic upgrade => v1.9.0
go: golang.org/x/text upgrade => v0.3.7
go: github.com/go-openapi/jsonpointer upgrade => v0.19.5
go: k8s.io/apimachinery upgrade => v0.24.2
go: golang.org/x/time upgrade => v0.0.0-20220609170525-579cf78fd858
go: google.golang.org/appengine upgrade => v1.6.7
go: github.com/Microsoft/go-winio upgrade => v0.5.2
go: github.com/google/gofuzz upgrade => v1.2.0
go: github.com/Azure/go-autorest/autorest/adal upgrade => v0.9.20
go: go.uber.org/multierr upgrade => v1.8.0
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: github.com/aws/aws-sdk-go upgrade => v1.44.44
go: github.com/prometheus/client_model upgrade => v0.2.0
go: github.com/Azure/go-autorest/autorest upgrade => v0.11.27
go: sigs.k8s.io/structured-merge-diff/v4 upgrade => v4.2.1
go: github.com/golang/groupcache upgrade => v0.0.0-20210331224755-41bb18bfe9da
go: github.com/json-iterator/go upgrade => v1.1.12
go: github.com/google/uuid upgrade => v1.3.0
go: github.com/golang/glog upgrade => v1.0.0
go: github.com/mitchellh/go-homedir upgrade => v1.1.0
go: github.com/beorn7/perks upgrade => v1.0.1
go: github.com/mailru/easyjson upgrade => v0.7.7
go: k8s.io/kube-openapi upgrade => v0.0.0-20220627174259-011e075b9cb8
go: github.com/go-openapi/swag upgrade => v0.21.1
go: github.com/opentracing/opentracing-go upgrade => v1.2.0
go: k8s.io/client-go upgrade => v1.5.2
go: github.com/tinylib/msgp upgrade => v1.1.6
go: github.com/gogo/protobuf upgrade => v1.3.2
go: github.com/golang-jwt/jwt/v4 upgrade => v4.4.2
go: github.com/modern-go/reflect2 upgrade => v1.0.2
go: github.com/prometheus/procfs upgrade => v0.7.3
go: github.com/munnerz/goautoneg upgrade => v0.0.0-20191010083416-a7dc8b61c822
go: github.com/DataDog/datadog-go upgrade => v4.8.3+incompatible
go: github.com/spf13/pflag upgrade => v1.0.5
go: github.com/google/gnostic upgrade => v0.6.9
go: golang.org/x/term upgrade => v0.0.0-20220526004731-065cf7ba2467
go: github.com/modern-go/concurrent upgrade => v0.0.0-20180306012644-bacd9c7ef1dd
go: github.com/miekg/dns upgrade => v1.1.50
go: github.com/PuerkitoBio/purell upgrade => v1.1.1
go: k8s.io/utils upgrade => v0.0.0-20220210201930-3a6ce19ff2f9
go: github.com/jmespath/go-jmespath upgrade => v0.4.0
go: github.com/PuerkitoBio/urlesc upgrade => v0.0.0-20170810143723-de5bf2ad4578
go: github.com/openzipkin/zipkin-go upgrade => v0.4.0
go: github.com/Azure/go-autorest/tracing upgrade => v0.6.0
go: github.com/Azure/go-autorest/logger upgrade => v0.2.1
go: github.com/imdario/mergo upgrade => v0.3.13
go: github.com/Azure/go-autorest/autorest/date upgrade => v0.3.0
go: github.com/DataDog/datadog-go/v5 upgrade => v5.1.1
go: github.com/DataDog/datadog-agent/pkg/obfuscate upgrade => v0.37.1
go: finding module for package k8s.io/client-go/plugin/pkg/client/auth/gcp
go: finding module for package k8s.io/client-go/plugin/pkg/client/auth/openstack
go: finding module for package k8s.io/client-go/tools/clientcmd
go: finding module for package k8s.io/client-go/kubernetes
go: finding module for package k8s.io/client-go/plugin/pkg/client/auth/oidc
go: finding module for package k8s.io/client-go/rest
go: finding module for package k8s.io/client-go/tools/clientcmd/api
go: downloading cloud.google.com/go v0.102.0
go: finding module for package k8s.io/client-go/tools/cache
go: downloading cloud.google.com/go/compute v1.7.0
go: github.com/googleapis/enterprise-certificate-proxy upgrade => v0.1.0
go: finding module for package k8s.io/client-go/tools/clientcmd
go: finding module for package k8s.io/client-go/plugin/pkg/client/auth/oidc
go: finding module for package k8s.io/client-go/tools/cache
go: finding module for package k8s.io/client-go/tools/clientcmd/api
go: finding module for package k8s.io/client-go/plugin/pkg/client/auth/gcp
go: finding module for package k8s.io/client-go/kubernetes
go: finding module for package k8s.io/client-go/rest
go: finding module for package k8s.io/client-go/plugin/pkg/client/auth/openstack
plugin\kubernetes\controller.go:20:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/kubernetes
plugin\kubernetes\setup.go:20:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/plugin/pkg/client/auth/gcp
plugin\kubernetes\setup.go:21:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/plugin/pkg/client/auth/oidc
plugin\kubernetes\setup.go:22:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/plugin/pkg/client/auth/openstack
plugin\kubernetes\kubernetes.go:28:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/rest
plugin\kubernetes\object\informer.go:8:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/tools/cache
plugin\kubernetes\kubernetes.go:29:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/tools/clientcmd
plugin\kubernetes\kubernetes.go:30:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/tools/clientcmd/api
PS D:\workspace\other\coredns> ^C
PS D:\workspace\other\coredns> ^C
PS D:\workspace\other\coredns> ^C
PS D:\workspace\other\coredns> ^C
PS D:\workspace\other\coredns> ^C
PS D:\workspace\other\coredns> ^C
PS D:\workspace\other\coredns>

**Comment by Webster-Yang** [comment]
PS D:\workspace\other\coredns> go get k8s.io/client-go@latest
go: k8s.io/client-go latest => v1.5.2


报错如下：
plugin\kubernetes\controller.go:20:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/kubernetes
plugin\kubernetes\setup.go:20:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/plugin/pkg/client/auth/gcp
plugin\kubernetes\setup.go:21:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/plugin/pkg/client/auth/oidc
plugin\kubernetes\setup.go:22:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/plugin/pkg/client/auth/openstack
plugin\kubernetes\kubernetes.go:28:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/rest
plugin\kubernetes\object\informer.go:8:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/tools/cache
plugin\kubernetes\kubernetes.go:29:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/tools/clientcmd
plugin\kubernetes\kubernetes.go:30:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/tools/clientcmd/api

**Comment by Webster-Yang** [comment]
PS D:\workspace\other\coredns> go get k8s.io/client-go@v0.20.4
go: downloading k8s.io/client-go v0.20.4

报错如下：
[Running] go run "d:\workspace\other\coredns\coredns.go"
go: finding module for package k8s.io/api/batch/v2alpha1
go: finding module for package k8s.io/api/discovery/v1alpha1
..\..\gopath\pkg\mod\k8s.io\client-go@v0.20.4\kubernetes\scheme\register.go:37:2: module k8s.io/api@latest found (v0.24.2), but does not contain package k8s.io/api/batch/v2alpha1
..\..\gopath\pkg\mod\k8s.io\client-go@v0.20.4\kubernetes\scheme\register.go:43:2: module k8s.io/api@latest found (v0.24.2), but does not contain package k8s.io/api/discovery/v1alpha1

**Comment by Tantalor93** [comment]
Imo this is not very nicely described issue, if you have question, you shoud ask it and properly describe what happened, what did you want to achieve, why, version of GO etc. See https://github.com/coredns/coredns/blob/master/.github/CONTRIBUTING.md#bug-reports .  Dumping commands into issue template is not a good way to get help.

Regarding your issue, you need to compile CoreDNS with atleast GO 1.17 https://github.com/coredns/coredns#compilation-from-source also your go mod cache might be corrupted so you might want to run `go clean -modcache`.
