### ISSUE TITLE
CoreDNS conditional resolve depending on the domain name

### ISSUE THREAD

**Issue by m1iktea** [miekg/coredns#5475]
> Still unclear what you want to do. Again, examples would help.
> 
> Do you require external.abc.com to be resolved by an upstream dns, but foo.external.abc.com to be resolved internally?

hi , I have the same problem now,
I want to require out1.abc.com out2.abc.com outn.abc.com to be resolved by an upstream dns, but inside1.abc.com inside2.abc.com insiden.abc.com to be resolved internally 
This is my configfile, but not work
`corefile`
```
abc.com {
   file /etc/coredns/db.abc.com
   reload 30s
   log
   forward . 8.8.8.8
}
```
`db.abc.com`
```
$ORIGIN abc.com.
@	3600 IN	SOA sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600
	3600 IN NS a.iana-servers.net.
	3600 IN NS b.iana-servers.net.

@                      IN  NS    ns1
ns1                    IN  A     192.168.1.22
@                      IN  A     192.168.1.22
inside1                IN  A     192.168.1.22
inside2                IN  A     192.168.1.22
inside3                IN  A     192.168.1.22
inside4                IN  A     192.168.1.22
...
```

_Originally posted by @m1iktea in https://github.com/coredns/coredns/issues/5094#issuecomment-1170885800_

**Comment by m1iktea** [comment]
@chrisohaver I see you solved a similar problem, I wonder if you could help me with this

**Comment by m1iktea** [comment]
well, now i have a complex solution
`corefile`
```
inside1.abc.com inside2.abc.com inside3.abc.com inside4.abc.com inside5.abc.com insiden.abc.com ...{
   file /etc/coredns/db.abc.com
   reload 30s
   log
}
```
maybe Is there a better solution?

**Comment by chrisohaver** [comment]
So, generally if you want to serve a zone internally, it should be its own zone.  That said, there is a round about way to make two zones act like they are in same zone from a client perspective, by using _rewrite_ plugin:

```
abc.com {
   # add rewrite plugin here to rewrite insideX.abc.com -> insideX.abc.internal

   # and move the internal zone to a separate zone  ...
   file /etc/coredns/db.abc.internal

   forward . 8.8.8.8
}
```

Note that the internal zone would be defined as `abc.internal`, but the _rewrite_ plugin will obfuscate that from clients, and make it look like all the `insideX` records are in `abc.com`.

**Comment by m1iktea** [comment]
Glad to see your suggestion, as you say, when i request `insideX.abc.com`  `rewrite` plugin turn it to `insideX.abc.internal`,then use `file` plugin resolved it, when request `not-define.abc.com` , it will be resolved by upstream dns
