### ISSUE TITLE
Safe Search example

### ISSUE THREAD

**Issue by mrbluecoat** [miekg/coredns#5480]
How do I enable browser search engine safe search with CoreDNS via CNAME? For example: https://www.leowkahman.com/2017/09/11/enforce-safe-search-on-google-youtube-bing/

I tried `rewrite type CNAME bing.com strict.bing.com` but it threw this error: `plugin/rewrite: type rules must have exactly two arguments`

ref #3865

**Comment by chrisohaver** [comment]
IIUC, you just want to rewrite `bing.com` to `strict.bing.com`

```
rewrite name bing.com strict.bing.com
```

The fact that `strict.bing.com` holds a CNAME record doesn't matter.

**Comment by mrbluecoat** [comment]
Thanks!

**Comment by chrisohaver** [comment]
> The fact that strict.bing.com holds a CNAME record doesn't matter.

Actually `strict.bing.com` doesn't hold a CNAME. Using CNAMEs is just one of the proposed solutions in the provided link. CoreDNS could solve it the same way, using CNAMES via the template plugin instead of using rewrite. Two different ways to solve the same problem.  However, the rewrite plugin method is shorter/simpler.

**Comment by mrbluecoat** [comment]
@chrisohaver I tried this example:

`rewrite name pixabay.com safesearch.pixabay.com`

But when I browse to https://pixabay.com/images/search/example/ the **SafeSearch** checkbox is unchecked whereas https://safesearch.pixabay.com/images/search/example/ has it checked. Thoughts? Can you perhaps provide an example with `template` to see if that works better?

**Comment by chrisohaver** [comment]
I've opened a PR to add a CNAME example to the template README.

https://github.com/coredns/coredns/blob/25c5e34babfb60426303f1232d8b8370bfa6f538/plugin/template/README.md#fabricate-a-cname

To create the CNAME as you describe:

```
  template IN ANY pixabay.com {
    match "^pixabay\.com\.$"
    answer "pixabay.com 60 IN CNAME safesearch.pixabay.com"
  }
```

**Comment by mrbluecoat** [comment]
That appears to have worked from a DNS dig perspective but the end result doesn't have safe search enabled by default on the pixabay.com domain. Not sure if it's because it requires a true redirect rather than CNAME or if it's because CNAME isn't supported on apex domains

**Comment by mrbluecoat** [comment]
I don't think it's the apex issue because I also don't get the desired end result on

```
  template IN ANY www.ask.com {
    match "^www\.ask\.com\.$"
    answer "www.ask.com 60 IN CNAME safesearch.ask.com"
  }
```

**Comment by chrisohaver** [comment]
what do you mean by "true redirect"

**Comment by mrbluecoat** [comment]
sorry, browser redirect (higher network level)

**Comment by mrbluecoat** [comment]
Here's my test after setting the CNAME as provided above

https://pixabay.com/images/search/test/

![image](https://user-images.githubusercontent.com/382164/181260223-1e0e6694-6dfa-4521-a354-d4780c20d99a.png)

https://safesearch.pixabay.com/images/search/test/

![image](https://user-images.githubusercontent.com/382164/181260360-06153896-676a-4216-96ae-4065906fe98c.png)

**Comment by chrisohaver** [comment]
Appears as if the solution provided in https://www.leowkahman.com/2017/09/11/enforce-safe-search-on-google-youtube-bing/ isn't correct.

**Comment by mrbluecoat** [comment]
Can CoreDNS create a _301 redirect_?

**Comment by chrisohaver** [comment]
> Can CoreDNS create a _301 redirect_?

No, CoreDNS only receives and serves DNS queries.  It never sees the HTTP request.

**Comment by mrbluecoat** [comment]
Got it, thanks. I think this covers most my safe search needs so I'll close this and find an external solution for pixabay. Thanks!
