### ISSUE TITLE
Upgrading to coredns 1.8.4 broke Kubernetes cluster

### ISSUE THREAD

**Issue by d-wire** [miekg/coredns#5495]
**What happened**:
After upgrading our AWS EKS cluster in our prod env to 1.21, we then tried to upgrade the coredns add-on to 1.8.4 from 1.8.0. When the coredns pods started back up after the upgrade, we got this initial warning message:
`1.8.4: [WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API`
Followed by a constant stream of these error messages:
`E0706 21:02:37.616396       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:kube-system:coredns" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope`
and then all of the pods in the cluster started crashing, so we were forced to revert back to 1.8.0.

**What you expected to happen**:
coredns to upgrade successfully and the EKS cluster to continue running successfully.

**How to reproduce it (as minimally and precisely as possible)**:
This very well may be an issue with our EKS environment, so it might not be reproducible outside of our env. Would appreciate suggestions though.

**Anything else we need to know?**:

**Environment**:
- the version of CoreDNS: 1.8.4 (1.8.0 was working fine)
- OS (e.g: `cat /etc/os-release`): Alpine Linux 3.16.0
- kubernetes cluster version: 1.21
- aws-k8s-cni version: 1.11.2
- kube-proxy version: 1.21.2-eksbuild.2

**Comment by chrisohaver** [comment]
Starting in 1.8.1 ([notes](https://github.com/coredns/coredns/blob/master/notes/coredns-1.8.1.md)), CoreDNS requires list/watch permission to EndpointSlices.

**Comment by d-wire** [comment]
> Starting in 1.8.1 ([notes](https://github.com/coredns/coredns/blob/master/notes/coredns-1.8.1.md)), CoreDNS requires list/watch permission to EndpointSlices.

Does that need to be manually added to an IAM role? Because we never specified that in our dev env and it worked perfectly fine there.

**Comment by chrisohaver** [comment]
> Does that need to be manually added to an IAM role?

endpointslices list/watch needs to be added to the system:coredns CluserRole.

> Because we never specified that in our dev env and it worked perfectly fine there.

Perhaps the ClusterRole already had permission in Dev.  Or perhaps the K8s version in dev is < 1.19? 
For clusters < 1.19, Kubernetes still uses the Endpoints API to Route ClusterIP traffic to Pods. In 1.19 and later, it uses Endpointslices.  Therefore CoreDNS will monitor Endpointslices in clusters >= 1.19, but for clusters < 1.19 it will instead monitor Endpoints.

**Comment by d-wire** [comment]
> > Does that need to be manually added to an IAM role?
> 
> endpointslices list/watch needs to be added to the system:coredns CluserRole.
> 
> > Because we never specified that in our dev env and it worked perfectly fine there.
> 
> Perhaps the ClusterRole already had permission in Dev. Or perhaps the K8s version in dev is < 1.19? For clusters < 1.19, Kubernetes still uses the Endpoints API to Route ClusterIP traffic to Pods. In 1.19 and later, it uses Endpointslices. Therefore CoreDNS will monitor Endpointslices in clusters >= 1.19, but for clusters < 1.19 it will instead monitor Endpoints.

Huh our dev environment cluster role does have those permissions, but we never manually added them and we have no record of the coredns role in our Terraform. Any idea what normally creates that role and what could've updated it in dev but not prod?

**Comment by chrisohaver** [comment]
> Any idea what normally creates that role

The system:coredns ClusterRole is created by the tool used to install/upgrade the cluster.  E.g. kubeadm

> what could've updated it in dev but not prod?

K8s 1.21 still used CoreDNS 1.8.0 by default (when installed by kubeadm), so the upgrade tool would not have added the endpointslices roles when upgrading to 1.21. kubeadm started deploying CoreDNS 1.8.4 (with the endpointslices role) in k8s' following minor release, 1.22 - so if kubeadm upgraded dev to 1.22, it would have the updated permission.

How was coredns was upgraded on the systems? e.g. a manual update the coredns image version in the Deployment,  or was a tool used such as helm?  Was the same procedure used on dev and production?

**Comment by d-wire** [comment]
> How was coredns was upgraded on the systems? e.g. a manual update the coredns image version in the Deployment, or was a tool used such as helm? Was the same procedure used on dev and production?

We updated coredns via
`kubectl set image --namespace kube-system deployment.apps/coredns \
coredns=602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/coredns:v1.8.4-eksbuild.1`

And what might've happened is we tried to upgrade dev to 1.22 and it failed, but it's possible that it still updated the clusterrole while failing on the overall upgrade. Whereas prod we never even tried upgrading to 1.22.

**Comment by chrisohaver** [comment]
> ...we tried to upgrade dev to 1.22 and it failed ... Whereas prod we never even tried upgrading to 1.22.

Yeah that's probably it.  I presume the upgrade tool didn't 100% cleanly roll back after the failed upgrade.
