### ISSUE TITLE
Allow configuring min & max TTL in rewrite plugin

### ISSUE THREAD

**Issue by AndreasHuber-CH** [miekg/coredns#5501]
The rewrite plugin allows overwriting the TTL in DNS response to a fixed value.
I wanted to use this plugin to reduce TTL on some domains. But while using it I realized that if the existing TTL value is already lower than the configured value, the rewrite plugin actually increases the TTL value by overriding it - that is not the behavior I wanted.

I think overwriting TTL could be used more flexibly if the plugin accepts a **min-max** TTL range instead of a single value.
The logic would then be to set TTL to **min** if it is lower than **min**, set it to **max** if it is greater than **max**, or else leave TTL value unchanged.

For example setting **ttl suffix . 30-300** would restrict TTL values on all domains to the range 30s to 300s.
And to stay backwards compatible with a single TTL value, both **min** and **max** can be set to the single provided value.

Is anyone else interested in this feature? If yes, I could work on a pull request.

Does the syntax **min-max** make sense or would you prefer using 2 separate arguments for **min** and **max** with the 2nd being optional for backwards compatibility?

**Comment by chrisohaver** [comment]
I think a single argument is most backward compatible.

In essence,

```
rewrite ttl example.com. 11
```
... would be equivalent shorthand for ...
```
rewrite ttl example.com. 11-11
```

... and behave identically: Everything goes to 11 :guitar: 


cap at 11, no minimum ...
```
rewrite ttl example.com. 0-11
```

There's a bit of a syntax knot when specifying a lower bound with no upper bound.
The user could put a really big number as the max (e.g. max allowed TTL), which is a tad awkward.
Or, maybe allow leading and trailing dashes?  E.g.

```
rewrite ttl ceil.example.com. -11  # equivalent to rewrite ttl ceil.example.com. 0-11
rewrite ttl floor.example.com. 5-
```

**Comment by AndreasHuber-CH** [comment]
I find -11 and 5- a tiny bit awkward at first glance. But I agree its preferable than writing something like 5-99999.
For -11 I'd use 0-11 myself, but if both are supported its up to the user's preference.

Another option would be to use range notation in the form [min,max] allowing for unbounded ranges.
```
rewrite ttl shorthand.example.com. 30 # equivalent to rewrite ttl shorthand.example.com. [30,30]
rewrite ttl range.example.com. [30,300]
rewrite ttl ceil.example.com. [,11]  # equivalent to rewrite ttl ceil.example.com. [0,11]
rewrite ttl floor.example.com. [5,]
```
but I'm unsure whether this syntax makes is really better, or only more complicated.

**Comment by chrisohaver** [comment]
Maybe  `0:11` `:11` `30:` is less awkward...  `:11` looks less like a "negative 11."
But you get things that look like times ... `10:45` ... which could appear awkward.

Dunno - kinda splitting hairs here.
