### ISSUE TITLE
coredns/coredns:v1.8.6 --platform=arm64 but get Architecture=amd64

### ISSUE THREAD

**Issue by tukwila** [miekg/coredns#5507]
**What happened**:
when i pull image with the following cmd:
docker pull k8s.gcr.io/coredns/coredns:v1.8.6 --platform=arm64
i got the amd64 arch image.
**What you expected to happen**:
i need v1.8.6 arm64 coredns docker images
**How to reproduce it (as minimally and precisely as possible)**:
step 1: docker pull k8s.gcr.io/coredns/coredns:v1.8.6 --platform=arm64
step 2: docker images|grep coredns
k8s.gcr.io/coredns/coredns                             v1.8.6          edaa71f2aee8   9 months ago    46.8MB
step 3: $ docker inspect edaa71f2aee8
[
    {
        "Id": "sha256:edaa71f2aee883484133da046954ad70fd6bf1fa42e5aec3f7dae199c626299c",
        "RepoTags": [
            "k8s.gcr.io/coredns/coredns:v1.8.6"
        ],
        "RepoDigests": [
            "k8s.gcr.io/coredns/coredns@sha256:5b6ec0d6de9baaf3e92d0f66cd96a25b9edbce8716f5f15dcd1a616b3abd590e"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-10-07T13:15:28.986860811Z",
        "Container": "674e3d19cdb150251c172ff53c0f1a8cc45318e541e8ea75db35d8aec335fb86",
        "ContainerConfig": {
            "Hostname": "674e3d19cdb1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {},
                "53/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/coredns\"]"
            ],
            "Image": "sha256:a0615a6f4f58af3f79cb7c5d89136e45c30b8a1d9b702699f8e9178d8f599cec",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/coredns"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "20.10.8",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {},
                "53/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "sha256:a0615a6f4f58af3f79cb7c5d89136e45c30b8a1d9b702699f8e9178d8f599cec",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/coredns"
            ],
            "OnBuild": null,
            "Labels": null
        },
        **"Architecture": "amd64",**
        "Os": "linux",
        "Size": 46808803,
        "VirtualSize": 46808803,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/36958ebbcee25fd1f33f3d238dd482583f78d7bf6aa1d565e5d7c1cfff2ae633/diff",
                "MergedDir": "/var/lib/docker/overlay2/3da4fb11507f4b062c2ae1c132889fb81fc2f874438d3a44b157f3570840f0c5/merged",
                "UpperDir": "/var/lib/docker/overlay2/3da4fb11507f4b062c2ae1c132889fb81fc2f874438d3a44b157f3570840f0c5/diff",
                "WorkDir": "/var/lib/docker/overlay2/3da4fb11507f4b062c2ae1c132889fb81fc2f874438d3a44b157f3570840f0c5/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:256bc5c338a684323ce8b6f58f1b0d0573f5137e610e7b0a05bc4460d9ea0219",
                "sha256:4d29303809df0afe9eb5eb1e3a2e1e21a6c5c90d9be29f948bb98955986afff7"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Environment**:
os: cent7.9 
Linux node1 4.18.0-348.20.1.el7.aarch64 #1 SMP Wed Apr 13 20:57:50 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by chrisohaver** [comment]
@tukwila can you format the description to be human readable?  e.g. wrap commands and results in code block tags https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by tukwila** [comment]
> @tukwila can you format the description to be human readable? e.g. wrap commands and results in code block tags https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

hi，I delete some redundant info; please focus on the coredns docker image architecture value is not the expected value that I pull with 'platform=arm64'.

**Comment by chrisohaver** [comment]
> > @tukwila can you format the description to be human readable? e.g. wrap commands and results in code block tags https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code
> 
> hi，I delete some redundant info; please focus on the coredns docker image architecture value is not the expected value that I pull with 'platform=arm64'.

Can you wrap the CLI output in monospace code tags per the link I sent?  Thanks!

**Comment by chrisohaver** [comment]
This looks like the same issue as reported in #5363.
