### ISSUE TITLE
cname chaining with rewrite plugin not working as expected

### ISSUE THREAD

**Issue by ryaneorth** [miekg/coredns#5513]
I have the following scenario:

`a.mysite.com` is a CNAME to the AWS ELB `bd461bc04746446a1b571a40fb15648c-711623325.us-west-2.elb.amazonaws.com`.

This AWS ELB is associated with a service in my Kubernetes cluster (`my-service.default.svc.cluster.local`).

My goal is to avoid hair-pinning when hitting `a.mysite.com` from within the cluster and instead have it route directly to `my-service.default.svc.cluster.local`. To accomplish this, I am trying to use the rewrite plugin. Here is what my corefile looks like:

```
    .:53 {
        errors
        health
        ready
        rewrite name bd461bc04746446a1b571a40fb15648c-711623325.us-west-2.elb.amazonaws.com my-service.default.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

When I perform the following from a pod within my cluster, it works as expected (note `172.20.156.79` is the ClusterIP associated with the service `my-service.default.svc.cluster.local`):

```
root@sh:/# host bd461bc04746446a1b571a40fb15648c-711623325.us-west-2.elb.amazonaws.com
bd461bc04746446a1b571a40fb15648c-711623325.us-west-2.elb.amazonaws.com has address 172.20.156.79
```

However, when I do the same for `a.mysite.com` it doesn't seem to work as I'd expect:

```
root@sh:/# host a.mysite.com
a.mysite.com is an alias for bd461bc04746446a1b571a40fb15648c-711623325.us-west-2.elb.amazonaws.com.
bd461bc04746446a1b571a40fb15648c-711623325.us-west-2.elb.amazonaws.com has address 35.167.27.53
bd461bc04746446a1b571a40fb15648c-711623325.us-west-2.elb.amazonaws.com has address 54.191.2.51
bd461bc04746446a1b571a40fb15648c-711623325.us-west-2.elb.amazonaws.com has address 52.88.87.149
```

As a note, I recognize I could change the `rewrite` plugin in my corefile to be:

```
        rewrite name a.mysite.com my-service.default.svc.cluster.local
```

in order to achieve the results I want. However, I'd like to avoid this as there are hundreds of CNAMEs to the ELB `bd461bc04746446a1b571a40fb15648c-711623325.us-west-2.elb.amazonaws.com` in addition to `a.mysite.com`, with more being added all the time. I also know I could use a regular expression in the `rewrite` plugin in order to capture all of these CNAMEs, but that also is difficult to do given the structure of our domains.

Any ideas on why I'm seeing this behavior and how I can achieve the behavior I'm expecting using the `rewrite` (or perhaps a different) plugin?

**Comment by chrisohaver** [comment]
The entire answer (which contains both the CNAME and target A record) for `a.mysite.com` is being provided by the upstream name server. CoreDNS just forwards the result back to the client. CoreDNS in this instance never sees a query for the ELB name, so the rewrite rule never matches. 

rewrite is currently only capable of rewriting responses in two very specific ways: as it relates to avoiding name question/answer name mismatches, and for rewriting TTLs.

I think a generic response record rewriter would be a challenging feature to add (hard to implement and arrive at a good config syntax). But just a CNAME target rewrite option I think would be much easier, and I think would be useful on its own.

**Comment by ryaneorth** [comment]
Thanks for the quick response @chrisohaver . In your opinion do you think this is worth requesting as a feature?

**Comment by chrisohaver** [comment]
I think it's worth adding as a feature.  I could see it as a new `FIELD` option ... `cname`. If you're not up to adding it, you can request the feature and wait for someone else in the community to pick it up.
