### ISSUE TITLE
Reverse zones failed

### ISSUE THREAD

**Issue by alexio777** [miekg/coredns#5514]
**What happened**:

Resolve PTR not working.

**What you expected to happen**:

PTR resolve should work.

**How to reproduce it (as minimally and precisely as possible)**:

Corefile:
```
. {
  log
  any
}
10.0.0.0/24:0 {
  whoami
}
```

```
dig @127.0.0.1 -x 10.0.0.17
....
;; QUESTION SECTION:
;17.0.0.10.in-addr.arpa.                IN      PTR
....
```

nothing is returned in response

**Environment**:

- the version of CoreDNS: CoreDNS-1.9.3
- logs, if applicable:
```[INFO] 127.0.0.1:48154 - 24028 "PTR IN 17.0.0.10.in-addr.arpa. udp 63 false 4096" - - 0 0.00005195s```
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04 LTS

**Comment by mariuskimmina** [comment]
Not exactly sure what you expect the PTR record to be, what answer do you expect?

Also, when you modify the Corefile to log on both instances

```
. {
  log
  any
}
10.0.0.0/24:0 {
  log
  whoami
}
```

you will notice that you still only get 1 log entry. 
You could do something like this instead

```
.:1053 {
  log
  any
  forward . 127.0.0.1:1054
}
10.0.0.0/24:1054 {
  log
  whoami
}
```
to receiv an answer from the `whoami` plugin
```
;; QUESTION SECTION:
;; 17.0.0.10.in-addr.arpa.              IN      PTR

;; ADDITIONAL SECTION:
17.0.0.10.in-addr.arpa. 0       IN      A       127.0.0.1
_udp.17.0.0.10.in-addr.arpa.    0       IN      SRV     0 0 59363 .
```

If this does not answer your question, please elaborate a bit further.

**Comment by chrisohaver** [comment]
```
. {
  log
  any
}
10.0.0.0/24:0 {
  whoami
}
```

The corefile doesn't actually have any plugins in it that provide answers, hence an empty answer.  This is expected.
