### ISSUE TITLE
"Name or service not known" error with valid domain name

### ISSUE THREAD

**Issue by dankirkpatrick** [miekg/coredns#5525]
I'm having a similar issue as https://github.com/coredns/coredns/issues/5348 but that issue is closed.  I commented on that, but I also am opening a new issue.  Hopefully that I the correct course of action.

We have an on-prem k8s cluster.  A service is configured to call out to an internal-only DNS name, let's say "fubar.example.com".  "example.com" is a valid domain with an authoritative name server, but "fubar.example.com" is internal-only, with a DNS entry only on our internal DNS server, not on the authoritative name server.  About 50% of my requests fail with "name or server not known", while the other 50% of requests succeed with the internal IP address.  This is on a cluster with little-to-no traffic, so it's not a result of high load.

I'm running a DNSUtils pod where I can make DNS requests directly.  Using dig, nslookup, and host apps, the behavior is the same, with 50% of requests failing.  I run a shell script to repeatedly call dig/nslookup/host every 35 seconds (less than 30 seconds seems to cache the DNS server, so all requests either succeed or fail).  Based upon these symptoms, I presume that 1 of my 2 CoreDNS pods is failing, and depending upon which pod my requests get routed to they succeed or fail.  However, from my logs I can get a success then a failure with both requests being serviced by the same CoreDNS pod.

My CoreDNS config looks like:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
    }
```
Logs in CoreDNS of a successful then a failing request, using nslookup:

```
2022-07-19T09:29:56.263793400-07:00 [INFO] 10.233.64.0:41956 - 2212 "A IN fubar.example.com.default.svc.cluster.local. tcp 67 false 65535" NXDOMAIN qr,aa,rd 160 0.0001617s
2022-07-19T09:29:56.265911500-07:00 [INFO] 10.233.64.0:41956 - 38936 "A IN fubar.example.com.svc.cluster.local. tcp 59 false 65535" NXDOMAIN qr,aa,rd 152 0.0001502s
2022-07-19T09:29:56.267069800-07:00 [INFO] 10.233.64.0:41956 - 61309 "A IN fubar.example.com.cluster.local. tcp 55 false 65535" NXDOMAIN qr,aa,rd 148 0.0001048s
2022-07-19T09:30:12.678203100-07:00 [INFO] 10.233.64.0:44030 - 41709 "A IN fubar.example.com.default.svc.cluster.local. tcp 67 false 65535" NXDOMAIN qr,aa,rd 160 0.0001805s
2022-07-19T09:30:12.679498300-07:00 [INFO] 10.233.64.0:44030 - 15851 "A IN fubar.example.com.svc.cluster.local. tcp 59 false 65535" NXDOMAIN qr,aa,rd 152 0.0001183s
2022-07-19T09:30:12.680276400-07:00 [INFO] 10.233.64.0:44030 - 35506 "A IN fubar.example.com.cluster.local. tcp 55 false 65535" NXDOMAIN qr,aa,rd 148 0.0001047s
```

And here is the output from my DNSUtils client:
```
root@dnsutils:/# nslookup fubar.example.com
Server:         10.233.0.10
Address:        10.233.0.10#53

Name:   fubar.example.com
Address: 10.211.80.251


root@dnsutils:/# nslookup fubar.example.com
Server:         10.233.0.10
Address:        10.233.0.10#53

** server can't find fubar.example.com: NXDOMAIN
```

Here is a dig request that fails:
```
root@dnsutils:/# dig fubar.example.com

; <<>> DiG 9.9.5-9+deb8u19-Debian <<>> fubar.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 16635
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;fubar.example.com.       IN      A

;; AUTHORITY SECTION:
example.com.         30      IN      SOA     ns1-01.azure-dns.com. azuredns-hostmaster.microsoft.com. 1 3600 300 2419200 300

;; Query time: 40 msec
;; SERVER: 10.233.0.10#53(10.233.0.10)
;; WHEN: Tue Jul 19 16:52:19 UTC 2022
;; MSG SIZE  rcvd: 155
```

and here is the dig output on a successful request:

```
root@dnsutils:/# dig fubar.example.com

; <<>> DiG 9.9.5-9+deb8u19-Debian <<>> fubar.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15652
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;fubar.example.com.       IN      A

;; ANSWER SECTION:
fubar.example.com. 30     IN      A       10.211.80.251

;; Query time: 2 msec
;; SERVER: 10.233.0.10#53(10.233.0.10)
;; WHEN: Tue Jul 19 16:54:01 UTC 2022
;; MSG SIZE  rcvd: 91
```

(Note: I've replaced my actual DNS names with fubar.example.com in my copy/pastes above)
(Note: This is on a Kubespray/kubeadm-installed cluster, v1.21.9, with CoreDNS v1.8.0)

**Comment by chrisohaver** [comment]
The symptoms you give suggest you may have two upstream dns servers configured in CoreDNS Pod's /etc/resolv.conf, one of them able to answer the query, and the other returning NXDOMAIN. By default, the forward plugin uses a random policy selecting an upstream at random to forward to. This would result in a 50% NXDOMAIN rate if only one of two upstreams can provide an answer. All upstream entries in a resolv.conf file should be able to answer the same set of domains. It should never contain a mix of recursive public servers and private domain dns servers. This is in general, not just in the context of CoreDNS.

To configure private stub domains in coredns, see: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns

**Comment by chrisohaver** [comment]
... Also noticing that you don't have a _forward_ configured in the Corefile.  I don't know if this is because you deleted it when scrubbing, or if it actually doesn't have one.

If the later, then I'm guessing you must have node-local-dns deployed, otherwise you'd never get an answer for anything outside of cluster.local, or reverse zones.  If so, then the resolv.conf at play is the one configured in the node local coredns instance on the same node the dns client is running; Also any private zone stub domain configuration would need to be done on the node local coredns instances.

**Comment by dankirkpatrick** [comment]
Thanks for your help!  I was indeed missing the forward..apparently I removed it when I was debugging.  The issue was in my nodelocaldns configuration.  Your comments helped me identify the root cause.  I was looking only at coredns & my /etc/resolv.conf.
