### ISSUE TITLE
plugin/rewrite: Support CNAME target record answer rewrite

### ISSUE THREAD

**Issue by ryaneorth** [miekg/coredns#5527]
**What would you like to be added**:
Add a new `cname` option for the FIELD parameter in the rewrite plugin

**Why is this needed**:
The use-case this new field option would meet can found in [this question](https://github.com/coredns/coredns/issues/5513).

**Comment by chrisohaver** [comment]
The description needs to fully describe what the requested option does.

**Comment by chrisohaver** [comment]
Actually - while I was typing up an example description for you, I realize this request is more complicated than it might initially seem.

**Effectively, it must mutate the CNAME targets, _and also_ the attached records for those targets (both name and IPs). And to do that it needs to perform lookups for them ... which is something _rewrite_ doesn't do.**

I'm not sure where this kind of function should be implemented.  Maybe extending _rewrite_ to do this sort of thing is the way to go - maybe another plugin is a better approach.

**Comment by chrisohaver** [comment]
I'm thinking this should be OK to include in _rewrite_, as opposed to a new plugin.  It is unique compared to other rewrite operations, but I think it still fits.  The lookup should be easy to do with the `upstream` package.

@greenpau, @johnbelamaric, WDYT?

**Comment by chrisohaver** [comment]
This kind of dips _another_ toe into growing _rewrite_ into a fully fledged _answer_ rewriter (with the ability to ad-hoc rewrite any fields of records in an answer).  When deciding the syntax for this function, we should keep in mind possible future syntax for that kind of ad-hoc answer rewrite function.

**Comment by Amila-Rukshan** [comment]
Hi @chrisohaver 
I came across this issue when looking for an issue to contribute to in this repo. I understand the problem in the linked original issue but could not get my head around the suggested solution. Are you able to provide some corefile reflecting the implemented feature (using cname FIELD in rewrite) and input query and output response to better understand it?

Thanks for your time!

**Comment by chrisohaver** [comment]
Thanks for considering contributing!

A query for name `abc.example.com`, type `A`

The response without rewrite...
```
abc.example.com IN CNAME def.example.com
def.example.com IN A 1.2.3.4
```

The response with CNAME target answer rewrite,
using the proposed syntax `rewrite cname def.example.com. xyz.example.com.`
```
abc.example.com IN CNAME xyz.example.com
xyz.example.com IN A 5.6.7.8
```

**Comment by Amila-Rukshan** [comment]
@chrisohaver, Thanks for the quick response! 
Now it's clear to me. The task is to generate the modified response using `cname` record with target to `xyz.example.com.`(from the rewrite rule) and resove `A` records for new target. I will check the rewrite plugin code and get back to you if need any help!

**Comment by Amila-Rukshan** [comment]
@chrisohaver, I could create the basic version of the rewrite of the cname target in the answer[ like this in my forked repo ](https://github.com/coredns/coredns/compare/master...Amila-Rukshan:coredns:cname_rewrite?expand=1). So, the cname target rewrite is working now. It is using a ResponseRule same as done in ttl rewrite. Now I need to rewrite the A records with new IPs for the target. I see two ways to do it:

1. Resolve A records at plugin creation time and use them when a response matches the rule
2. When the response is matching then do resolve A record  for target and do the rewrite

Either way, I have no clue how to do it since it is another separate DNS request as I feel. Could you please give me some pointers for that and let me know if I'm I the right path?

Thanks!

**Comment by chrisohaver** [comment]
For various reasons, you should resolve the A record every time (your 2nd option above). Mainly because the upstream values could change over time, but also because a regex target name should be able to back reference the matched query name, and thus the cname target could be different for every query. 

You can use the Upstream package in coredns to do the lookup. Several plugins use that package to do CNAME look ups.

**Comment by Amila-Rukshan** [comment]
Thanks! I will check them

**Comment by Amila-Rukshan** [comment]
@chrisohaver 
Now I can do an `upstream.Lookup` call in the `RewriteResponse` method as [here](https://github.com/coredns/coredns/compare/master...Amila-Rukshan:coredns:cname_rewrite?expand=1#diff-79e6bd7aae2fe013041d958a4f7cfeee3be2c4ceb0844a0dc8166fb392d890c7R44)
But it creates an infinite loop as I can see with the log:
```
[INFO] Sending upstream request...
[INFO] Sending upstream request...
[INFO] Sending upstream request...
[INFO] Sending upstream request...
[INFO] Sending upstream request...
```
Am I doing something obviously wrong in that line of code?

**Comment by ryaneorth** [comment]
Hey @Amila-Rukshan - first I want to thank you for taking a look at this issue. I was curious if you ever solved your infinite loop issue in your implementation/were able to make progress in implementing this feature?

**Comment by chrisohaver** [comment]
Sorry - this slipped through the cracks.  @Amila-Rukshan if you are still having this issue, I can try to help.
Please let me know.

**Comment by chrisohaver** [comment]
@Amila-Rukshan, I think with this feature, it may be possible to create a rewrite rule that creates an infinite loop.  What was the configuration were you testing?

**Comment by Amila-Rukshan** [comment]
Hi @chrisohaver, This is configuration. Did not make any progress after that. I will check it this weekend
```
.:5300 { 
  any
  log
  rewrite cname chat.openai.com.cdn.cloudflare.net. developerdiary.me.
  forward . 1.1.1.1
}
``` 
and request
```
dig -p 5300 -t A chat.openai.com  @localhost
```
Code changes - https://github.com/coredns/coredns/compare/master...Amila-Rukshan:coredns:cname_rewrite?expand=1#diff-79e6bd7aae2fe013041d958a4f7cfeee3be2c4ceb0844a0dc8166fb392d890c7R44

**Comment by chrisohaver** [comment]
Thanks, That doesn't look inherently loopy.  I'll take a look at the code to see if I see why it could be recursing infinitely.

**Comment by chrisohaver** [comment]
~Does that link include all the changes?  It seems like its missing some parts.~

Nevermind - I found the bit I was looking for.

**Comment by ryaneorth** [comment]
I looked into this briefly and added a `debug.PrintStack()` to @Amila-Rukshan 's `cname_target.go` just before the call to `resp, err := r.Upstream.Lookup(r.ctx, r.state, r.toTarget, dns.TypeA)`. I used the same Corefile configuration they were using. Here is what the output looks like on the third recursive loop:

```
goroutine 98 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/coredns/coredns/plugin/rewrite.(*cnameResponseRule).RewriteResponse(0xc000534ea0, 0xc0007a45a0?, {0x3213368, 0xc0000ccc80})
	/Users/admin/dev/coredns/plugin/rewrite/cname_target.go:45 +0x135
github.com/coredns/coredns/plugin/rewrite.(*ResponseReverter).rewriteResourceRecord(...)
	/Users/admin/dev/coredns/plugin/rewrite/reverter.go:94
github.com/coredns/coredns/plugin/rewrite.(*ResponseReverter).WriteMsg(0xc00079e280, 0xc0007a4510?)
	/Users/admin/dev/coredns/plugin/rewrite/reverter.go:83 +0x2a2
github.com/coredns/coredns/plugin/forward.(*Forward).ServeDNS(0xc0001c0000, {0x320dbc8, 0xc00043a8a0}, {0x3213260, 0xc00079e280}, 0xc0007a4480)
	/Users/admin/dev/coredns/plugin/forward/forward.go:189 +0xc2d
github.com/coredns/coredns/plugin.NextOrFailure({0x2d270a5?, 0xc0005e4330?}, {0x31f82b8, 0xc0001c0000}, {0x320dbc8, 0xc00043a8a0}, {0x3213260, 0xc00079e280}, 0x0?)
	/Users/admin/dev/coredns/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/rewrite.Rewrite.ServeDNS({{0x31f82b8, 0xc0001c0000}, {0xc00014f6b0, 0x1, 0x1}, {0x31fe050, 0xc00019593c}}, {0x320dbc8, 0xc00043a8a0}, {0x32131b0, ...}, ...)
	/Users/admin/dev/coredns/plugin/rewrite/rewrite.go:60 +0x55a
github.com/coredns/coredns/plugin.NextOrFailure({0x2d220d6?, 0x0?}, {0x31fe028, 0xc000135480}, {0x320dbc8, 0xc00043a8a0}, {0x32131b0, 0xc0000ccbc0}, 0x0?)
	/Users/admin/dev/coredns/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/any.Any.ServeDNS({{0x31fe028?, 0xc000135480?}}, {0x320dbc8?, 0xc00043a8a0?}, {0x32131b0?, 0xc0000ccbc0?}, 0x9?)
	/Users/admin/dev/coredns/plugin/any/any.go:19 +0x305
github.com/coredns/coredns/plugin.NextOrFailure({0x2d221de?, 0x1?}, {0x31fddf8, 0xc00014f760}, {0x320dbc8, 0xc00043a8a0}, {0x32131b0, 0xc0000ccbc0}, 0x0?)
	/Users/admin/dev/coredns/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/log.Logger.ServeDNS({{0x31fddf8, 0xc00014f760}, {0xc000696690, 0x1, 0x1}, {}}, {0x320dbc8, 0xc00043a8a0}, {0x3213310?, 0xc0001a6ab0?}, ...)
	/Users/admin/dev/coredns/plugin/log/log.go:36 +0x346
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0xc000064500, {0x320dbc8, 0xc00043a8a0}, {0x3213310, 0xc0001a6ab0}, 0xc0007a4480)
	/Users/admin/dev/coredns/core/dnsserver/server.go:364 +0x867
github.com/coredns/coredns/plugin/pkg/upstream.(*Upstream).Lookup(0x4?, {0x320dbc8, 0xc00043a8a0}, {0xc0007a42d0, {0x32131b0, 0xc0000cca40}, {0x0, 0x0}, 0x0, 0x0, ...}, ...)
	/Users/admin/dev/coredns/plugin/pkg/upstream/upstream.go:32 +0x187
github.com/coredns/coredns/plugin/rewrite.(*cnameResponseRule).RewriteResponse(0xc000534ea0, 0xc0007a43f0?, {0x3213368, 0xc0000ccb00})
	/Users/admin/dev/coredns/plugin/rewrite/cname_target.go:46 +0x1c3
github.com/coredns/coredns/plugin/rewrite.(*ResponseReverter).rewriteResourceRecord(...)
	/Users/admin/dev/coredns/plugin/rewrite/reverter.go:94
github.com/coredns/coredns/plugin/rewrite.(*ResponseReverter).WriteMsg(0xc00079e1e0, 0xc0007a4360?)
	/Users/admin/dev/coredns/plugin/rewrite/reverter.go:83 +0x2a2
github.com/coredns/coredns/plugin/forward.(*Forward).ServeDNS(0xc0001c0000, {0x320dbc8, 0xc00043a8a0}, {0x3213260, 0xc00079e1e0}, 0xc0007a42d0)
	/Users/admin/dev/coredns/plugin/forward/forward.go:189 +0xc2d
github.com/coredns/coredns/plugin.NextOrFailure({0x2d270a5?, 0xc0005e4250?}, {0x31f82b8, 0xc0001c0000}, {0x320dbc8, 0xc00043a8a0}, {0x3213260, 0xc00079e1e0}, 0x0?)
	/Users/admin/dev/coredns/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/rewrite.Rewrite.ServeDNS({{0x31f82b8, 0xc0001c0000}, {0xc00014f6b0, 0x1, 0x1}, {0x31fe050, 0xc00019592c}}, {0x320dbc8, 0xc00043a8a0}, {0x32131b0, ...}, ...)
	/Users/admin/dev/coredns/plugin/rewrite/rewrite.go:60 +0x55a
github.com/coredns/coredns/plugin.NextOrFailure({0x2d220d6?, 0x0?}, {0x31fe028, 0xc000135480}, {0x320dbc8, 0xc00043a8a0}, {0x32131b0, 0xc0000cca40}, 0xc0007aa6f8?)
	/Users/admin/dev/coredns/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/any.Any.ServeDNS({{0x31fe028?, 0xc000135480?}}, {0x320dbc8?, 0xc00043a8a0?}, {0x32131b0?, 0xc0000cca40?}, 0x9?)
	/Users/admin/dev/coredns/plugin/any/any.go:19 +0x305
github.com/coredns/coredns/plugin.NextOrFailure({0x2d221de?, 0x1?}, {0x31fddf8, 0xc00014f760}, {0x320dbc8, 0xc00043a8a0}, {0x32131b0, 0xc0000cca40}, 0x0?)
	/Users/admin/dev/coredns/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/log.Logger.ServeDNS({{0x31fddf8, 0xc00014f760}, {0xc000696690, 0x1, 0x1}, {}}, {0x320dbc8, 0xc00043a8a0}, {0x3213310?, 0xc0001a6930?}, ...)
	/Users/admin/dev/coredns/plugin/log/log.go:36 +0x346
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0xc000064500, {0x320dbc8, 0xc00043a8a0}, {0x3213310, 0xc0001a6930}, 0xc0007a42d0)
	/Users/admin/dev/coredns/core/dnsserver/server.go:364 +0x867
github.com/coredns/coredns/plugin/pkg/upstream.(*Upstream).Lookup(0x4?, {0x320dbc8, 0xc00043a8a0}, {0xc0007a4000, {0x32131b0, 0xc0000cc100}, {0x0, 0x0}, 0x0, 0x0, ...}, ...)
	/Users/admin/dev/coredns/plugin/pkg/upstream/upstream.go:32 +0x187
github.com/coredns/coredns/plugin/rewrite.(*cnameResponseRule).RewriteResponse(0xc000534ea0, 0xc0007a4240?, {0x3213368, 0xc0000cc580})
	/Users/admin/dev/coredns/plugin/rewrite/cname_target.go:46 +0x1c3
github.com/coredns/coredns/plugin/rewrite.(*ResponseReverter).rewriteResourceRecord(...)
	/Users/admin/dev/coredns/plugin/rewrite/reverter.go:94
github.com/coredns/coredns/plugin/rewrite.(*ResponseReverter).WriteMsg(0xc00079e0f0, 0xc0007a4090?)
	/Users/admin/dev/coredns/plugin/rewrite/reverter.go:83 +0x2a2
github.com/coredns/coredns/plugin/forward.(*Forward).ServeDNS(0xc0001c0000, {0x320dbc8, 0xc00043a8a0}, {0x3213260, 0xc00079e0f0}, 0xc0007a4000)
	/Users/admin/dev/coredns/plugin/forward/forward.go:189 +0xc2d
github.com/coredns/coredns/plugin.NextOrFailure({0x2d270a5?, 0xc0005e4060?}, {0x31f82b8, 0xc0001c0000}, {0x320dbc8, 0xc00043a8a0}, {0x3213260, 0xc00079e0f0}, 0x0?)
	/Users/admin/dev/coredns/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/rewrite.Rewrite.ServeDNS({{0x31f82b8, 0xc0001c0000}, {0xc00014f6b0, 0x1, 0x1}, {0x31fe050, 0xc0001944f4}}, {0x320dbc8, 0xc00043a8a0}, {0x32131b0, ...}, ...)
	/Users/admin/dev/coredns/plugin/rewrite/rewrite.go:60 +0x55a
github.com/coredns/coredns/plugin.NextOrFailure({0x2d220d6?, 0x0?}, {0x31fe028, 0xc000135480}, {0x320dbc8, 0xc00043a8a0}, {0x32131b0, 0xc0000cc100}, 0x0?)
	/Users/admin/dev/coredns/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/any.Any.ServeDNS({{0x31fe028?, 0xc000135480?}}, {0x320dbc8?, 0xc00043a8a0?}, {0x32131b0?, 0xc0000cc100?}, 0x9?)
	/Users/admin/dev/coredns/plugin/any/any.go:19 +0x305
github.com/coredns/coredns/plugin.NextOrFailure({0x2d221de?, 0x1?}, {0x31fddf8, 0xc00014f760}, {0x320dbc8, 0xc00043a8a0}, {0x32131b0, 0xc0000cc100}, 0x0?)
	/Users/admin/dev/coredns/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/log.Logger.ServeDNS({{0x31fddf8, 0xc00014f760}, {0xc000696690, 0x1, 0x1}, {}}, {0x320dbc8, 0xc00043a8a0}, {0x3213310?, 0xc0001a65d0?}, ...)
	/Users/admin/dev/coredns/plugin/log/log.go:36 +0x346
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0xc000064500, {0x320dbc8, 0xc00043a8a0}, {0x3213310, 0xc0001a65d0}, 0xc0007a4000)
	/Users/admin/dev/coredns/core/dnsserver/server.go:364 +0x867
github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1({0x3214e90, 0xc000138080}, 0xc0007a4001?)
	/Users/admin/dev/coredns/core/dnsserver/server.go:178 +0x9b
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0007a2000?, {0x3214e90?, 0xc000138080?}, 0xc0007a4000?)
	/Users/admin/go/pkg/mod/github.com/miekg/dns@v1.1.51/server.go:37 +0x2f
github.com/miekg/dns.(*Server).serveDNS(0xc00079a000, {0xc0007a2000, 0x2c, 0x200}, 0xc000138080)
	/Users/admin/go/pkg/mod/github.com/miekg/dns@v1.1.51/server.go:659 +0x451
github.com/miekg/dns.(*Server).serveUDPPacket(0xc00079a000, 0xc00043c660?, {0xc0007a2000, 0x2c, 0x200}, {0x32128c8?, 0xc00000ea68}, 0xc00060c0a0, {0x0, 0x0})
	/Users/admin/go/pkg/mod/github.com/miekg/dns@v1.1.51/server.go:603 +0x1dc
created by github.com/miekg/dns.(*Server).serveUDP
	/Users/admin/go/pkg/mod/github.com/miekg/dns@v1.1.51/server.go:533 +0x485
```

It appears that the call to `Upstream.Lookup` is causing the request to go through the entire plugin chain and the last plugin to execute (forward) ultimately ends up invoking the `RewriteResponse` function on the `cnameResponseRule` by way of the `ResponseReverter`

**Comment by chrisohaver** [comment]
> It appears that the call to Upstream.Lookup is causing the request to go through the entire plugin chain

Yes, this is how Upstream works.

However, if the CNAME rewrite code is correctly matching names, it should not match the CNAME target query coming through the second time in and pass it along un-rewritten.   It's as if the cname rewrite rule is indiscriminately rewriting every response it sees.

**Comment by chrisohaver** [comment]
When the lookup is done for `developerdiary.me.` the response will contain just an A record.  The rewrite rule should not be doing anything with that answer... it's not a CNAME, it doesn't have a target.  The code may be looking up the wrong thing in the first place (e.g. re-sending the original query instead of looking up `developerdiary.me.`). Or perhaps the code is always rewriting A responses, regardless if the response also contains a CNAME (I suspect this is the cause).

@Amila-Rukshan, I recommend using a debugger to step through each iteration so see how the CNAME rule is handling things, or if you don't have a debugger, use some print statements to get an idea of what's going wrong.

Unrelated thoughts:
* the solution should handle any record that can be targeted by a CNAME - not just A records.
* ideally, the solution should allow not just exact name matching, but also other types of matching (similar to request name rewrites - regex, suffix, etc).

**Comment by Amila-Rukshan** [comment]
@ryaneorth, @chrisohaver, thanks a lot for the debugging it posting the findings. I will go through them carefully and continue the implementation.

**Comment by Amila-Rukshan** [comment]
@chrisohaver, @ryaneorth, when I debug the code it was obvious that I was making the upstream request without the condition check for cname target. Looping issue is resolved now and got it working - [updated changes](https://github.com/coredns/coredns/compare/master...Amila-Rukshan:coredns:cname_rewrite?expand=1)

I need a clarifications before extending the solution for other supports regex, suffix, ..etc. 

Currently, I have changed the `reverter.go`'s `RewriteResponse` to input `res` along `rr` (record). It seems reveters architecture was to do the rewite for individual record. This way cname's response rule will get called a few times depending on the number of records in the answer but the final output will be the same. Is this okay? I can add another method but it will end up defining empty methods in other response rewrite methods.

**Comment by chrisohaver** [comment]
closed by https://github.com/coredns/coredns/pull/6004
