### ISSUE TITLE
feat: add opentelemetry plugin

### ISSUE THREAD

**Issue by dongjiang1989** [miekg/coredns#5530]
**What would you like to be added**:

[opentelemetry](https://opentelemetry.io/) as an observability framework for cloud-native software is ♨️.

**Why is this needed**:

CoreDNS as a network centre handler, it's observability is critical, It will be helpful for CoreDns‘s simplicity connect with open-telemetry.

[Golang SDK](https://github.com/open-telemetry/opentelemetry-go)

**Comment by Tantalor93** [comment]
To add some more missing reasoning:

currently, for observability (tracing) purposes, there is an existing [trace](https://coredns.io/plugins/trace/) plugin, which is built on top of [Opentracing](https://opentracing.io/), but Opentracing as a project was deprecated and it is recommended to migrate to a new standard which is a [Opentelemetry](https://opentelemetry.io/docs/migration/opentracing/). Overall I think it makes sense to introduce a new plugin built on top of Opentelemetry and deprecate `trace` plugin.

Marking as a nice candidate for a first contribution to the project 👍 If you are up to it, you can pick it up @dongjiang1989

**Comment by dongjiang1989** [comment]
@Tantalor93  Thanks for your reply.  I want to pick up this feat.

**Comment by gkum99** [comment]
Hi @Tantalor93 i am new to open source and I would like to work on this issue.

**Comment by Tantalor93** [comment]
@2022H1030014G as there is not any activity on this, I think you can freely work on this and when you have some skeleton ready, just open a new draft PR, where we can talk on the details

**Comment by 75asu** [comment]
Hi @Tantalor93 , @2022H1030014G , If there isn't any movement on this one then I would like to pick this up and requesting @Tantalor93 to provide me some resources and file location to get this done

**Comment by Dentrax** [comment]
Any updates on this? Looking forward to this feature! @eminaktas

**Comment by KiranSatyaRaj** [comment]
is anyone working on this issue, has any pull request been made regarding this, if not I would love to take it up. @dongjiang1989

Edit: I started working on it folks. 
Edit: This is my first time working on a technical issue, So I might take more time, if anyone wants to work on it please go ahead

**Comment by Tantalor93** [comment]
It seems that @KiranSatyaRaj unassigned himself, I will assign myself to the issue and handle it as part of our company hacksgiving next week

**Comment by chrisohaver** [comment]
Closing this, per [comments](https://github.com/coredns/coredns/pull/5777#issuecomment-1327205020).
