### ISSUE TITLE
CoreDNS fails to start because KUBERNETES_SERVICE_HOST is undefined

### ISSUE THREAD

**Issue by linuswagner** [miekg/coredns#5542]
I am deploying a K8 cluster using kubeadm 1.21.0 and on top of that kubeEdge 1.8.1.
Sadly, the DNS within the cluster does not seem to work properly and I cannot access external addresses. I believe the reason is that the coredns pods are in an error state.  
When I look into the logs of the coredns pods, I see the following message:  

`plugin/kubernetes: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`

As far as I understand it, these environment variables are created based on all running services when the container is created (see https://kubernetes.io/docs/concepts/containers/container-environment/#cluster-information). But shouldn't the kubernetes service run in any case before coredns?

I could not find any information to my problem online. Do you have any suggestion?

**Comment by Tantalor93** [comment]
Hello, 

I dont know how your CoreDNS is configured and my knowledge of kubeEdge is very limited, but I think that it is a design of a [kubeEdge](https://github.com/kubeedge/kubeedge/issues/2092#issuecomment-677001097) that edge nodes cannot connect to the api server, therefore an instance of CoreDNS will not be able to work properly. For DNS purposes there is a [edgemesh](https://github.com/kubeedge/edgemesh). 

If need be, you can try configure kubernetes plugin and set api server endpoints properly, see https://github.com/coredns/coredns/tree/c2dbb7141a7c95aa521a41b27bed3af25de8f546/plugin/kubernetes#syntax

Nevertheless I would say it is mainly a question for kubeEdge and I can see that you opened an issue there already https://github.com/kubeedge/kubeedge/issues/4079 👍

**Comment by linuswagner** [comment]
Indeed, installing edgemesh has solved the problem. CoreDNS still shows up in an error state, but the DNS resolution seems to work
