### ISSUE TITLE
At work we use infoblox, at home I used a windows server w/ dns enabled, but could I use coreDNS and drop windows server?

### ISSUE THREAD

**Issue by lknite** [miekg/coredns#5547]
CoreDNS within a kubernetes cluster has the dns for the internal workings of kubernetes ... but could I just spin it up (as another coredns instance within my kubernetes server) and use it with external-dns and use it as onprem, home lab dns server ... and get rid of my aging windows server dns instance?  -- i don't see a good infoblox open source alternative

**Comment by johnbelamaric** [comment]
Yep.

**Comment by lknite** [comment]
```
isClusterService: false
```

Also, external-dns has [documentation ](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/coredns.md)on how to use coredns.
