### ISSUE TITLE
Question about load balancing behavior(RR).

### ISSUE THREAD

**Issue by 0Ams** [miekg/coredns#5566]
coredns version : v1.8.0, kubernetes v1.18
and used headless service.

Hello, I have a question about coredns behavior.

my service is composed of a frontend and a backend.
the frontend service http with service name as parameter.
I believe their service discovery is done through coredns.

But the problem is load balancing.
There are some pods get too many requests compared to the other pods.

**setting corefile**
```json
# this is part of it, and only the important part
backend-service.default.svc.cluster.local {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        reload
        loadbalance
}
```

**Script for checking dns call results**
```sh
    for i in {1..100}; do curl -o /dev/null -s --write-out '%{remote_ip}' backend-service.default.svc.cluster.local:5672 >> dns.log; echo "" >> dns.log; done
```

**checked result**
```sh
$ cat dns.log | awk '{print $1}' | sort -n | uniq -c
     60 10.xx.81.10
     10 10.xx.81.11
     7 10.xx.81.12
     3 10.xx.81.13
     6 10.xx.81.14
     4 10.xx.81.15
     10 10.xx.81.16
```

even if I try many times, I get a similarly high value for a specific IP address(10.xx.81.10).

It is similar to question [issues/2815,](https://github.com/coredns/coredns/issues/2815) but in my case, I send an HTTP request and get IP to the domain address and call it.

can you explain to me how to get a uniform IP address?

**Comment by Tantalor93** [comment]
Hello, you are using quite old version of CoreDNS.  Version 1.8.7 should contain improvements to the consistency and uniformity of loadbalancing of provided IPs made by @chrisohaver https://github.com/coredns/coredns/pull/4961 

I would recommend you to upgrade CoreDNS if possible.

**Comment by 0Ams** [comment]
TX!! 
I checked that it was working normally after changing the version(coredns:1.8.7).
