### ISSUE TITLE
How to add a record with type '@', for example @.example.com ? 

### ISSUE THREAD

**Issue by flexboy** [miekg/coredns#5569]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by Tantalor93** [comment]
Hello! This is not a bug, please consider opening new discussion https://github.com/coredns/coredns/discussions and please add more details about your problem and usecase
