### ISSUE TITLE
How to set the cname, mx, ns record in etcd backend?

### ISSUE THREAD

**Issue by yangzw1024** [miekg/coredns#5570]
I use etcd as the backend for coredns,, then how to set the cname, mx, ns and any other type record in etcd?

**Comment by johnbelamaric** [comment]
It used to be the case - and I assume it still is - that the etcd backend
plugin isn't really a general purpose backend plugin. It emulates skydns.
That's it. Probably should have been called skydns plugin. So, AFAIK the
answer to your question is "you cannot". :(

John
