### ISSUE TITLE
CoreDNS is failing to resolve reverse zone records correctly

### ISSUE THREAD

**Issue by ohorvath** [miekg/coredns#5593]
**What happened**:

Reverse DNS lookups are failing if you scale your deployments from 1 pod to 2 pods. 

**What you expected to happen**:

Reverse lookup should work for both endpoints of your service. 

**How to reproduce it (as minimally and precisely as possible)**:

Please see this related issue reported for Azure AKS: 

https://github.com/Azure/AKS/issues/3157

**Anything else we need to know?**:

We've found the root cause already:

https://github.com/kubernetes/kubernetes/issues/109115

coreDNS users should upgrade to 1.9.2 or later to fix this. Maybe this issue should be documented on coreDNS side also. 

**Environment**: Azure AKS 1.22, 1.23, EKS 1.22

- the version of CoreDNS: 1.8.7

**Comment by chrisohaver** [comment]
> Maybe this issue should be documented on coreDNS side also.

We don't really have a place for documenting known bugs for old versions.
I suppose the existence of this GitHub issue is a form of documentation, so thank you for reporting it

Closing this, since the bug has already been fixed in the version of client-go that the CoreDNS 1.9.2 release uses.

**Comment by chrisohaver** [comment]
Affected CoreDNS versions: 1.8.7, 1.9.0, 1.9.1

All of those versions of CoreDNS used client-go 1.23.x, which had the indexing regression.

**Comment by ohorvath** [comment]
@chrisohaver Thank you for your answer. You're right, we just wanted to let the community know about this issue, as the big cloud providers (Microsoft, Amazon) use 1.8.7 as a default in their k8s 1.22 and 1.23 clusters. :)
