### ISSUE TITLE
transfer failure with tsig between 2 coredns servers

### ISSUE THREAD

**Issue by linuxdevel7** [miekg/coredns#5600]
I want to use the tsig plugin between two coredns servers.

(the transfer error appears also when coredns is slave of a server on bind)

# my configs : 

## OS/version
I compiled the sources from the github repository.
I use the latest version of opensuse tumbleweed in container

### Corefile
```
. {
    root /etc/coredns

    bind 172.16.1.10

    errors
    log
    debug

    file ocn.org.hosts ocn.org

    transfer {
      to *
    }

    tsig {
      secret ocn.org.key. NoTCJU+DMqFWywaPyxSijrDEA/eC3nK0xi3AMEZuPVk=
      require AXFR IXFR
    }
}

```
### ocn.org.hosts
```
$ORIGIN ocn.org.
@       3600 IN SOA dns.ocn.org. admin.ocn.org. 2022090501 7200 3600 1209600 3600
        3600 IN NS dns1.ocn.org.
        3600 IN NS dns2.ocn.org.

www     IN A     172.16.1.1
dns1    IN A     172.16.1.10
dns2    IN A     172.16.1.11
```

### Corefile
```
. {
    root /etc/coredns

    bind 172.16.1.11

    errors
    log
    debug

    secondary ocn.org. {
       transfer from 172.16.1.10
    }
    transfer {
       to *
    }
    tsig ocn.org. {
       secrets /etc/coredns/coredns.keys
    }
}
```

### /etc/coredns/coredns.keys
```
key "ocn.org.key." {
    algorithm hmac-sha512;
    secret "NoTCJU+DMqFWywaPyxSijrDEA/eC3nK0xi3AMEZuPVk=";
};
```

# Results : 

I get the following errors: 
### on the master:
```
[INFO] 172.16.1.11:55490 - 44549 "AXFR IN ocn.org. tcp 28 false 65535" REFUSED qr 28 0.00007724s
[DEBUG] rejecting 'AXFR' request without TSIG
```

### on the slave:
```
[ERROR] plugin/file: Failed to transfer `ocn.org.' from "172.16.1.10:53": dns: bad xfr rcode: 5
[WARNING] plugin/secondary: All 'ocn.org.' masters failed to transfer, retrying in 250ms: dns: bad xfr rcode: 5
```

# Tests : 

The tests I have done : 

| master  | slave   | result |
|---------|---------|:--------:|
| coredns | dig     | OK     |
| coredns | bind    | OK     |
| bind    | coredns | KO 😭     |
| coredns    | coredns | KO 😭      |

**Comment by chrisohaver** [comment]
TSIG transfers are not yet implemented in the secondary plugin.
This was a known to-do listed with other to-dos in the PR [comments](https://github.com/coredns/coredns/pull/4957#issuecomment-992852683), but I accidentally omitted this one from the docs.

I've opened a PR to update the docs, and opened an issue to implement tsig in secondary.
