### ISSUE TITLE
tsig plugin: documentation, tag release and issue

### ISSUE THREAD

**Issue by fcolista** [miekg/coredns#5601]
Hello. 
Thanks first of all for this great software! :)

I'm in the need of using `tsig plugin`, that is not yet pushed within a tagged release, so I went ahead and backported the patch and started to test.

So, first question: **when we can expect a tagged release of coredns?**

Second and third "question":
In order to configure tsig, I checked the documentation, but I'm not sure how the slave should be configured.
https://github.com/coredns/coredns/blob/master/plugin/tsig/README.md

I've prepared a tiny testbed with two server with a primary and a slave.
Without the tsig plugin, all is working fine, with tsig, no.
I proceeded as follow:  ran ```tsig-keyen``` from `bind-tools` to get a tsig key and applied the same config to master and secondary.

**PRIMARY**
```
(base) {
    health localhost:8080
    prometheus localhost:9153
    root /etc/coredns
    log stdout
    errors stdout
    acl {
        allow net 127.0.0.1/32
        allow net ::1/128
        allow net 10.0.0.0/8
        block
    }
}

test.lan:53 {
    auto {
        directory /etc/coredns ^(test.lan)\.zone {1}
        reload 10s
    }
    tsig {                        
        secret key 0aQhubzGv0lt9M4N2J9Xq5K6zzz40ejyGLWlMNj3v78=
        require AXFR IXFR
    }  
    transfer {
        to 10.10.10.102
    }
    import base
}
```

**SECONDARY**
```
(base) {
    health localhost:8080
    prometheus localhost:9153
    log stdout
    errors stdout
    loop
    acl {
        allow net 10.0.0.0/8
        block
    }
}

test.lan:53 {
    secondary {
        transfer from 10.10.10.103
    }
    tsig {                        
        secret key 0aQhubzGv0lt9M4N2J9Xq5K6zzz40ejyGLWlMNj3v78=
        require AXFR IXFR
    }
    import base
}
```

Coredns LOG on secondary ns:
```
[ERROR] plugin/file: Failed to transfer `test.lan.' from "10.10.10.103:53": dns: bad xfr rcode: 5
[WARNING] plugin/secondary: All 'test.lan.' masters failed to transfer, retrying in 8s: dns: bad xfr rcode: 5
```

Dumping the traffic i see the DNS request with a standard AXFR request for test.lan from the secondary to the primary,
and the primary replies with `Refused AXFR test.lan` with code (5).

Perhaps is a misconfiguration, so the documentation can be improved, or perhaps is a real issue.

Do you have any hint/suggestion?

**OS:** : Alpine Linux Edge
tsig merged in: https://git.alpinelinux.org/aports/commit/?id=5b64cfd128dc
tsig plugin enabled in: https://git.alpinelinux.org/aports/commit/?id=c0f6697ac2e01583d4391e8ea7c69aa6f591f385

I'm the maintainer of CoreDNS package in Alpine.

Thank you for your valuable inputs.

.: Francesco

**Comment by yongtang** [comment]
Added #5603 for 1.9.4 release tracking.

**Comment by chrisohaver** [comment]
> So, first question: when we can expect a tagged release of coredns?

Probably within the next couple of weeks.

> Do you have any hint/suggestion? 

At first glance, your testbed configs looks fine.  I'll try to find time to take a look at reproducing it and debugging this week.

**Comment by chrisohaver** [comment]
OK, It's been so _long_ since I looked at the tsig plugin.  

TSIG support for the _secondary_ plugin is not yet implemented.  It's mentioned in the PR in a [comment](https://github.com/coredns/coredns/pull/4957#issuecomment-992852683), but I accidentally omitted it from the README.

I'll update that in the README, and open feature request to implement it (If some one else has time to pick it up that would be awesome, if not I'll do it when I get a chance).

**Comment by yongtang** [comment]
As the other documentation issue has been covered, we will try to release 1.9.4 today, unless there is a surprise.
