### ISSUE TITLE
plugin/file Transfer does not seem to work

### ISSUE THREAD

**Issue by vorgusa** [miekg/coredns#5607]
**What happened**:
I have a 3rd party DNS hosting service that points to a CoreDNS server and does notifies to when changes are made.  This works fine, but I am trying to have more CoreDNS servers that this node would notify of the changes after it receives them.  From reading the docs, I feel like I configured it right, but I see no traffic going out of CoreDNS using tcpdump or any notifies on the second server's logs

**What you expected to happen**:
I was expecting server 1 to send a notify or transfer to server 2

**How to reproduce it (as minimally and precisely as possible)**:
Configs below

**Anything else we need to know?**:

**Environment**:
2 servers in the same subnet with an external IP on server 1

- the version of CoreDNS: 1.9.3
- Corefile:
<SERVER 1>
```
.:53 {
    forward . <other DNS server IP> {
        except example.org
    }
}
example.org:53 {
  secondary {
    transfer from <3rd party IP>
  }
  transfer {
    to * <internal IP>
  }

  health :8080
  log all
}
```
SERVER 2
```
.:53 {
    forward . <other DNS server IP> {
        except example.org
    }
}
example.org:53 {
  secondary {
    transfer from <Server 1's IP>
  }
  health :8080
  log all
}
```
- logs, if applicable:
- 
```
Sep 07 17:06:25 zgqfwavkndqqnrwcvvaf-sysrv.example.org [1]: Started CoreDNS DNS server.
Sep 07 17:06:25 zgqfwavkndqqnrwcvvaf-sysrv.example.org coredns[6577]: .:53
Sep 07 17:06:25 zgqfwavkndqqnrwcvvaf-sysrv.example.org coredns[6577]: example.org.:53
Sep 07 17:06:25 zgqfwavkndqqnrwcvvaf-sysrv.example.org coredns[6577]: CoreDNS-1.9.3
Sep 07 17:06:25 zgqfwavkndqqnrwcvvaf-sysrv.example.org coredns[6577]: linux/amd64, go1.18.2, 45b0a11
Sep 07 17:06:26 zgqfwavkndqqnrwcvvaf-sysrv.example.org coredns[6577]: [INFO] plugin/file: Transferred: example.org. from <3rd party IP>:53
Sep 07 17:06:35 zgqfwavkndqqnrwcvvaf-sysrv.example.org coredns[6577]: [INFO] plugin/file: Notify from <3rd party IP> for example.org.: checking transfer
Sep 07 17:06:36 zgqfwavkndqqnrwcvvaf-sysrv.example.org coredns[6577]: [INFO] plugin/file: Transferred: example.org. from 208.78.68.66:53
Sep 07 17:06:58 zgqfwavkndqqnrwcvvaf-sysrv.example.org coredns[6577]: [INFO] plugin/file: Notify from <3rd party IP>  for example.org.: checking transfer
Sep 07 17:06:59 zgqfwavkndqqnrwcvvaf-sysrv.example.org coredns[6577]: [INFO] plugin/file: Transferred: example.org. from <3rd party IP>:53
```
- OS (e.g: `cat /etc/os-release`): Centos 7
- Others:

**Comment by chrisohaver** [comment]
I edited the description to make the corefiles and logs easier to read.

**Comment by chrisohaver** [comment]
> I am trying to have more CoreDNS servers that this node would notify of the changes after it receives them.

I'm not understanding what you mean here, can you phrase it differently?

**Comment by vorgusa** [comment]
Thanks for cleaning up the corefiles.   Basically I am trying to have a 3rd party DNS hosted service notify CoreDNS Server 1 which will then notify CoreDNS Servers 2,3,4,5,etc.  Hopefully that makes more sense

 <3rd party DNS Server>  -> Server 1 -> Server 2,3,4,5,etc

**Comment by chrisohaver** [comment]
Gotcha

> I was expecting server 1 to send a notify or transfer to server 2

You won't see a notify, since server 1 transfers to `*`.  It needs to have an IP defined in the `to`, so it has an actual destination to send the notify. (i.e. cant send notifies to `*`)

You should however see periodic transfer requests from server2 to server 1. One at start up, and then periodically based on the zone's SOA record.

**Comment by vorgusa** [comment]
I have tried lots of configs on Server 1 and have never seen any attempts.  The initial transfer when the CoreDNS starts up works fine just no notifies and we were hoping for an immediate update from the hosted DNS zone
```
example.org:53 {
  secondary {
    transfer from <3rd party IP>
  }
  transfer {
    to * <internal IP>
  }

  health :8080
  log all
}
```
```
example.org:53 {
  secondary {
    transfer from <3rd party IP>
  }
  transfer {
    to <internal IP>
  }

  health :8080
  log all
}
```
```
example.org:53 {
  secondary {
    transfer from <3rd party IP>
  }
  transfer {
    to * 
    to <internal IP>
  }

  health :8080
  log all
}
````

**Comment by chrisohaver** [comment]
Side note:  Your log statements `log all`, actually only log requests in the domain `all.` ... just `log` will do what you want.

**Comment by vorgusa** [comment]
that log was just on my Server 1 config, and I was seeing those logs.  So should not have impacted much

**Comment by chrisohaver** [comment]
Looking over the code, it looks like notifies are not implemented for the _secondary_ plugin. 

At a glance, it looks like it wouldn't  be too complicated to add, if there are no devils is in the details.

**Comment by vorgusa** [comment]
ohhh the documentation mentions secondary and even gives [examples](https://coredns.io/plugins/secondary/) with it.  Guessing this would not be super quick to add?

**Comment by chrisohaver** [comment]
> ohhh the documentation mentions secondary and even gives [examples](https://coredns.io/plugins/secondary/) with it

The documentation for the secondary does indeed mention "secondary" ... But it doesn't mention "notify", which is what prompted me to check the code.

> Guessing this would not be super quick to add?

Maybe - I'll give it a shot.

**Comment by vorgusa** [comment]
Thanks for your help!

**Comment by chrisohaver** [comment]
First stab didn't work.  I'll pick it back up tomorrow.

**Comment by vorgusa** [comment]
Thanks for trying it out.  Good luck tomorrow

**Comment by ferret1** [comment]
Has this issue been resolved?

As I am having the same problem. I have a few questions;

Is the transfer process only transferring the db file?
Will the whole zone record be transferred, e.g the "rewrite" rule?

**Comment by chrisohaver** [comment]
I have not yet implemented this feature because I have not been able to focus time on coding tasks in CoreDNS recently. I’ll open an enhancement issue in case someone else wants to pick it up before I get back to it. 
 
rewrite rules cannot be transferred. Records are transferred using the names the source records of a single plugin.

**Comment by chrisohaver** [comment]
I’ve opened an issue to add notifies to the secondary plugin.  #5669
