### ISSUE TITLE
Steering Committee Election

### ISSUE THREAD

**Issue by chrisohaver** [miekg/coredns#5614]
OK, let's kick off the (first) steering committee election process.

* We'll initially aim to fill 5 seats.  If there isn't enough interest, we should discuss if we should reduce the committee size to 3 seats.
* Folks who want to be in the steering committee please declare that here in this issue.
* After some time (two weeks?), we will start the voting.

How does this sound?

@bradbeam
@chrisohaver
@darshanime
@dilyevsky
@ekleiner
@greenpau
@ihac
@inigohu
@Isolus
@jameshartig
@johnbelamaric
@miekg
@mqasimsarfraz
@nchrisdk
@nitisht
@pmoroney
@rajansandeep
@rdrozhdzh
@rtreffer
@snebel29
@stp-ip
@SuperQ
@Tantalor93
@varyoo
@ykhr53
@yongtang
@zouyee

**Comment by yongtang** [comment]
> We'll initially aim to fill 5 seats. If there isn't enough interest, we should discuss if we should reduce the committee size to 3 seats.

One of the concerns is that we want to make sure no single company can dominate the decision making process. Note CNCF   _explicitly_ does not want to see one or two company dominate the governance.

If a structure is going to be changed then there are multiple options available I believe.

**Comment by chrisohaver** [comment]
> If a structure is going to be changed then there are multiple options available I believe.

Thanks.  We can discuss those if there isn't enough interest to fill 5 seats.

**Comment by chrisohaver** [comment]
I'd like to run for a committee member seat. I am employed by Infoblox.

**Comment by johnbelamaric** [comment]
I'd like to run for a committee member seat. I am employed by Google.

**Comment by Tantalor93** [comment]
Even though I am a relatively new maintainer, I'd like to run for a committee member seat. I am employed by Jamf.

**Comment by stp-ip** [comment]
Context: My time and therefore activity is quite low currently, but I am trying to stay up to date on issues as always and am happy to help out with the steering committee.

Therefore I am open to running for a committee member seat. I am "employed" by Okkur Labs and Rekkur Solutions.

**Comment by yongtang** [comment]
If no other maintainers expresses interest I am open to running for a committee member seat as independent.

Open source activities and opinions are my own, and the company I currently work for (ivanti) is not involved. The company has no seat or involvement in CNCF, and has no business interest or activity in DNS area. Note while running as an independent (not representing a company), happy to step aside if needed so the restriction of no company taking more than one seat still applies.

**Comment by SuperQ** [comment]
I would like to run for the steering committee. I am a member of the Prometheus developer team and maintain various parts of the Prometheus ecosystem. I am employed by Reddit.

**Comment by chrisohaver** [comment]
OK, it's been two weeks.  There are 5 folks clearly interested being on the committee, and (per my understanding) 1 interested if only 4 other maintainers expressed an interest.

If this is indeed the case, since the number of interested maintainers does not exceed the number of available seats, there is no seat contention and IMO we do not need to do a vote.

Does this sound fair?
