### ISSUE TITLE
If third level domain exists, name server will not return second level ip

### ISSUE THREAD

**Issue by papandadj** [miekg/coredns#5619]
I use etcd as storage and have two record.
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/25424898/190325779-50d3cff6-01be-4bcd-9ee2-ca2574467e33.png">
If `/coredns/com/ttdd1/t1` not exist, `nslookup ttdd1.com` will return 100.100.100.101.
if `/coredns/com/ttdd1/t1` exist, `nslookup ttdd1.com` will return 100.100.100.102.
if other third level domain exist( `/coredns/com/ttdd1/t2`, `/coredns/com/ttdd1/t3`) , it will return third level domain ip load balance.

Is it designed in this way?

Why name server not return original data (100.100.100.101) when third level domain exist?

**Comment by chrisohaver** [comment]
> Is it designed in this way?
> Why name server not return original data (100.100.100.101) when third level domain exist?

I'm not sure, SkyDNS is weird.  It seems though, that if your intent is to have it return all the IPs, you should put all the IPs in the same level.  This is how examples are done in https://github.com/skynetservices/skydns#service-discovery-via-the-dns

**Comment by papandadj** [comment]
Hi @chrisohaver , thank you for your answer.
I'll try again.
