### ISSUE TITLE
Serving with DOH insecure when behind a reverse proxy that provides the SSL endpoint

### ISSUE THREAD

**Issue by nodje** [miekg/coredns#5623]
Is it possible to configure a server block with the `https://` protocol and configure it in an insecure mode?
I couldn't find any reference to this in the doc.
Thx

**Comment by Tantalor93** [comment]
Hello, yes, see https://github.com/coredns/coredns#examples CoreDNS can also accept DoH requests over plain HTTP

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/5522817/190717510-65f8085e-4828-4b63-8a3c-be17864a0d65.png">

**Comment by nodje** [comment]
Cheers, I didn't read the examples 'till the end, my bad :)

**Comment by nodje** [comment]
Actually I'm not sure I understand the doc correctly:

> you can also start DNS server serving DoH without TLS termination (plain HTTP), but beware that in such scenario there has to be some kind of TLS termination proxy before CoreDNS instance, which forwards DNS requests otherwise clients will not be able to communicate via DoH with the server
```
https://example.org {
    whoami
}
```
is this supposed to listen on port 80 or 443 in plain?

I guess it should answer on HTTP 80, but SEEING https in the server conf makes me doubt
