### ISSUE TITLE
Bufsize gets overwritten to 2048 on cache miss when logic enables DNSSEC

### ISSUE THREAD

**Issue by gcs278** [miekg/coredns#5640]
**What happened**:
As I understand, forwarded/upstream DNS requests triggered by a cache miss, will have DNSSEC enabled (DO bit) regardless if the client set it. During this logic, when the DO bit is not set and an EDNS0 record exists, an existing EDNS0 record with the bufsize as specified in the corefile, is overwritten to 2048.

This change was introduced in v1.7.1 by commit https://github.com/coredns/coredns/commit/acf9a0fa19928e605ac8ac3314890c9fef73e16b. Prior to this change, the DNS cache refresh logic used the `bufsize` in the corefile. This becomes an issue when users' networks have UDP size limitations of less than 2048.

**What you expected to happen**:
The DNS cache refresh request should use `bufsize` as specified in the corefile as it did prior to v1.7.1.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a CoreDNS instance >= v1.7.1 with the corefile below (`./coredns --conf corefile`)
2. `dig @127.0.0.1 google.com`
4. Log output of coredns process will show payload/bufsize of 2048 (see logs below)

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: >= v1.7.1
- Corefile:
```
.:53 {
  bufsize 512
  forward . 127.0.0.1:8053
  cache
}

.:8053 {
  log
  forward . 8.8.8.8
}
```
- logs, if applicable:
   - Client Sets Bufsize (UDPSize) of 4096, but DNS refresh sets to 2048 despite `bufsize 512` in corefile:
 ```
[INFO] 127.0.0.1:37106 - 63758 "A IN google.com. udp 51 true 2048" NOERROR qr,rd,ra 65 0.062822559s
 ```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
```
- Others:
  - I'm pretty new to CoreDNS, so I don't really understand the complexities, but a solution I had success with was removing `o.SetUDPSize(defaultUDPBufSize)` from the `setDO` function if a EDNS0 record existed, so it wouldn't be overridden:
https://github.com/coredns/coredns/blob/85370b1662491cfee647066a8b89e00fb1bef241/plugin/cache/handler.go#L160-L165

Let me know if you have any questions and/or agree with my suggested way forward.

**Comment by Tantalor93** [comment]
Hello, thanks for reporting the issue! I think it is more easily reproducible by running CoreDNS with configuration
```
.:53 {
  bufsize 512
  forward . 127.0.0.1:8053
  cache
}

.:8053 {
  log
  forward . 8.8.8.8
}
```
and then after doing `dig @127.0.0.1 google.com`
CoreDNS will log size 2048 even though I would expect size to be 512
```
[INFO] 127.0.0.1:52644 - 12299 "A IN google.com. udp 51 true 2048" NOERROR qr,rd,ra 65 0.009471971s
```

Imho the `cache` plugin should consider the UDP size set by `bufsize` plugin or client while doing a refresh and the fix you propose does not sound that bad 🤔

**Comment by gcs278** [comment]
@Tantalor93 Great point, I updated the reproducer to reflect your suggestion. Much easier. Thanks!

I'm curious if overwriting the UDP Payload Size of the cache refresh request to a hardcoded value (not `bufsize`) was the intention of https://github.com/coredns/coredns/commit/acf9a0fa19928e605ac8ac3314890c9fef73e16b or if this is unintended. Is @miekg still around? Do you have thoughts on this issue?

**Comment by chrisohaver** [comment]
A quick thought here: The DNSSEC cache solution introduced in https://github.com/coredns/coredns/commit/acf9a0fa19928e605ac8ac3314890c9fef73e16b is (IMO) a novel and clever low-code approach to adding cache support for DNSSEC, but it does this by changing non-dnssec cache processing flow, and has resulted in a few (3-4?) latent bugs that have taken time to surface.

I don't know if would be a good idea at this point to re-implement DNSSEC cache support in a less novel way (i.e. in such a way that non-DNSSEC queries are left alone, and keeping dnssec cache responses separate from non-dnssec).  This would be more code heavy, but probably safer in terms of collateral bugs affecting non-DNSSEC queries.  Aside from the few bugs that have arisen, the current solution results in counterintuitive behavior to an observer:  The fact that all upstream queries get tagged as requesting DNSSEC can be confusing to an observer when clients are not requesting DNSSEC. And it has been raised as a concern by users who are acutely bandwidth conscious, as it will cause unnecessary overhead if an upstream server serves DNSSEC, but clients never actually request it.

**Comment by johnbelamaric** [comment]
> I don't know if would be a good idea at this point to re-implement DNSSEC cache support in a less novel way (i.e. in such a 

I think you make a very good point here. Of course, I won't be doing the work so it's easy for me to say, "let's re-implement it" :)

**Comment by chrisohaver** [comment]
> ... re-implement DNSSEC cache support ...

I'm probably missing something, but it seems like this may be as simple as reverting back to the previous logic before https://github.com/coredns/coredns/commit/acf9a0fa19928e605ac8ac3314890c9fef73e16b, and instead of using the _result_ DO bit in the cache key when writing the cache, use the _query_ DO bit (which is available in the ResponseWriter).

**Comment by gcs278** [comment]
> I'm probably missing something, but it seems like this may be as simple as reverting back to the previous logic before https://github.com/coredns/coredns/commit/acf9a0fa19928e605ac8ac3314890c9fef73e16b, and instead of using the result DO bit in the cache key when writing the cache, use the query DO bit (which is available in the ResponseWriter).

So I might be out of my depth, but I took a stab at doing exactly this in WIP PR: https://github.com/coredns/coredns/pull/5671. I have some questions about implementation, and I'll post them in the PR. Still very much WIP to see if I'm going the right direction.
