### ISSUE TITLE
How to forward to a local hostname, without binding to an IP

### ISSUE THREAD

**Issue by nodje** [miekg/coredns#5644]
In a Docker context, I need a server config that forwards to another container.

I'd like to forward using its hostname. 
Is it at all possible supported?
```
. {
    forward . nextdnshop
}
```

plugin/forward: not an IP address or file: "nextdnshop"

**Comment by chrisohaver** [comment]
It’s not supported.

**Comment by nodje** [comment]
thanks!
Any interest in having this become a feature request?

**Comment by chrisohaver** [comment]
It’s a little more involved than it may initially seem to implement. It kinda opens a can of worms, but it is feasible. It’s been requested and rejected before, but there has been some maintainer turnover since, so it could get traction if requested again.

**Comment by nodje** [comment]
I certainly understand the oddity of it.
But as matter of fact, in a container context you can't get a stable setup using IPs.

I'll open an Enhancement Request, and let's see how it goes this time :)
