### ISSUE TITLE
Basic DoH config testing: `dns: buffer size too small` or `dns: overflow unpacking uint16`

### ISSUE THREAD

**Issue by nodje** [miekg/coredns#5645]
this is running in Docker:

```
https://.:443 {
    errors
    log
    any
    health :8080 #answers OK on /health request

    forward . 172.24.0.3 #nextdockerdnshop

    cache 60
    prometheus 0.0.0.0:9153 # uses /metrics EP
}

example.org {
    whoami
}
```

`curl http://172.20.0.15:443/dns-query?dns=ZG5zLmVhc3Rjb2RlLm9yZw`
produces a `dns: buffer size too small`
`curl http://172.20.0.15:443/dns-query?dns=Z29vZ2xlLmNvbQ`
a `dns: overflow unpacking uint16`

Is there anything I'm using wrong or ?

**Comment by chrisohaver** [comment]
How are you generating the dns values in the requests?

**Comment by nodje** [comment]
I originally went with `printf "google.com" | basenc --base64url` but then there seem to be unexpected padding with `=` chars at the end that caused `illegal base64 data at input` so I used online https://www.base64url.com/ instead.
But it mostly produces the same result.

And I had some apparent initial success, e.g. with: `curl http://172.20.0.15:443/dns-query?dns=ZWFzdGNvZGUub3Jn`
and this generated expected logs from CoreDNS. So I thought the problem doesn't come from the Base64 encoding.

Now I can't seem to get any log anymore, even though that initial working query still works, at least the call part.
And besides this working query I can't find any domain name that doesn't produce and error. `dns: bad rdata` is another one I get.

There must be some issues in the way I test the server.

Oddly having log and error plugin activated doesn't help in getting any information, and /var/log is empty.
I'm a bit at a loss as for where to look for helpful bits of information.

**Comment by chrisohaver** [comment]
DoH requires the payload be the wire format dns request message, base64 encoded.
The bare request name is not a valid dns message, so there will be errors when trying to parse the payload.

**Comment by chrisohaver** [comment]
If you're looking for a valid value to test with, the DoH RFC has an example for an `A` record lookup for `www.example.com`:

`AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB`


link: https://www.rfc-editor.org/rfc/rfc8484.html#section-4.1.1

**Comment by nodje** [comment]
alright, thanks for this.
At least I can see examples working so definitely not a CoreDNS issue.

Though, I keep scratching my head on this: RFC not useful in understanding what exactly beyond the target domain is encoded. 
And Base64 decoding of working examples show mixed results, at least not re-encodable strings when results are in clear ASCII character...

**Comment by chrisohaver** [comment]
> RFC not useful in understanding what exactly beyond the target domain is encoded.

IETF RFCs tend to be very technical which makes them a bit on the esoteric/unaccessible side (definitely on the opposite end of the spectrum of technical documents from a tutorial). 

The DoH RFCs defines the content of the payload here: https://www.rfc-editor.org/rfc/rfc8484.html#section-6
And references another RFC that defines the wire format: https://www.rfc-editor.org/rfc/rfc1035#section-4

> And Base64 decoding of working examples show mixed results, at least not re-encodable strings when results are in clear ASCII character...

The message value encoded is the dns message in wire format, which is the series of bits sent over the wire of a normal tcp/udp dns request (the "application" later portion of the network packet). The dns message includes other request data such as request flags, and the requested record type. Its compact data, and won't represent cleanly as ascii.

**Comment by nodje** [comment]
Thanks for this.

It's a bit hard to understand why it's so difficult to Base64 encode this format, where it's as easy as 
`curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=example.com&type=A'`
when the resolver understands JSON
I would expect to Base64url encode something like `A>example.com` and get DNS Wireformat payload.

And it's still surprisingly difficult to find a simple DoH client.
Though I realize dig has some options: `dig @172.20.0.15 -p443 +http-plain-get example.com` should work in theory.
It doesn't in practice with a `;; communications error to 172.20.0.15#443: connection reset`

**Comment by chrisohaver** [comment]
CoreDNS just follows the DoH RFC proposed standard.

Cloudflare's json option is either their invention, or Google's invention (they do the same thing), or maybe someone else, but it is not a proposed standard in IETF, AFAIK.

From the design perspective of implementing and integrating DoH transport support, it's less overhead (both operationally and code-wise) to leave the message in native "struct" wireformat than to deconstruct it into json on the client side, and then reconstruct it back to into wireformat on the server end so it can be read by the dns server.

**Comment by chrisohaver** [comment]
Yes, Cloudflare [says they copied what Google did, and points out that it is not an IETF standard](https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/dns-json/): "For lack of an agreed upon JSON schema for DNS over HTTPS in the Internet Engineering Task Force (IETF), Cloudflare has chosen to follow the same schema as Google’s DNS over HTTPS resolver."

**Comment by nodje** [comment]
Alright, everything working with SSL layer offloaded to reverse proxy.
and `dig @server.name google.com +https` just does the job as a client (dig probably needs to be recent enough)

My specific instance doesn't seem to play well with Android Private DNS feature though, which leads me to the chicken and egg question that I dare ask you here since you have been so helpful already: how the hell is the DoH server name resolved?

**Comment by nodje** [comment]
It actually does work now on Android Private DNS.
I feel it's all about having the device's DNS cache know about your DoH server name's IP beforehand.
