### ISSUE TITLE
CoreDNS Server configuration to listen to dns:// on TCP?

### ISSUE THREAD

**Issue by nodje** [miekg/coredns#5647]
I was thinking this should be possible, but couldn't find any config documentation on this

```
dns://.:53 {
    whoami
}
```
How do you have this server listen on TCP instead of UDP?

**Comment by chrisohaver** [comment]
CoreDNS listens on both UDP and TCP by default. 
For plain DNS, listening on TCP only would violate DNS server requirements (defined in RFCs).

**Comment by nodje** [comment]
Thanks for this, again!
