### ISSUE TITLE
Allow login to shell for troubleshooting

### ISSUE THREAD

**Issue by zm1990s** [miekg/coredns#5656]
**What would you like to be added**:
CoreDNS should be more open for troubleshooting, for example allow user to check A record, or login to shell to do some low level troubleshootting. 

**Why is this needed**:
I don't know if it's a kubernetes issue or CoreDNS issue, in a Kubernetes cluster, CoreDNS is really hard to troubleshoot. Users are not allowed to login to shell, and there's no way to check dns record. The only way I found useful is logging but that's not always helpful.

In real world, an issue can be caused by many problems, any underlay network or iptables/IPVS issue will also cause DNS resolution fail in Kubernetes cluster, but it's difficult to troubleshoot CoreDNS, one always need to do a packet capture to see the packet flow and locate the problem, it's just not user friendly. 

And since CoreDNS is not working, any other applicaitons like advanced troubleshooting tools can't be deployed. It's a loop dependency.

I know CoreDNS is an important part and should not be configurable and this will make it more secure, but, is this the right way?

**Comment by chrisohaver** [comment]
> in a Kubernetes cluster, CoreDNS is really hard to troubleshoot

Have you tried going through the troubleshooting steps in https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/ ?

**Comment by zm1990s** [comment]
> 

Yes, this isn't enough in some cases.

**Comment by chrisohaver** [comment]
> Users are not allowed to login to shell,

This is a pretty standard security practice. 

> and there's no way to check dns record.

You can query with a tool like `dig` to check dns records. 

> I know CoreDNS is an important part and should not be configurable 

CoreDNS is configurable. In K8s, you can configure CoreDNS by editing its ConfigMap.

> one always need to do a packet capture

If a coredns pod is not receiving dns traffic, logging into its shell and doing a packet capture isn’t going to help. 

It is possible do packet captures of traffic to/from a Pod, from the _node_ the pod is running on.  IOW, you don't have to have a shell on the Pod to capture its network traffic.

**Comment by johnbelamaric** [comment]
Images without a shell are a best practice for security. Newer versions of
K8s allow creation of “ephemeral containers” aka debug containers that
attach to a Pod and can contain whatever tools you need. You may want to
look into that.
