### ISSUE TITLE
coredns 1.8.0/1.8.3 not able to resolve records which has CNAME/ALIAS on alpine 3.9.6, 3.12, 3.16.1 - curl/wget

### ISSUE THREAD

**Issue by kranthirachakonda** [miekg/coredns#5673]
I m having a kind of weird issue with resolution with curl/wget of an endpoint on our pods/rancher k8s-cluster (1.20), which is using coredns-1.8.0 (& 1.8.3) and alpine 3.9.6, 3.12, 3.16.1 (i tried all versions of 3.9+). As most of the other dns issues filed earlier, same resolution works on local mac and VM/Nodes using same NS servers. Other public records like github.com, 

I tried couple of things and read about of known issues with alpine dns resolution issues, but not sure if I am running into a known issue or something wrong with my setup. Need help resolving it.

Record which is having issue (changed hostname, its not correct record):

dev.apim.sample-dns.com is an alias for sample-dns-apim-dev.azure-api.net.
sample-dns-apim-dev.azure-api.net is an alias for abc123459cgudpyyjn4c34vuw.trafficmanager.net.
abc123459cgudpyyjn4c34vuw.trafficmanager.net is an alias for sample-dns-apim-dev-eastus-01.regional.azure-api.net.
sample-dns-apim-dev-eastus-01.regional.azure-api.net is an alias for abcdns1234564ef174badlkbkiw0s6xvttwcjjn90n.eastus.cloudapp.azure.com.
abcdns1234564ef174badlkbkiw0s6xvttwcjjn90n.eastus.cloudapp.azure.com has address 1xx.2x.3x.4

On the pod:
```
/ # curl -vk dev.apim.sample-dns.com
* Could not resolve host: dev.apim.sample-dns.com
* Closing connection 0
curl: (6) Could not resolve host: dev.apim.sample-dns.com
/ # nslookup dev.apim.sample-dns.com
Server:         10.3.0.10
Address:        10.3.0.10#53


dev.apim.sample-dns.com is an alias for sample-dns-apim-dev.azure-api.net.
sample-dns-apim-dev.azure-api.net is an alias for abc123459cgudpyyjn4c34vuw.trafficmanager.net.
abc123459cgudpyyjn4c34vuw.trafficmanager.net is an alias for sample-dns-apim-dev-eastus-01.regional.azure-api.net.
sample-dns-apim-dev-eastus-01.regional.azure-api.net is an alias for abcdns1234564ef174badlkbkiw0s6xvttwcjjn90n.eastus.cloudapp.azure.com.
Name:   abcdns1234564ef174badlkbkiw0s6xvttwcjjn90n.eastus.cloudapp.azure.com
Address: 1xx.2x.3x.4
```
```
/ # cat /etc/resolv.conf 
nameserver 10.3.0.10
search default.svc.cluster.local svc.cluster.local cluster.local sample-dns.com 123.sampledns.com
options ndots:5
/ # 


Tried these which didnt help, i.e. curl/wget doesnt resolve above record:

```
- Reduced ndots to 3
- Initially nslookup was failing to resolve and giving some random public ips. Read somewhere installing bind-tools helps.
```
/ # nslookup dev.apim.sample-dns.com
nslookup: can't resolve '(null)': Name does not resolve


Name:      dev.apim.sample-dns.com
Address 1: 93.239.133.128 p5def8580.dip0.t-ipconnect.de

Installed bind-tools as apk add bind-tools for test. And that helped nslookup to resolve with correct/expected ip-address and dns name
```

-  Took a tcpdump and see that traffic from pod to coredns/kube-dns.kube-system.svc.cluster.local and there to our infoblox server. In response, I do see correct aliases, cname, A record in tcpdump. However response on my resolution shows random public ips.

- curl and wget resolve to different ips. Not sure why
- nslookup & dig resolve to correct/expected ip.

```
corefile:
.:53 {
    log
    health {
      lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . "/etc/resolv.conf"
    bufsize 1232 << added this for other records which were >512B
    cache 30
    loop
    reload
    loadbalance
} # STUBDOMAINS - Rancher specific change
```

coredns logs

`[INFO] 10.2.9.142:55395 - 33583 "AAAA IN dev.apim.sample-dns.com.lowes.com. udp 53 false 1232" NXDOMAIN qr,aa,rd,ra 127 0.000153288s
[INFO] 10.2.9.142:55395 - 33258 "A IN dev.apim.sample-dns.com.lowes.com. udp 53 false 1232" NXDOMAIN qr,aa,rd,ra 127 0.000126996s
[INFO] 10.2.9.142:39655 - 51233 "AAAA IN dev.apim.sample-dns.com. udp 43 false 1232" NOERROR qr,aa,rd,ra 526 0.000095743s
[INFO] 10.2.9.142:39655 - 51038 "A IN dev.apim.sample-dns.com. udp 43 false 1232" NOERROR qr,aa,rd,ra 854 0.00173528s`

Please let me know if there are any questions or need additional info.

**Comment by chrisohaver** [comment]
> Took a tcpdump and see that traffic from pod to coredns/kube-dns.kube-system.svc.cluster.local and there to our infoblox server. In response, I do see correct aliases, cname, A record in tcpdump. However response on my resolution shows random public ips.

It sounds like you are sniffing traffic between the client pod, and coredns. And that you have verified that CoreDNS is correctly resolving the records and _sending the correct answer back_ to the client.

If so, this would appear to be some kind of problem with the client, not CoreDNS.
