### ISSUE TITLE
plugin/reload: leaking (*time.Ticker) in goroutine inside hook

### ISSUE THREAD

**Issue by odeke-em** [miekg/coredns#5680]
Reported by [Static Major from Orijtech Inc](https://github.com/marketplace/actions/staticmajor-analyzer), we can see this 
```shell
/coredns/plugin/reload/reload.go:118:6: leaking resource created on line 85
/coredns/plugin/reload/reload.go:121:5: leaking resource created on line 85
```

which originates from https://github.com/coredns/coredns/blob/2f24b512d3999e9687ffbfaf8f8226c64185dca1/plugin/reload/reload.go#L85 for which there is a missing `defer tick.Stop()`

Kindly FYI-ing @willpoint @jhusdero @elias-orijtech @kirbyquerby

**Comment by Tantalor93** [comment]
seems fair, I have opened a PR, thanks!

**Comment by yongtang** [comment]
As #5686 has been merged, believe the issue can be closed. Thanks @odeke-em !

**Comment by odeke-em** [comment]
Thanks @Tantalor93 for the fix and @yongtang for the merge and close! Minor nit @Tantalor93: in your PRs if you can add the single line `Fixes #NNNN` it'll automatically close the issue and associate the PR with it :-)
