### ISSUE TITLE
dot is broken in some cases

### ISSUE THREAD

**Issue by sanyo0714** [miekg/coredns#5703]
**What happened**:
dot is broken in the case of 【kdig version 3.2.1+】 and 【coredns 1.8.5+ build at golang 1.18.1+】

doh&dot use same [TLSConfig]  with corefile 
```
https://.:8443 tls://.:8080 {
	tls plugin/tls/test_cert.pem  plugin/tls/test_key.pem  plugin/tls/test_ca.pem
}
```
doh set tlsConfig.NextProtos = []string{"h2", "http/1.1"}
dot also has tlsConfig.NextProtos = []string{"h2", "http/1.1"}
```
the code @core/dnsserver/register.go line 150
c.TLSConfig = c.firstConfigInBlock.TLSConfig
```

**What you expected to happen**:
with 【coredns 1.8.5+ build at golang 1.18.1+】 and 【kdig version 3.2.1+】 the dot is work

**How to reproduce it (as minimally and precisely as possible)**:

【coredns 1.8.5+ build at golang 1.18.1+】 and 【kdig version 3.2.1+】 , with corefile 

```
https://.:8443 tls://.:8080 {
	tls plugin/tls/test_cert.pem  plugin/tls/test_key.pem  plugin/tls/test_ca.pem
}
```

**Anything else we need to know?**:

fix the bug with
```
@core/dnsserver/register.go line 150
c.TLSConfig = c.firstConfigInBlock.TLSConfig.Clone()
```
**Environment**:

- the version of CoreDNS: 1.8.5+
- Corefile:
```
https://.:8443 tls://.:8080 {
	tls plugin/tls/test_cert.pem  plugin/tls/test_key.pem  plugin/tls/test_ca.pem
}
```
- logs, if applicable:

![image](https://user-images.githubusercontent.com/14814461/196366199-da1a41ff-c3c5-45a5-b611-2edd933e287d.png)

- Others:
tools: 
kdig (Knot DNS), version 3.2.1
![image](https://user-images.githubusercontent.com/14814461/196914286-763a5a19-9ff0-476e-b81a-2fe7a0a6f62f.png)

golang 1.18.1+
@ src/crypto/tls/handshake_server.go line 220 & line 281
```
func (hs *serverHandshakeState) processClientHello() error {
 ...
      selectedProto, err := negotiateALPN(c.config.NextProtos, hs.clientHello.alpnProtocols)
      if err != nil {
          c.sendAlert(alertNoApplicationProtocol)
          return err
      }
 ...
}


// negotiateALPN picks a shared ALPN protocol that both sides support in server
// preference order. If ALPN is not configured or the peer doesn't support it,
// it returns "" and no error.
func negotiateALPN(serverProtos, clientProtos []string) (string, error) {
	if len(serverProtos) == 0 || len(clientProtos) == 0 {
		return "", nil
	}
	var http11fallback bool
	for _, s := range serverProtos {
		for _, c := range clientProtos {
			if s == c {
				return s, nil
			}
			if s == "h2" && c == "http/1.1" {
				http11fallback = true
			}
		}
	}
	// As a special case, let http/1.1 clients connect to h2 servers as if they
	// didn't support ALPN. We used not to enforce protocol overlap, so over
	// time a number of HTTP servers were configured with only "h2", but
	// expected to accept connections from "http/1.1" clients. See Issue 46310.
	if http11fallback {
		return "", nil
	}
	return "", fmt.Errorf("tls: client requested unsupported application protocols (%s)", clientProtos)
}
```

**Comment by sanyo0714** [comment]
@miekg @chrisohaver

**Comment by chrisohaver** [comment]
Can you open a PR with your fix?
