### ISSUE TITLE
CoreDNS-1.10.0  cannot resolve A record

### ISSUE THREAD

**Issue by ormosias** [miekg/coredns#5704]
**What happened**:
CoreDNS-1.10.0  cannot resolve A record
**What you expected to happen**:
can resolve A record
**How to reproduce it (as minimally and precisely as possible)**:

## install & config
```
[root@localhost ~]# cat /usr/lib/systemd/system/coredns.service
[Unit]
Description=CoreDNS DNS server
Documentation=https://coredns.io
After=network.target

[Service]
PermissionsStartOnly=true
LimitNOFILE=1048576
LimitNPROC=512
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
User=coredns
WorkingDirectory=~
ExecStart=/usr/bin/coredns -conf=/etc/coredns/Corefile
ExecReload=/bin/kill -SIGUSR1 $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target

```

```
[root@localhost ~]# cat /etc/coredns/Corefile
.:53 {
  bind 192.168.6.85
  hosts {
1.1.1.4 a.b.com
    fallthrough
  }

  forward . 114.114.114.114 8.8.8.8
  cache 120
  reload 6s
  log
  errors
}
```

`systemctl start coredns`

![image](https://user-images.githubusercontent.com/90101814/197115717-a821f4da-2e2e-46d7-b786-83fd758d6c80.png)

## use & logs

![image](https://user-images.githubusercontent.com/90101814/197115838-972e12b9-771c-4851-ae7c-2ddf638fc036.png)

It is found that only AAAA records can be resolve, not A records.

![image](https://user-images.githubusercontent.com/90101814/197115966-806417dc-b2c3-408f-a12b-0db71908650f.png)

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 
```[root@localhost ~]# coredns -version
CoreDNS-1.10.0
linux/amd64, go1.19.1, 596a9f9
```
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): 
```
[root@localhost ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@localhost ~]#
```
- Others:

**Comment by chrisohaver** [comment]
If you are getting NXDOMAIN responses, but they aren’t being logged by coredns, that means the answers are probably coming from something else other than coredns.

**Comment by sanyo0714** [comment]
@ormosias nslookup do DNS request both A & AAAA,   the answers are probably coming from AAAA

**Comment by ormosias** [comment]
@chrisohaver @sanyo0714     
Thank you for your reply.


The strange thing is, my network is resolvable, my colleague's network is not resolvable, but my colleague's dns resolution request has reached CoreDNS .  We are under different networks.

my network：

![image](https://user-images.githubusercontent.com/90101814/197446044-186b22a6-2165-48ab-b525-278f0d7927d4.png)

**Comment by chrisohaver** [comment]
Please test using the `dig` tool and share output.  `nslookup` is difficult to troubleshoot with because it obfuscates what query it actually sends and what the actual response received is.
