### ISSUE TITLE
LLRB print_test incorrect

### ISSUE THREAD

**Issue by houfengjiejie** [miekg/coredns#5705]
https://github.com/coredns/coredns/blob/6cb5e107077e2081ba13f1755ee9da34e7f6fc96/plugin/file/tree/print_test.go#L63
server3.example.com. should be server4.example.com. left sub-tree
but code show server3.example.com. is server1.example.com. left sub-tree

**Comment by chrisohaver** [comment]
> server3.example.com. should be server4.example.com. left sub-tree
but code show server3.example.com. is server1.example.com. left sub-tree

Do you mean to say _comment_ in the code is wrong?
