### ISSUE TITLE
CoreDNS Fails to Proxy

### ISSUE THREAD

**Issue by Nero22k** [miekg/coredns#5720]
Here is my Corefile:

```
.:53 {
    forward . 8.8.8.8:53
    log
}

test.example.org {
   forward . 10.23.111.32:53
   log
}
```

The issue is when I query my root domain I get DNS timeouts. I thought that this should be using 8.8.8.8 to resolve but it doesn't. If I query test.example.org than that gets send to the internal DNS server but other queries are not being resolved to 8.8.8.8. If anyone has a solution to this I'm open.

**Comment by chrisohaver** [comment]
Can coredns (the host coredns is running on) reach 8.8.8.8 on port 53?
