### ISSUE TITLE
Coredns gets old results from the cache when time changes

### ISSUE THREAD

**Issue by chaohan1** [miekg/coredns#5731]
**What happened**:
In my k8s cluster，we use coredns to resolve the service domain name.  If I change the time to a past time，such as modify time from  20:00:00 to 15:00:00，and update the service to change the service's ClusterIP，such as modify ClusterIP from 10.254.139.206 to 10.254.244.106. Then use coredns to resolve the service domain name, and always get the old ClusterIP(10.254.139.206) instead of the latest ClusterIP(10.254.244.106).

**What you expected to happen**:
Although we have modified the time, we still want to get the latest ClusterIP.

**How to reproduce it (as minimally and precisely as possible)**:
1. Change the time to a past time, such as modify time from 20:00:00 to 15:00:00;
2. Update the service to change the service's ClusterIP, such as delete the service and then create the service again;
3. Use coredns to resolve the service domain name；
4. And then，you always get the old ClusterIP;

**Anything else we need to know?**:
According to my analysis，coredns will store the dns result in the local cache，the TTL of cache is 5s default. Coredns always get result from the cache as long as the cache is not expired. But when we change the time to a past time, then the cache will not expire until the time we changed, so we always get the old result from the cache.

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
Thanks. This is the same issue as https://github.com/coredns/coredns/issues/5478.
