### ISSUE TITLE
plugin/kubernetes returns wrong response when ExternalName Service is present

### ISSUE THREAD

**Issue by kariya-mitsuru** [miekg/coredns#5733]
**What happened**:

If we do the following steps, the pod `nginx1` will respond.

```sh
kubectl create namespace nginx
kubectl run --image=nginx --port=80 --expose -n nginx nginx1
kubectl run --image=nginx --port=80 --expose -n nginx nginx2
kubectl create service externalname --external-name=nginx1.nginx.svc.cluster.local nginx
kubectl get svc -A
kubectl run -it --rm --restart=Never --image=curlimages/curl curl -- -vI http://nginx2.nginx/
```

A sample output of `kubectl get svc -A`
```
NAMESPACE     NAME         TYPE           CLUSTER-IP      EXTERNAL-IP                      PORT(S)                  AGE
default       kubernetes   ClusterIP      10.96.0.1       <none>                           443/TCP                  53m
default       nginx        ExternalName   <none>          nginx1.nginx.svc.cluster.local   <none>                   45m
kube-system   kube-dns     ClusterIP      10.96.0.10      <none>                           53/UDP,53/TCP,9153/TCP   53m
nginx         nginx1       ClusterIP      10.101.12.129   <none>                           80/TCP                   45m
nginx         nginx2       ClusterIP      10.98.127.55    <none>                           80/TCP                   45m
```

A sample output of `kubectl run -it ...`
```
*   Trying 10.101.12.129:80...
* Connected to nginx2.nginx (10.101.12.129) port 80 (#0)
> HEAD / HTTP/1.1
> Host: nginx2.nginx
> User-Agent: curl/7.86.0-DEV
> Accept: */*
.
.
.
```

The IP address to connect to is the `CLUSTER-IP` of the `nginx1`.

**What you expected to happen**:

The pod `nginx2` responds.

Kubernetes' default search list is `default.svc.cluster.local svc.cluster.local cluster.local`.
Therefore, if we try to resolve `nginx2.nginx`, first search for `nginx2.nginx.default.svc.cluster.local` and not found, then search for `nginx2.nginx.svc.cluster.local` and `CLUSTER-IP` of `nginx2` should be found.

**How to reproduce it (as minimally and precisely as possible)**:

The above steps.

**Anything else we need to know?**:

If the ExternalName Service `nginx` is not present, the correct response will be returned.

```sh
kubectl delete svc/nginx
kubectl run -it --rm --restart=Never --image=curlimages/curl curl -- -vI http://nginx2.nginx/
```

A sample output of `kubectl run -it ...`
```
*   Trying 10.98.127.55:80...
* Connected to nginx2.nginx (10.98.127.55) port 80 (#0)
> HEAD / HTTP/1.1
> Host: nginx2.nginx
> User-Agent: curl/7.86.0-DEV
> Accept: */*
.
.
.
```

The IP address to connect to is correctly `CLUSTER-IP` of `nginx2`.

If the ExternalName Service `nginx` is present, a search for `nginx2.nginx.default.svc.cluster.local` will ignore the first `nginx2` and CNAME record for `nginx.default.svc.cluster.local` are returned.

```sh
kubectl run -it --rm --restart=Never --image=alpine alpine -- \
  sh -c 'apk add --no-cache bind-tools; dig nginx2.nginx.default.svc.cluster.local'
```

A sample output of the answer section
```
;; ANSWER SECTION:
nginx2.nginx.default.svc.cluster.local. 30 IN CNAME nginx1.nginx.svc.cluster.local.
nginx1.nginx.svc.cluster.local. 30 IN   A       10.101.12.129
```

**Environment**:

- the version of CoreDNS: 1.9.3
- Corefile: 
    ```
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: coredns
      namespace: kube-system
    data:
      Corefile: |
        .:53 {
            errors
            health {
               lameduck 5s
            }
            ready
            kubernetes cluster.local in-addr.arpa ip6.arpa {
               pods insecure
               fallthrough in-addr.arpa ip6.arpa
               ttl 30
            }
            prometheus :9153
            forward . /etc/resolv.conf {
               max_concurrent 1000
            }
            cache 30
            loop
            reload
            loadbalance
        }
    ```

- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):

    kubernetes version : 1.25.2
- Others:

**Comment by chrisohaver** [comment]
Thanks - this bug has probably been present since the beginning.  This was caused by the code ignoring the endpoint subdomain in the request if the matched service is an externalService.  The fix in https://github.com/coredns/coredns/pull/5734 explicitly checks to make sure the endpoint is empty before matching it.
