### ISSUE TITLE
corebot is unable to push to master branch

### ISSUE THREAD

**Issue by Tantalor93** [miekg/coredns#5742]
**What happened**:
[Go Fmt](https://github.com/coredns/coredns/actions/runs/3409532192/jobs/5671421346) and [Go tidy](https://github.com/coredns/coredns/actions/workflows/go.tidy.yml) GitHub actions are failing due to corebot not being able to push changes to the protected master branch

**What you expected to happen**:
Go tidy and Go Fmt actions to successfully run

**How to reproduce it (as minimally and precisely as possible)**:
run GitHub actions manually or wait for their scheduled time

**Comment by Tantalor93** [comment]
I guess a workaround can be to make Corebot open pull requests with changes 🤔

**Comment by chrisohaver** [comment]
Or switch things up to have these checked in PRs before merge.

**Comment by Tantalor93** [comment]
agreed, I think we can make golangci-lint to check formatting, but I am not sure about checking a need for go mod tidy 🤔

**Comment by chrisohaver** [comment]
I think dependabot already cleans up go.mod/go.sum every time it opens a PR.   Which is kind of sloppy, but at least it gets fixed once a week.

**Comment by Tantalor93** [comment]
it seems that reviewdog is already doing some gofmt check as part of its workflow on PR (https://github.com/coredns/coredns/blob/master/.github/workflows/reviewdog.yml), meaning I guess we can just remove Go Fmt action and as you said if Dependabot is already doing go mod tidy we can also remove Go mod tidy action, WDYT?
