### ISSUE TITLE
how to enter   container  internal?

### ISSUE THREAD

**Issue by zwbdzb** [miekg/coredns#5744]
docker run --rm -i -t -v $PWD:/v -w /v golang:1.18 make

>  dockerfile says that :   SHELL [ "/bin/sh", "-ec" ]

```
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "ls": executable file not found in $PATH: unknown
```

how to enter container  internal?

**Comment by mariuskimmina** [comment]
I don't quite understand what you are trying to do here. You are running a make command on a container with the golang 1.18 image, right? what are you trying to build? Which dockerfile are you talking about, the one for golang 1.18? How is this related to CoreDNS? 
I think we need some more information to help you here.

**Comment by zwbdzb** [comment]
https://github.com/coredns/coredns/blob/master/Dockerfile

yes，the question is not related to coredns，i just want to see the coredns conf in coredns container，

but i can not use the shell to enter the container 。

**Comment by mariuskimmina** [comment]
There is no shell on that container 
```
FROM --platform=$BUILDPLATFORM debian:stable-slim
SHELL [ "/bin/sh", "-ec" ]
```

is only the first stage, see here for more infos: https://docs.docker.com/build/building/multi-stage/
later we switch to 

```
FROM --platform=$TARGETPLATFORM scratch
```

Using [sratch](https://hub.docker.com/_/scratch) the container is super minimal, basically only containing the coredns binary.

**Comment by mariuskimmina** [comment]
Also, to answer your other question - I belive there is no Corefile present by default. Which means that the default config is being used which is just the `whoami` plugin 

https://coredns.io/manual/toc/#testing
Without a Corefile CoreDNS will load the [whoami](https://coredns.io/plugins/whoami) plugin that will respond with the IP address and port of the client.
