### ISSUE TITLE
rewrite plugin, answer value, complain about 3 arguments

### ISSUE THREAD

**Issue by sl45sms** [miekg/coredns#5751]
**What happened**:
I tried to reproduce the following from the doc [rewriting of the value in the ANSWER SECTION](https://github.com/coredns/coredns/blob/master/plugin/rewrite/README.md#:~:text=rewriting%20of%20the%20value%20in%20the%20ANSWER%20SECTION)
```
    rewrite stop {
        name suffix .arpa .arpa
        answer name auto
        answer value (.*)\.service\.consul\. {1}.coredns.rocks.
    }
```
but iv got 
`
plugin/rewrite: response rewrites must consist only of a name rule with 3 arguments and an answer rule with 3 arguments
`

**What you expected to happen**:
to work as document says

**How to reproduce it (as minimally and precisely as possible)**:
even the exact example from documentation does not work

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.8.0
- Corefile:
 ```
    version.bind version.server authors.bind hostname.bind id.server {
    chaos SkarvelisDNS-001 info@skarvelis.gr
    }
    skarvelis.gr {
       forward . 88.198.229.192
       rewrite stop {
        name suffix .gr .gr
        answer name auto
        answer value (.*)\.hetzner\.com\. {1}.skarvelis.gr.
       }
    }
    .:53 {
        acl {
          block net 10.1.86.1/32
        }
        errors
        health {
          lameduck 5s
        }
        ready
        log . {
          class error
          class denial
          class success
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 8.8.8.8 8.8.4.4 
        cache 30
        loop
        reload
        loadbalance
    }
 ```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:
on mikcrok8s

**Comment by mariuskimmina** [comment]
If I just use the example from the documentation in a minimalistic Corefile

```
.:54 {
    rewrite stop {
        name suffix .arpa .arpa
        answer name auto
        answer value (.*)\.service\.consul\. {1}.coredns.rocks.
    }
}
```

I don't get any error. 
I am on CoreDNS 1.10.0 tho, could you try updating?

**Comment by mariuskimmina** [comment]
Just tried it with 1.8.0, there I get the same error
```
plugin/rewrite: response rewrites must consist only of a name rule with 3 arguments and an answer rule with 3 arguments
```

So there is a good chance that updating will fix it for you

**Comment by sl45sms** [comment]
@mariuskimmina thank's, I will try to make a custom build for microk8s.

**Comment by sl45sms** [comment]
Confirm that is working on latest microk8s 1.25.3, that uses coredns 1.9.3
