### ISSUE TITLE
external  server  can not  accessthe coredns prometheus plugin listen addr 

### ISSUE THREAD

**Issue by zwbdzb** [miekg/coredns#5763]
**What happened**:
   
  build the coredns by docker container,  we can not access the prometheus  metricss  through  {ip:9153}. 

 so the prometheus can not  collect the metrics from the  coredns using pull mode.

**How to reproduce it (as minimally and precisely as possible)**:
   branch:  master   

   launch the coredns server,  access the metrics addr : {ip}:9153  

**Anything else**:
 I have reviewed  the prometheus  plugin source code , the listen addr  is fixed with  "localhost:9153".

https://github.com/coredns/coredns/blob/master/plugin/metrics/setup.go#L105
https://github.com/coredns/coredns/blob/master/plugin/metrics/setup.go#L74

**Comment by mariuskimmina** [comment]
Some questions to help troubleshooting:

1. Can you share your configuration (Corefile)? 
2. Is CoreDNS in general reachable? (e.g. can you send a DNS request and get a reply)

**Comment by zwbdzb** [comment]
> Some questions to help troubleshooting:
> 
> 1. Can you share your configuration (Corefile)?
> 2. Is CoreDNS in general reachable? (e.g. can you send a DNS request and get a reply)

1.  the corefile is simple:
```
 . {
     whoami
     prometheus 127.0.0.1:9153
}
```
2.  the coredns function is  reachable， we are talk about  the   metrics.

 when you change  the metric addr to  "prometheus  0.0.0.0:9153" ,  we cannot  access the addr  by   ip.

**Comment by mariuskimmina** [comment]
The following worked for me

```
docker run -d --name coredns --restart=always --volume=/home/marius/projects/tests/:/root/ -p 54:54/udp -p 9153:9153/tcp coredns/coredns -conf /root/Corefile
```

```
.:54 {
    whoami
    prometheus 0.0.0.0:9153
}
```

This way metrics are accessible on the host system, port 9153, using the usual `/metrics` path.

**Comment by zwbdzb** [comment]
> The following worked for me
> 
> ```
> docker run -d --name coredns --restart=always --volume=/home/marius/projects/tests/:/root/ -p 54:54/udp -p 9153:9153/tcp coredns/coredns -conf /root/Corefile
> ```
> 
> ```
> .:54 {
>     whoami
>     prometheus 0.0.0.0:9153
> }
> ```
> 
> This way metrics are accessible on the host system, port 9153, using the usual `/metrics` path.

sorry，  It's my problem， I  add a push mode in metrics plugin , and i  do not pay attention to the `args` rewrite. 

 the issue can  be closed.
