### ISSUE TITLE
Unreachable secondary notifications makes start/reload painfully slow with plugin/auto

### ISSUE THREAD

**Issue by NCRonB** [miekg/coredns#5767]
**What would you like to be added**:

I would like transfer notifications to be handled after all zones are inserted by plugin/auto on start/reload instead of waiting for notifications to complete for each zone as it's inserted.

**Why is this needed**:

If a secondary server is unreachable, startup/reload is painfully slow (+6 seconds per zone). With my 24 zones, it takes over two minutes to start/reload if a secondary is unreachable. During this time, CoreDNS does not respond to requests.

**Comment by chrisohaver** [comment]
Makes sense to me.  I've opened a PR to do this https://github.com/coredns/coredns/pull/5774.
