### ISSUE TITLE
CoreDNS pods are failing with below error. Do we have a solution around this one?

### ISSUE THREAD

**Issue by strikingraghu** [miekg/coredns#5778]
**What happened**:
I am running K8s 1.24 in our setup along with the CoreDNS add-on.
However, CoreDNS pods are failing with below error:

[root@lintsb029 ~]# kubectl logs coredns-6f4b4bd8fb-25624 --kubeconfig admin.kubeconfig -n kube-system
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
.:53
[INFO] plugin/reload: Running configuration SHA512 = 26dec110ea918fd3ebfd794bd8a216ad7525634327792826859b6f87d9307f668561c93f82c794add0c704e57e77660b5cebeb0e15b938626c49689d03770a7b
CoreDNS-1.9.4
linux/amd64, go1.19.1, 1f0a41a
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:34463->10.118.225.100:53: i/o timeout
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:39555->10.118.225.100:53: i/o timeout
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:48634->10.118.225.100:53: i/o timeout
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:52473->10.118.225.100:53: i/o timeout
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:39258->10.118.225.100:53: i/o timeout
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:44477->10.118.225.100:53: i/o timeout
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:37129->10.118.225.100:53: i/o timeout
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:39135->10.118.225.100:53: i/o timeout
[WARNING] plugin/kubernetes: Kubernetes API connection failure: Get "https://10.96.0.1:443/version": dial tcp 10.96.0.1:443: i/o timeout
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:51197->10.118.225.100:53: i/o timeout
[ERROR] plugin/errors: 2 2645034031827185895.3589184578021158306. HINFO: read udp 10.32.0.2:52257->10.118.225.100:53: i/o timeout
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"

**What you expected to happen**:
CoreDNS pods should run successfully and a busybox test for nslookup should resolve to ip/name

**How to reproduce it (as minimally and precisely as possible)**:
Deployment the latest version of CoreDNS service on K8s 1.24 version

**Anything else we need to know?**:
No, logs are attached above

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
The errors mean your kubernetes API service is unreachable, either because it’s not running or otherwise unable to accept connections.

This will affect any service trying to connect to the kubernetes API, not just CoreDNS.

**Comment by strikingraghu** [comment]
Thanks @chrisohaver!
I was able to resolve this issue with below steps:

CoreDNS pods were not in running state:
a) Just add hostname in /etc/hosts file
b) Set net.ipv4.ip_forward = 1 in /etc/sysctl.conf
c) SELinux is in disabled or permissive state
d) Reboot & swapoff -a before starting the kubelet
