### ISSUE TITLE
Forwarding to a DoH service

### ISSUE THREAD

**Issue by LukasAfonso** [miekg/coredns#5786]
How do I foraward to an https server all the requests?
I have the following but it is not resolving DNS on localhost.

```
.:53 {
  any
  errors
  log

  forward . https://94.140.14.14/dns-query {
    tls
    tls_servername dns.adguard-dns.com
  }
}
```

**Comment by Tantalor93** [comment]
Hello @LuisCarlos-104171, `forward` plugin as such does not support forwarding via DoH, but there are external plugins that you might use like https://github.com/v-byte-cpu/coredns-https for forwarding via DoH

**Comment by LukasAfonso** [comment]
It tells me `context dead line exceeded`, what can be the cause?

**Comment by Tantalor93** [comment]
external plugins are not managed by us, for troubleshooting these plugins I suggest contacting the author of the plugin
