### ISSUE TITLE
Route53 empty responses for a zone containing geoip records

### ISSUE THREAD

**Issue by brekke-roq** [miekg/coredns#5800]
**What happened**:

There is a fairly basic setup:

```
. {
    log
 #   debug
    errors
    health {
       lameduck 5s
    }
    ready
    cancel
    prometheus :9153
 
 
    route53 nonworking.eu.:aaaaaaaaaaaaaa
    route53 int.working.pl.:bbbbbbbbbbbbbb
    route53 working.pl.:cccccccccccccc
 
    forward . 8.8.8.8 1.1.1.1 9.9.9.9 {
       max_concurrent 1000
       except nonworking.eu working.pl
    }
 
    cache 30
    loop
    auto
    reload
    loadbalance
 }
```

We do have 3 public zones in the same account. I can list it's content via aws cli using the same aws credentials. For unknown reason queries for *.nonworking.eu always returns SOA.

In contrast to *.working.pl zone *.nonworking.eu contains some geoip records and i was querying from localhost and private space ipv4 addresses.

You can note that route53 configured domains are blacklisted in forwarder. I did that to make sure we get this zones from aws api. I can remove forwarding configuration and even two working domain zones (caching as well) and this one zone still returns SOA for each query.

**What you expected to happen**:

nonworking.eu being correctly served via route53 plugin and not forwarder.
If something is wrong with api calls warnings should be shown in the debug (which is not the case).

**How to reproduce it (as minimally and precisely as possible)**:

The only difference between domains i presence of geoip records in *.nonworking.eu. I can provide additional data but i need something more than ordinary debug mode.

**Anything else we need to know?**:
Do i miss some plugin?
Perhaps route53 plugin is not aware of it's location therefore not able to serve geoip records and breaking a whole zone in a result?

**Environment**:

- the version of CoreDNS: k8s.gcr.io/coredns/coredns:v1.10.0
- Corefile: shown above
- logs, if applicable: no logs unfortunately
- OS (e.g: `cat /etc/os-release`): Docker image running on Fedora kernel 6.0.11-300.fc37.x86_64
- Others:

THX

**Comment by dilyevsky** [comment]
@brekke-roq thanks for report! Hm, I don't see anything in the code suggesting geoip is treated differently. They are supposed to return regular typed RRs, just with additional fields set. Also, just to confirm, by "geoip" you're referring to [Geolocation](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-geo.html) not [Geoproximity](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-geoproximity.html)?

Have you tried running `aws route53 list-resource-record-sets --hosted-zone-id aaaaaaaaaaaaaa` by chance?

**Comment by brekke-roq** [comment]
@dilyevsky Hello! Routing policy for this non-woking records is `Geolocation`. I have checked this zone by using aws cli already. Records seem to be here. Should i look for anything particular?

**Comment by brekke-roq** [comment]
@dilyevsky  Hah, I have just learned that route53 plugin does not support the aliases and i do use aliases a lot. Perhaps that's the reason?

**Comment by dilyevsky** [comment]
@brekke-roq that's right we do not support it within route53 plugin so it should just ignore those. I think last time we looked at those it was difficult to do a clean implementation since there were a lot of tie ins with AWS-specific features.
