### ISSUE TITLE
we need coredns for ARM

### ISSUE THREAD

**Issue by killsnow** [miekg/coredns#5846]
Our server is based ARM, the image in hub.docker.com can't be used, everytime I downlod use this command:
docker pull --platform=linux/arm coredns/coredns:1.8.7
The result is:
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 43204323
Can you push a real arm version, or put a Dockerfile on the github.
Thanks a lot.
![截屏2023-01-11 13 30 29](https://user-images.githubusercontent.com/8868724/211725257-bdc70089-1f9f-49eb-abdd-03e8527d466a.png)

**Comment by chrisohaver** [comment]
Should be fixed in next release.

see: https://github.com/coredns/coredns/issues/5842#issuecomment-1375738388
