### ISSUE TITLE
nslookup timedout occasionally 

### ISSUE THREAD

**Issue by w-wenbo** [miekg/coredns#5852]
**What happened**:

I set up a OKE cluster on oci, and when I use nslookup to check coredns is work correctly, I got timed out error **occasionally**,

1000 times nslookup and get 71 times timed out.

```bash
$ for i in `seq 0 1000`; do nslookup www.google.com >> nslookup.log; done
$ cat nslookup.log | grep "timed out" | wc -l
71
```

**What you expected to happen**:

there is no timed out error

**How to reproduce it (as minimally and precisely as possible)**:

Setup a OKE cluster, And run a dnsutils pod, then Just run the code above.

**Environment**:
Kubernetes v1.24.1 on OCI cloud.

- the version of CoreDNS:1.8.6(oke-public-coredns)

**Comment by Tantalor93** [comment]
Hello, if those errors are not happening consistently, I would suggest checking the cluster networking. I would start with checking whether all the DNS requests arrive to CoreDNS pod. With the info you provided, nothing points to CoreDNS

**Comment by w-wenbo** [comment]
thx for your answer
