### ISSUE TITLE
How to add  A record for a  specific  pod in k8s?

### ISSUE THREAD

**Issue by YE-Fan** [miekg/coredns#5861]
I want to add A record for only specific pod can resolve.
For example,  
if a dns query from pod A,    coreDNS return  abc.com -> 1.1.1.1
if a dns query from pod B,    coreDNS return  abc.com ->  2.2.2.2

**Comment by chrisohaver** [comment]
This should be possible with metadata based views, but it would require CoreDNS to maintain an extra instance of the _kubernetes_ plugin, which is taxing on resources.

It would look something like the following added to the _top_ of your existing Corefile ...

```txt
abc.com {
  view podA {
    expr metadata('kubernetes/client-pod-name') == 'pod A'
  }
  metadata
  hosts {
    1.1.1.1 abc.com
  }
  kubernetes cluster.local {
    pods verified
  }
}

```

**Comment by YE-Fan** [comment]
thanks for your answer, it's really helpful
