### ISSUE TITLE
unable to connect internet through pod in RHEL 8.7 using microk8s - coredns 1.8.0

### ISSUE THREAD

**Issue by parshva-shah-dsw** [miekg/coredns#5882]
ENV :- 1.21.13 k8s
OS :- RHEL 8.7
 Getting below error in core dns pod logs :- 
 
[INFO] 10.1.100.28:51514 - 47986 "A IN security.ubuntu.com.pkad13xkf0cudnn2zfxjoc0xic.rx.internal.cloudapp.net. udp 89 false 512" NOERROR - 0 2.000206338s
[ERROR] plugin/errors: 2 security.ubuntu.com.pkad13xkf0cudnn2zfxjoc0xic.rx.internal.cloudapp.net. A: read udp 10.1.100.35:37686->8.8.8.8:53: i/o timeout
[INFO] 10.1.100.28:51514 - 5751 "AAAA IN security.ubuntu.com.pkad13xkf0cudnn2zfxjoc0xic.rx.internal.cloudapp.net. udp 89 false 512" NOERROR - 0 2.000290839s
[ERROR] plugin/errors: 2 security.ubuntu.com.pkad13xkf0cudnn2zfxjoc0xic.rx.internal.cloudapp.net. AAAA: read udp 10.1.100.35:34504->8.8.4.4:53: i/o timeout

both tcp and upd port 53 is open
```
core-dns config map
Corefile:
----
.:53 {
    errors
    health {
      lameduck 5s
    }
    ready
    log . {
      class error
    }
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . 8.8.8.8 8.8.4.4
    cache 30
    loop
    reload
    loadbalance
}
```

**Comment by chrisohaver** [comment]
If `pkad13xkf0cudnn2zfxjoc0xic.rx.internal.cloudapp.net.` is a private domain, you 'll need to [add a stub domain for it](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configuration-of-stub-domain-and-upstream-nameserver-using-coredns).

**Comment by parshva-shah-dsw** [comment]
@chrisohaver in documentation it is mentioned we can not use FQDNs.

Note: CoreDNS does not support FQDNs for stub-domains and nameservers (eg: "ns.foo.com"). During translation, all FQDN nameservers will be omitted from the CoreDNS config.

**Comment by chrisohaver** [comment]
~Can you link to that?~

I see it… even in context, I have no idea what that means.

**Comment by chrisohaver** [comment]
> ~Can you link to that?~
> 
> I see it… even in context, I have no idea what that means.

Ok - now I realize what it means. It means you cannot forward to a dns name, you must forward to an IP address. This should not be a problem. 

The documentation is worded poorly and misleading.  IMO. It should be … 

> CoreDNS does not support forwarding to FQDN nameservers (eg: "ns.foo.com"). Nameservers must be IP addresses.

**Comment by parshva-shah-dsw** [comment]
@chrisohaver we did a change while deploying the resources by adding below resolv.conf : - 

dnsPolicy: "Default"
dnsConfig:
    nameservers:
     - 168.63.129.16
     searches:
     - pkad13xkf0cudnn2zfxjoc0xic.rx.internal.cloudapp.net

by adding this pod were able to connect to internet.
This we feel is wrong way ideally it should be seamless.

**Comment by chrisohaver** [comment]
> by adding this pod ...

You added a Pod? I dont understand.

**Comment by chrisohaver** [comment]
If you could clearly state your question and problem we may be able to help better.

**Comment by chrisohaver** [comment]
> by adding this pod were able to connect to internet.

ok - I was reading this as "By adding this Pod, we're able to connect to internet."

But I think you meant ...

"By adding this, the Pod was able to connect to the internet"

That fix does not look correct.

Is `pkad13xkf0cudnn2zfxjoc0xic.rx.internal.cloudapp.net` your private domain?
