### ISSUE TITLE
Does cache plugin TTL override real TTL?

### ISSUE THREAD

**Issue by ronyrv13** [miekg/coredns#5892]
Hello Team,
I am Using CoreDNS server as our DNS solution for internal domain's.
Same coreDns server's are used by default for external domains as well.
For External domain we are using forward plugin with Proxy to Google Public DNS and cache upto 3600

Our Config -
`.:53 {
    forward . 8.8.8.8 9.9.9.9
    cache 3600
    log
    health :8080
    prometheus :9153
    errors
}`

But the cache plugin ttl is not overriding the real TTL value of the record!

is that the default behaviour of CoreDns?
using rewrite plugin I was able to override the TTL, is it the right approach?

Your response can make my day, Thanks

**Comment by chrisohaver** [comment]
`cache 3600` will cache records for up to 3600 seconds but not longer than their original TTL, after which they expire from cache. While in cache the TTL in a response reflects the amount of time remaining before the record will expire from cache.

If you literally just want to overwrite TTL to a specific value, the _rewrite_ plugin is the right approach. 

If instead your goal is to cache items for longer, eg for _at least_ 3600 seconds, set the minimum cache time in the cache plugin (see the cache plugin readme).

**Comment by ronyrv13** [comment]
Thank you @chrisohaver for your response.

We are using CoreDNS in 2 stages

- In AKS By default as azure aks managed pods in kube-system namespace.
- Then we use CoreDNS as custom DNS Servers in AKS Nodes, so AKS managed CoreDNS pods forwards requests to our custom coredns servers.
-  I have tweaked the TTL in custom coredns servers for example.com to `3600` and enabled `cache 3600`

But when application pod's perform DNS request to AKS managed CoreDNS Pods, it overrides the cache value to 30 from 3600
How can I resolve this issue?
Should I have to update CoreFile for AKS managed coredns as well?

**Comment by chrisohaver** [comment]
> Should I have to update CoreFile for AKS managed coredns as well?

Yes. Since you have two caches deployed in series, the lower maximum of the two takes precedence.

**Comment by ronyrv13** [comment]
gotcha , Thanks @chrisohaver 🫡
