### ISSUE TITLE
How can I read /etc/resolv.conf file?

### ISSUE THREAD

**Issue by Simas1** [miekg/coredns#5896]
CoreDNS do not have tools, so I can read file:
- do not have shell (sh, bash, etc) (kubectl exec -it coredns.... -- /bin/sh)
- do not have 'cat' or similar to view contents
- do not have tools to copy files (e.g. kubectl cp ...)
- do not have package manager (e.g. apt), so I can't install tools

So how I can view contents of the file inside CoreDNS container?

**Comment by mqasimsarfraz** [comment]
Is using [ephemeral container](https://github.com/coredns/coredns/discussions/5264#discussioncomment-2364247)  an option?

**Comment by Simas1** [comment]
It is inside Azure AKS cluster. And if I try to use ephemeral container:
error: ephemeral containers are disabled for this cluster (error from server: "the server could not find the requested resource").

**Comment by mqasimsarfraz** [comment]
Can you create a test pod with same [dnsPolicy/dnsConfig](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#poddnsconfig-v1-core) as CoreDNS. Then checking resolv.conf in test pod should help?

**Comment by chrisohaver** [comment]
Generally in Kubernetes the coredns Pod resolv.conf is the same as the one on the node the pod runs on.  That’s the default behavior of kubelet, but kubelet can optionally be configured to set up pods with same dnsPolicy as coredns with a different resolv.conf.

**Comment by Simas1** [comment]
> Generally in Kubernetes the coredns Pod resolv.conf is the same as the one on the node the pod runs on. That’s the default behavior of kubelet, but kubelet can optionally be configured to set up pods with same dnsPolicy as coredns with a different resolv.conf.

That I would like to confirm, not just assume. I would like to see how and when resolv.conf is updated (for example when I change Vnet DNS list)

**Comment by Simas1** [comment]
> Can you create a test pod with same [dnsPolicy/dnsConfig](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#poddnsconfig-v1-core) as CoreDNS. Then checking resolv.conf in test pod should help?

Interesting idea, juts not sure if that will be the same result. I still would like to confirm, not assume, or do some mocking

**Comment by chrisohaver** [comment]
Build coredns in your own container that supports a shell.

**Comment by Simas1** [comment]
> Generally in Kubernetes the coredns Pod resolv.conf is the same as the one on the node the pod runs on. That’s the default behavior of kubelet, but kubelet can optionally be configured to set up pods with same dnsPolicy as coredns with a different resolv.conf.

I created container with dnsPolicy: Default (the same like DnsCore container) - this kind of works, I see it get values from node I can confirm this (even it's not the same container).

Is anyone knows how frequently it is sync with node? (if resolv.conf is changed on node, how long it will take to refresh in container, or this is only done on creation Container and later I need to rebuild container if I want to update?)

**Comment by chrisohaver** [comment]
> Is anyone knows how frequently it is sync with node? (if resolv.conf is changed on node, how long it will take to refresh in container, or this is only done on creation Container and later I need to rebuild container if I want to update?)

That is managed by kubelet, a Kubernetes component we don't maintain here.  I _suspect_ (though I do not know for sure) that kubelet just does this at container creation time. IMO, the resolv.conf file was designed to be somewhat static, not a dynamic configuration - changes in the upstream nameserver list are expected to be relatively uncommon.

Regardless, CoreDNS's _forward_ plugin only reads the resolv.conf at start up, and _reload_ plugin does not monitor the file if it changes.

So, for multiple reasons, you'll need to restart the Pod when resolv.conf changes.

**Comment by Simas1** [comment]
> That is managed by kubelet, a Kubernetes component we don't maintain here. I _suspect_ (though I do not know for sure) that kubelet just does this at container creation time. IMO, the resolv.conf file was designed to be somewhat static, not a dynamic configuration - changes in the upstream nameserver list are expected to be relatively uncommon.
> 
> Regardless, CoreDNS's _forward_ plugin only reads the resolv.conf at start up, and _reload_ plugin does not monitor the file if it changes.
> 
> So, for multiple reasons, you'll need to restart the Pod when resolv.conf changes.

Thanks for details. Yes, it's not very frequent DNS servers change, but when it happens we need to know what needs to be done so DNS will function as expected. So seems that after I change DNS list on Vnet, via DHCP it will propagate to VM (AKS cluster node), then I need to restart all CoreDNS pods - so it will get new copy of /etc/resolv.conf from node. And only then DNS queries (external) start working with new DNS list.

**Comment by Simas1** [comment]
and actually this is one of the reasons why I need to read /etc/resolv.conf on CoreDns pod, not to do some mocking (create new Container with dnsPolicy: Default), because I can get different contents (in case DNS list was changed on Node, and CoreDNS pods was not restarted). So this would be required for troubleshooting also, because if DNS list would be changed on Node (VM) and CoreDNS pods is not restarted - I need a way to examine /etc/resolv.conf contents - so I can identify issue.
Maybe it's possible to add to the CoreDNS image some small utility which can show contents of resolv.conf?

**Comment by chrisohaver** [comment]
> Maybe it's possible to add to the CoreDNS image some small utility which can show contents of resolv.conf?

Build coredns in your own container that supports a shell.

**Comment by Simas1** [comment]
> > Maybe it's possible to add to the CoreDNS image some small utility which can show contents of resolv.conf?
> 
> Build coredns in your own container that supports a shell.

This will create new container with updated new resolv.conf, it will not show me issue (I will not see old outdated resolv.conf)

**Comment by Simas1** [comment]
Also keep in mind that I'm using Managed K8s Cluster - Azure AKS. I change only ConfigMap if required here.
But for troubleshooting I need possibility to investigate such important part of DNS like resolv.conf

**Comment by chrisohaver** [comment]
> ... Azure AKS. I change only ConfigMap ...

Given the restrictions imposed by AKS, I don't see a solution. Even adding a sidecar to the Pod that monitors the file is not possible if you are not allowed to change the Deployment.

I think the best you can do is infer the configured upstreams from the forward plugin's coredns_forward_requests_total metric (which holds a count of requests for each configured nameserver).

**Comment by Simas1** [comment]
> I think the best you can do is infer the configured upstreams from the forward plugin's coredns_forward_requests_total metric (which holds a count of requests for each configured nameserver).

I try to add this Prometheus metrics, but it seems I'm missing something, need to dig more how to collect this.
But, is it going to show me results per nameserver, or just total count?

P.S> also Log Analytics is not free, so I will need to pay for ingestion volume :(

**Comment by chrisohaver** [comment]
>  is it going to show me results per nameserver

per nameserver

**Comment by chrisohaver** [comment]
Closing, since there is no apparent acceptable solution to the problem.

You are welcome to make an enhancement request.
