### ISSUE TITLE
[Bug] tls plugin does not use path set by root plugin

### ISSUE THREAD

**Issue by rahilarious** [miekg/coredns#5910]
**What happened**:
Following config does not load /config/cert.pem but tries to load /cert.pem (from execution dir)
```
tls://example.com:853 {
      root /config
     tls cert.pem key.pem
    whoami
}
```

**What you expected to happen**:
It should be loading from /config/cert.pem

**Anything else we need to know?**:
Probably happens because https://github.com/coredns/coredns/blob/055b2c31a9cf28321734e5f71613ea080d216cd3/plugin.cfg#L25 is loading before https://github.com/coredns/coredns/blob/055b2c31a9cf28321734e5f71613ea080d216cd3/plugin.cfg#L30 in plugin.cfg

**Environment**:
- the version of CoreDNS: 1.10.1
- OS: official docker image

**Comment by mariuskimmina** [comment]
I can confirm the issue and I also tried to rebuild coredns with `root:root` before `tls:tls` in my `plugin.cfg` but without success, it still looks for the cert in the current directory.

**Comment by mariuskimmina** [comment]
The file plugin actively checks for `config.Root` in it's `setup.go` file - the tls plugin does not. I think I can make a fix for this in the next few days - @chrisohaver can you assign this to me?

**Comment by rahilarious** [comment]
> The file plugin actively checks for `config.Root` in it's `setup.go` file - the tls plugin does not. I think I can make a fix for this in the next few days - @chrisohaver can you assign this to me?

Hey, thank you for looking into this.
