### ISSUE TITLE
Is there a plugin for TSIG key config for nsupdate?

### ISSUE THREAD

**Issue by akaraon8bit** [miekg/coredns#5916]
Is there a plugin for TSIG key config to replicate BIND config for the following BIND configuration or plugin to update DNS on the fly?

``zone "mydomain.com"  {``
``  type master;``
 `` file "/var/named/mydomain.com.db";``
  ``allow-update {  key privaterdnskey. ; };``
``};``

**Comment by chrisohaver** [comment]
No, there is not.

**Comment by akaraon8bit** [comment]
found this https://github.com/coredns/coredns/pull/4957/files#diff-1badee195e8dfe7984062b78f18b924170595896a56a60749b474e0ba85a0132


``auth.zone {``
  `` tsig {``
    `` secret auth.zone.key. NoTCJU+DMqFWywaPyxSijrDEA/eC3nK0xi3AMEZuPVk=``
  ``   require all``
 ``  }``

**Comment by chrisohaver** [comment]
Yes. But coredns does not support or even forward dns updates.

**Comment by akaraon8bit** [comment]
> Yes. But coredns does not support or even forward dns updates.

Thank you, I hope this featured will be grounded soon.

**Comment by chrisohaver** [comment]
Unfortunately adding support for DNS updates would require a _very_ large effort due to its complexity. It is not currently in development that I am aware, so not likely to be available soon.
