### ISSUE TITLE
coredns  CrashLoopBackOff   

### ISSUE THREAD

**Issue by Hhheveyday** [miekg/coredns#5918]
[root@k8s-master01 install-k8s]# kubectl get  pod  -A
NAMESPACE       NAME                                        READY   STATUS             RESTARTS   AGE
kube-system     coredns-5c98db65d4-drk6r                    0/1     CrashLoopBackOff   10         31m
kube-system     coredns-5c98db65d4-rh5wn                    0/1     CrashLoopBackOff   10         31m

kubectl  logs  -n kube-system  coredns-5c98db65d4-drk6r
E0213 16:31:25.044487       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:317: **Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kube-system:coredns" cannot list resource "endpoints" in API group "" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "system:coredns" not found**
E0213 16:31:25.044487       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:317: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kube-system:coredns" cannot list resource "endpoints" in API group "" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "system:coredns" not found
log: exiting because of error: log: cannot create log: open /tmp/coredns.coredns-5c98db65d4-drk6r.unknownuser.log.ERROR.20230213-163125.1: no such file or directory

kubectl  describe  pod  -n kube-system   coredns-5c98db65d4-drk6r
Name:                 coredns-5c98db65d4-drk6r
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 k8s-node02/192.168.66.21
Start Time:           Mon, 13 Feb 2023 23:54:40 +0800
Labels:               k8s-app=kube-dns
                      pod-template-hash=5c98db65d4
Annotations:          <none>
Status:               Running
IP:                   10.244.2.192
Controlled By:        ReplicaSet/coredns-5c98db65d4
Containers:
  coredns:
    Container ID:  docker://849a37bab4a004332a46f8bf1eb5e2cdc75b30f516ba4c594e7bd1d10be6a7d7
    Image:         k8s.gcr.io/coredns:1.3.1
    Image ID:      docker://sha256:eb516548c180f8a6e0235034ccee2428027896af16a509786da13022fe95fe8c
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 14 Feb 2023 00:36:28 +0800
      Finished:     Tue, 14 Feb 2023 00:36:28 +0800
    Ready:          False
    Restart Count:  13
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8080/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-nhxh6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-nhxh6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-nhxh6
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                 Message
  ----     ------     ----                 ----                 -------
  Normal   Scheduled  46m                  default-scheduler    Successfully assigned kube-system/coredns-5c98db65d4-drk6r to k8s-node02
  Normal   Pulled     44m (x5 over 46m)    kubelet, k8s-node02  Container image "k8s.gcr.io/coredns:1.3.1" already present on machine
  Normal   Created    44m (x5 over 46m)    kubelet, k8s-node02  Created container coredns
  Normal   Started    44m (x5 over 46m)    kubelet, k8s-node02  Started container coredns
  Warning  BackOff    67s (x220 over 46m)  kubelet, k8s-node02  Back-off restarting failed container

**Comment by chrisohaver** [comment]
What version of k8s? CoreDNS 1.3.1 was released over 4 years ago.

**Comment by Hhheveyday** [comment]
The k8s version is v1.15.1; Is it caused by the DNS loop?

**Comment by chrisohaver** [comment]
> The k8s version is v1.15.1; Is it caused by the DNS loop?

No, loop errors look different. Is this a new system you are setting up? Or a cluster created 4 years ago? If something new, is using a more up to date release of k8s an option? 

The final exiting error looks like a possible API incompatibility problem. 

At the very least, the coredns account has insufficient roles, per earlier errors.

**Comment by chrisohaver** [comment]
Using google to search, I found that the "exiting because of error: log: cannot create log:"  appears the behavior of the old versions of the kubernetes api go client when it fails to connect to API under certain conditions.  Not sure if more contemporary versions of the the API client would actually exit in this scenario (IMO an exiting is a bad behavior). 

Anyways, it seems that "RBAC: clusterrole.rbac.authorization.k8s.io "system:coredns" not found" is the root of the issue.
You are missing RBAC roles for the coredns account.

**Comment by chrisohaver** [comment]
https://github.com/kubernetes/kubernetes/issues/75414

**Comment by Hhheveyday** [comment]
The query found that ClusterRoleBinding lacks [annotations]. 
#kubectl describe clusterrolebindings
Name:         system:coredns
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  system:coredns
Subjects:
  Kind            Name     Namespace
  ----            ----     ---------
  ServiceAccount  coredns  kube-system
