### ISSUE TITLE
Release build system decommission

### ISSUE THREAD

**Issue by chrisohaver** [miekg/coredns#5930]
The system that builds our releases (aka "drone") is going to be decommissioned soon.  The datacenter in which it sits is being shut down permanently.  It's a bare metal device, so virtual migration to a new datacenter is not an option.  AFAIK, we would need to rebuild this system in a new datacenter if we want to keep it.

We've got two options:
1. We can try to rebuild drone in a new datacenter. We'll need access to drone, to learn what's on it.
2. We can migrate to building releases via GitHub action, as @yongtang has done for docker releases.

I think 2 is preferable.  I'm not sure what other services drone provides if any or how important they are.

**Comment by Tantalor93** [comment]
I think option two is better, but I think we should consider other options like [GoReleaser](https://goreleaser.com/). It seems that GoReleaser nowadays is quite common used for releasing GO projects. It can also handle docker builds, binaries, github releases, etc.

**Comment by vielmetti** [comment]
If the team does not already have access to the "drone" system, please let me know and I can arrange for that to happen.
