### ISSUE TITLE
[plugin/dnstap]:  No connection to dnstap endpoint

### ISSUE THREAD

**Issue by BhumikaMatharu** [miekg/coredns#5954]
I am using coredns 1.6.9 (OS: Ubuntu 18.04) and trying to implement dnstap plugin.
I am seeing following error on adding the plugin, 
![image](https://user-images.githubusercontent.com/50544476/223850920-4d0c6e87-11c9-4e03-9198-9152a5bc3e6b.png)

Do we need to create a UNIX socket and enable dnstap there? 
Any suggestion would be helpful!

**Comment by chrisohaver** [comment]
please share your configuration (Corefile).

**Comment by BhumikaMatharu** [comment]
.:53 {
    forward . 8.8.8.8 {
            health_check 5s
    }
    errors
    cache
    dnstap /tmp/dnstap.sock full
    reload 5s
}

**Comment by chrisohaver** [comment]
> Do we need to create a UNIX socket and enable dnstap there?

yes, the socket needs to exist, and some process listening to it for dnstap messages.

e.g. something like ... https://github.com/coredns/coredns/tree/master/plugin/dnstap#command-line-tool

**Comment by BhumikaMatharu** [comment]
Setting up the dnstap command line tool should be enough?

**Comment by chrisohaver** [comment]
> Setting up the dnstap command line tool should be enough?

yes - it creates the unix socket and listens on it.

**Comment by BhumikaMatharu** [comment]
Thanks @chrisohaver

**Comment by BhumikaMatharu** [comment]
I am re-opening this issue because it still doesn't seem to work. I got the dnstap (go utility) here as you can see below,
![image](https://user-images.githubusercontent.com/50544476/224171825-5d8366a8-c029-4da0-a7ad-eb05d7e8b2e8.png)

I added the path of dnstap to PATH variable as well.
Still I am getting the same issue. Any idea why so?

Do we need Unbound dns server as mentioned here to make dnstap work?
http://dnstap.info/Tutorials/NANOG60/

**Comment by BhumikaMatharu** [comment]
I tried launch the dnstap utility, with this command: https://github.com/coredns/coredns/tree/master/plugin/dnstap#:~:text=%24-,dnstap%20%2Du%20/tmp/dnstap.sock,-The%20following%20command

Its not able to find it:
![image](https://user-images.githubusercontent.com/50544476/224173987-f612e4e0-962c-4af1-a4db-84b3966975d6.png)

**Comment by chrisohaver** [comment]
The way this works...

1) You need a dnstap server/listener running.  This is not part of CoreDNS. The dnstap server/listener creates a unix socket and listening on it when it starts. This part can be done with the dnstap utility mentioned in the docs, which is not part of coredns.
2) Configure coredns to write dnstap to the unix socket, using the dnstap plugin.
