### ISSUE TITLE
Question: Why is cache shardSize (shard count) hard-coded?

### ISSUE THREAD

**Issue by mlowery** [miekg/coredns#5988]
In looking at our metrics, it appeared that our cache was always full, using the default value of 10000. So the obvious option was to increase this value to increase cache hits. However, I was wondering if lock contention would become an issue since more items would fall into each shard and the lock is per shard. Is that a possibility? Are there benchmarks with higher cache sizes? Is a user-defined shard count a possibility?

**Comment by chrisohaver** [comment]
https://coredns.io/plugins/cache/#capacity-and-eviction

> I was wondering if lock contention would become an issue since more items would fall into each shard and the lock is per shard. Is that a possibility? 

I don't think lock contention would become an issue. Each shard is bigger, but the number of shards remains the same. And the query load remains the same.  So it's the same number of writes/reads into each shard.

I would expect contention to increase only with higher load, or smaller number of shards.

> Are there benchmarks with higher cache sizes? 

Not that I am aware of.

> Is a user-defined shard count a possibility?

Yes this is feasible, and IMO we should welcome adding this knob if it can be shown to significantly improve performance in scale tests.

**Comment by mlowery** [comment]
Ah I see what you're saying. Given no change to incoming queries, the attempted reads and writes to the cache are the same. Thanks!
