### ISSUE TITLE
Will many i/o timeout exceptions result in high memory?

### ISSUE THREAD

**Issue by LiamLea** [miekg/coredns#5992]
I want to know if memory usage will increase when there are many i/o timeouts.
If it does, what's the detail?

Why do i have the question?
In my k8s cluster, coredns restarts frequently and there are some unreachable dns server in the `/etc/resolve.conf` file. But the cluster has been destroyed so i can't get the log.
* We used the default the configuration of coredns and didn't many any change.
* My guess: 
  * many i/o timeout exceptions result in memory increation which hits the limit of memory so that k8s restart it.

**Comment by lobshunter** [comment]
There is a `metrics` [plugin](https://github.com/coredns/coredns/blob/master/plugin/metrics/README.md) that exports metrics of CoreDNS. You can use prometheus to scrape the metrics and visualize CoreDNS's memory usage.

Or do a quick check of OOM by running `kubectl get pod <coredns-pod> -o yaml`, then check the `.status.containerStatuses[].lastState`(see if terminated reason is `OOMKilled`).

**Comment by LiamLea** [comment]
Hi @lobshunter , I can't get these info because i can't get access to the cluster which has around 2000 pods and services. 
It will take some time to verify it in my own cluster.

I hope there's a quick answer if someone knows it.

**Comment by chrisohaver** [comment]
AFAIK this is not a known issue.

Agree with @lobshunter, first thing is to determine the cause of the coredns restarts.  Is it being OOM killed? Or are health checks failing?  Or is it crashing?

**Comment by LiamLea** [comment]
I have tested this in my cluster.Many i/o timeout exceptions have little effection on memory.
