### ISSUE TITLE
Confused about REFUSED handle in coredns

### ISSUE THREAD

**Issue by sologgfun** [miekg/coredns#5999]
My scenario is that multiple resolvers are configured in the "forward" setting, but only one can resolve the domain name "a". Sometimes when I access the domain name "a" in my pod, I get a REFUSED error, while it works fine when accessing from the host. However, I thought coredns would retry all resolvers, right?

After checking the source code of coredns-forward, I found that ServeDNS will retry resolvers within the timeout period. 

However, the article below suggests that it won't retry:
https://stackoverflow.com/questions/69709844/how-to-forward-request-to-next-resolver-if-name-not-resolved

What is the actual situation? I noticed that the coredns documentation says, "Any response that is not a network error (REFUSED, NOTIMPL, SERVFAIL, etc) is taken as a healthy upstream." Does this mean that REFUSED is not considered an error in coredns? However, I checked the RFC specification and found that REFUSED is indeed considered an error.

**Why do I still get a REFUSED error instead of a retry when I have a resolver that can resolve the domain name "a" in coredns? Can you please help me? Thank you!**

<img width="778" alt="image" src="https://user-images.githubusercontent.com/13819034/228710151-e626b381-7f40-4032-b196-8bd024b4f5b4.png">

**Comment by chrisohaver** [comment]
In a nutshell, _forward_ will only try another upstream if there is no response from the DNS application.  Note that any DNS protocol response is considered a response. A network error is not actually a response from the DNS application - it's a response from something  between the DNS application and the client application.

**Comment by sologgfun** [comment]
@chrisohaver 

First of all, thank you for your reply. However, if it is as you said, then even I set the upstream to resolv.conf, the results I resolve domain in the pod and on the node will be different, right?

For example, when the domain name "a" can only be resolved by the second resolver in resolv.conf, the pod will sometimes fail to resolve it according to the logic of coredns(random policy), but the node will default to try subsequent resolves when fail to resolve it. Am I correct?

If so, why not keep the retry logic of coredns consistent with the default retry logic of Linux? In my opinion, the logic in Linux has a higher success rate, right?

**Comment by chrisohaver** [comment]
> @chrisohaver
> 
> First of all, thank you for your reply. However, if it is as you said, then even I set the upstream to resolv.conf, the results I resolve domain in the pod and on the node will be different, right?
> 
> For example, when the domain name "a" can only be resolved by the second resolver in resolv.conf, the pod will sometimes fail to resolve it according to the logic of coredns(random policy), but the node will default to try subsequent resolves when fail to resolve it. Am I correct?

That is not how multiple dns servers in resolv.conf are supposed to be used.  This is documented in the resolv.conf man page, but not explicitly in detail.  It's a common misconception. 

A source of confusion: I think _nslookup_ specifically may behave differently in this regard than everything else. nslookup is its own thing, acting differently in various ways than other resolvers. This unfortunately results in some misconceptions about standard DNS client behavior.

**Comment by chrisohaver** [comment]
The following answer in superuser summarizes the intended use of resolv.conf well...

https://superuser.com/questions/1713723/multiple-domains-with-unique-dns-servers-in-resolv-conf

> The resolver library is designed on the assumption of a uniform DNS namespace. Multiple nameservers in /etc/resolv.conf are only used for redundancy in case some of them are unreachable or otherwise unavailable.
>
> Specifically, if the first consulted nameserver does not know a domain name it does not time out but return NXDOMAIN which means "this domain name does not exist." Consequently, the resolver will not contact the next nameserver in the list hoping for a different answer, but will accept that result and pass it on to the application which did the query.

**Comment by sologgfun** [comment]
@chrisohaver 
Thank you very much for your reply, it has been very helpful for me to understand the logic of this area!
