### ISSUE TITLE
log and cache and forward plugin make memory bug

### ISSUE THREAD

**Issue by snail2sky** [miekg/coredns#6002]
**What happened**:
When we specify to use the cache plug-in and forward plug-in  and log plug-in in the Corefile, there will be a serious bug. At this time, coredns is easy to be attacked, resulting in memory overflow, causing coredns to be oom

**What you expected to happen**:
Under normal circumstances, requests can be processed by consuming very little memory, but this is not the case. If the concurrency is high, the memory can be exhausted in 1 minute or even 30 seconds

**How to reproduce it (as minimally and precisely as possible)**:
```bash
# Corefile
cat Corefile
.:53 {
    cache
    forward . 8.8.8.8
    log
}

# record to query
cat dns-records.txt
google.com A

# run coredns in the background
./coredns

# Another tty, Stress queries on coredns
dnsperf -s 127.0.0.1 -d dns-records.txt -c 500 -l 120

# Another tty, Observe memory usage
watch -n1 free
```

**Anything else we need to know?**:
No

**Environment**:
Linux x86_64

- the version of CoreDNS: CoreDNS-1.10.1 linux/amd64, go1.20, 055b2c3
- Corefile: 
   ```Corefile
   .:53 {
    cache
    # forward . 8.8.8.8
    log
   }
   ```
- logs, if applicable: There are too many logs, and there are no exception logs
- OS (e.g: `cat /etc/os-release`): 
    ```cat /etc/os-release
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"

    CENTOS_MANTISBT_PROJECT="CentOS-7"
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"
    ```
- Others: None

**Comment by snail2sky** [comment]
@chrisohaver hi, This is a problem I found last week, and it can be reproduced stably. I don’t know if it’s a bug? will always result in a memory leak

**Comment by chrisohaver** [comment]
Can you provide more details/evidence there is a leak?

**Comment by chrisohaver** [comment]
Some thoughts:

_log_ is not a plugin that should be used lightly in production, since by default it logs every query responded to in text format. 

CoreDNS does not try to limit the load it processes. It will consume as many resources as it can to process the load thrown at it. The only limit is the system's resources (or container's resources when running in a container).

IIRC, dnsperf will try to seek the max QPS the dns server can handle by ramping up QPS rate until it starts to get timeouts. Those timeouts only happen once coredns has exhausted available resources. Note, this is not necessarily a leak.

There could be a memory leak but the evidence presented so far does not necessarily prove that.

**Comment by snail2sky** [comment]
Ok, I just found out that there is this problem, and throwing it out, it's enough for more experienced people to notice it, maybe a bug, maybe not~







                       
Original Email
                       
                     

Sender:"chrisohaver"< ***@***.*** &gt;;

Sent Time:2023/4/7 22:29

To:"coredns/coredns"< ***@***.*** &gt;;

Cc recipient:"snail"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [coredns/coredns] log and cache and forward plugin make memorybug (Issue #6002)




 
Some thoughts:
 
log is not a plugin that should be used lightly in production, since by default it logs every query responded to in text format.
 
CoreDNS does not try to limit the load it processes. It will consume as many resources as it can to process the load thrown at it. The only limit is the system's resources (or container's resources when running in a container).
 
IIRC, dnsperf will try to seek the max QPS the dns server can handle by ramping up QPS rate until it starts to get timeouts. Those timeouts only happen once coredns has exhausted available resources. Note, this is not necessarily a leak.
 
There could be a memory leak but the evidence presented so far does not necessarily prove that.
