### ISSUE TITLE
variable {/kubernetes/client-namespace} in kubernetes plugin

### ISSUE THREAD

**Issue by alexkayzer** [miekg/coredns#6025]
Hello! Why variable {/kubernetes/client-namespace} not working in kubernetes section?
```
        kubernetes cluster.local  in-addr.arpa ip6.arpa {
            pods verified
            namespaces kube-system default "{/kubernetes/client-namespace}"
            fallthrough in-addr.arpa ip6.arpa
        }
```
I need the service to be able to work with DNS in the current namespace but not beyond it. But the request immediately goes outside the cluster
P.S. in log section "{/kubernetes/client-namespace}" is available and not null

**Comment by chrisohaver** [comment]
The namespaces option in the kubernetes plugin does not accept metadata.

Additionally, the namespaces option just limits what the kubernetes plugin will answer. It doesn’t prevent other plugins from answering.

The view plugin can do what I think you want to do.
