### ISSUE TITLE
Even if kubernetes ttl is set to 1, it is set to 5s.

### ISSUE THREAD

**Issue by JoohyunOh** [miekg/coredns#6027]
Even though ttl is set to 0 or 1 in the configmap of coredns, it is set to 5s.

    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 1
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            policy sequential
        }
        cache 30 {
            denial 9984 5
        }
        loop
        reload
        loadbalance
    }

Why can't it be set below 5s?
Is there any way to set it up?

**Comment by chrisohaver** [comment]
The _cache_ plugin has a minimum TTL that it assigns to all records entering cache with a TTL less than that minimum.  See the cache plugin README for more detail. https://github.com/coredns/coredns/tree/master/plugin/cache

**Comment by johnbelamaric** [comment]
That said, you can turn off the cache for the cluster.local zone. The kubernetes plug-in answers from an in memory cache anyway so it will still be fast.

**Comment by chrisohaver** [comment]
> you can turn off the cache for the cluster.local zone

For those looking to do that, this option was added in 1.9.4.
