### ISSUE TITLE
Upgrade CoreDNS without downtime and without kubernetes

### ISSUE THREAD

**Issue by kokizzu** [miekg/coredns#6034]
So i write a plugins on CoreDNS, everytime i deploy new version, replace the binary then restart, there's around 10-30s of downtime, is it possible to make it without downtime?

normally if it's http or another protocol, there's reverse proxy (fabioLB for example) that we send signal to not route next request to backend that will be restarted until healthcheck is up again, or if it's single instance without reverse proxy, I'll just use jpillora/overseer Golang package.

Is there any way doing this for CoreDNS?

**Comment by kokizzu** [comment]
reading at the code there's already upgrade mechanism in coredns
seems just need to replace the binary, then send SIGUSR2 signal?

```
			case syscall.SIGUSR2:
				log.Println("[INFO] SIGUSR2: Upgrading")
				if err := Upgrade(); err != nil {
					log.Printf("[ERROR] SIGUSR2: upgrading: %v", err)
				}
```

code in coredns:
`/pkg/mod/github.com/coredns/caddy@v1.1.1/sigtrap_posix.go`

**Comment by kokizzu** [comment]
tested works
```
make
cat '.:1053 {
    log . {combined} {
       class all
    }
    debug
    whoami
}' > Corefile
./coredns
```
modify `whoami` plugin
```
make
ps aux | grep cordns # get the pid
kyz      1514204  0.0  0.0 764784 37632 pts/30   SNl+ 15:44   0:00 ./coredns
kill -s USR2 1514204
```
the log:
```
# before SIGUSR2
.:1053
CoreDNS-1.9.4
linux/amd64, go1.20.3, 81159d2f-dirty

# after SIGUSR2 
[INFO] SIGUSR2: Upgrading
[INFO] Upgrading
whoami Name called
whoami Name called
whoami Name called
.:1053
CoreDNS-1.9.4
linux/amd64, go1.20.3, 81159d2f-dirty
[INFO] Upgrade finished

# make sure new process up
kyz      1524156  0.0  0.0 764784 37888 pts/30   SNl  15:49   0:00 ./coredns
````

**Comment by chrisohaver** [comment]
Cool. This is an inherited feature from the caddy framework. I was unaware of it. Thanks for following up!

**Comment by cattyhouse** [comment]
@kokizzu nice findings. well, if coredns is started via systemd service configured with `Restart=always`, it will be restarted again by systemd after `USR2` `upgrade`. 

`journalctl -afu coredns` will see the pid got changed twice.
