### ISSUE TITLE
wildcard domain name except 

### ISSUE THREAD

**Issue by flylan** [miekg/coredns#6035]
I want to achieve the following effect：

a.example.com             =>                192.168.33.11
b.example.com             =>                192.168.33.12
*.example.com              =>                192.168.33.10

I want to achieve *. example.com to point to 192.168.33.10, but a.example.com and b.example.com point to other IPs. I realized *. example.com pan Domain Name System through the template plug-in, but I don't know how to achieve a.example.com or b.example.com A record resolution

I tried to implement it through the hosts plugin, but found that the parsing of a.example.com was captured by the template and did not enter the parsing of the hosts plugin at all

![image](https://user-images.githubusercontent.com/12097229/232727489-7dd1e9a9-cd35-4d2c-8757-90642e3c03dc.png)

I found a similar problem:https://github.com/coredns/coredns/issues/5204, but it did not solve my question

**Comment by flylan** [comment]
similar problem:https://github.com/coredns/coredns/issues/776,but it didn't solve my question either

**Comment by chrisohaver** [comment]
*template* is executed before the hosts plugin. Execution order of plugins is static, set at build time, and not controlled by the order defined in the configuration. 

The *file* plugin supports wildcard records. It executes after hosts.

If you’re set on using template, you can set it up in a separate server block listening on a separate port, and use the forward plugin to forward from the host server block to the template server block. This is less efficient because it involves an extra, albeit local, hop.

**Comment by flylan** [comment]
> _template_ is executed before the hosts plugin. Execution order of plugins is static, set at build time, and not controlled by the order defined in the configuration.
> 
> The _file_ plugin supports wildcard records. It executes after hosts.
> 
> If you’re set on using template, you can set it up in a separate server block listening on a separate port, and use the forward plugin to forward from the host server block to the template server block. This is less efficient because it involves an extra, albeit local, hop.

I now use the file plug-in to implement pan Domain Name System, but it seems that the file plug-in can not work with the forward plug-in, so that currently only *. example.com domain names can be resolved, and other domain names can not be resolved, such as www.github.com

Corefile：
```go
.:53 {
    bind 127.0.0.1
    file db.example.com
    forward . 8.8.8.8:53
    forward . 8.8.4.4:53
    errors
}
``` 

db.example.com：
```go
$ORIGIN example.com.
$TTL 86400
@	3600 IN	SOA example.com. rname.invalid. 2023041914 3600 60 1209600 3600

*	 IN A    192.168.33.10
a        IN A    192.168.33.11
b        IN A    192.168.33.12
``` 

Now it has been implemented：
```go
a.example.com => 192.168.33.11
b.example.com => 192.168.33.12
*.example.com => 192.168.33.10
``` 

But other public domain names cannot be resolved：
```go
www.github.com => unknow
www.google.com => unknow
...
``` 

Similar questions：https://github.com/coredns/coredns/issues/4444

**Comment by flylan** [comment]
~~I found the answer through chatgpt：~~
~~Corefile：~~

~~.:53 {~~
~~bind 127.0.0.1~~
~~forward . 8.8.8.8:53~~
~~forward . 8.8.4.4:53~~
~~}~~

~~example.com {~~
~~file db.example.com~~
~~}~~

**Comment by flylan** [comment]
> _template_ is executed before the hosts plugin. Execution order of plugins is static, set at build time, and not controlled by the order defined in the configuration.
> 
> The _file_ plugin supports wildcard records. It executes after hosts.
> 
> If you’re set on using template, you can set it up in a separate server block listening on a separate port, and use the forward plugin to forward from the host server block to the template server block. This is less efficient because it involves an extra, albeit local, hop.

~~My problem has been solved, thank you~~

**Comment by chrisohaver** [comment]
Also could be done in one server block if you specify the zone for file. 

FWIW, there is still a problem with the forward plugins. The second forward will never be used, since the first instance is for the same domain. Correct would be to put both upstreams in one forward instance:

`forward . 8.8.8.8 8.8.4.4`

**Comment by flylan** [comment]
> Also could be done in one server block if you specify the zone for file.
> 
> FWIW, there is still a problem with the forward plugins. The second forward will never be used, since the first instance is for the same domain. Correct would be to put both upstreams in one forward instance:
> 
> `forward . 8.8.8.8 8.8.4.4`

I found that the file plugin and forward plugin seem to be unable to coordinate their work，I also seem to have a problem with this configuration

![image](https://user-images.githubusercontent.com/12097229/233086915-be480d56-cc83-44d4-9500-7df47bd2c021.png)

The file plug-in can implement pan Domain Name System, and specify a specific domain name instead of pan Domain Name System. The file plug-in does not support fallthrough. I hope the forward plug-in can work with the file plug-in, but I don't know how to configure it

**Comment by chrisohaver** [comment]
If you really only want to listen on localhost, then you'll need to include the `bind` plugin in the `example.com` server block too (see https://coredns.io/plugins/bind/#bugs). If that isn't your intent, then remove it from the `.` server block.

... and your forward plugins are still misconfigured per earlier comment.

**Comment by flylan** [comment]
> If you really only want to listen on localhost, then you'll need to include the `bind` plugin in the `example.com` server block too (see https://coredns.io/plugins/bind/#bugs). If that isn't your intent, then remove it from the `.` server block.
> 
> ... and your forward plugins are still misconfigured per earlier comment.

Yes, my previous configuration was also wrong. I now use the file plug-in to implement universal Domain Name System and specific domain name A record pointing. But there is a problem with other public network Domain Name System. I found that the file plug-in and the forward plug-in do not work together

My latest configuration has been changed to this, but it still cannot achieve the expected effect
Corefile：
```go
.:53 {
    file db.example.com
    forward . 8.8.8.8 8.8.4.4
    errors
}
```

**Comment by flylan** [comment]
> If you really only want to listen on localhost, then you'll need to include the `bind` plugin in the `example.com` server block too (see https://coredns.io/plugins/bind/#bugs). If that isn't your intent, then remove it from the `.` server block.
> 
> ... and your forward plugins are still misconfigured per earlier comment.

Indeed, as you mentioned, my previous configuration was due to one adding a bind and the other not, resulting in unexpected results. Now, I have removed the bind plugin and it will work normally

Or perhaps this is the correct answer：

Corefile:
```go
.:53 {
    forward . 8.8.8.8 8.8.4.4
}

example.com {
    file db.example.com
}
``` 

db.example.com：
```go
$ORIGIN example.com.
$TTL 86400
@	3600 IN	SOA example.com. rname.invalid. 2023041914 3600 60 1209600 3600

*	 IN A    192.168.33.10
a        IN A    192.168.33.11
b        IN A    192.168.33.12
```
