### ISSUE TITLE
question about kubernetes plugin 

### ISSUE THREAD

**Issue by Laizl95** [miekg/coredns#6041]
I don't understand how to use  **pods**  parameter. In what scenario will this attribute be used. this domain 1-2-3-4.ns.pod.cluster.local means that the name of the pod is 1-2-3-4?

**Comment by chrisohaver** [comment]
> this domain 1-2-3-4.ns.pod.cluster.local means that the name of the pod is 1-2-3-4?

No, it means the Pod IP is 1.2.3.4... (in insecure mode, the pod may not actually exist)
The Pod name is not reflected in the `pod.cluster.local` subdomain

Here's the description from the docs...

>* `pods` **POD-MODE** sets the mode for handling IP-based pod A records, e.g.
>   `1-2-3-4.ns.pod.cluster.local. in A 1.2.3.4`.
>   This option is provided to facilitate use of SSL certs when connecting directly to pods. Valid
>   values for **POD-MODE**:
>
>   * `disabled`: Default. Do not process pod requests, always returning `NXDOMAIN`
>   * `insecure`: Always return an A record with IP from request (without checking k8s).  This option
>     is vulnerable to abuse if used maliciously in conjunction with wildcard SSL certs.  This
>     option is provided for backward compatibility with kube-dns.
>   * `verified`: Return an A record if there exists a pod in same namespace with matching IP.  This
>     option requires substantially more memory than in insecure mode, since it will maintain a watch
>     on all pods.

FWIW, the `pod.cluster.local.` subdomain has been deprecated in kubernetes for a very long time now (over 4 years?).
So, there really should not be anything that relies on this feature.  **Assuming that you have no services relying on this deprecated domain, you should be safe to disable it.**

Perhaps we should mark the `pods` option as deprecated.

**Comment by Laizl95** [comment]
> > this domain 1-2-3-4.ns.pod.cluster.local means that the name of the pod is 1-2-3-4?
> 
> No, it means the Pod IP is 1.2.3.4... (in insecure mode, the pod may not actually exist) The Pod name is not reflected in the `pod.cluster.local` subdomain
> 
> Here's the description from the docs...
> 
> > * `pods` **POD-MODE** sets the mode for handling IP-based pod A records, e.g.
> >   `1-2-3-4.ns.pod.cluster.local. in A 1.2.3.4`.
> >   This option is provided to facilitate use of SSL certs when connecting directly to pods. Valid
> >   values for **POD-MODE**:
> >   
> >   * `disabled`: Default. Do not process pod requests, always returning `NXDOMAIN`
> >   * `insecure`: Always return an A record with IP from request (without checking k8s).  This option
> >     is vulnerable to abuse if used maliciously in conjunction with wildcard SSL certs.  This
> >     option is provided for backward compatibility with kube-dns.
> >   * `verified`: Return an A record if there exists a pod in same namespace with matching IP.  This
> >     option requires substantially more memory than in insecure mode, since it will maintain a watch
> >     on all pods.
> 
> FWIW, the `pod.cluster.local.` subdomain has been deprecated in kubernetes for a very long time now (over 4 years?). So, there really should not be anything that relies on this feature. **Assuming that you have no services relying on this deprecated domain, you should be safe to disable it.**
> 
> Perhaps we should mark the `pods` option as deprecated.

### Thank you very much  for your answer
