### ISSUE TITLE
ETCD plugin : Issue when requesting subname when using RR

### ISSUE THREAD

**Issue by shamil2** [miekg/coredns#6055]
Hi,

I have currently in my etcd 3 inputs as per documentation 

```
KEY                                                  VALUES
/prefix/intern/site/machine/x1                       '{"host":"1.1.1.1","ttl":60}'
/prefix/intern/site/machine/submachine/x1            '{"host":"1.1.1.2","ttl":60}'
/prefix/intern/site/machine/submachine/x2.           '{"host":"1.1.1.3","ttl":60}'
```

I was expecting   :
dig +short machine.site.intern  to resolve to 1.1.1.1
but i got all 3 values

dig +short submachine.machine.site.intern  to resolve to 1.1.1.2 & 1.1.1.3 (OK)

If that is the case, how do i handle that we have can have "." in subdomains?

**Comment by chrisohaver** [comment]
This is the expected behavior of skydns, which is what the _etcd_ plugin implements.

**Comment by chrisohaver** [comment]
https://github.com/coredns/coredns/blob/master/plugin/etcd/README.md?plain=1#L9-L12

**Comment by shamil2** [comment]
You are right. I completely missed that point. Looking for another backend then
