### ISSUE TITLE
coredns pods are Running but not in Ready state

### ISSUE THREAD

**Issue by manaspal2** [miekg/coredns#6057]
**What happened**:
I have a system booted with CBL-Mariner. I installed a kubernetes cluster followed by deploying Flannel with kubectl. 

**What you expected to happen**:
I was expecting following pods to be READY and Running.

kube-flannel-ds-bh9vc                 
coredns-787d4945fb-jf7qv              
coredns-787d4945fb-qc6k6              
etcd-master-node                      
kube-apiserver-master-node            
kube-controller-manager-master-node   
kube-proxy-q69x9                      
kube-scheduler-master-node            

**How to reproduce it (as minimally and precisely as possible)**:

STEP 1: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=40.40.40.1 --cri-socket=unix:///var/run/containerd/containerd.sock --node-name=40.40.40.1
STEP 2:  mkdir -p $HOME/.kube
STEP 3:  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
STEP 4:  sudo chown $(id -u):$(id -g) $HOME/.kube/config
STEP 5:  kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

**Anything else we need to know?**:
Following are the logs and outputs captured:-

root@pf-cloud$ kubectl get pods --all-namespaces -o wide
NAMESPACE      NAME                                 READY   STATUS    RESTARTS   AGE     IP            NODE         NOMINATED NODE   READINESS GATES
kube-flannel   kube-flannel-ds-6n2qt                1/1     Running   0          4h41m   40.40.40.1    40.40.40.1   <none>           <none>
kube-system    coredns-787d4945fb-6z9lt             0/1     Running   0          4h22m   10.244.0.14   40.40.40.1   <none>           <none>
kube-system    coredns-787d4945fb-l5pwv             0/1     Running   0          4h22m   10.244.0.15   40.40.40.1   <none>           <none>
kube-system    etcd-40.40.40.1                      1/1     Running   35         4h46m   40.40.40.1    40.40.40.1   <none>           <none>
kube-system    kube-apiserver-40.40.40.1            1/1     Running   34         4h46m   40.40.40.1    40.40.40.1   <none>           <none>
kube-system    kube-controller-manager-40.40.40.1   1/1     Running   1          4h46m   40.40.40.1    40.40.40.1   <none>           <none>
kube-system    kube-proxy-ql8jd                     1/1     Running   0          4h46m   40.40.40.1    40.40.40.1   <none>           <none>
kube-system    kube-scheduler-40.40.40.1            1/1     Running   15         4h46m   40.40.40.1    40.40.40.1   <none>           <none>

root@pf-cloud$ kubectl logs pods/coredns-787d4945fb-6z9lt -n kube-system
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[INFO] plugin/kubernetes: waiting for Kubernetes API before starting server
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
.:53
[INFO] plugin/reload: Running configuration SHA512 = 591cf328cccc12bc490481273e738df59329c62c0b729d94e8b61db9961c2fa5f046dd37f1cf888b953814040d180f52594972691cd6ff41be96639138a43908
CoreDNS-1.9.3
linux/amd64, go1.18.2, 45b0a11
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[WARNING] plugin/kubernetes: Kubernetes API connection failure: Get "https://10.96.0.1:443/version": dial tcp 10.96.0.1:443: i/o timeout
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[WARNING] plugin/kubernetes: Kubernetes API connection failure: Get "https://10.96.0.1:443/version": dial tcp 10.96.0.1:443: i/o timeout

root@pf-cloud$ kubectl describe pods/coredns-787d4945fb-6z9lt -n kube-system
Name:                 coredns-787d4945fb-6z9lt
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Service Account:      coredns
Node:                 40.40.40.1/40.40.40.1
Start Time:           Fri, 28 Apr 2023 22:52:55 +0000
Labels:               k8s-app=kube-dns
                      pod-template-hash=787d4945fb
Annotations:          <none>
Status:               Running
IP:                   10.244.0.14
IPs:
  IP:           10.244.0.14
Controlled By:  ReplicaSet/coredns-787d4945fb
Containers:
  coredns:
    Container ID:  containerd://e173dfd514cc80f5368b6de08876d8d45c0ca17a88c1c69facf44a33106ed2bb
    Image:         registry.k8s.io/coredns/coredns:v1.9.3
    Image ID:      registry.k8s.io/coredns/coredns@sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Running
      Started:      Fri, 28 Apr 2023 22:52:56 +0000
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ccdnt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  kube-api-access-ccdnt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly op=Exists
                             node-role.kubernetes.io/control-plane:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  50s (x1803 over 4h25m)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 503

root@pf-cloud$ kubectl get svc -o wide
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE     SELECTOR
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   4h49m   <none>

root@pf-cloud$ kubectl get pods/coredns-787d4945fb-6z9lt -n kube-system -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-04-28T22:52:55Z"
  generateName: coredns-787d4945fb-
  labels:
    k8s-app: kube-dns
    pod-template-hash: 787d4945fb
  name: coredns-787d4945fb-6z9lt
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-787d4945fb
    uid: 47a81d1d-0e50-4c4d-a90e-0cd8aab8ee75
  resourceVersion: "2331"
  uid: 43013097-3745-43a5-8b91-c265b02cb535
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - kube-dns
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    image: registry.k8s.io/coredns/coredns:v1.9.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: coredns
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    - containerPort: 9153
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8181
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - all
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ccdnt
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: 40.40.40.1
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns
  serviceAccountName: coredns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: coredns
    name: config-volume
  - name: kube-api-access-ccdnt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-04-28T22:52:55Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-04-28T22:52:55Z"
    message: 'containers with unready status: [coredns]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-04-28T22:52:55Z"
    message: 'containers with unready status: [coredns]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-04-28T22:52:55Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e173dfd514cc80f5368b6de08876d8d45c0ca17a88c1c69facf44a33106ed2bb
    image: registry.k8s.io/coredns/coredns:v1.9.3
    imageID: registry.k8s.io/coredns/coredns@sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a
    lastState: {}
    name: coredns
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-04-28T22:52:56Z"
  hostIP: 40.40.40.1
  phase: Running
  podIP: 10.244.0.14
  podIPs:
  - ip: 10.244.0.14
  qosClass: Burstable
  startTime: "2023-04-28T22:52:55Z"
root@pf-cloud$ date
Sat Apr 29 03:23:50 UTC 2023

**Environment**:
Two node Kubernetes cluster - master and worker node.

- the version of CoreDNS: v1.9.3
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- root@pf-cloud$ cat /etc/os-release
NAME="Common Base Linux Mariner"
VERSION="2.0.20230407"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"

- Others:

**Comment by manaspal2** [comment]
Few things to add:-

I do not have firewall service enabled in the servers.

root@pf-cloud$ sudo firewall-cmd --state
sudo: firewall-cmd: command not found
root@pf-cloud$ sudo systemctl status firewalld
Unit firewalld.service could not be found.
root@pf-cloud$

kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-04-11T01:15:57Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4", GitCommit:"f89670c3aa4059d6999cb42e23ccb4f0b9a03979", GitTreeState:"clean", BuildDate:"2023-04-12T12:05:35Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by chrisohaver** [comment]
Is the api server healthy and accepting connections?

**Comment by manaspal2** [comment]
As per my observation, kubeapi server is working fine.

root@pf-cloud$ kubectl get service
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   85m
root@pf-cloud$ kubectl describe service
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.96.0.1
IPs:               10.96.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         40.40.40.1:6443
Session Affinity:  None
Events:            <none>

root@pf-cloud$ wget "https://10.96.0.1:443/version" --no-check-certificate
--2023-04-29 16:49:21--  https://10.96.0.1/version
Connecting to 10.96.0.1:443... connected.
WARNING: cannot verify 10.96.0.1's certificate, issued by 'CN=kubernetes':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 263 [application/json]
Saving to: 'version'

version                         100%[=======================================================>]     263  --.-KB/s    in 0s

2023-04-29 16:49:22 (44.5 MB/s) - 'version' saved [263/263]


I see even the kubeapi server log gets populated.

I0429 17:26:51.782737       1 trace.go:219] Trace[704132233]: "Get" accept:application/json, */*,audit-id:12500fbc-db63-4523-a437-42cdb5bb8f36,client:40.40.40.1,protocol:HTTP/2.0,resource:pods,scope:resource,url:/api/v1/namespaces/kube-system/pods/kube-apiserver-40.40.40.1/log,user-agent:kubectl/v1.26.3 (linux/amd64) kubernetes/9e64410,verb:GET (29-Apr-2023 17:25:26.534) (total time: 85247ms):
Trace[704132233]: ---"Writing http response done" 85244ms (17:26:51.782)
Trace[704132233]: [1m25.247740815s] [1m25.247740815s] END

But for Coredns connection attempt, i do not see any logs in kube-apiserver.

Any more pointer please.

**Comment by manaspal2** [comment]
> As per my observation, kubeapi server is working fine.
> 
> root@pf-cloud$ kubectl get service NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE kubernetes ClusterIP 10.96.0.1 443/TCP 85m root@pf-cloud$ kubectl describe service Name: kubernetes Namespace: default Labels: component=apiserver provider=kubernetes Annotations: Selector: Type: ClusterIP IP Family Policy: SingleStack IP Families: IPv4 IP: 10.96.0.1 IPs: 10.96.0.1 Port: https 443/TCP TargetPort: 6443/TCP Endpoints: 40.40.40.1:6443 Session Affinity: None Events:
> 
> root@pf-cloud$ wget "https://10.96.0.1:443/version" --no-check-certificate --2023-04-29 16:49:21-- https://10.96.0.1/version Connecting to 10.96.0.1:443... connected. WARNING: cannot verify 10.96.0.1's certificate, issued by 'CN=kubernetes': Unable to locally verify the issuer's authority. HTTP request sent, awaiting response... 200 OK Length: 263 [application/json] Saving to: 'version'
> 
> version 100%[=======================================================>] 263 --.-KB/s in 0s
> 
> 2023-04-29 16:49:22 (44.5 MB/s) - 'version' saved [263/263]
> 
> I see even the kubeapi server log gets populated.
> 
> I0429 17:26:51.782737 1 trace.go:219] Trace[704132233]: "Get" accept:application/json, _/_,audit-id:12500fbc-db63-4523-a437-42cdb5bb8f36,client:40.40.40.1,protocol:HTTP/2.0,resource:pods,scope:resource,url:/api/v1/namespaces/kube-system/pods/kube-apiserver-40.40.40.1/log,user-agent:kubectl/v1.26.3 (linux/amd64) kubernetes/9e64410,verb:GET (29-Apr-2023 17:25:26.534) (total time: 85247ms): Trace[704132233]: ---"Writing http response done" 85244ms (17:26:51.782) Trace[704132233]: [1m25.247740815s] [1m25.247740815s] END
> 
> But for Coredns connection attempt, i do not see any logs in kube-apiserver.
> 
> Any more pointer please.

As per my observation, kubeapi server is working fine.

root@pf-cloud$ kubectl get service
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
kubernetes ClusterIP 10.96.0.1 443/TCP 85m
root@pf-cloud$ kubectl describe service
Name: kubernetes
Namespace: default
Labels: component=apiserver
provider=kubernetes
Annotations:
Selector:
Type: ClusterIP
IP Family Policy: SingleStack
IP Families: IPv4
IP: 10.96.0.1
IPs: 10.96.0.1
Port: https 443/TCP
TargetPort: 6443/TCP
Endpoints: 40.40.40.1:6443
Session Affinity: None
Events:

root@pf-cloud$ wget "[https://10.96.0.1:443/version](https://10.96.0.1/version)" --no-check-certificate
--2023-04-29 16:49:21-- https://10.96.0.1/version
Connecting to 10.96.0.1:443... connected.
WARNING: cannot verify 10.96.0.1's certificate, issued by 'CN=kubernetes':
Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 263 [application/json]
Saving to: 'version'

version 100%[=======================================================>] 263 --.-KB/s in 0s

2023-04-29 16:49:22 (44.5 MB/s) - 'version' saved [263/263]

I see even the kubeapi server log gets populated.

I0429 17:26:51.782737 1 trace.go:219] Trace[704132233]: "Get" accept:application/json, /,audit-id:12500fbc-db63-4523-a437-42cdb5bb8f36,client:40.40.40.1,protocol:HTTP/2.0,resource:pods,scope:resource,url:/api/v1/namespaces/kube-system/pods/kube-apiserver-40.40.40.1/log,user-agent:kubectl/v1.26.3 (linux/amd64) kubernetes/9e64410,verb:GET (29-Apr-2023 17:25:26.534) (total time: 85247ms):
Trace[704132233]: ---"Writing http response done" 85244ms (17:26:51.782)
Trace[704132233]: [1m25.247740815s] [1m25.247740815s] END

But for Coredns connection attempt, i do not see any logs in kube-apiserver.

Any more pointer please.

**Comment by manaspal2** [comment]
> Is the api server healthy and accepting connections?

As per my observation, kubeapi server is working fine.

root@pf-cloud$ kubectl get service
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
kubernetes ClusterIP 10.96.0.1 443/TCP 85m
root@pf-cloud$ kubectl describe service
Name: kubernetes
Namespace: default
Labels: component=apiserver
provider=kubernetes
Annotations:
Selector:
Type: ClusterIP
IP Family Policy: SingleStack
IP Families: IPv4
IP: 10.96.0.1
IPs: 10.96.0.1
Port: https 443/TCP
TargetPort: 6443/TCP
Endpoints: 40.40.40.1:6443
Session Affinity: None
Events:

root@pf-cloud$ wget "[https://10.96.0.1:443/version](https://10.96.0.1/version)" --no-check-certificate
--2023-04-29 16:49:21-- https://10.96.0.1/version
Connecting to 10.96.0.1:443... connected.
WARNING: cannot verify 10.96.0.1's certificate, issued by 'CN=kubernetes':
Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 263 [application/json]
Saving to: 'version'

version 100%[=======================================================>] 263 --.-KB/s in 0s

2023-04-29 16:49:22 (44.5 MB/s) - 'version' saved [263/263]

I see even the kubeapi server log gets populated.

I0429 17:26:51.782737 1 trace.go:219] Trace[704132233]: "Get" accept:application/json, /,audit-id:12500fbc-db63-4523-a437-42cdb5bb8f36,client:40.40.40.1,protocol:HTTP/2.0,resource:pods,scope:resource,url:/api/v1/namespaces/kube-system/pods/kube-apiserver-40.40.40.1/log,user-agent:kubectl/v1.26.3 (linux/amd64) kubernetes/9e64410,verb:GET (29-Apr-2023 17:25:26.534) (total time: 85247ms):
Trace[704132233]: ---"Writing http response done" 85244ms (17:26:51.782)
Trace[704132233]: [1m25.247740815s] [1m25.247740815s] END

But for Coredns connection attempt, i do not see any logs in kube-apiserver.

Any more pointer please.

**Comment by chrisohaver** [comment]
> As per my observation, kubeapi server is working fine.

Can you reach kubeapi from a _Pod_?

**Comment by hitsub2** [comment]
> > As per my observation, kubeapi server is working fine.
> 
> Can you reach kubeapi from a _Pod_?

Why does this matters? We have encountered the same error.

**Comment by lvtujingji** [comment]
Why does this matters? We have encountered the same error.
