### ISSUE TITLE
Is coredns misconfigured in the kubespray v2.21.0? The service always times out, but node ips from the service work fine.

### ISSUE THREAD

**Issue by brujoand** [miekg/coredns#6076]
I realise that this problem might be in kubespray, calico, coredns or me, so I've added this as a question rather than a bug. 

I've deployed k8s 1.25.6 with kubespray v2.21.0, using calico, coredns and nodelocaldns. The coredns config is this:

```
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          prefer_udp
          max_concurrent 1000
        }
        cache 30

        loop
        reload
        loadbalance
    }
```
For the record the host `/etc/resolv.conf` is identical on all nodes, and contain my network dns and the nodelocaldns address as nameservers like so:

```
nameserver 169.254.25.10
nameserver 10.30.1.1
search fet
```

The running version is CoreDNS-1.9.3. I first noticed that in all my nodelocaldns pods there were errors like these:
```
2023/05/05 09:56:06 [INFO] Starting node-cache image: 1.21.1
2023/05/05 09:56:06 [INFO] Using Corefile /etc/coredns/Corefile
2023/05/05 09:56:06 [INFO] Using Pidfile
2023/05/05 09:56:07 [ERROR] Failed to read node-cache coreFile /etc/coredns/Corefile.base - open /etc/coredns/Corefile.base: no such file or directory
2023/05/05 09:56:07 [INFO] Skipping kube-dns configmap sync as no directory was specified
2023/05/05 09:56:07 [INFO] Added interface - nodelocaldns
cluster.local.:53 on 169.254.25.10
in-addr.arpa.:53 on 169.254.25.10
ip6.arpa.:53 on 169.254.25.10
.:53 on 169.254.25.10
[INFO] plugin/reload: Running configuration MD5 = 5bc9ac48f7ba58018ec5b8fd787058a9
CoreDNS-1.7.0
linux/amd64, go1.16.8,
[INFO] Added back nodelocaldns rule - {raw PREROUTING [-p tcp -d 169.254.25.10 --dport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw PREROUTING [-p udp -d 169.254.25.10 --dport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {filter INPUT [-p tcp -d 169.254.25.10 --dport 53 -j ACCEPT]}
[INFO] Added back nodelocaldns rule - {filter INPUT [-p udp -d 169.254.25.10 --dport 53 -j ACCEPT]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p tcp -s 169.254.25.10 --sport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p udp -s 169.254.25.10 --sport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {filter OUTPUT [-p tcp -s 169.254.25.10 --sport 53 -j ACCEPT]}
[INFO] Added back nodelocaldns rule - {filter OUTPUT [-p udp -s 169.254.25.10 --sport 53 -j ACCEPT]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p tcp -d 169.254.25.10 --dport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p udp -d 169.254.25.10 --dport 53 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p tcp -d 169.254.25.10 --dport 8080 -j NOTRACK]}
[INFO] Added back nodelocaldns rule - {raw OUTPUT [-p tcp -s 169.254.25.10 --sport 8080 -j NOTRACK]}
[ERROR] plugin/errors: 2 netchecker-service.default.svc.cluster.local. AAAA: dial tcp 10.133.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 netchecker-service.default.svc.cluster.local. A: dial tcp 10.133.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 netchecker-service.default.svc.cluster.local. AAAA: dial tcp 10.133.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 netchecker-service.default.svc.cluster.local. A: dial tcp 10.133.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 netchecker-service.default.svc.cluster.local. AAAA: dial tcp 10.133.0.3:53: i/o timeout
[ERROR] plugin/errors: 2 netchecker-service.default.svc.cluster.local. A: dial tcp 10.133.0.3:53: i/o timeout
... this goes on forever....
```

If I ask all my nodes to query a cluster dns record using the coredns pods ip, I always get the correct repsonse.
If I ask all my nodes to query a cluster dns record using the coredns service ip, only one of them get the correct response. (The rest get a timeout)
If I ask all my nodes to query a cluster dns record using the nodelocaldns ip, I always get the correct response.

I've also deployed the netchecker app, which can be accessed on localhost by all nodes, except one. Well it does actually return a result, but it takes 1 minute. All replies say that a single pod netchecker-agent-hostnet is failing, and it's running on the same host which uses 1 minute to respond to the command curl http://localhost:31081/api/v1/connectivity_check | jq '.'
1 minute and 5 seconds to be exact. Every single time. Which is really interesting, but I'm not sure where to look for this odd 1 minute timeout.

The failing netcheker:
```
E0505 11:40:45.801310       1 agent.go:135] DNS look up host error. Details: lookup netchecker-service on 169.254.25.10:53: no such host
I0505 11:40:45.801829       1 agent.go:114] Send payload via URL: http://netchecker-service:8081/api/v1/agents/netchecker-agent-hostnet-rnntp
E0505 11:40:59.802109       1 agent.go:306] Error while sending info. Details: Post http://netchecker-service:8081/api/v1/agents/netchecker-agent-hostnet-rnntp: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
I0505 11:40:59.802168       1 agent.go:301] Sleep for 15 second(s)
E0505 11:41:13.802609       1 agent.go:199] Get http://netchecker-service:8081/api/v1/ping: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

The funny thing is that I tried asking all the netchecker pods to lookup the `netchecker-service`. It took some time, but they alle managed it:
```
for pod in $(kgp | grep agent | cut -d ' ' -f 1); do echo "$pod:"; ke "$pod" -- nslookup netchecker-service.default.svc.cluster.local; done
netchecker-agent-8rwdr:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202 netchecker-service.default.svc.cluster.local

netchecker-agent-d4qhc:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202 netchecker-service.default.svc.cluster.local

netchecker-agent-hostnet-fc948:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202 netchecker-service.default.svc.cluster.local

netchecker-agent-hostnet-jdd85:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202 netchecker-service.default.svc.cluster.local

netchecker-agent-hostnet-kwmwl:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202 netchecker-service.default.svc.cluster.local

netchecker-agent-hostnet-nxgjc:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202 netchecker-service.default.svc.cluster.local

netchecker-agent-hostnet-rnntp:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202

netchecker-agent-pcrgp:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202 netchecker-service.default.svc.cluster.local

netchecker-agent-vjthk:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202 netchecker-service.default.svc.cluster.local

netchecker-agent-vjv2x:
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202 netchecker-service.default.svc.cluster.local
```
I'm so confused right now. Does anyone have any tips on debugging this?

**Comment by brujoand** [comment]
The netchecker pod `netchecker-agent-hostnet-rnntp` is the one reported to be failing, as it's output is also slightly different. 

```
Server:    169.254.25.10
Address 1: 169.254.25.10

Name:      netchecker-service.default.svc.cluster.local
Address 1: 10.133.53.202
```

But I'm not familiar enough with nslookup to say what that difference means.

**Comment by brujoand** [comment]
If I run a debug pod for a nodelocaldns pod:

`kubectl debug nodelocaldns-gm5bf --image ubuntu -it bash`

```
# dig +short netchecker-service.default.svc.cluster.local @10.133.0.3
;; communications error to 10.133.0.3#53: timed out
;; communications error to 10.133.0.3#53: timed out
;; communications error to 10.133.0.3#53: timed out
;; no servers could be reached

# dig +short netchecker-service.default.svc.cluster.local @169.254.25.10
10.133.53.202
```

So I'm honestly baffeled as to how the nodelocaldns pods have any dns information at all since the only name servers it has is my network DNS and 10.133.0.3 which I can't reach. 

Edit: oooh, but if I query over tcp from the nodelocaldns debug pod:

```
# dig +tcp +short netchecker-service.default.svc.cluster.local @10.133.0.3
10.133.53.202
```

**Comment by brujoand** [comment]
This just feels like an endless rabbit hole. All my nodes fail to query 10.133.0.3 over UDP, but all but one can do it over TCP. The last one times out.

Sorry for the wall of text. I'll try to get some food and restore some faith in technology.

**Comment by chrisohaver** [comment]
> For the record the host /etc/resolv.conf is identical on all nodes, and contain my network dns **and the nodelocaldns address** as nameservers like so:

This is problematic. Nodelocaldns sends non-cluster domain queries to the upstream servers listed in `/etc/resolv.conf`.  If one of those servers is the nodelocaldns address itself, then you've created a partial forwarding loop, where nodelocaldns has a 50% chance of forwarding any non-cluster domain query to itself.

**Comment by brujoand** [comment]
Right that makes sense and a loop here sounds bad. So I went ahead and replaced the symlink to the systemd generated resolv.conf which was currently inplace for all my nodes and instead created an new file without the nodelocaldns nameserver listing. 

The thing though is that after changeing this, restarting coredns pods and nodelocaldns pods they both still have the nodelocaldns listed as one of two nameservers. 

ahh, that is coming from the kubelet-config:
`resolvConf: /run/systemd/resolve/resolv.conf`

No idea why 169.254.25.10 is being added by systemd though. 

But even after updating the kublet-config, restarting the kubelet service, the coredns pods and nodelocaldns pods they all have 169.254.25.10 as a second nameserver. And the nodelocaldns pods are still logging the timeout errors.

**Comment by chrisohaver** [comment]
Possibly related to this...

https://github.com/kubernetes-sigs/kubespray/issues/9948

... looks like kube-spray defaults to creating a forwarding loop?

**Comment by brujoand** [comment]
Good call. Just found this in one of the nodelocaldns logs:
`[FATAL] plugin/loop: Loop (10.133.64.71:35692 -> 169.254.25.10:53) detected for zone "in-addr.arpa.", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 1956073987928419037.1871532948686855462.in-addr.arpa."`

Haven't noticed it before.

**Comment by chrisohaver** [comment]
> But even after updating the kublet-config, restarting the kubelet service, the coredns pods and nodelocaldns pods they all have 169.254.25.10 as a second nameserver. And the nodelocaldns pods are still logging the timeout errors.

coredns and nodelocaldns pods need to be restarted to re-read the updated resolv.conf. 

... or maybe you did already - depends on how you parse that sentence. If you did - maybe systemd-resolved is restoring the link?

**Comment by brujoand** [comment]
Yeah I did a restart of both coredns and nodelocaldns pods after restarting the kubelet. And I just verified that the /etc/resolv.conf has not been changed since I updated it. But running `systemd-resolve --status` on a master node gives:

```
Global
           Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: foreign
         DNS Servers: 169.254.25.10
Fallback DNS Servers: 10.30.1.1
```

So somehow, both my network DNS and the nodelocaldns are "loaded" eventhough the nodelocaldns is not listed in /etc/resolve.conf anymore. This is even after a reboot of the master node. 

But I did found this: https://unix.stackexchange.com/questions/515154/how-do-you-remove-bad-dns-server-ips-from-systemd-resolved
Which showed me how to add my Network DNS server, and led me to find `/etc/systemd/resolved.conf` which for some reason had the nodelocaldns ip set as main DNS. Removing that, and reloading systemd-resolved finally gave my nodelocaldns pods the correct /etc/resolve.conf. 

However, nodelocaldns pods are still logging the errors on timeouts reaching 10.133.0.3:53. xD

**Comment by chrisohaver** [comment]
10.133.0.3 would be coredns's service address.  So something is wrong with the networking setup (calico or kubeproxy?).  Unfortunately, I don't have experience with kube-spray, so I don't know how it tries to set things up.

**Comment by brujoand** [comment]
Yeah it's the service address. I'm using calico, but I actually also deployed a cluster with cilium to see if the error was still there, and it was. 

But I just checked the kubelet logs, and found this:

`kubelet[105902]: E0504 11:15:28.543564  105902 kubelet.go:2373] "Container runtime network notready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"` 

which I guess is a good indicator that you're right about something being wrong with the network setup.  And looks like the calico kube-controller agrees: 

```
2023-05-05 02:04:34.508 [INFO][1] ipam_allocation.go 175: Candidate IP leak handle="k8s-pod-network.8ab0cdee3be7c903e6afa5e1775fa2ebe851c91f6306430f16a039b94b4c5748" ip="10.133.112.46" node="tindbox.fet" pod="automation/home-assistant-5f5fcd846-jxm5b"
...
2023-05-05 14:12:16.711 [ERROR][1] client.go 290: Error getting cluster information config ClusterInformation="default" error=Get "https://10.133.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
2023-05-05 14:12:16.712 [ERROR][1] main.go 275: Failed to verify datastore error=Get "https://10.133.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
2023-05-05 14:12:20.714 [ERROR][1] main.go 293: Received bad status code from apiserver error=Get "https://10.133.0.1:443/healthz": context deadline exceeded status=0
2023-05-05 14:12:20.722 [INFO][1] main.go 309: Health check is not ready, retrying in 2 seconds with new timeout: 8s
2023-05-05 14:12:30.730 [ERROR][1] client.go 290: Error getting cluster information config ClusterInformation="default" error=Get "https://10.133.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
2023-05-05 14:12:30.730 [ERROR][1] main.go 275: Failed to verify datastore error=Get "https://10.133.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
2023-05-05 14:12:38.733 [ERROR][1] main.go 293: Received bad status code from apiserver error=Get "https://10.133.0.1:443/healthz": context deadline exceeded status=0
```

So I guess this is definitely not something I can blame on coredns then.

**Comment by brujoand** [comment]
Okay, so it turns out that calico and nodelocaldns will compete for iptables configuration, and calico eventually always wins. I've made a change to the  FelixConfiguration adding a `chainInsertMode: Append` and now the iptable rules from nodelocaldns seems to stick around. I can access the coredns service from all nodes so all should be well. But still, there just as many timouts. And it seems to me that what's happening is that the coreos pod is taking longer than 2 seconds to reply the first time it sees a domain query. I tested this myself and most non-cached domains timeout after 2 seconds, but succeeded if I set the timeout to 5 seconds. Any pointers on digging further into that would be great.

**Comment by brujoand** [comment]
So I started googling for this 1m timeout. Came across this: https://github.com/projectcalico/calico/issues/3145
Turns out that the fix is nothing but `sudo ethtool --offload vxlan.calico rx off tx off`. And boom. Problem is completely and instantly gone.
