### ISSUE TITLE
Support extra data in dnstap payload

### ISSUE THREAD

**Issue by swapmat** [miekg/coredns#6092]
**What would you like to be added**:

dnstap supports sending `extra` bytes in the payload. This is defined in the [dnstap.proto](https://github.com/dnstap/dnstap.pb/blob/master/dnstap.proto#L40)
However, the dnstap plugin and forward plugin which uses dnstap do not allow sending this extra field. Hence, this enhancement request to update the dnstap plugin to support sending the extra bytes.

There is no limit to the size of the `extra` but we can cap it based on a config.

**Why is this needed**:

We have a use-case where we want to add some extra meta-data/context in the dns log to be sent to the dnstap receiver.

**Comment by Tantalor93** [comment]
Hello, can you more describe your use case? What would you like to see in the extra section?

**Comment by chrisohaver** [comment]
IIUC, the use case is to add the dnstap `extra` field to the dnstap message, set to a CoreDNS metadata value that the user would define in the Corefile.  e.g. configured via an option like `extra METADATA`, where METADATA defines a CoreDNS metadata value.

**Comment by Tantalor93** [comment]
so if I understand correctly, something like this
```
.:53 {
	dnstap /tmp/dnstap.sock {
  		identity my-dns-server1
  		version MyDNSServer-1.2.3
		extra forward/upstream
	}
	forward . 8.8.8.8
}
```
would add to dnstap `extra` field a value of `forward/upstream` [metadata](https://github.com/coredns/coredns/tree/master/plugin/forward#metadata) from forward plugin?

**Comment by chrisohaver** [comment]
yes.  metadata plugin also required ... e.g. 

```
.:53 {
        metadata
	dnstap /tmp/dnstap.sock {
  		identity my-dns-server1
  		version MyDNSServer-1.2.3
		extra forward/upstream
	}
	forward . 8.8.8.8
}
```

**Comment by Tantalor93** [comment]
ok, makes sense! 👍

**Comment by Nitesh639** [comment]
@Tantalor93, can I work on this issue?

**Comment by chrisohaver** [comment]
I think this would be a good first issue since it doesn't require deep DNS protocol knowledge.

**Comment by Nitesh639** [comment]
@chrisohaver Thank you for suggesting this issue as a good first task. I'm new to the organization and excited to contribute. I agree that it's a great choice since it doesn't require deep DNS protocol knowledge. I want to start working on it.

**Comment by Tantalor93** [comment]
@Nitesh639 sure, go ahead 👍

**Comment by chenyuheng** [comment]
Looks like no further update for a couple of months, I'd like to contribute, can I have a try to solve this issue?
