### ISSUE TITLE
coredns log panic

### ISSUE THREAD

**Issue by hiddletian** [miekg/coredns#6109]
version: 1.6.7
Occasionally, there may be panic messages in coredns, but there is no abnormal feedback from the business. What may be the reason for this?

**Comment by chrisohaver** [comment]
Perhaps it's a bug that has been fixed in the 3 years since 1.6.7 was released.  You could try a more recent version to see if the problems go away.

If you want more help, you need to provide more information than this.  logs, stack trace, and corefile (configuration).

**Comment by hiddletian** [comment]
I would like to know if this bug affects the business?When is this bug usually triggered

**Comment by Tantalor93** [comment]
please provide additional info describing the issue, otherwise we cannot help you
