### ISSUE TITLE
[BUG] DNS resolution of external names fails sporadically with CoreDNS

### ISSUE THREAD

**Issue by wzrdtales** [miekg/coredns#6114]
**Describe the bug**

We're facing this bug for more than 2 years now, but didn't come to report it yet, due to it being very hard to track down and until today we have not yet found a reason why this is happening.

So what is going on?

Sporadically pods will have problems resolving external DNS names such as github.com. With external I mean names that are not from the kubernetes cluster, but from the public internet. This error only occurs for this exact DNS request and afterwards on the same node, same pod, same DNS name will resolve on the next DNS resolve. This is causing problems all over in different things, leading to crashes if programs can't handle it, or retries.

How do we know this is CoreDNS's "fault"?

Simple: Whenever we convert a cluster back to kubedns, the problem disappears completely.
Do we have any special setup? No, RKE1 default coredns setup.

Is this a provider specific problem? No, we had this problem occurring in all our clusters, on literally by now every provider that exists. Everytime the same pattern.

**To Reproduce**

Use CoreDNS and try to resolve external DNS names such as github.com continuously, some request will fail with could not resolve host sporadically.

Let me know what I could do to get meaningful logs or information to track down this bug. CoreDNS wasn't actually logging any problems at all. 

**Rancher Server Setup**
- Rancher version: since CoreDNS was introduced, now v2.6.12
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, calico network
- Proxy/Cert Details: NOne

**Information about the Cluster**
- Kubernetes version: 1.24, but affects all other versions as well
- Cluster Type (Local/Downstream): Downstream, happens with all providers, tested: AWS, Azure, OVH, WX-One, Linode, DO, GCP
- CoreDNS version rancher deploys currently is: 1.9.3

Rancher RKE1 generates this default config for coredns with which this is occurring:

```
 .:53 {
    errors
    health {
      lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . "/etc/resolv.conf"
    cache 30
    loop
    reload
    loadbalance
} # STUBDOMAINS - Rancher specific change
```

Also posted here: https://github.com/rancher/rancher/issues/41658

**Comment by Tantalor93** [comment]
Hello, could you enable [log](https://coredns.io/plugins/log/) plugin in Corefile and reproduce the issue and collect the logs? So we can check that CoreDNS handles those problematic queries? 

Otherwise have you checked the CoreDNS [forward](https://coredns.io/plugins/forward/#metrics) plugin metrics? Were there any anomalies there? 

Does CoreDNS instances in your cluster have enough resources? Isnt CoreDNS subject to CPU throttling?

How does your /etc/resolv.conf look like?
