### ISSUE TITLE
Wrong file suffix: plugins/kubernetes/metrics_test.backup 

### ISSUE THREAD

**Issue by mrueg** [miekg/coredns#6117]
**What happened**:
It looks like this file got moved by accident in https://github.com/coredns/coredns/commit/9121e784966d52bb93696d83d9ab394ac2efd77d#diff-78f1878318474b70c57617551a2a68162a32f4e2206c4cc0d34642d055fc7332
https://github.com/coredns/coredns/blob/master/plugin/kubernetes/metrics_test.backup
**What you expected to happen**:
It should probably be 
https://github.com/coredns/coredns/blob/master/plugin/kubernetes/metrics_test.go
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Tests currently fail, so renaming is not enough

```
=== RUN   TestDNSProgrammingLatencyEndpointSlices
    metrics_test.go:183: unexpected object &EndpointSlice{ObjectMeta:{my-service-12345  testns    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[kubernetes.io/service-name:my-service] map[endpoints.kubernetes.io/last-change-trigger-time:2023-05-25T22:52:51.414480598+02:00] [] [] []},Endpoints:[]Endpoint{Endpoint{Addresses:[1.2.3.4],Conditions:EndpointConditions{Ready:nil,Serving:nil,Terminating:nil,},Hostname:nil,TargetRef:nil,Topology:map[string]string{},NodeName:nil,Hints:nil,},},Ports:[]EndpointPort{},AddressType:,}
```
**Environment**:

- the version of CoreDNS: master
- Corefile: -
- logs, if applicable: -
- OS (e.g: `cat /etc/os-release`): -
- Others: -

**Comment by mrueg** [comment]
@chrisohaver FYI

**Comment by chrisohaver** [comment]
> It looks like this file got moved by accident

Per the commit comment, the tests were disabled per review feedback.  The reviewer didn't want the tests to exist in coredns/coredns repo.

**Comment by mrueg** [comment]
@chrisohaver ah understood. I misread the "removed" in the commit message differently (not moved to a backup file). Closing then! thanks for clarifying!
