### ISSUE TITLE
Breaking change with DNS version upgrade

### ISSUE THREAD

**Issue by chasewilson** [miekg/coredns#6122]
**What happened**:
After upgrading [dns from 1.1.49 -> 1.1.50](https://github.com/coredns/coredns/pull/6082), domain names starting with "." no longer work. This is an unannounced breaking change and needs to be reverted to ensure readiness. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.1.50
- Corefile: 
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others: [go.mod](https://github.com/coredns/coredns/blob/90c1e7b70fcb1069c110e705d299fde6ed82a2ee/go.mod)

**Comment by chrisohaver** [comment]
OK, we haven't released yet.  But I recall (perhaps incorrectly) that server block domains with a leading dot were always invalid (only exception being the root domain `.` ).

**Comment by chrisohaver** [comment]
Next release is slated to be 1.11.0, minor version bump, so we could include this change, and document it in the release notes.

I see a "improve isFQDN" commit in the change notes - I presume this is where the change is?  If so, it applies more broadly than server block domains.  But in what contexts is a FQDN with a leading dot valid, and going to produce meaningful behavior?

**Comment by chrisohaver** [comment]
> server block domains with a leading dot were always invalid

Vaguely recall that coredns would actually run the server, but then never serve any queries for that domain, because it interpreted the first dot as part of the first label - or something like that. Incoming queries would never match it.

**Comment by chrisohaver** [comment]
I don't think this needs to be reverted.  The new(ish) behavior (exiting when a domain is invalid) is preferable to the previous behavior (more or less ignoring the server block with the invalid domain silently).
