### ISSUE TITLE
CoreDNS hosts entry not working

### ISSUE THREAD

**Issue by akshaysgithub** [miekg/coredns#6134]
Hello,

On GKE, I have installed CoreDNS as a helm-chart, and overall it's working fine, other than the hosts entry. For hosts-entry I am adding a private-IP address, but it's not working, I keep getting a public-IP address for the same. Also, if I remove fallthrough, the chain fails and resolution to that domain stops working. 

Is the hosts plugin not enabled when using helm-chart for installation or does the hosts plugin needs to be installed separately? What am I doing wrong? 

Corefile: 

`
Data
====
Corefile:
----
.:53 {
    errors
    health {
        lameduck 5s
    }
    ready
    hosts {
        10.64.84.60 private-domain-name.com
        ttl 300
        reload 1m
        fallthrough
    }
    kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    }
    prometheus 0.0.0.0:9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}

`

Installation:

`
resource "helm_release" "coredns" {
  name       = "coredns"
  namespace  = "kube-system"
  repository = "https://coredns.github.io/helm"
  chart      = "coredns"
  version    = var.coredns_helm_chart_pinned_version
  timeout    = 300

  values = [
    try(file("${path.root}/files/coredns/coredns-${trim(replace(terraform.workspace, "helm", ""), "-")}.yaml"), tostring(""))
  ]
}
`
Thanks a lot.

**Comment by Tantalor93** [comment]
hello, and what domain are you trying to resolve? Can you give an example using dig command, which reproduces the issue?

also you can enable the[log](https://coredns.io/plugins/log/)  plugin in CoreDNS and reproduce the issue and share the log?

**Comment by chrisohaver** [comment]
And do you have node local dns cache deployed. If so, you need to put external domains hosts plugin configurations in the node local dns cache configmap.
