### ISSUE TITLE
forward plugin metrics renamed

### ISSUE THREAD

**Issue by Tantalor93** [miekg/coredns#6160]
As part of https://github.com/coredns/coredns/pull/5951 most of the forward plugin metrics were moved under different namespace (`forward` =>`proxy`), which caused that those metrics are renamed. This change is not backward compatible and is quite dangerous without proper announcement

also the documentation is no longer true https://github.com/coredns/coredns/tree/master/plugin/forward#metrics

for example `coredns_forward_healthcheck_failures_total` => `coredns_proxy_healthcheck_failures_total`

I think it would be safest to revert the mentioned PR, WDYT @chrisohaver

**Comment by chrisohaver** [comment]
Why not fix the namespace. 

(Ie change the namespace back to forward instead of proxy, instead of reverting the entire PR)

**Comment by chrisohaver** [comment]
@patdowney, FYI

**Comment by Tantalor93** [comment]
> Why not fix the namespace.
> 
> (Ie change the namespace back to forward instead of proxy, instead of reverting the entire PR)

that would work as well 🙂

**Comment by patdowney** [comment]
Thanks @chrisohaver - sorry @Tantalor93 - let me take a look

**Comment by patdowney** [comment]
There's some conversation going on on #6178 that is leaning towards removing the duplicate metrics and documenting the changes as breaking. The `README.md` is being updated appropriately. Might need to rename the PR!
