### ISSUE TITLE
How to expose coredns on WSL to local network?

### ISSUE THREAD

**Issue by LeenHawk** [miekg/coredns#6167]
I'm trying to install coredns in WSL and expose it to my home network. I have expose 53,80,443 to local network and 80 and 443 can work, but `nslookup example.com 192.168.1.102` can't work in windows. How could I expose coredns on WSL to local network?

There is my whole effort:
```shell
wget https://github.com/coredns/coredns/releases/download/v1.10.1/coredns_1.10.1_linux_amd64.tgz
tar xf coredns_1.10.1_linux_amd64.tgz
mv coredns /usr/local/bin/

useradd coredns -s /sbin/nologin

mkdir -p /data/coredns
mkdir /etc/coredns

cat > /etc/coredns/Corefile << EOF
.:53 {
  bind 0.0.0.0
  hosts {
    example.com 192.168.1.102
    #hangup
    ttl 60
    reload 1m
    fallthrough
  }
  forward . /etc/resolv.conf
  cache {
    success 65536 3600 300
    denial 8192 600 60
    prefetch 1 60m 10%
  }
  reload 6s
  log
  errors
}
EOF

chown coredns:coredns -R /etc/coredns

cat > /lib/systemd/system/coredns.service << EOF
[Unit]
Description=CoreDNS DNS server
Documentation=https://coredns.io
After=network.target

[Service]
PermissionsStartOnly=true
LimitNOFILE=1048576
LimitNPROC=512
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
User=coredns
WorkingDirectory=/etc/coredns/
ExecStart=/usr/local/bin/coredns -conf=/etc/coredns/Corefile
ExecReload=/bin/kill -SIGUSR1 \$MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload \
&& systemctl enable coredns.service --now \
&& systemctl status coredns.service 
```

open 53,80,443 on windows firewall. And in powershell (admin):
```shell
netsh interface portproxy add v4tov4 listenport=53 listenaddress=0.0.0.0  connectport=53 connectaddress=172.30.55.102
netsh interface portproxy add v4tov4 listenport=80 listenaddress=0.0.0.0  connectport=80 connectaddress=172.30.55.102
netsh interface portproxy add v4tov4 listenport=443 listenaddress=0.0.0.0  connectport=443 connectaddress=172.30.55.102
```
And test dns:
```shell
nslookup example.com 172.30.55.102
nslookup example.com 192.168.1.102
```
The first one successed but the second one failed.It show `DNS request timed out.` And I have a web in 80 port, it can be opened in brower. I have open both tcp and udp port. I don't know where is the problem, could someone help me?

And `telnet 182.168.1.102 53` can work.

**Comment by pemensik** [comment]
Note, DNS typically uses UDP ports, which may require some switch to forward. ``protocol=udp`` is missing, according to [MS article](https://learn.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy#add-v4tov4). TCP requires a switch, ISC BIND's nslookup supports ``nslookup -vc example.com 172.30.55.102`` to query over TCP. Windows version might have that too.
