### ISSUE TITLE
plugin/kubernetes  Cannot correctly identify the source ip of Pod

### ISSUE THREAD

**Issue by liyuntao** [miekg/coredns#6168]
**background**: I'm trying to write a custom plugin that does special policies based on pod/namespace names(of request sender) in Kubernetes, but it seems in the flannel host-gw model, the remote-ip which coredns received, is hostIp with random port. The sender's ip in logs is not equal to the sender's pod-ip, and {/kubernetes/client-namespace} {/kubernetes/client-pod-name} in log output basically not right at all.

 Do you have any good suggestions?

```text
.:53 {
    metadata .
    log . "{remote}:{port} {type} {class} {name} {/kubernetes/client-namespace} {/kubernetes/client-pod-name} "
    errors
    health {
        lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods verified
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf {
      prefer_udp
    }
    cache 30
    reload
    loadbalance
}
```

**Comment by liyuntao** [comment]
```text
[INFO] 10.233.71.0:58322 AAAA IN localhost.test.svc.cluster.local. - -
[INFO] 10.233.71.0:58322 AAAA IN localhost.svc.cluster.local. - -
[INFO] 10.233.71.0:58322 AAAA IN localhost.cluster.local. - - 
[INFO] 10.233.68.0:23837 AAAA IN grafana.com.monitoring.svc.cluster.local. - - 
[INFO] 10.233.68.0:23837 A IN grafana.com.svc.cluster.local. - - 
[INFO] 10.233.68.0:23837 AAAA IN grafana.com.cluster.local. - - 
[INFO] 10.233.73.0:30527 A IN localhost.test.svc.cluster.local. - -
[INFO] 10.233.73.0:30527 AAAA IN localhost.svc.cluster.local. - - 
[INFO] 10.233.73.0:30527 AAAA IN localhost.cluster.local. - - 
```

There's maybe something I didn't notice, still not working after I switch flannel to vxlan mode.

**Comment by liyuntao** [comment]
maybe infected by "node local cache"?

**Comment by chrisohaver** [comment]
> maybe infected by "node local cache"? 

Yes, Since node local cache forwards requests, the pod's IP is no longer the source ip of the DNS request the CoreDNS receives it.  So CoreDNS has no way of knowing who the original requestor was.

The only way to solve this currently is to add the kubernetes plugin to node-local cache.  This will however increase load on the k8s API, since now every dns node cache instance will be requesting a watch on pods.

**Comment by liyuntao** [comment]
Thanks for your help, @chrisohaver     I'll try to think of other options.
