### ISSUE TITLE
Failed to list EndpointSlice

### ISSUE THREAD

**Issue by xh4n3** [miekg/coredns#6176]
**What happened**:
In a K8s cluster, CoreDNS replicas keep printing error messages like below:
```bash
W0620 11:14:10.499478       1 reflector.go:324] /build/plugin/kubernetes/controller.go:405: failed to list *v1beta1.EndpointSlice: the server could not find the requested resource
E0620 11:14:10.499497       1 reflector.go:138] /build/plugin/kubernetes/controller.go:405: Failed to watch *v1beta1.EndpointSlice: failed to list *v1beta1.EndpointSlice: the server could not find the requested resource
```

**What you expected to happen**:
No error messages.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a K8s cluster of version 1.20.*
2. Install CoreDNS of version 1.9.3 on this cluster
3. Upgrade this cluster to 1.26.*

**Anything else we need to know?**:
The K8s cluster's audit log shows the CoreDNS is still using the discovery/v1beta1 API to reach APIServer after upgrade to 1.26.

Possible root cause for it is the API detection for endpointSlice is only done on startup, not dynamically. So the kubernetes plugin won't notice the APIServer removed the API deprecation.

However, since #6147 removed the support for v1beta1 API, maybe we do not need to fix it?

**Environment**:

- the version of CoreDNS: 1.9.3

**Comment by chrisohaver** [comment]
> However, since https://github.com/coredns/coredns/pull/6147 removed the support for v1beta1 API, maybe we do not need to fix it?

Yes, The code was removed, so it's no longer a problem. 

The fix in the field is to restart coredns as part of the upgrade.

> Upgrade this cluster to 1.26.*

How did you upgrade?  e.g. if via kubeadm, may want to fix this in kubeadm (i.e. restart coredns as part of upgrade).

**Comment by xh4n3** [comment]
@chrisohaver Thanks!

> How did you upgrade? 

In our practice, we separate CoreDNS from kubeadm's lifecycle management (i.e. manually skip upgrading CoreDNS during cluster upgrading). 

I just noticed a forced CoreDNS upgrade in kubeadm's post-upgrade phase, so this may not affect most users. Let me close this issue.
