### ISSUE TITLE
Clarification on buffer limit of 10000 messages in dnstap plugin

### ISSUE THREAD

**Issue by BhumikaMatharu** [miekg/coredns#6177]
According to the documentation, after 10000 messages dnstap plugin will start dropping the messages.
This buffer/limit is a bit confusing to me.

I went through the code and saw it refers to the queue size in writer function.
Does it mean that after 10000 messages are sent to the socket, dnstap will start dropping the rest of the messages?
Because I did an experiment and I sent 10000 messages to the socket and was reading it to the file through dnstap command line tool and I didn't see any drops after that. 

Since I was reading the messages from the socket, does it mean I was clearing the buffer?
If I was not reading the messages from the socket, then I would have reached the buffer/limit?
It would be really helpful if you clarify the buffer/limit here.

**Comment by chrisohaver** [comment]
As you read dnstap messages from the socket, they are removed from the buffer.
