### ISSUE TITLE
new version of coredns in kubernetes causes to many nxdomain

### ISSUE THREAD

**Issue by nessa829** [miekg/coredns#6202]
Hello,  I recently migrated EKS from version 1.22 to version 1.27, in preparation for the recent version deprecation. 
However, after the migration, the load of coredns seemed to increase, so I proceeded with the analysis.
The phenomenon was as follows. (refer to attached)
- The coredns request itself rises (from 300M to a maximum of 530M)
- coredns nxdomain error rises (from almost 0 to 400M)

Upon further analysis, there was a change log from the EKS 1.25 version,
https://docs.aws.amazon.com/ko_kr/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.25 

```
The support for wildcard queries was deprecated in CoreDNS 1.8.7 and removed in CoreDNS 1.9. This was done as a security measure. Wildcard queries no longer work and return NXDOMAIN instead of an IP address.
```

even if nxdomain is considered a normal process to find the actual domain, it seems to be too much pressure to coredns. 

For example, If you look at fluentbit's dns query log in the attached capture, fluentbit's query continued to use wildcards, but only kubernetes.default.svc.cluster.local succeeded. It seems that too many unnecessary queries are being made.

![스크린샷 2023-07-11 오후 5 52 07](https://github.com/aws/aws-for-fluent-bit/assets/105766217/ea56ef6b-80cf-4d00-b6be-9702d505821e)

It happens all across the micro services in the cluster. 
how can I call only the necessary domains without using wildcards? Would changing ndot help? 

below is fluent-bit pod's resolv.conf, FYI. 
```
bash-4.2# cat /etc/resolv.conf 
search amazon-cloudwatch.svc.cluster.local svc.cluster.local cluster.local ap-northeast-2.compute.internal
nameserver 172.20.0.10
options ndots:5
```

**Comment by wondywang** [comment]
After migrated to version 1.10, I alse encountered the problem that the headless service resolution returns NXDOMAIN.

```yaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        log
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
```

**Comment by chrisohaver** [comment]
AFAIK coredns only ever supported wildcard card queries with *s in the left most segments. The examples given would always have resulted in NXDOMAIN.
