### ISSUE TITLE
How to Disable ipv6 (AAAA) DNS lookup in coredns

### ISSUE THREAD

**Issue by pyelulkar** [miekg/coredns#6203]
We are using coredns version - v1.8.7 in eks .
We want to disable ipv6 (AAAA) DNS lookup. We did below configuration change in coredns configmap - 
```
   .:53 {
        rewrite stop type AAAA A
        errors
        health
        kubernetes cluster.local in-addr.arpa {
          pods insecure
          fallthrough in-addr.arpa
        }
        forward . /etc/resolv.conf {
        except local
        }
        prometheus :9153
        cache 30
        reload
        loop
        loadbalance
        log . "{remote} {type} {name} {class} {size} {rcode} {duration}"
    }
```

But still we see AAAA lookup in coredns logs - 
```
[INFO] *.*.218 A sts.eu-west-1.amazonaws.com.svc.cluster.local. IN 74 NXDOMAIN 0.000105216s
[INFO] *.*.218 AAAA sts.eu-west-1.amazonaws.com.svc.cluster.local. IN 74 NXDOMAIN 0.000182401s
[INFO] *.*.218 AAAA sts.eu-west-1.amazonaws.com.cluster.local. IN 70 NXDOMAIN 0.000120075s
[INFO] *.*.218 A sts.eu-west-1.amazonaws.com. IN 56 NOERROR 0.000071708s
[INFO] *.*.218 AAAA sts.eu-west-1.amazonaws.com.crossplane-system.svc.cluster.local. IN 92 NXDOMAIN 0.000118104s
[INFO] *.*.218 AAAA sts.eu-west-1.amazonaws.com.svc.cluster.local. IN 74 NXDOMAIN 0.000165613s
[INFO] *.*.218 A sts.eu-west-1.amazonaws.com.svc.cluster.local. IN 74 NXDOMAIN 0.000094366s
[INFO] *.*.218 A sts.eu-west-1.amazonaws.com.eu-west-1.compute.internal. IN 83 NXDOMAIN 0.000080151s
[INFO] *.*.218 AAAA tempo-devops-stg.s3.dualstack.eu-west-1.amazonaws.com. IN 82 NOERROR 0.000773629s
[INFO] *.*.218 A tempo-devops-stg.s3.dualstack.eu-west-1.amazonaws.com. IN 82 NOERROR 0.000125591s
```

How can we stop DNS lookups for AAAA records in coredns ?

**Comment by chrisohaver** [comment]
It is impossible for a DNS server to stop clients from requesting AAAA records.
Clients will request what they want, and the DNS server has no control over that.

The approach of rewriting AAAA to A is problematic because it would confuse clients, which would be receiving incompatible record types it did not ask for.

A better approach would be to use the _template_ plugin to return an empty response for all AAAA requests.

**Comment by pyelulkar** [comment]
@chrisohaver, So Coredns does not have any control over lookups? Is it  dependent on client to query A or AAAA record ?

**Comment by chrisohaver** [comment]
Yes, and not just coredns. This is an axiom of DNS servers (and servers in general - wrt preventing a client from asking certain questions).

**Comment by chrisohaver** [comment]
While you can’t prevent a client from asking for AAAA records, you can configure coredns to deny their existence (eg with template plugin). In theory you could even configure coredns to ignore the requests and not respond at all, but this would cause client timeout and retries, resulting in even more AAAA requests, so not advisable.

**Comment by chrisohaver** [comment]
In more recent versions of coredns*, the _acl_ plugin does this more succinctly than the _template_ plugin. e.g. 

```
    acl {
        filter type AAAA
    }
```

* edit - actually, I think 1.8.7 may have the `filter` option in it, so above config should work without coredns upgrade.

**Comment by pyelulkar** [comment]
> In more recent versions of coredns*, the _acl_ plugin does this more succinctly than the _template_ plugin. e.g.
> 
> ```
>     acl {
>         filter type AAAA
>     }
> ```
> 
> * edit - actually, I think 1.8.7 may have the `filter` option in it, so above config should work without coredns upgrade.

I will try this

**Comment by pyelulkar** [comment]
` acl {
        filter type AAAA
    }`  works in 1.8.7 same as template plugin

**Comment by cattyhouse** [comment]
```
.:53 {
    ...
    template ANY AAAA {
        rcode NOERROR
    }
    ...
}
```
