### ISSUE TITLE
CoreDNS v1.10.0, headless service resolution returns NXDOMAIN

### ISSUE THREAD

**Issue by wondywang** [miekg/coredns#6210]
**What happened**:
After migrated from v1.6.7 to version v1.10.0(or v1.11.0), I encountered the problem that the headless service domain resolution returns NXDOMAIN.
```bash
"A IN headless-svc-name.kube-system.svc.cluster.local. udp 84 false 512" NXDOMAIN qr,aa,rd 177 0.000248503s
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: v1.10.0
- Corefile:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        log
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): linux
- Others:
- Kubernetes： 1.22

**Comment by chrisohaver** [comment]
Does the service exist and have endpoints?

**Comment by wondywang** [comment]
> Does the service exist and have endpoints?

thx @chrisohaver! I found out where the problem is. Because the pod is not ready, so have no record. I set up the service with publishNotReadyAddresses=true will return ok.
