### ISSUE TITLE
How to redefine coredns return code

### ISSUE THREAD

**Issue by wondywang** [miekg/coredns#6214]
### User Story
When CoreDNS is doing domain name resolution, if it encounters an unknown domain name, CoreDNS will return an `NXDOMAIN` error.  But the default behavior for `resolv.conf` will only try the next nameserver if the first nameserver times out or it receives a SERVFAIL from the first nameserver. 

I found that the Template plugin can accomplish a similar effect. But Template has no way to filter the return code. For example, I just want to redefine the error code of `NXDOMAIN` as `SERVFAIL`. 

```yaml
    .:53 {
        template ANY ANY {
          rcode SERVFAIL
        }
    }
```

So I would like to ask, is there any other way to do it? Or the Template plugin needs to support similar functions? In addition, the Template plugin is executed before the Forward plugin. So there is no way to redefine the return code of the Forward plugin.

**Comment by chrisohaver** [comment]
There are some external plugins that support your implied use case. Eg _alternate_  https://github.com/coredns/alternate

**Comment by chrisohaver** [comment]
I am assuming the implied use case is that you want incoming queries to try one upstream server first, then if that response is   does not have a positive result, discard that result and try a second upstream server.

**Comment by chrisohaver** [comment]
What’s the underlying problem you are trying to solve with the proposed solution. Eg why do you want to do this. Why do you expect your upstream servers hold different sets of records?

If one resolves public domains, and the other resolves a private domain, then the proper way to handle this is by creating a server block for your private domain, routing queries based on their domain, instead of trying to implement a sort of cascading chain of forwards.

**Comment by wondywang** [comment]
> I am assuming the implied use case is that you want incoming queries to try one upstream server first, then if that response is does not have a positive result, discard that result and try a second upstream server.

thx @chrisohaver .

The scene I encountered was a bit special. There are two network cards on pod A, which come from different VPCs. One of the network cards communicates with the CoreDNS.

The pod A needs to access a special domain name. This domain name needs to pass through the DNS of the other network card to have correct resolution. Therefore, the resolv.conf of pod A configures two nameservers, one of which is the clusterip of CoreDNS, and the other is the dns server corresponding to another VPC. 

It is hoped here that in pod A, after accessing CoreDNS domain name resolution fails, go to another nameserver to try again. The premise is that CoreDNS domain name resolution needs to return `SERVFAIL`.

I don't know if my description is clear. ^_^

**Comment by chrisohaver** [comment]
If I understand correctly, the proper DNS way to do this would be to also give coredns access to both DNS servers, and configure it to forward queries for that "special" (i.e. private?) domain to the VPC dns server.

**Comment by chrisohaver** [comment]
> It is hoped here that in pod A, after accessing CoreDNS domain name resolution fails, go to another nameserver to try again. The premise is that CoreDNS domain name resolution needs to return SERVFAIL.

I expect this approach may cause unexpected results elsewhere. E.g. it may short circuit (break) resolv.conf query domain suffix searching.  I think it would also cause problems for some clients that do parallel A/AAAA queries, and "Happy Eyeballs".

**Comment by wondywang** [comment]
> If I understand correctly, the proper DNS way to do this would be to also give coredns access to both DNS servers, and configure it to forward queries for that "special" (i.e. private?) domain to the VPC dns server.

That won't work because the VPC of pod A (or maybe pod i) is unknown.

**Comment by chrisohaver** [comment]
> That won't work because the VPC of pod A (or maybe pod i) is unknown.

Sounds like you don't have full control over the environment?  Can I assume this is in a Kubernetes deployment here, since you are using the word "Pod"?

**Comment by wondywang** [comment]
> Sounds like you don't have full control over the environment? Can I assume this is in a Kubernetes deployment here, since you are using the word "Pod"?

Yes, in a Kubernetes. And the pods are in different network spaces.

**Comment by wondywang** [comment]
Thanks @chrisohaver! 
I am trying to solve the problem of such a special case. If I return `SERVFAIL` by force, I know that will cause unexpected results some where.

**Comment by chrisohaver** [comment]
Since the proposed solution is hacky and will break other things, take care to only apply it to the "special" domain in question.

There is an open PR to add response code rewrite to the the _rewrite_ plugin. #6204. This should be able to implement the solution you propose.

**Comment by chrisohaver** [comment]
>> If I understand correctly, the proper DNS way to do this would be to also give coredns access to both DNS servers, and configure it to forward queries for that "special" (i.e. private?) domain to the VPC dns server.

> That won't work because the VPC of pod A (or maybe pod i) is unknown.

CoreDNS doesnt have to have direct access to the VPC, It could instead forward to another dns service in the cluster that has a Pod in the VPC (like your "Pod A").

I don't understand what you mean by the VPC of "Pod A" is "unknown".

**Comment by wondywang** [comment]
> There are some external plugins that support your implied use case. Eg _alternate_ https://github.com/coredns/alternate

I want to know that, in alternate plugin, did it request forward first, and then go to alternate, or directly bypass forward to request alternate?

**Comment by chrisohaver** [comment]
> > There are some external plugins that support your implied use case. Eg _alternate_ https://github.com/coredns/alternate
> 
> I want to know that, in alternate plugin, did it request forward first, and then go to alternate, or directly bypass forward to request alternate?

The former. The readme explains how it works in more detail. Iirc there are examples that help illustrate how it works.
