### ISSUE TITLE
Wrong argument count or unexpected line ending after 'keepttl' using cache plugin and . zone

### ISSUE THREAD

**Issue by gijzelaerr** [miekg/coredns#6225]
if i enable the cache plugin with `coredns:1.10.1` like this:
```
services.example.net {
   cache 60 . {
     success 524288
     denial 524288
    keepttl
 }
}
```
I get:
```
plugin/cache: Corefile:94 - Error during parsing: Wrong argument count or unexpected line ending after 'keepttl'
```

If i remove `keepttl` or the `.` zone from the config the server starts normally:
```
services.example.net {
   cache 60 {
     success 524288
     denial 524288
     keepttl
   }
}
```
For me it is not directly clear why this is the case from the documentation, so i think this is  a bug in the config parser log, or something is missing in the documentation

**Comment by MrFreezeex** [comment]
Hmm copy pasting your example works for me with the same coredns version :thinking:

**Comment by gijzelaerr** [comment]
interesting. let me isolate the problem a bit further tomorrow.

**Comment by MrFreezeex** [comment]
TBH it's unlikely that the problem is from keepttl since the config parsing is tested. My best guess would be that this is something else that is causing this. Probably if you swap the keepttl line with the line above the error would change to refer to the option above...

**Comment by chrisohaver** [comment]
Sometimes trailing or extra (or missing) white space can create parse errors like this.  I don't see any in the examples, but perhaps some white space was changed in the process of copying to the issue description.

**Comment by gijzelaerr** [comment]
I can replicate the problem this way:
```
$  cat tmp/coredns.conf

services.example.net {
  cache 60 . {
    keepttl
  }
}

$  docker run -it --rm -v `pwd`/tmp/coredns.conf:/Corefile coredns/coredns:1.10.1
plugin/cache: Corefile:4 - Error during parsing: Wrong argument count or unexpected line ending after 'keepttl'
```

**Comment by MrFreezeex** [comment]
Oh hmmm actually this is a bug... keepttl args (https://github.com/coredns/coredns/blob/master/plugin/cache/setup.go#L244) takes by default the zone lists if it has been given to the cache plugin, not sure what should be done here to fix that :thinking:

**Comment by chrisohaver** [comment]
@MrFreezeex , the code is missing a `args := c.RemainingArgs()` before the arg length check.
