### ISSUE TITLE
coredns pod  CrashLoopBackOff 

### ISSUE THREAD

**Issue by qwert007** [miekg/coredns#6236]
k8s v1.27.0 coredns:v1.10.1 

detail：

Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  23m                   default-scheduler  Successfully assigned kube-system/coredns-65dcc469f7-2h9zw to gie-ec-node16
  Normal   Pulled     21m (x5 over 23m)     kubelet            Container image "registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.10.1" already present on machine
  Normal   Created    21m (x5 over 23m)     kubelet            Created container coredns
  Warning  Failed     21m (x5 over 23m)     kubelet            Error: failed to start container "coredns": Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:284: applying cgroup configuration for process caused \"No such device or address\""
  Warning  BackOff    3m6s (x101 over 23m)  kubelet            Back-off restarting failed container coredns in pod coredns-65dcc469f7-2h9zw_kube-system(8aebaf44-7e3b-4edb-9feb-98eaf7fb50d0)

**Comment by dilyevsky** [comment]
@qwert007 most likely you have a misconfigured host
