### ISSUE TITLE
coredns/coredns:1.11.0 is not available

### ISSUE THREAD

**Issue by ry4nz** [miekg/coredns#6247]
**What happened**:
coredns/coredns:1.11.0 is not available

**What you expected to happen**:
coredns/coredns:1.11.0 is available, similar to 1.10.1

**How to reproduce it (as minimally and precisely as possible)**:
`docker pull coredns/coredns:1.11.0`

**Anything else we need to know?**:
Although we can use `latest` for now, but I'd prefer to have a `1.11.0` version tagged.

**Environment**:

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
There was a problem with the docker build. Averted for now by #6246.  

The 1.11.0 image should be there now.
