### ISSUE TITLE
Coredns fails to compile with Go@v1.21.0

### ISSUE THREAD

**Issue by TraumaER** [miekg/coredns#6248]
**What happened**:

When trying to compile from source (no changes) I receive the following error when using Go@v1.21.0
```bash
➜  coredns git:(master) ✗ make
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=9f4aa9d2-dirty" -o coredns
github.com/quic-go/quic-go/internal/handshake
# github.com/quic-go/quic-go/internal/handshake
../../go/pkg/mod/github.com/quic-go/quic-go@v0.37.3/internal/handshake/crypto_setup.go:362:37: cannot use h.allow0RTT (variable of type bool) as tls.QUICSessionTicketOptions value in argument to h.conn.SendSessionTicket
make: *** [Makefile:16: coredns] Error 1
```

**What you expected to happen**:

The compile to succeed

**How to reproduce it (as minimally and precisely as possible)**:

1. install [Go@v1.21.0 ](https://go.dev/dl/)
2. clone the repo `git clone https://github.com/coredns/coredns.git`
3. Run make

**Anything else we need to know?**:

When downgrading to `Go@v1.20.7` coredns compiled as expected.

**Environment**:

- the version of CoreDNS: `master`

- OS (e.g: `cat /etc/os-release`):
    - `Ubuntu 22.10`
    - and `Ubuntu 22.04.3`

**Comment by chenyuheng** [comment]
This looks like a problem of quic-go, see https://github.com/quic-go/quic-go/pull/4020
