### ISSUE TITLE
Is it possible to configure CoreDNS to not include NS in authority for answers?

### ISSUE THREAD

**Issue by jeffwesthead** [miekg/coredns#6256]
I have CoreDNS serving responses from a zone file. It includes the NS record set for the zone in positive answers. I would like to turn this off and only have answers in the response. Is there a setting for this?

**Comment by donl** [comment]
Try using the `minimal` plugin in the relevant section of your Corefile.

**Comment by jeffwesthead** [comment]
Thanks I had seen that but misunderstood its purpose. It looks like exactly what I am looking for.
________________________________

**Comment by chrisohaver** [comment]
I think though that _minimal_ detects presence of NS records in the Authority section of a successful response as a delegation and therefore would not modify the message.

**Comment by jeffwesthead** [comment]
Tested just now and it seems to do what I asked. Thanks!
