### ISSUE TITLE
coredns 1.7.0 CPU usage is huge

### ISSUE THREAD

**Issue by im-jinxinwang** [miekg/coredns#6257]
**What happened**:
I have coredns running in kubernetes cluster, but their cpu usage load is very high, i think it's an abnormal phenomenon

![image](https://github.com/coredns/coredns/assets/39941928/bed8bd7e-a3cd-4613-ade4-4dce882eafd1)

There are no exceptions in the logs except for slow parsing.
![image](https://github.com/coredns/coredns/assets/39941928/f668bc6d-b65f-4c04-9dd4-016bc5be1744)

My configuration file is as follows：
```text
cluster.local {
    errors
    health {
        lameduck 5s
    }
    ready
    kubernetes cluster.local 169.169.0.0/16 {
        fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
cxxxxxxx.cn {
    errors
    cache 30
    reload
    forward . 10.x.x.120 10.x.x.245
}
api.xxx.xxxx.cmcc {
    errors
    log
    cache 30
    reload
    forward . 10.x.x.247 10.x.x.4
}
. {
    etcd . {
        fallthrough .
        path /skydns
        endpoint http://10.x.x.x:1159 http://10.x.x.x6:1159 http://10.x.x.x:1159
    }
    loadbalance
    forward . /etc/resolv.conf
    cache 30
}
cmcc.cn {
    errors
    cache 60
    reload
    forward . 10.x.x.120 10.x.x.245 {
        max_fails 1;
        fail_timeout 10s;
    }
}
```

**Environment**:
- the version of CoreDNS: 1.7.0
- Others:  kubernetes 1.23.6

**Comment by chrisohaver** [comment]
CoreDNS 1.7.0 is very old. Do you see the issue in 1.11.0 or 1.10.1 ?

**Comment by seniordevops7** [comment]
Same problem on docker version 1.11.0

**Comment by chrisohaver** [comment]
@enmanuelmoreira, you may be seeing #6255, which has a fix committed, in process of being released shortly.

**Comment by seniordevops7** [comment]
Thank you @chrisohaver !
