### ISSUE TITLE
"recursion not available", but Header Set in Config File

### ISSUE THREAD

**Issue by arrmo** [miekg/coredns#6262]
**What happened**:
nslookup is failing, with the error message,
```
;; Got recursion not available from 192.168.0.3, trying next server
```
I also checked with dig, on 3 different clients - all report,
```
;; WARNING: recursion requested but not available

```
**What you expected to happen**:
I don't expect this error, as I have added in the configuration file,
```
    header {
        response set ra
    }
```
**How to reproduce it (as minimally and precisely as possible)**:
Run dig or nslookup, on a (LAN) name, that calls `coredns` for name resolution.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
```
CoreDNS-1.11.0
linux/amd64, go1.20.7, 141c7608-dirty
```
- Corefile:
```
.:53 {
    health :8080
    header {
        response set ra
    }
    omada {
        controller_url http://192.168.0.3:8088
        site vmOmadaSDN
        username XXXXX
        password XXXXX
        refresh_minutes 1
    }
    forward . tls://2606:4700:4700::1111 tls://1.1.1.1
    log
    errors
    cache
}

```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- Others:

**Comment by mqasimsarfraz** [comment]
I have a feeling that it might be related to order of plugins in `plugin.cfg`. Can you please share it? I will try to reproduce it.

**Comment by arrmo** [comment]
Sure, NP! Here is the file,
```
# Directives are registered in the order they should be executed.
#
# Ordering is VERY important. Every plugin will feel the effects of all other
# plugin below (after) them during a request, but they must not care what plugin
# above them are doing.
omada:github.com/dougbw/coredns_omada

# How to rebuild with updated plugin configurations: Modify the list below and
# run `go generate && go build`

# The parser takes the input format of:
#
#     <plugin-name>:<package-name>
# Or
#     <plugin-name>:<fully-qualified-package-name>
#
# External plugin example:
#
# log:github.com/coredns/coredns/plugin/log
# Local plugin example:
# log:log

metadata:metadata
geoip:geoip
cancel:cancel
tls:tls
timeouts:timeouts
reload:reload
nsid:nsid
bufsize:bufsize
root:root
bind:bind
debug:debug
trace:trace
ready:ready
health:health
pprof:pprof
prometheus:metrics
errors:errors
log:log
dnstap:dnstap
local:local
dns64:dns64
acl:acl
any:any
chaos:chaos
loadbalance:loadbalance
tsig:tsig
cache:cache
rewrite:rewrite
header:header
dnssec:dnssec
autopath:autopath
minimal:minimal
template:template
transfer:transfer
hosts:hosts
route53:route53
azure:azure
clouddns:clouddns
k8s_external:k8s_external
kubernetes:kubernetes
file:file
auto:auto
secondary:secondary
etcd:etcd
loop:loop
forward:forward
grpc:grpc
erratic:erratic
whoami:whoami
on:github.com/coredns/caddy/onevent
sign:sign
view:view
```

Thanks!

**Comment by mqasimsarfraz** [comment]
I see, `omada` plugin at the top, so plugins below won't be able to [mutate response](https://github.com/coredns/coredns/blob/master/plugin.md#mutating-a-response) for it. Can you please try with:

```
# Directives are registered in the order they should be executed.
#
# Ordering is VERY important. Every plugin will feel the effects of all other
# plugin below (after) them during a request, but they must not care what plugin
# above them are doing.
header:header
omada:github.com/dougbw/coredns_omada

# How to rebuild with updated plugin configurations: Modify the list below and
# run `go generate && go build`

# The parser takes the input format of:
#
#     <plugin-name>:<package-name>
# Or
#     <plugin-name>:<fully-qualified-package-name>
#
# External plugin example:
#
# log:github.com/coredns/coredns/plugin/log
# Local plugin example:
# log:log

metadata:metadata
geoip:geoip
cancel:cancel
tls:tls
timeouts:timeouts
reload:reload
nsid:nsid
bufsize:bufsize
root:root
bind:bind
debug:debug
trace:trace
ready:ready
health:health
pprof:pprof
prometheus:metrics
errors:errors
log:log
dnstap:dnstap
local:local
dns64:dns64
acl:acl
any:any
chaos:chaos
loadbalance:loadbalance
tsig:tsig
cache:cache
rewrite:rewrite
dnssec:dnssec
autopath:autopath
minimal:minimal
template:template
transfer:transfer
hosts:hosts
route53:route53
azure:azure
clouddns:clouddns
k8s_external:k8s_external
kubernetes:kubernetes
file:file
auto:auto
secondary:secondary
etcd:etcd
loop:loop
forward:forward
grpc:grpc
erratic:erratic
whoami:whoami
on:github.com/coredns/caddy/onevent
sign:sign
view:view
```

and see if it helps?  Or `omada` can be moved down in order?

**Comment by chrisohaver** [comment]
> Or omada can be moved down in order?

I would recommend moving omada down instead of header up. Moving header up will alter its position relative to other plugins and manifest other issues that may not immediately be apparent.

**Comment by arrmo** [comment]
Sure, can do. Just to confirm ... rebuild (make) after changing the order?

Thanks!

**Comment by arrmo** [comment]
OK, made the change, rebuilt and ...
1) If `omada` is at the end, I never get a reply from this plugin => all requests seem to be forwarded to root servers. Does that make sense? BTW, I initially added `omada` first on the list, based on this "[direction](https://github.com/dougbw/coredns_omada/blob/main/docs/build.md)".
2) With `omada` right after `header`, things seem to work. Woohoo! Is this the right place for it though? Thinking I want it right before going to root servers ... agreed? But which one is that ... `forward`? Or something else?

Thanks!

**Comment by chrisohaver** [comment]
> OK, made the change, rebuilt and ...
> 
> 1. If `omada` is at the end, I never get a reply from this plugin => all requests seem to be forwarded to root servers. Does that make sense?

Yes. thats expected.

> BTW, I initially added `omada` first on the list, based on this "[direction](https://github.com/dougbw/coredns_omada/blob/main/docs/build.md)".

That guide would seem to be misinformed.

> 2. With `omada` right after `header`, things seem to work. Woohoo! Is this the right place for it though? Thinking I want it right before going to root servers ... agreed? But which one is that ... `forward`? Or something else?

right before forward sounds best.  that way _hosts_ and _template_ plugins still take precedence if you needed to use them for some reason.

**Comment by arrmo** [comment]
> Yes. thats expected.
> 
> >

Because of forward? I need to find where the various plugins are described 😆 

> That guide would seem to be misinformed.
> 
> >

Kinda figured that - I'll report it to them.



> right before forward sounds best. that way _hosts_ and _template_ plugins still take precedence if you needed to use them for some reason.

OK, so I did guess right 🤣, It made sense ... and I guess when, for example, forward is called, that's the end of the "pipeline"?

Thanks!

**Comment by mqasimsarfraz** [comment]
@arrmo I see [omada](https://github.com/dougbw/coredns_omada/issues/14) updated the order. Can we please close this issue if `header` plugin works as expected now?

**Comment by arrmo** [comment]
Yes, absolutely - agreed. Closing. And thanks for the help!
