### ISSUE TITLE
dnstap bug

### ISSUE THREAD

**Issue by sftfjugg** [miekg/coredns#6275]
dnstap存在 DATA RACE

github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/dnstap.Dnstap.ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/dnstap/handler.go:81 +0x36c
  github.com/coredns/coredns/plugin/dnstap.(*Dnstap).ServeDNS()
      <autogenerated>:1 +0x12b

**Comment by chrisohaver** [comment]
duplicate of #6276 opened at same time.
