### ISSUE TITLE
cache bug DATA RACE

### ISSUE THREAD

**Issue by sftfjugg** [miekg/coredns#6276]
版本：v1.11.1

==================
WARNING: DATA RACE
Write at 0x00c001ff82d4 by goroutine 392013:
  github.com/coredns/coredns/plugin/cache.filterRRSlice()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/cache/dnssec.go:15 +0x127
  github.com/coredns/coredns/plugin/cache.(*ResponseWriter).WriteMsg()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/cache/cache.go:209 +0xa5c
  github.com/coredns/coredns/plugin/forward.(*Forward).ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/forward/forward.go:239 +0x1b71
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/loop.(*Loop).ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/loop/loop.go:35 +0x657
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/cache.(*Cache).doRefresh()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/cache/handler.go:158 +0x19ee
  github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/cache/handler.go:43 +0x1957
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
      <autogenerated>:1 +0xa5
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/dnstap.Dnstap.ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/dnstap/handler.go:81 +0x36c
  github.com/coredns/coredns/plugin/dnstap.(*Dnstap).ServeDNS()
      <autogenerated>:1 +0x12b
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/log.Logger.ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/log/log.go:36 +0x3ec
  github.com/coredns/coredns/plugin/log.(*Logger).ServeDNS()
      <autogenerated>:1 +0x104
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/errors.(*errorHandler).ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/errors/errors.go:84 +0xc7
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/bufsize.Bufsize.ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/bufsize/bufsize.go:23 +0xfd
  github.com/coredns/coredns/plugin/bufsize.(*Bufsize).ServeDNS()
      <autogenerated>:1 +0xa5
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/metadata.(*Metadata).ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/metadata/metadata.go:30 +0xa4
  github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/core/dnsserver/server.go:316 +0x1344
  github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1()
      /usr/local/gowork/src/coredns-v1.11.1/core/dnsserver/server.go:178 +0xb2
  github.com/miekg/dns.HandlerFunc.ServeDNS()
      /usr/local/gowork/pkg/mod/github.com/miekg/dns@v1.1.55/server.go:37 +0x4d
  github.com/miekg/dns.(*Server).serveDNS()
      /usr/local/gowork/pkg/mod/github.com/miekg/dns@v1.1.55/server.go:659 +0x85d
  github.com/miekg/dns.(*Server).serveUDPPacket()
      /usr/local/gowork/pkg/mod/github.com/miekg/dns@v1.1.55/server.go:603 +0x37b
  github.com/miekg/dns.(*Server).serveUDP.func3()
      /usr/local/gowork/pkg/mod/github.com/miekg/dns@v1.1.55/server.go:533 +0xf1

Previous read at 0x00c001ff82d0 by goroutine 392014:
  github.com/miekg/dns.(*A).copy()
      /usr/local/gowork/pkg/mod/github.com/miekg/dns@v1.1.55/ztypes.go:803 +0xef
  github.com/miekg/dns.Copy()
      /usr/local/gowork/pkg/mod/github.com/miekg/dns@v1.1.55/msg.go:1048 +0x1c5
  github.com/coredns/coredns/plugin/cache.filterRRSlice()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/cache/dnssec.go:17 +0x79
  github.com/coredns/coredns/plugin/cache.(*item).toMsg()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/cache/item.go:90 +0x69a
  github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/cache/handler.go:81 +0x12cc
  github.com/coredns/coredns/plugin.NextOrFailure()
      <autogenerated>:1 +0xa5
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/dnstap.Dnstap.ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/dnstap/handler.go:81 +0x36c
  github.com/coredns/coredns/plugin/dnstap.(*Dnstap).ServeDNS()
      <autogenerated>:1 +0x12b
  github.com/coredns/coredns/plugin.NextOrFailure()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/plugin.go:80 +0x2cf
  github.com/coredns/coredns/plugin/log.Logger.ServeDNS()
      /usr/local/gowork/src/coredns-v1.11.1/plugin/log/log.go:36 +0x3ec

**Comment by chrisohaver** [comment]
Please provide steps to reproduce this.
