### ISSUE TITLE
Examples of expression for Expr

### ISSUE THREAD

**Issue by antonmedv** [miekg/coredns#6278]
Hello!

I'd like to integrate CodeDNS expressions into Expr https://github.com/antonmedv/expr package. Something similar to https://github.com/antonmedv/expr/blob/master/testdata/crowdsec.json. 

Where I can find some expressions used by CoreDNS?

**Comment by SuperQ** [comment]
The expressions are used in the [view plugin](https://github.com/coredns/coredns/tree/master/plugin/view#examples). There's also an example [view+geoip combo](https://github.com/coredns/coredns/tree/master/plugin/geoip#examples) expression.

**Comment by antonmedv** [comment]
I've added tests in https://github.com/antonmedv/expr/blob/master/test/coredns/coredns_test.go

Will be cool to have more examples. Is were a way to gather more examples?

**Comment by SuperQ** [comment]
Nice, thanks.

Not without people publishing their Corefile contents. The `view` plugin is somewhat new, not sure how widespread the use is.

**Comment by antonmedv** [comment]
Understood. If some more examples will be surfaced please let me know.
