### ISSUE TITLE
Missing 1.11.1 on registry.k8s.io

### ISSUE THREAD

**Issue by nox-404** [miekg/coredns#6287]
Hello,
is there any plan to release the `1.11.1` versions to `registry.k8s.io` ?

The last release available there is `1.11.0`:
https://explore.ggcr.dev/?repo=registry.k8s.io%2Fcoredns%2Fcoredns

**Comment by chrisohaver** [comment]
Yes

**Comment by stp-ip** [comment]
v1.11.1 was pushed to the registry a day or so after release. Aka now it's available.
