### ISSUE TITLE
 TestCorefile1 fails on x86_64-darwin

### ISSUE THREAD

**Issue by kirillrdy** [miekg/coredns#6289]
**What happened**:

test  TestCorefile1 fails on x86_64-darwin

**What you expected to happen**:

test not to fail

**How to reproduce it (as minimally and precisely as possible)**:

cd test && go test .

**Anything else we need to know?**:

here is full ( ish ) log

```
go test .
--- FAIL: TestCorefile1 (0.00s)
    corefile_test.go:15: Expected an error got none
```

**Environment**:

- the version of CoreDNS: 0.11.0+
- Corefile:
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):  22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64
- Others:

**Comment by chrisohaver** [comment]
The test passes for me: `22.6.0 Darwin Kernel Version 22.6.0`


```
=== RUN   TestCorefile1
--- PASS: TestCorefile1 (0.00s)
```

**Comment by kirillrdy** [comment]
indeed passes on 22.6.0 ! thank you for looking into it
