### ISSUE TITLE
What is the process to include multicluster plugin into the coredns image by default

### ISSUE THREAD

**Issue by SriHarsha001** [miekg/coredns#6313]
What is the process to include multicluster plugin into the coredns image by default
https://github.com/coredns/multicluster

Use case - To enable clusterset fqdn working in AKS fleet.

**Comment by chrisohaver** [comment]
There are instructions for building coredns with the multicluster external plugin in https://github.com/coredns/multicluster

**Comment by SriHarsha001** [comment]
Yes, I had gone through the instructions. But wanted to check on how (or request) to include multicluster external plugin into coreDNS (built-in) by default. Similar to caddy plugin https://github.com/coredns/caddy included here - https://github.com/coredns/coredns/blob/master/plugin.cfg

**Comment by chrisohaver** [comment]
Open an issue to request it to be added by default. Or open a PR that adds it.

**Comment by SriHarsha001** [comment]
oh ok sure. Thank you.
