### ISSUE TITLE
Cluster internal PTR requests getting forwarded to upstream DNS servers

### ISSUE THREAD

**Issue by vveeregandha** [miekg/coredns#6315]
**What happened**:
Issue: We are seeing lot of PTR requests getting forwarded to upstream DNS servers. All these PTR requests are trying to resolve cluster internal IPs'. These should get resolved internally to cluster and not get forwarded to upstream DNS servers. This is causing a huge amount of spamming on out upstream DNS servers. Interesting thing is, these requests are not failing and getting resolved fine.

**What you expected to happen**:

All cluster internal IPs' should get not leave cluster and get resolved in the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
This is the setup we have:
Setup: 
Kubernetes Cluster version: v1.22.8
coredns version - k8s.gcr.io/coredns/coredns:v1.8.0
nodelocaldns - k8s.gcr.io/dns/k8s-dns-node-cache:1.21.1

coredns configmap:

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          prefer_udp
        }
        cache 30

        loop
        reload
        loadbalance
    }
kind: ConfigMap
``` 

**Environment**:
Setup: 
Kubernetes Cluster version: v1.22.8
coredns version - k8s.gcr.io/coredns/coredns:v1.8.0
nodelocaldns - k8s.gcr.io/dns/k8s-dns-node-cache:1.21.1

- the version of CoreDNS:
- Corefile:
- logs, if applicable:
Sample log:
![image](https://github.com/coredns/coredns/assets/96138063/3109b832-07bc-4c7d-ab95-b26681d55517)
- OS (e.g: `cat /etc/os-release`):

```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by chrisohaver** [comment]
duplicate https://github.com/kubernetes/kubernetes/issues/120585
