### ISSUE TITLE
Feature Request - Adding support for displaying DNS resolution results in the CoreDNS console

### ISSUE THREAD

**Issue by djbonedev001** [miekg/coredns#6316]
I would like to report an issue regarding the log format of CoreDNS. Currently, it does not seem to support displaying the resolved DNS results in the logs. It would be very useful if we could see the resolution results in the CoreDNS console to verify whether the resolutions are correct.

Is there any plan to add this feature to CoreDNS? If not, is there any workaround or alternative solution available?

Thank you for your attention and assistance.

**Comment by lobshunter** [comment]
> is there any workaround or alternative solution available

I personally use tcpdump + wireshark I diagnose such issues.

**Comment by chrisohaver** [comment]
dnstap would fit well. 

https://github.com/coredns/coredns/tree/master/plugin/dnstap
