### ISSUE TITLE
Duplicate cipher suite configuration

### ISSUE THREAD

**Issue by weiguozhang** [miekg/coredns#6317]
While reading the CoreDNS code, I noticed that in the setTLSDefaults function of the plugin/pkg/tls/tls.go file, cipher suites are configured. However, I found that the last three cipher suites are duplicated with the ones configured earlier. Is there any specific purpose for this duplicate configuration?

```go
ctls.CipherSuites = []uint16{
    tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
    tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
    tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
    tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
}
```

**Comment by chrisohaver** [comment]
> Is there any specific purpose for this duplicate configuration?

Probably not. It is most likely unintentional.
