### ISSUE TITLE
[ERROR] plugin/errors: 2 example.org. A: plugin/auto: no next plugin found

### ISSUE THREAD

**Issue by felixkrohn** [miekg/coredns#6318]
**What happened**:
Between CoreDNS  v1.10.1 and v1.11.1 the behaviour of the `auto` plugin seems to have changed. The same Corefile working with 1.10.1 (Docker image `docker.io/coredns/coredns@sha256:a0ead06651cf580044aeb0a0feba63591858fb2e43ade8c9dea45a6a89ae7e5e`) now leads to the error message mentioned above with the latest v1.11.1 (`docker.io/coredns/coredns@sha256:1eeb4c7316bacb1d4c8ead65571cd92dd21e27359f0d4917f1a5822a73b75db1`)

**What you expected to happen**:
no behavioral change between those two versions

**How to reproduce it (as minimally and precisely as possible)**:

```
example.org example.com {
  auto {
    directory /zonefiles/ (.*)\.fwd\.signed {1}
  }
  errors
  log
}
```
CoreDNS is started with cmdline flag `-dns.port 53` as non-root, usage of port 53 to standard user is granted through `net.ipv4.ip_unprivileged_port_start` sysctl
/zonefiles/example.org.fwd.signed and /zonefiles/example.com.fwd.signed exist and contain valid signed zonefiles.
I currently serve them through separate `file` stanzas as a workaround.

going back to v1.10.1 also works with the above Corefile.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: v1.11.1
- Corefile: see above
- logs, if applicable: dig output

;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 9192
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

- OS (e.g: `cat /etc/os-release`): standard coredns docker image (hashes see above)

**Comment by felixkrohn** [comment]
In order to make sure it's not related to the zonefiles, here's a complete example with unsigned example files.

Corefile:

```
example.org example.com {
  auto {
    directory /zonefiles/ (.*)\.fwd {1} 
  }
  errors
  log 
}
```

and the corresponding zonefiles, `/zonefiles/example.org.fwd` and `/zonefiles/example.com.fwd`:
```
$ORIGIN example.org.
@       3600 IN SOA sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600
        3600 IN NS a.iana-servers.net.
        3600 IN NS b.iana-servers.net.

www     IN A     127.0.0.1
        IN AAAA  ::1
```

```
$ORIGIN example.com.
@       3600 IN SOA sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600
        3600 IN NS a.iana-servers.net.
        3600 IN NS b.iana-servers.net.

www     IN A     127.0.0.1
        IN AAAA  ::1
```

This yields the same results:
```
[INFO] Reloading                                                                                                                                                                                                                                                                                                               
[INFO] plugin/reload: Running configuration SHA512 = 094fa7791c117187a6b0d61083f5c3f952e0eb8326dc400d3cbb2371752fd6aa104deca52b13c4f2db7eb5902c11934dfa23bde5fd964c06502283293ea171dc                                                                                                                                          
[INFO] Reloading complete                                                                                                                                                                                                                                                                                                      
[INFO] y.y.y.y:6812 - 18441 "A IN example.com. udp 52 false 1232" - - 0 0.000050359s                                                                                                                                                                                                                                      
[ERROR] plugin/errors: 2 example.com. A: plugin/auto: no next plugin found                                                                                                                                                                                                                                                     
```

The dig command:
```
$ dig -4 example.com @MYSERVER a

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> -4 example.com @MYSERVER a
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 18441
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: e69f4eaf9497a7ff (echoed)
;; QUESTION SECTION:
;example.com.                   IN      A

;; Query time: 40 msec
;; SERVER: x.x.x.x#53(MYSERVER) (UDP)
;; WHEN: Wed Sep 13 21:04:50 CEST 2023
;; MSG SIZE  rcvd: 52
```

The parsing of the Corefile and reading of the zonefiles seems to work to a certain extent, as `dig` returns an REFUSED error when querying for example.net, no logs on coredns side.

**Comment by chrisohaver** [comment]
I think most likely related to the changes that add notify to auto zone transfer: https://github.com/coredns/coredns/pull/5774/files

If not that, then something more indirect since I don't see any other changes to the auto plugin between those versions.

**Comment by chrisohaver** [comment]
Thanks very much for the self contained repro example!

**Comment by chrisohaver** [comment]
When I test your example using the latest ~release~ commit, it works fine for me. I don't see `no next plugin found` errors, and I get an expected negative response.


```
; <<>> DiG 9.18.18 <<>> example.org @localhost -t A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44717
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: b9c989829549fa09 (echoed)
;; QUESTION SECTION:
;example.org.			IN	A

;; AUTHORITY SECTION:
example.org.		3600	IN	SOA	sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600

;; Query time: 0 msec
;; SERVER: ::1#5399(localhost) (UDP)
;; WHEN: Wed Sep 13 16:16:07 EDT 2023
;; MSG SIZE  rcvd: 133

```

**Comment by chrisohaver** [comment]
In your log snips, I don't see the "inserting zone" message, which suggests that the files cannot be found/read.  A permission issue?

**Comment by felixkrohn** [comment]
@chrisohaver That seems to have nailed it. I originally didn't check file permissions to start with as the `file` plugin was able to read the zonefiles without issue, and v1.10.1 as well.
What I had to do is `chmod 755 zonefiles` to make the directory world-readable and world-executable (=listable). The files in there were already world readable (644).
As soon as I revert this setting (`chmod 711 zonefiles`)  I get the error again.

Now here's the next quiz: knowing how to fix the issue is one thing, but do you have any idea what causes this change between `v1.10.1` and `v1.11.1`?
`v1.10.1` reproducively accepts the zonefiles dir with chmod 711, `latest` (from the published docker image as well as a self-built image from master@b5e62911) expects more.

**Comment by felixkrohn** [comment]
I leave this issue open as I believe it's a bug that coredns starts without warning when unable to read files (?) in the given directory.

**Comment by chrisohaver** [comment]
Coredns no longer runs as root in the docker image as of 1.11.0. From your descriptions above I thought you were executing the binary directly. But if you are running it in the docker image, then this is likely caused by coredns running as non root. 

edit: FWIW I interpreted "CoreDNS is started with cmdline flag -dns.port 53 as non-root," incorrectly.
