### ISSUE TITLE
Steering Committee Membership Term End

### ISSUE THREAD

**Issue by chrisohaver** [miekg/coredns#6327]
All current steering committee members' terms are ending next week.

Technically, per our GOVERNANCE.md guidelines, we are supposed to start voting for the next term at least 4 weeks before terms end (terms ending next week... so 3 weeks ago).  Thanks @SuperQ for the reminder!

**To all maintainers**:  If you would like to serve on the steering committee for the next term, please open a PR to add your name to the list in CODEOWNERS.md.  If you are currently on the steering committee and would like to continue through the next term, open a PR to extend your term.

**Comment by SuperQ** [comment]
Please remember to :+1: or :-1: your votes according to the GOVERNANCE.md.
