### ISSUE TITLE
Seems like cache option doesn't work. Node-local-dns continues forward traffic to upstream

### ISSUE THREAD

**Issue by Jack200062** [miekg/coredns#6332]
**What happened**:
Using node-local-dns(1.22.23) and coredns (v1.9.3-eksbuild.5). Facing problems with node-local-dns using cache. 
**What you expected to happen**:
We expect node-local-dns to serve reqests using cache within it's max ttl(30 sec in our case)
**How to reproduce it (as minimally and precisely as possible)**:
1) Use the same node-local-dns and coredns versions in EKS k8s implementation and setup coredns and node-local-dns with the configs below. 
2) Create a pod => exec into it => start resolving any record in a loop with a timeout of 10 sec, I've been resolving kubernetes.default.svc.cluster.local. (while true; do nslookup kubernetes.default.svc.cluster.local. && sleep 10; done)
3) Then go to any node where coredns pods located at and tcpdump on it. I've been using this command: tcpdump -i any -n -v | grep <record_name>. 
    At the same time you can tcpdump on the same node pod located at.
    
 So the problem is that node-local-dns continues to go to the upstream(coredns) using tcp and not using it's cache on each request being made.

- node-local-dns Corefile:
```
    cluster.local:53 {
        errors
        cache {
                success 9984 30
                denial 9984 5
        }
        reload
        loop
        bind 172.20.0.10 - kube-dns-svc
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9253
        health 169.254.20.10:8080
        }, where __PILLAR__CLUSTER__DNS__ is the address of coredns upstream svc
```
- coredns Corefile:
```
.:53 {  
    errors  
    health  
    prometheus:9153 
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure 
      fallthrough in-addr.arpa ip6.arpa
     }
    forward . /etc/resolv.conf
    cache 30  
    loop  
    reload  
    loadbalance
}
```

**Comment by chrisohaver** [comment]
> We expect node-local-dns to serve reqests using cache within it's max ttl(30 sec in our case)

Your CoreDNS is not configured to be able to resolve cluster domain records (e.g. in `cluster.local.`). It forwards everything to upstream DNS servers (from `/etc/resolv.conf`). Perhaps there is more to the picture that makes this configuration make sense, but on its own it does not.

It's reasonable to assume those upstream DNS servers (from `/etc/resolv.conf`) cannot resolve cluster domain records, thus nodelocal dns would get NXDOMAIN responses.  Those responses would be cached for a maximum of 5 seconds, according to the nodelocal cache configuration (not 30).  However, if the negative responses from the upstream DNS servers are missing SOA records, or are of type SERVFAIL, they won't be cached at all.

**Comment by Jack200062** [comment]
@chrisohaver Hi, Thanks for your answer. You're correct there's a typo in current  issue description CoreDns corefile(forgot to add kubernetes plugin with cluster.local zone) - fixed
So what I expect is that when performing a dnslookup client(pod) will have kind of this flow: 
pod => kube-dns svc => node-local-dns:
if there's an item in the cache - node-local-dns gives a response to the client
If there's no item in the cache - node-local-dns goes to upstream(coredns) using tcp 

But What I'm facing is that node-local-dns goes to coredns with tcp during each request from the client

**Comment by chrisohaver** [comment]
> But What I'm facing is that node-local-dns goes to coredns with tcp during each request from the client

This is expected if the response is not cache-able.

Can you give some concrete examples of queries and responses?  Please use a dns query tool such as `dig`, that shows DNS response codes.

**Comment by Jack200062** [comment]
Sorry, wdym  by not cache-able responses..?  Do you mean UPDATE requests for example? 

> Can you give some concrete examples of queries and responses

Sure, here I'm doing: **dig kubernetes.default.svc.cluster.local.**. Request being made from the pod in the cluster
<img width="543" alt="dig_command" src="https://github.com/coredns/coredns/assets/43829135/7a8c3ca5-9a49-47a5-a87e-3f3e34d03ced">

And judging by tcpdump from the node(where coredns pods located) - I can see tcp traffic related to this query

**Comment by chrisohaver** [comment]
> start resolving any record in a loop with a timeout of 10 sec, I've been resolving kubernetes.default.svc.cluster.local. (`while true; do nslookup kubernetes.default.svc.cluster.local. && sleep 10; done`)

The default TTL of Kubernetes records is 5 seconds.  Your nodelocal cache is configured to store records for _up to_ 30 seconds  - but it will not cache any records for longer than their original TTL (doing so would break DNS caching rules).

So sleeping for 10 seconds makes it expire from the cache before you query again.

**Comment by Jack200062** [comment]
So, basically you're saying that there is no much point in setting ttl higher than 5 sec to all cluster.local zone, because of the default ttl of kubernetes records? 

So we can assume that node-local-dns is going to cache kubernetes records if requests are being made, with a 3 sec timeout for example, am I right? 
while true; do nslookup kubernetes.default.svc.cluster.local. && sleep 3; done

**Comment by chrisohaver** [comment]
> Sorry, wdym by not cache-able responses..?

The issue is that entries expire from cache before you query them.  Nevertheless less to answer this question, dns responses that do not contain a TTL would not be cached (this happens for bad NXDOMAIN responses w/o SOA, or for SERVFAIL responses).

**Comment by chrisohaver** [comment]
> So, basically you're saying that there is no much point in setting ttl higher than 5 sec to all cluster.local zone, because of the default ttl of kubernetes records?

Yes.  Although you can increase the TTL of k8s records in the kubernetes plugin config with the `ttl` option.

> So we can assume that node-local-dns is going to cache kubernetes records if requests are being made, with a 3 sec timeout for example, am I right? while true; do nslookup kubernetes.default.svc.cluster.local. && sleep 3; done

Partly.  The cache still expires after 5 seconds.  So, iterating ...

```
T   - cache hit/miss
0s  - miss (new cache expires at 5s)
3s  - hit
6s  - miss (new cache expires at 11s)
9s  - hit
12s - miss (new cache expires at 17s)
15s - hit 
18s - miss (new cache expires at 23s)
21s - hit
24s - miss (new cache expires at 29s)
```
etc... (probably some addition mistakes in there, but you get the idea)

**Comment by Jack200062** [comment]
I see. Thank you @chrisohaver  - your comments helped me a lot to understand, what's happening :)
