### ISSUE TITLE
Some clarification regarding serve_stale parameters

### ISSUE THREAD

**Issue by Jack200062** [miekg/coredns#6334]
1) Is it possible to configure node-local-dns to serve_stale responses until upstream server is online? It's only possible to serve stale cache during 'duration' in corefile.
2) Do I understand correctly that in the case of serve_stale with verify refresh mode - node-local-dns are going to connect to the upstream each time client requests an item with expired ttl in cache?

**Comment by chrisohaver** [comment]
> Is it possible to configure node-local-dns to serve_stale responses until upstream server is online? 

 It's only possible to serve stale cache up to the defined `DURATION`.  You can make the duration really long, but there is no "infinity" option.

> node-local-dns are going to connect to the upstream each time client requests an item with expired ttl in cache?

Yes. This happens in both modes. `immediate` sends request upstream after sending response to client. `verify` sends request upstream before sending response to client.

**Comment by Jack200062** [comment]
But the difference between immediate and verify, is that immediate fetching request in made asynchronously, right?

**Comment by chrisohaver** [comment]
> But the difference between immediate and verify, is that immediate fetching request in made asynchronously, right?

Yes `immediately` does the request upstream asynchronously.  However, it will always send the expired cache entry to the client, regardless of when the response arrives.

**Comment by Jack200062** [comment]
I see. Thanks!

**Comment by Jack200062** [comment]
@chrisohaver Sorry, but I had another question ..
How will node-local-dns behave in situation if upstream is unavailabe for whatever reason and we have serve_stale option enabled with verify refresh mode parameter? or immediate? 
Will node-local-dns dos coredns trying to refresh it's item in the cache? Or it depends on the **expire** parameter from forward plugin?

**Comment by chrisohaver** [comment]
In both modes, it will serve a stale record from cache up to the defined `DURATION` in cache.

Forward's `expire` option is not related and doesn't come into play (it relates to _connection_ re-use, not _record_ caching).

**Comment by Jack200062** [comment]
So node-local-dns will spam coredns with requests in both mod, on each request? Even if upstream (coredns) is down?

**Comment by chrisohaver** [comment]
No. Cache will _try_ to refresh the cache entry on each request, but forward will not forward requests upstream if it deems the upstream is down.

**Comment by Jack200062** [comment]
> Cache will try to refresh the cache entry on each request

It turns out that node-local-dns will still try to reach the upstream in order to refresh the item in the cache by making requests to upstream? 
How does node-local-dns refreshes cache, I thought he is going to make a request on each time it wants to refresh an item in the cache

Coredns is down:
client makes a request => node-local-dns has this record expired in the cache => node-local-dns are going to try and refresh an item by going to the upstream, but in our case coredns(upstream) is down. Does this flow looks correct?

**Comment by chrisohaver** [comment]
Yes. If there are zero healthy upstream servers in the forward list, forward will send requests to one of the upstreams. In your case, since there is only one upstream, when it is unhealthy forward will still attempt to send queries to it.

**Comment by Jack200062** [comment]
Soo, then we can rely on the expire parameter in the forward plugin? If ttl=5, and default expire is 10s then node-local-dns will try to open a new (tcp) connection in our case each 10s? So even if the upstream is down, he'll still try to reach coredns on each request OR each 10s, but during the dns lookup? Meaning there's no "healtchecking" requests going to upstream

**Comment by chrisohaver** [comment]
Forward's expire option relates to connection re-use, not record caching.

**Comment by Jack200062** [comment]
By making each time request to upstream, node local dns checks whether upstream is online, right? Somewhere in the background asynchronously(if we using immediate option)
