### ISSUE TITLE
cname rewrite FORMERR random issue

### ISSUE THREAD

**Issue by valodzka** [miekg/coredns#6345]
**What happened**:

cname rewrite fails randomly

**How to reproduce it (as minimally and precisely as possible)**:

**UPDATE**: Issue can be reproduced with only coredns, read here https://github.com/coredns/coredns/issues/6345#issuecomment-1738521789

dnsmasq runs on port 53 and confired to request coredns for one zone:
`server=/internal/127.0.0.1#5350`

coredns runs on port 5350 and confired to rewrite .internal => .service.consul and to rewrite cnames to resolve them. For `.consul` services it requests consul and for everything else dnsmasq
Corefile
```
.:5350 {
  forward consul. 127.0.0.1:8600
  forward . 127.0.0.1
  log
  errors

  rewrite continue cname regex (.*) {1}
  rewrite name suffix .internal .service.consul
}

```

Consul has `mailer`  services configured with address `z.host`, `z.host` is configured in /etc/hosts so everyting happends localy. Consul has no recursors configured so it simply returns `CNAME`

Expected flow:

- dnmasq requests corends
- coredns perform name rewrite and requests consul
- consul returns cname
- coredns perform cname rewrite and requests dnsmasq for host name
- dnsmasq resolves it via /etc/hosts and returns ip
- coredns returns result

It works perfectly i request `mailer.internal` via dig (from dnsmasq or coredns directly). But if do `ping mailer.internal` (or `getent ahosts`) it fails in aprox 50% cases. It changes nothing if I run coredns on port 53 directly (and dnsmqsq on different port for communication with coredns), resolution fails randomly.

Here logs from failed case:

**coredns**
```
[INFO] 127.0.0.1:6979 - 63721 "AAAA IN z.host. udp 24 false 512" NOERROR qr,aa,rd,ra 58 0.00014504s
[INFO] 127.0.0.1:6979 - 7931 "A IN mailer.internal. udp 45 false 512" NOERROR qr,aa,rd 129 0.027540822s
[INFO] 127.0.0.1:6979 - 36603 "AAAA IN mailer.internal. udp 24 false 512" FORMERR qr,rd 48 0.052110229s
```

**dnsmasq**
```
Sep 27 19:39:08 dnsmasq[795187]: query[A] mailer.internal from 127.0.0.1
Sep 27 19:39:08 dnsmasq[795187]: forwarded mailer.internal to 127.0.0.1#5350
Sep 27 19:39:08 dnsmasq[795187]: query[AAAA] mailer.internal from 127.0.0.1
Sep 27 19:39:08 dnsmasq[795187]: forwarded mailer.internal to 127.0.0.1#5350
Sep 27 19:39:08 dnsmasq[795187]: query[AAAA] z.host from 127.0.0.1
Sep 27 19:39:08 dnsmasq[795187]: /etc/hosts z.host is :ipv6-addr:
Sep 27 19:39:08 dnsmasq[795187]: reply mailer.internal is NODATA-IPv4
Sep 27 19:39:08 dnsmasq[795187]: reply error is 1
```

Here logs from successfull case:

**coredns**
```
[INFO] 127.0.0.1:6979 - 8522 "AAAA IN z.host. udp 24 false 512" NOERROR qr,aa,rd,ra 58 0.000178474s
[INFO] 127.0.0.1:6979 - 31171 "A IN mailer.internal. udp 45 false 512" NOERROR qr,aa,rd 129 0.051229646s
[INFO] 127.0.0.1:6979 - 8522 "AAAA IN z.host. udp 24 false 512" NOERROR qr,aa,rd,ra 58 0.00021655s
[INFO] 127.0.0.1:6979 - 8522 "AAAA IN mailer.internal. udp 24 false 512" NOERROR qr,aa,rd 129 0.051307307s
```

**dnsmasq**
```
Sep 27 19:39:00 dnsmasq[795187]: query[A] mailer.internal from 127.0.0.1
Sep 27 19:39:00 dnsmasq[795187]: forwarded mailer.internal to 127.0.0.1#5350
Sep 27 19:39:00 dnsmasq[795187]: query[AAAA] mailer.internal from 127.0.0.1
Sep 27 19:39:00 dnsmasq[795187]: forwarded mailer.internal to 127.0.0.1#5350
Sep 27 19:39:00 dnsmasq[795187]: query[AAAA] z.host from 127.0.0.1
Sep 27 19:39:00 dnsmasq[795187]: /etc/hosts z.host is :ipv6-addr:
Sep 27 19:39:00 dnsmasq[795187]: reply mailer.internal is NODATA-IPv6
Sep 27 19:39:00 dnsmasq[795187]: query[AAAA] z.host from 127.0.0.1
Sep 27 19:39:00 dnsmasq[795187]: /etc/hosts z.host is :ipv6-addr:
Sep 27 19:39:00 dnsmasq[795187]: reply mailer.internal is NODATA-IPv4
```

My guess it's related to fact that something (glibc?) runs parallel A and AAAA resolution and and causes FORMERR  somehow.

**Environment**:

- the version of CoreDNS: 1.11.1
- OS (e.g: `cat /etc/os-release`): Debian 12
- Others: dnsmasq  2.89-1

**Comment by chrisohaver** [comment]
On the surface, it looks like this configuration would produce an infinite forwarding loop.
And I'm not quite grasping the purpose of the cname rewrite ... `(.*) {1}` seems like it would be a no-op, matching the entire cname target and replacing it with the match (i.e. changing nothing, but doing extra work and lookups in the process).

**Comment by valodzka** [comment]
> On the surface, it looks like this configuration would produce an infinite forwarding loop.

No, it doesn't. At least resolution (successfull or not) is fast.

> And I'm not quite grasping the purpose of the cname rewrite ... (.*) {1} seems like it would be a no-op, matching the entire cname target and replacing it with the match (i.e. changing nothing, but doing extra work and lookups in the process).

You described reason yourself here https://github.com/coredns/coredns/pull/6216#issuecomment-1645488272
> no-op cname rewrite (rewrite target to itself) may result in looking up and adding the missing target record

**Comment by chrisohaver** [comment]
> You described reason here https://github.com/coredns/coredns/pull/6216#issuecomment-1645488272

I see.  Thanks for referring me to my own comment.

**Comment by chrisohaver** [comment]
I’d like to try to reproduce this locally. Can you share the dnsmasq configuration?

**Comment by valodzka** [comment]
@chrisohaver I played a bit more and turns out that reproducer can be simplifed to only coredns:

Corefile
```
# ~consul
.:86 {
  template IN ANY mailer.service.consul {
      answer "mailer.service.consul 60 IN CNAME z.host"
  }
}

# ~dnsmasq
.:55 {
  log
  errors

  hosts {
    127.0.0.1 z.host
    ::1 z.host

    ttl 1
  }
}

.:53 {
  forward consul. 127.0.0.1:86
  forward . 127.0.0.1:55
  log
  errors

  rewrite continue cname regex (.*) {1}
  rewrite name suffix .internal  .service.consul
}

```

Thats all, then ` ./coredns -conf Corefile`. As you can see below some getent calls do fail (return nothing) and other don't 

```
~# getent ahosts mailer.internal
~# getent ahosts mailer.internal
::1             STREAM z.host
::1             DGRAM
::1             RAW
~# getent ahosts mailer.internal
::1             STREAM z.host
::1             DGRAM
::1             RAW
~# getent ahosts mailer.internal
::1             STREAM z.host
::1             DGRAM
::1             RAW
~# getent ahosts mailer.internal
~# getent ahosts mailer.internal
```

**Critial**: `getent `or other program using system resolution must be used, not `dig`. Also probably dual ip stack linux machine required (/etc/resolv.conf should be configured to 127.0.0.1 of course).

**Comment by chrisohaver** [comment]
This is difficult for me to reproduce locally due to a DNS agent running on my system (enforced by company policy) that listens on port 53. I can test on higher ports, but since `getent` cannot specify a server/port that is not an easy option. I could perhaps execute getent from within a docker container, and use iptables to rewrite port 53 to a higher port - or run coredns as a forwarder in the container to forward to coredns host instance on higher port.  

I did test on a higher port using `nslookup`, which does do a lookup for both A and AAAA, but it does not produce the FORMERR issue. AFAIK, `nslookup` doesn't use glibc to do its lookups.

**Comment by valodzka** [comment]
> I did test on a higher port using nslookup, which does do a lookup for both A and AAAA, but it does not produce the FORMERR issue. AFAIK, nslookup doesn't use glibc to do its lookups.

Just tested and can confirm that issue isn't reproducible with `nslookup`

**Comment by valodzka** [comment]
Thank to wonderfull [arch wiki authors](https://wiki.archlinux.org/title/Domain_name_resolution) I learnt about `options single-request` and now I can confirm that the issue cause is parallel A/AAAA resolution, adding `single-request` to `/etc/resolv.conf` resolves the issue.

**Comment by valodzka** [comment]
Well, turns out that simply running two dig in parallel is enougth to reproduce:

`dig @127.0.01 -p 5353 -t AAAA mailer.internal > 1 & dig @127.0.0.1 -p 5353 -t A mailer.internal > 2 & wait`

**Comment by chrisohaver** [comment]
Cool. That will be easier to replicate and debug.

**Comment by chrisohaver** [comment]
Additional observation: When there is a FORMERR, The other query has the wrong answer type.  That is, if the A response is a FORMERR, then the AAAA response will contain an A record in the answer instead of an AAAA. The messages do have different IDs as expected.

... and I cannot replicate the format error response when I run in debug mode, even without any stops ... perhaps debug mode slows things down enough to prevent the concurrency from happening.  But the types are mismatched when i test in debug mode, the answer to one of the questions is always the wrong type (as if it's the same answer being used for both responses).
