### ISSUE TITLE
CoreDNS does not work on recent amazon-linux-2023 releases

### ISSUE THREAD

**Issue by gabrielbull** [miekg/coredns#6368]
**What happened**:

Starting with `al2023-ami-2023.2.20231002.0-kernel-6.1-x86_64` (ami-036f5574583e16426), setting up a fresh Kubernetes cluster will not work and CoreDNS will not be able to be setup with either calico or flannel. 

Affected versions:
- ami-09d9029d9fc5e5238 |  al2023-ami-2023.2.20231016.0-kernel-6.1-x86_64  |
- ami-080c09858e04800a1 |  al2023-ami-2023.2.20231011.0-kernel-6.1-x86_64  |
- ami-036f5574583e16426 |  al2023-ami-2023.2.20231002.0-kernel-6.1-x86_64  |

**What you expected to happen**:

CoreDNS should start and work.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
sudo yum upgrade -y
sudo yum install -y nmap-ncat iproute-tc git
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

# sysctl params required by setup, params persist across reboots
cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

# Apply sysctl params without reboot
sudo sysctl --system

# Install containerd
sudo yum install containerd -y
sudo mkdir -p /etc/containerd
sudo containerd config default | sudo tee /etc/containerd/config.toml
sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
sudo sed -i 's/sandbox_image = "registry.k8s.io\/pause:.*/sandbox_image = "registry.k8s.io\/pause:3.8"/g' /etc/containerd/config.toml
sudo systemctl restart containerd
sudo systemctl enable --now containerd

# Add kubernetes repo to yum
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

# Set SELinux in permissive mode (effectively disabling it)
sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

# Install kubernetes
sudo yum install -y kubelet-1.27.3-0 kubeadm-1.27.3-0 kubectl-1.27.3-0 --disableexcludes=kubernetes
sudo systemctl restart kubelet
sudo systemctl enable --now kubelet
```

Steps to reproduce with calico:
```bash
sudo kubeadm init --pod-network-cidr=192.168.0.0/16

# Install calico
sudo curl https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/calico.yaml -O
kubectl apply -f calico.yaml --kubeconfig=/etc/kubernetes/admin.conf
```

Steps to reproduce with flannel:
```bash
sudo kubeadm init --pod-network-cidr=10.244.0.0/16

# Install flannel
kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
```

**Anything else we need to know?**:

CoreDNS fails to fetch the "https://10.96.0.1:443/version" even if it is reachable using CURL or similar methods.

**Environment**:

- the version of CoreDNS: 1.10.1

**Screenshots**:
Expected screenshot from al2023-ami-2023.2.20230920.1-kernel-6.1-x86_64 (ami-0d406e26e5ad4de53):
<img width="1274" alt="277453123-795aa57a-bbbe-4aeb-8b6e-fe79b73a2dfb" src="https://github.com/amazonlinux/amazon-linux-2023/assets/671923/49c58c43-c80b-4d61-8d4d-05efb93af12a">

Actual screenshot from al2023-ami-2023.2.20231002.0-kernel-6.1-x86_64 (ami-036f5574583e16426):
<img width="1277" alt="Capture d’écran, le 2023-10-23 à 15 27 05" src="https://github.com/amazonlinux/amazon-linux-2023/assets/671923/1eda4b33-6f40-4b59-b09c-8b6ba911c1d4">

**Comment by johnbelamaric** [comment]
Something else is wrong. CoreDNS can’t reach the API server. I suspect
neither can other apps. Notice all those crash looping pods in your second
screenshot (the restarts)? Check those logs too. Maybe a cluster networking
issue.

**Comment by gabrielbull** [comment]
@johnbelamaric you are right the issue is with Amazon Linux 2023 and a recent build that broke docker and Kubernetes. So I opened a ticket there instead.
