### ISSUE TITLE
How to run a command in coredns container ?

### ISSUE THREAD

**Issue by barmaxence** [miekg/coredns#6413]
I run CoreDNS using Docker (with 'health' plugin enabled) and I want to perform a health check in my docker-compose.yml file.
But it seems there is no `sh` in the docker image.

How can I perform the health check ?

```yml
healthcheck:
      test: curl --output /dev/null --silent --head --fail http://coredns:8080/health
```

**Comment by johnbelamaric** [comment]
The images contain only CoreDNS and certificates for TLS trust chains. You'll need to build your own images if you need other things in them.
