### ISSUE TITLE
Question regarding NS lookups made by Coredns

### ISSUE THREAD

**Issue by Jack200062** [miekg/coredns#6414]
Hi! I have a question. We have this flow of dns lookups: 

```
                                             
Pod => Node-local-dns: (2 ways)
1) if (cluster.local) => Coredns
2) if (. e.g root zone) => another upstream(forward /etc/resolv.conf)                                           
```

While I were investigating some dns issues - found some NS lookups for root zone(.) coming from coredns to "another upstream" located in /etc/resolv.conf. Seems like this is a part of forward plugin logic. So each time coredns  receives any response that is consideres as a network error (REFUSED, NOTIMPL, SERVFAIL, etc) he's going to perform health check with default interval of 0,5s

**The question is**: With the default coredns setup, meaning there is only "forward /etc/resolv.conf" line in Corefile, can there be any other reasons why Coredns would make such NS lookups? Or there's seems to be either prolbem with upstream or client is making werid lookups. Maybe there is a timeout for which this can happen?

Node-local-dns Corefile:
```
    cluster.local:53 {
        errors
        cache {
                success 9984 30
                denial 9984 5
                serve_stale 12h
        }
        reload
        loop
        bind 172.20.0.10 169.254.20.10
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9253
        health 169.254.20.10:8080
        }
    in-addr.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind 172.20.0.10 169.254.20.10
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9253
        }
    ip6.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind 172.20.0.10 169.254.20.10
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9253
        }
    .:53 {
        errors
        cache 30 {
            serve_stale 12h
        }
        reload
        loop
        log {
          class error
        }
        bind 172.20.0.10 169.254.20.10
        forward . /etc/resolv.conf
        prometheus :9253
        }
```

Coredns Corefile:
```
    .:53 {
      errors
      health
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      prometheus :9153
      forward . /etc/resolv.conf
      cache 30
      loop
      reload
      loadbalance
    }   
```

**Comment by chrisohaver** [comment]
> The question is: With the default coredns setup, meaning there is only "forward /etc/resolv.conf" line in Corefile, can there be any other reasons why Coredns would make such NS lookups?


The health checks are only done when CoreDNS fails to get a DNS response from the upstream (e.g. timeout, connection refused, etc).  DNS protocol error type responses (such as REFUSED, NOTIMPL, SERVFAIL, etc), are not considered failures in this context, and those responses are passed along to the client.

**Comment by Jack200062** [comment]
In forward plugin [doc](https://coredns.io/plugins/forward/). There is a sentence saying: 

> Any response that is not a network error (REFUSED, NOTIMPL, SERVFAIL, etc) is taken as a healthy upstream

That's why I thought that if coredns would receive a SERVFAIL response from upstream, it would perform health check with recursive NS . lookup. Am I wrong? Could you clarify please this moment to me, thanks!

**Comment by chrisohaver** [comment]
> I thought that if coredns would receive a SERVFAIL response from upstream, it would perform health check with recursive NS . lookup. Am I wrong? Could you clarify please this moment to me, thanks!

"Any response that is not a network error (REFUSED, NOTIMPL, SERVFAIL, etc) is taken as a healthy upstream"

Therefore...

"A response of SERVFAIL is considered a healthy upstream"

Since in this case the server is considered healthy, no health check is performed.

This is as designed.

**Comment by chrisohaver** [comment]
> "Any response that is not a network error (REFUSED, NOTIMPL, SERVFAIL, etc) is taken as a healthy upstream"

The phrasing in this sentence is ambiguous.  "(REFUSED, NOTIMPL, SERVFAIL, etc)" are examples of responses that are _not_ network errors.  They are not examples of responses that _are_ network errors.  Those Response codes are specifically called out because they _look_ like errors, but they are not _network_ errors.  

Nevertheless REFUSED, NOTIMPL, SERVFAIL cannot be network errors, because they are DNS response codes, and the only way you can get a dns response code back is if there was a successful network connection.
