### ISSUE TITLE
Why k8s pod subdomains have IPs in the name?

### ISSUE THREAD

**Issue by mrblacyk** [miekg/coredns#6439]
Hey guys!

I'm learning Kubernetes (v1.26.0) and I'm using coredns as the DNS server.

Specifically I'm learning about various objects registering in the DNS server for easier object discovery. 

It makes sense to me that when I create a service, it get registered and I can find its IP based on the service name, i.e.:

```bash
$ kc get svc
NAME    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
nginx   ClusterIP   10.102.213.74   <none>        80/TCP    38s

$ nslookup nginx.default.svc.cluster.local 10.96.0.10
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   nginx.default.svc.cluster.local
Address: 10.102.213.74
```

However, it doesn't make any sense to me when it comes to pod discovery via DNS.

```bash
$ kc get po -o wide
NAME                     READY   STATUS    RESTARTS   AGE   IP               NODE             NOMINATED NODE   READINESS GATES
nginx-748c667d99-c6c29   1/1     Running   0          13s   192.168.84.137   kube-worker-03   <none>           <none>

$ nslookup nginx-748c667d99-c6c29.default.pod.cluster.local 10.96.0.10
Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find nginx-748c667d99-c6c29.default.pod.cluster.local: NXDOMAIN

# Above doesn't work, but the instructor said we can "translate" / "find" IP of the Pod using the query below
# ..which has its IP in the name

$ nslookup 192-168-84-137.default.pod.cluster.local 10.96.0.10
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   192-168-84-137.default.pod.cluster.local
Address: 192.168.84.137
```

Here's where it doesn't make sense to me. 

Why would I want to ever query DNS with an IP literally in its subdomain part? I know that IP already by then. Is this some backward compatibility for something? Or does Kubernetes require to have this functionality and coredns doesn't allow finding pods by their name, and yet has to stay compliant with k8s requirements? I'm guessing.

Thanks for any tips helping me understand. 

Apologies it this is not something specific to coredns, but other component of Kubernetes.

**Comment by mrblacyk** [comment]
Forgot to mention that I also noticed I can put any IP in the FQDN and it "translates" it back to me, i.e.:

```bash
$ nslookup 99-88-77-66.default.pod.cluster.local 10.96.0.10
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   99-88-77-66.default.pod.cluster.local
Address: 99.88.77.66
```

**Comment by chrisohaver** [comment]
Yes, it is an old backward compatibility thing that was in a deprecated state for years in the [Kubernetes DNS-Based Service Discovery Specification](https://github.com/kubernetes/dns/blob/master/docs/specification.md), but has since been removed from the spec entirely.

We have not yet removed the function from CoreDNS, but may eventually do that.

The preferred K8s way of referencing individual pods is to use endpoint hostnames.   e.g. `hostname1.my-service.default.svc.cluster.local.` This requires you to define a Headless Service for the pod.

**Comment by mrblacyk** [comment]
Thank you very much for the explanation! Much appreciated :)
