### ISSUE TITLE
forward plugin policy sequential issues

### ISSUE THREAD

**Issue by wsy0101** [miekg/coredns#6449]
The configuration of the Fowrard plugin I am currently using is as follows:
`.:53 {
  forward . 172.16.210.130 172.16.102.245 8.8.8.8 {
    policy sequential
  }
  errors
  log
  health
}`

Is it true that when a client makes a query request, all requests will only be forwarded to the first upstream server 172.16.210.130, and only when the 172.16.210.130 server goes down will the query request be forwarded to the second upstream server 172.16.102.245?

However, my requirement is that when the client makes a query request, if the first upstream server parses the result as NXDOMAIN, SERVERFAIL, or no anwser, that is to say, when the first upstream server cannot parse the query request, it will forward the request to the second upstream server 172.16.102.245, and every time the client initiates a request, it must first query the first upstream server, When the first upstream server is unable to resolve, the request is forwarded to the second server. When the second server is unable to resolve, it is then forwarded to the third server.

Does the current version of Coredns support this?

How to adjust the configuration of this forwarding server if supported?

**Comment by chrisohaver** [comment]
> Is it true that when a client makes a query request, all requests will only be forwarded to the first upstream server [...] and only when [that server] goes down will the query request be forwarded to the second upstream server [...]?

yes

What you want to do is not supported by CoreDNS default plugins.

Look into compiling CoreDNS with the external plugin _alternate_. https://github.com/coredns/alternate

**Comment by wsy0101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
