### ISSUE TITLE
<namespace>.svc.cluster.local returns NOERROR

### ISSUE THREAD

**Issue by davidnortonjr-sps** [miekg/coredns#6450]
Hello, I don't think this is a bug, but I'm not quite sure how to get around it. I have a config file:

```
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
        rewrite name foobar-api kubernetes.default.svc.cluster.local
    }
```

The idea being that clients can use the hostname `foobar-api` as an alias for another service name.

However, with Kubernetes default DNS resolution, clients will use the search names, and resolve `foobar-api.<namespace>.svc.cluster.local`, `foobar-api.svc.cluster.local`, etc. This works fine, until we create a namespace named `foobar-api`. Then, most clients will bail out after they get a NOERROR response from CoreDNS for `foobar-api.svc.cluster.local`:

```
$ dig foobar-api +search +showsearch

; <<>> DiG 9.9.5-9+deb8u15-Debian <<>> foobar-api +search +showsearch
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 36276
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;foobar-api.default.svc.cluster.local. IN A

;; AUTHORITY SECTION:
cluster.local.		30	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1704485479 7200 1800 86400 30

;; Query time: 1 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Fri Jan 05 20:29:47 UTC 2024
;; MSG SIZE  rcvd: 158


; <<>> DiG 9.9.5-9+deb8u15-Debian <<>> foobar-api +search +showsearch
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31409
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;foobar-api.svc.cluster.local.	IN	A

;; AUTHORITY SECTION:
cluster.local.		30	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1704485479 7200 1800 86400 30

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Fri Jan 05 20:29:47 UTC 2024
;; MSG SIZE  rcvd: 150
```

Does this make sense? I don't love the default Kubernetes search list, but it's going to be a while before we can change it. A workaround that seems to work is to add `foobar-api.svc.cluster.local` as a rewrite rule as well, so that we can catch this -- but it seems hacky.

```
        rewrite name foobar-api.svc.cluster.local kubernetes.default.svc.cluster.local
```

Any other suggestions?

**Comment by chrisohaver** [comment]
That's exactly what I would suggest.

Alternately, if a client queries for a FQDN (which in DNS, includes a trailing dot `foobar-api.`), the client will not expand the search, and just search the bare name queried.  But not all clients can be configured to do this - many thinking that a trailing dot is invalid (e.g. in the context of a URL).
