### ISSUE TITLE
Dynamically change the DNS servers to forward the DNS request

### ISSUE THREAD

**Issue by kosmas-valianos** [miekg/coredns#6485]
Hello, I have a custom plugin that uses logic which brings DNS server settings according to the received DNS request. The question is how can the plugin "set" dynamically the DNS server to forward the received DNS request? I am thinking that the custom plugin could initialize/set-up somehow the forward plugin and then pass it on to it.

A second question, assuming the above can be solved, is if it is possible through the custom plugin to get hold of the underlying socket which will be used for sending the DNS request to the DNS server. Basically to be able to set a Dialer so that things like `SetsockoptInt` can be done on the socket (need to set a mark with `SO_MARK`)

```
func (m myPlugin) ServeDNS(ctx context.Context, w dns.ResponseWriter, r *dns.Msg) (int, error) {
// Logic that brings the DNS server details according to stuff from the DNS request
// Set up the forward DNS server according to these details
// Mark the socket (custom Dialer) of that DNS server
// Forward the DNS request  and send back the reply

**Comment by kosmas-valianos** [comment]
It looks there is no proper way to do this. While in your plugin you are able to create a `proxy.Proxy` and assign it to a `forward.Forward` with `SetProxy()`, you cannot set parameters on the `proxy.Proxy` as the parameters are private. In general, all these are only meant to get filled in from the configuration Corefile so it doesn't seem the use case is possible.

**Comment by chrisohaver** [comment]
The best way to approach this may instead be to use the view plugin, extending the view plugin if necessary.

**Comment by chrisohaver** [comment]
What aspects of the request are used to determine which proxy is used?

**Comment by chrisohaver** [comment]
Ah. You don’t want to dynamically select from a list, rather you want to allow the client to actually specify the ip address of the proxy?

If so, this would require a custom plugin that actually does the forwarding itself. Ie it probably cannot leverage the existing forward plugin to forward the request.

**Comment by kosmas-valianos** [comment]
>You don’t want to dynamically select from a list

Yeah exactly. Basically the DNS request is inspected and according to how it "looks like"(a magic ID prepended in the beginning of the hostname) an external db is queried (memcached) where the DNS servers information exist (IP, port and **routing mark**). The DNS request shall be forwarded to the respected DNS server and the socket used for that to be set with **routing mark**

>probably cannot leverage the existing forward plugin

Yeah because it's impossible to play with `proxy.Proxy` and use them dynamically

**Comment by chrisohaver** [comment]
> an external db is queried (memcached) where the DNS servers information exist

This is effectively selecting from a list of servers defined in a database is it not?

**Comment by kosmas-valianos** [comment]
Yes but there are not static at all, changing all the time, so they cannot be used in the Corefile if that's what you are heading at.

**Comment by chrisohaver** [comment]
Yeah. For this reason and for the custom socket option reasons, you’ll need a custom plugin that does the forwarding/proxy itself.

**Comment by kosmas-valianos** [comment]
Yeap, and to close this... I assume as the normal `dns.ResponseWriter` will be used to send back the responses, the normal power of coreDNS will still be available (caches etc.) which makes it much more appealing compared to writing this outside the realm of coreDNS

**Comment by chrisohaver** [comment]
> Yeap, and to close this... I assume as the normal `dns.ResponseWriter` will be used to send back the responses, the normal power of coreDNS will still be available (caches etc.)

yes
