### ISSUE TITLE
hostfile is not loaded periodically as expected

### ISSUE THREAD

**Issue by GitHub-huyuan** [miekg/coredns#6496]
Hello, I don't think this is a bug, but I'm not quite sure how to get around it. I have a config file

```
.:53 {
    forward . 183.60.83.19 183.60.82.98 {
        prefer_udp
        max_fails 4
        timeout 2000ms
        write_timeout 3000ms
        read_timeout 3000ms
        max_concurrent 100000
    }
    cache
    reload 3s
    log
    prometheus 0.0.0.0:9153
    errors
    hosts hostname {
        reload 3s
        ttl 10
        fallthrough
    }
}
```
Sometimes, I update the hostname (hostfile file) and add a new record in it, but it never takes effect
![image](https://github.com/coredns/coredns/assets/40454512/d7f64ffe-95af-4775-8797-a1b616d91718)
![image](https://github.com/coredns/coredns/assets/40454512/791c14d8-336d-4419-a779-805b67c97932)

I've read the plugin code but still haven't found the cause. 
Any other suggestions?

**Comment by chrisohaver** [comment]
You do say "never takes effect"... but is it possible that cache has the previous answer in it that has not yet expired?

**Comment by GitHub-huyuan** [comment]
Sorry, it's not true that it doesn't work all the time, but it takes a long time(About ten minutes) before it does.Are you talking about the cache plugin?But I'm sure the ip or machine name wasn't there before the hostfile.

**Comment by chrisohaver** [comment]
The cache will also keep negative answers (NXDOMAIN responses).
If a client makes a query for a host that is not defined in the _hosts_ plugin, the query gets passed to one of the upstream dns servers defined by the _forward_ plugin.  Those upstream servers may respond with an NXDOMAIN, in which case the _cache_ plugin would cache that result and server it until the TTL expires.

**Comment by GitHub-huyuan** [comment]
Thanks so much for the ideas provided. Is there any way we can tell that this parses in our cache

**Comment by chrisohaver** [comment]
As a test, you could disable cache and see if the issue persists.

**Comment by GitHub-huyuan** [comment]
In addition to this, I've run into another phenomenon where the A record parses fine, but there is a problem with the PTR
![image](https://github.com/coredns/coredns/assets/40454512/abb32eb6-b319-49e5-b420-53897a47a355)

**Comment by GitHub-huyuan** [comment]
And is there any way I can adjust this refresh time?

**Comment by chrisohaver** [comment]
> As a test, you could disable cache and see if the issue persists.

have you tested this?

**Comment by GitHub-huyuan** [comment]
Yes,Thanks.I can see why this is happening.I think this is the key
![image](https://github.com/coredns/coredns/assets/40454512/01bcb834-7019-471c-90a4-40ab05a836dd)
Because the PTR record is finally parsed by the forward
