### ISSUE TITLE
CoreDNS->Prometheus_Blackbox_Exporter plugin

### ISSUE THREAD

**Issue by nser77** [miekg/coredns#6531]
**What would you like to be added**:

TCP/IP health check.

**Why is this needed**:

CoreDNS only supports health checks for HTTP protocol but there are some cases where someone needs to monitor other TCP/IP based protocols, like SMTP, AMQP, FTP, SSH, etc..

**Comment by chrisohaver** [comment]
These seem like external plugin material unless a specific protocol can be identified as one that would have wide application.

**Comment by SuperQ** [comment]
This doesn't even seem like a CoreDNS issue. More like a Prometheus Blackbox Exporter thing.

**Comment by nser77** [comment]
Thanks to both of you for your answers.

> This doesn't even seem like a CoreDNS issue. More like a Prometheus Blackbox Exporter thing.

Really good and smart catch.

**Comment by nser77** [comment]
How should the `CoreDNS->Prometheus_Blackbox_Exporter` plugin be named?

Something like `cdpbe`?

**Comment by SuperQ** [comment]
It is a separate project, there is nothing to add here.
