### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by GitHub-huyuan** [miekg/coredns#6537]
1、If the return value is RcodeRefused, is the message automatically written back? Where is this logic?
2、The return value of ServerDNS is 0, which simply means that the plug-in processed it as expected？

**Comment by chrisohaver** [comment]
> 1、If the return value is RcodeRefused, is the message automatically written back? Where is this logic?

Assuming you mean "return value _from a plugin's implementation of ServeDNS_ is RcodeRefused": Yes, this happens in core/dnsserver/server.go ServerDNS().

> 2、The return value of ServerDNS is 0, which simply means that the plug-in processed it as expected?

If the return value from a plugin's implementation of ServeDNS is 0 (NOERROR), then the server assumes the plugin has written an answer to the client already.

A plugin's implementation of ServeDNS should never write an answer to the client if it returns an rcode listed in the `plugin.ClientWrite()` function. If it does, two responses will be written to the client (one by the plugin, and a second by the server).  In some cases a plugin will need to write one of these type responses to the client itself. When a plugin does that, it should return a 0 (NOERROR) rcode even if that was not the actual rcode sent in the DNS response to the client, so the sever does not also send an error response to the client.

**Comment by GitHub-huyuan** [comment]
Thanks
