### ISSUE TITLE
Monitoring the status of upstream DNS server

### ISSUE THREAD

**Issue by chandanD4** [miekg/coredns#6563]
Is there metrics available to monitor the status of upstream DNS server.    We have metrics which is based on the response received from the upstream dns server.  However, we are looking here for the scenario to track the attempted connection request i.e. over TCP or UDP to the upstream from coredns which resulted in failure.  We are looking metrics to track the connection failure count, as of now this only recorded in the log as failure message.  

Any suggestion or plan this would be very useful.

**Comment by SuperQ** [comment]
Have you looked at the [forward plugin documentation](https://coredns.io/plugins/forward/#metrics)?

**Comment by chandanD4** [comment]
I had checked the documentation an found the probably the suitable metrics . coredns_forward_healthcheck_failures_total.  It get incremented when the upstream dns server is not reachable.  However later we observed the counter is getting incremented irrespective of whether we are generating the request or not.  Moreover this metrics keep incrementing when the upstream server is reachable.  It does not looks to be usable  .  Not sure if i am missing something here . Need help on this.  Struggling to differentiate when the upstream up or down ... @SuperQ  @chrisohaver

**Comment by SuperQ** [comment]
How else would it be "usable". How do you know an upstream is down or not if you don't send requests? DNS is a stateless protocol.

Generally this falls under the [RED Method](https://grafana.com/blog/2018/08/02/the-red-method-how-to-instrument-your-services/) of "availability". You monitor the "error ratio", which would be the rate of errors over the rate of requests.

**Comment by chrisohaver** [comment]
Health checks don’t start until there is a failed query, and then they don’t stop until a health check passes (gets a response from upstream). From your description it sounds like your upstream is not responding to the health check queries. Can you enable logging and show coredns logs?

**Comment by chandanD4** [comment]
It error at my end .  Thanks for the support .  It is working as explained.
