### ISSUE TITLE
CoreDNS on FreeBSD does not answer reverse lookup requests (both hosts and file plugins)

### ISSUE THREAD

**Issue by leodus** [miekg/coredns#6584]
What happened: 
CoreDNS does not answer reverse queries when using the hosts and/or file plugin.
The hosts plugin should create PTR records automatically (this is stated in the documentation)!

What you expected to happen:
CoreDNS to answer reverse lookup queries

How to reproduce it (as minimally and precisely as possible):
Using the hosts plugin:
```
$ cd /etc/coredns

$ cat Corefile
.:53 {
   log
   errors
   hosts /etc/coredns/zones/hosts intra.domain.nu
}

$ cat zones/hosts
172.16.1.103      tst-03.intra.domain.nu ns1.intra.domain.nu
172.16.1.21       hst-01.intra.domain.nu

$ sudo service coredns restart
Stopping coredns.
Starting coredns.

$ sudo service coredns status
coredns is running as pid 55541.

$ drill @127.0.0.1 ns1.intra.domain.nu
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 38850
;; flags: qr aa rd ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; ns1.intra.domain.nu. IN      A

;; ANSWER SECTION:
ns1.intra.domain.nu.    3600    IN      A       172.16.1.103

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Tue Apr  2 12:14:13 2024
;; MSG SIZE  rcvd: 72

$ drill @127.0.0.1 -x 172.16.1.103
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 44500
;; flags: qr rd ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; 172.16.1.103.        IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Tue Apr  2 12:16:11 2024
;; MSG SIZE  rcvd: 30
```
Anything else we need to know?:
No

**Environment**:

- the version of CoreDNS: CoreDNS-1.11.1
freebsd/amd64, go1.20.14, 
- Corefile: see above
- logs, if applicable:

```
Apr  2 12:13:50 tst-03 daemon[55578]: .:53
Apr  2 12:13:50 tst-03 daemon[55578]: CoreDNS-1.11.1
Apr  2 12:13:50 tst-03 daemon[55578]: freebsd/amd64, go1.20.14, 
Apr  2 12:14:13 tst-03 daemon[55578]: [INFO] 127.0.0.1:27353 - 38850 "A IN ns1.intra.domain.nu. udp 37 false 512" NOERROR qr,aa,rd 72 0.000438251s
Apr  2 12:15:24 tst-03 daemon[55578]: [INFO] 127.0.0.1:13192 - 32252 "A IN 172.16.1.21. udp 29 false 512" - - 0 0.000057433s
Apr  2 12:15:24 tst-03 daemon[55578]: [ERROR] plugin/errors: 2 172.16.1.21. A: plugin/hosts: no next plugin found
Apr  2 12:15:44 tst-03 daemon[55578]: [INFO] 127.0.0.1:36224 - 38396 "A IN 172.16.1.103. udp 30 false 512" - - 0 0.000076058s
Apr  2 12:15:44 tst-03 daemon[55578]: [ERROR] plugin/errors: 2 172.16.1.103. A: plugin/hosts: no next plugin found
Apr  2 12:16:11 tst-03 daemon[55578]: [INFO] 127.0.0.1:21962 - 44500 "A IN 172.16.1.103. udp 30 false 512" - - 0 0.000035653s
Apr  2 12:16:11 tst-03 daemon[55578]: [ERROR] plugin/errors: 2 172.16.1.103. A: plugin/hosts: no next plugin found
```

- OS (e.g: `cat /etc/os-release`): FreeBSD 13.2-RELEASE-p11
- Others:

**Comment by chrisohaver** [comment]
Looks like drill is not sending a reverse query. 
It’s sending an A request for the ip address, which won’t match any A records in host, and thus the servfail response. If it were sending a reverse query correctly, it would be for a PTR request and the domain name would be in a different format.

**Comment by chrisohaver** [comment]
I’m not familiar with drill, but it may be sensitive to flag/argument order and silently ignore flags not positioned immediately after the command name. Usage is `drill [ OPTIONS ] name [ @server ] [ type ] [ class ]`

**Comment by chrisohaver** [comment]
IOW, try ordering the flags/options as per the drill man page: `drill -x 172.16.1.103 @127.0.0.1`

if that doesn't work, construct the reverse query manually: `drill 103.1.16.172.in-addr.arpa @127.0.0.1 PTR`

(and if that doesn't work, try using `dig` instead of `drill`)

**Comment by leodus** [comment]
Hi,
thank you for all the reactions and comments.
All ok now with both dig and drill!
Have reverse lookup now working (with both hosts and file plugin)!
