### ISSUE TITLE
proposal(plugin/dnstap): add configuration for filtering messages 

### ISSUE THREAD

**Issue by mathetake** [miekg/coredns#6640]
**What would you like to be added**:

I would like to add a plugin option of `dnstap` to filter out certain messages.
Such configuration might be based on the [message type](https://github.com/dnstap/dnstap.pb/blob/1061e3ed4430f68a0adb87eecadbb9208e7b51dd/dnstap.proto#L156-L228) of dnstap Message. But, it would be better for our usecase if there's a way to limit the messages to only the successful client responses (the one with RcodeSuccess) since we are only interested in the successful client responses. The latter can be complex and may result in a difficult API, so I am open to discuss the option API design here. I would appreciate it if anyone can enlighten me on the existing "filtering" API design if there's already such thing in another CoreDNS plugin.

**Why is this needed**:

Currently, dnstap plugin sends three [message type](https://github.com/dnstap/dnstap.pb/blob/1061e3ed4430f68a0adb87eecadbb9208e7b51dd/dnstap.proto#L156-L228):

* `FORWARDER_QUERY`: is sent by `forwarder` plugin whenever dnstap plugin is enabled.
* `CLIENT_RESPONSE`: is sent when the wrapped `WriteMsg` is called.
* `CLIENT_QUERY`: is sent when Dnstap.Serve is called.

Even though the dnstap is [designed](https://dnstap.info/Architecture/) to minimize the impacts on the query processing critical path, it would be better if there's a way to configure which message is supposed to get sent to dnstap upstream servers to minimize the unnecessary CPU/memory pressure on CoreDNS process.

I am happy to work on this by myself once approved.

**Comment by rdrozhdzh** [comment]
This may be partially related to https://github.com/coredns/coredns/issues/4198

**Comment by mathetake** [comment]
@rdrozhdzh thanks, that issue looks almost the same as this one. More importantly, I didn't know the fact that the similar configuration existed before. I will go ahead and open a PR soon, and will ping you there.

**Comment by mathetake** [comment]
https://github.com/coredns/coredns/pull/6643
