### ISSUE TITLE
etcd connection leakage when reload

### ISSUE THREAD

**Issue by Yukielz** [miekg/coredns#6645]
**What happened**:
etcd connection leakage when reload.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
use etcd plugin and modify corefile to trigger reload.
**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: v1.11.1
- Corefile:
```yaml
  .:53 {
      errors
      health {
          lameduck 5s
      }
      ready
      etcd com {
          path /skydns/ka2
          endpoint http://192.168.0.1:2379 http://192.168.0.2:2379 http://192.168.0.3:2379
          fallthrough
      }
      cache 10
      loop
      reload
      log
      loadbalance
  }
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by yangsenzk** [comment]
This bug can be reproduced. The **process_open_fds** metric of backend ETCD will be continuously increased by modify corefile that triggered coredns reload.

**Comment by Yukielz** [comment]
add more infomation:
when i add `log` to tigger coredns reload, it was obvious that the old connection was not released
![image](https://github.com/coredns/coredns/assets/56835284/74042e3d-bd29-4251-b5a7-a74f3fd12289)

**Comment by Yukielz** [comment]
@chrisohaver cc

**Comment by Yukielz** [comment]
@chrisohaver  Hi, chrisohaver. can you check this issue and review this [pr](https://github.com/coredns/coredns/pull/6646).
To avoid this, we must restart all coerdns pod when etcd endpoints changed.

**Comment by Yukielz** [comment]
#6646
