### ISSUE TITLE
CoreDNS fails on resolving external DNS

### ISSUE THREAD

**Issue by vvash94** [miekg/coredns#6700]
**What happened**:

**What you expected to happen**:
CoreDNS should be able to correctly resolve DNS.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Kubernetes 1.29.3 setup using KubeADM. CNI: Cilium (kube-proxy replacement mode)

- the version of CoreDNS: v1.11.1
- Corefile:

- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by Mattes83** [comment]
Can you please tell what the issue was? I have the same error

**Comment by vvash94** [comment]
@Mattes83 In our case it was Cilium which was the culprit. We had to redeploy it to fix the issue.
