### ISSUE TITLE
Question: Does CoreDNS support plugins to retrieve the original DNS requests containing mixed-case domain names?

### ISSUE THREAD

**Issue by hjsjhn** [miekg/coredns#6717]
Hello CoreDNS dev team! Im currently developing a CoreDNS plugin and aiming to check 0x20 bit encoding functionality by inspecting the case of domain names in DNS requests. However, I've noticed that **the DNS requests I can obtain within the plugin are all converted to lowercase**. Could you please tell me whether CoreDNS supports obtaining the original DNS requests with domain names that have not been converted to lowercase within the plugin? Many thanks :D

**Comment by chrisohaver** [comment]
How are you getting the requested name?

**Comment by hjsjhn** [comment]
> How are you getting the requested name?

Using the CoreDNS request lib:

``` Go
import (
	"net"
	"unicode"
	"context"
	"github.com/coredns/coredns/plugin"
	clog "github.com/coredns/coredns/plugin/pkg/log"
	"github.com/coredns/coredns/request"
	"github.com/miekg/dns"
)

var log = clog.NewWithPlugin("encoding20")

// speific id for 0x20 encoding response
type Sid struct {
	Next plugin.Handler
	Data string
}

func (m Sid) ServeDNS(ctx context.Context, w dns.ResponseWriter, r *dns.Msg) (int, error) {
	state := request.Request{W: w, Req: r}

	log.Infof("[%s]Request for %s", m.Name(), state.Name())
	// Check if the domain name in the DNS request is a mixed case request
	if !isLower(state.Name()) {
		// If it is a mixed case domain name request, return a special result IP
		log.Infof("Returning special IP for %s", state.Name())
		responseIP := m.Data
		return m.returnSpecialIP(w, r, responseIP)
	}

	// If it is not a mixed case domain name request, continue passing the request to the next plugin
	return plugin.NextOrFailure(m.Name(), m.Next, ctx, w, r)
}

...
```

I'm totally new to this. Id be appreciated if you could tell me if there are any errors in the code.

**Comment by chrisohaver** [comment]
state.Qname() returns the raw name received in the request.

**Comment by hjsjhn** [comment]
It works well with `state.QName()` now. Thank you!
