### ISSUE TITLE
Failed to download CoreDNS on a IPv6-only server

### ISSUE THREAD

**Issue by marek22k** [miekg/coredns#6756]
**What happened**:

The CoreDNS releases cannot be downloaded on an IPv6-only node because GitHub does not have IPv6.

**What you expected to happen**:

I can download the CoreDNS releases without any problems.

**How to reproduce it (as minimally and precisely as possible)**:

```
wget https://github.com/coredns/coredns/releases/download/v1.11.1/coredns_1.11.1_linux_amd64.tgz
```

**Comment by SuperQ** [comment]
This is a limitation of GitHub. They have not deployed IPv6 yet.

**Comment by marek22k** [comment]
Why did you close the issue? The problem still exists.

**Comment by mariuskimmina** [comment]
It's not a CoreDNS problem, it's a Github problem
