### ISSUE TITLE
Coredns forward upstream nameserver is invalid when policy is round_robin

### ISSUE THREAD

**Issue by ATAO-Y** [miekg/coredns#6782]
**What happened**:  coredns forward all request to the first nameserver1 in cluster

**What you expected to happen**:  

50% forward request nameserver1
50% forward request nameserver2

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.6.7
- Corefile:
.:53 {
    errors
    health {
      lameduck 5s
    }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf {
        policy round_robin
    }
    cache 30
    loop
    reload
    loadbalance
}

/etc/resolv.conf

nameserver xxx.xx.xxx.21
nameserver xxx.xx.xxx.22

- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
Can you reproduce the issue in the latest release?

**Comment by ATAO-Y** [comment]
@chrisohaver The coredns version v1.7.0 is ok.
