### ISSUE TITLE
CoreDNS returns REFUSED instead of SERVFAIL when no server block matches

### ISSUE THREAD

**Issue by nnmin-aws** [miekg/coredns#6805]
**What happened**:
CoreDNS returned REFUSED when no server block matches, hence DNS client didn't try next name server
**What you expected to happen**:
CoreDNS should return SERVFAIL when no server block matches, hence DNS client didn't try next name server. like https://coredns.io/2017/06/08/how-queries-are-processed-in-coredns/#:~:text=If%20no%20server,is%20returned. mentioned
**How to reproduce it (as minimally and precisely as possible)**:
corefile like below
example.com:53 {
    bind 127.0.0.2
    forward . 10.0.0.2
    log
}

**Anything else we need to know?**:

**Environment**:
Amazon Linux
- the version of CoreDNS:
- Corefile:
```
example.com:53 {
    bind 127.0.0.2
    forward . 10.0.0.2
    log
}
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by chrisohaver** [comment]
This is as designed. You can create a catch all block `.` with template plugin that returns servfail if you want different behavior.

**Comment by nnmin-aws** [comment]
thank you for the reply!
