### ISSUE TITLE
I have turned off kubernetes fallthrough but the behavior is not as expected

### ISSUE THREAD

**Issue by Goend** [miekg/coredns#6855]
**What happened**:
I used coredns without an upstream dns resolution server and removed the fallthrough part of the kubernetes plugin. However, the error was still reported 
```
[ERROR] plugin/errors: 2 _grpc._tcp.thanos-ruler-operated. SRV: plugin/kubernetes: no next plugin found
```

**What you expected to happen**:
return nxdomain status or give real error plugin

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
- CoreDNS-1.10.1
- Corefile:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
      addonmanager.kubernetes.io/mode: EnsureExists
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        acl githubusercontent.com grafana.com {
          filter
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
        }
        hosts /etc/add-hosts/node-hosts . { 
           10.240.2.27  domain1
           10.240.0.4  domain2
           fallthrough .
        }
        import /etc/custom/customdns.conf
        prometheus :9153
        cache 30
        reload
        loadbalance
        }
```
- logs, if applicable:
```
[root@xx ~]# kubectl  -n kube-system logs coredns-jm8bw
.:53
[INFO] plugin/reload: Running configuration SHA512 = a8f2d8d554758780452bacfaf3032a1748d56b6efdf6f0a35b69a5c987b67ca0dedbf15dffc30fffbf5d852798539cd87effbe3d19b423ad30fc5a97653c4e31
CoreDNS-1.10.1
linux/arm64, go1.20, 055b2c3
[ERROR] plugin/errors: 2 _grpc._tcp.thanos-ruler-operated. SRV: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 _grpc._tcp.thanos-ruler-operated. SRV: plugin/kubernetes: no next plugin found
[ERROR] plugin/errors: 2 _grpc._tcp.thanos-ruler-operated. SRV: plugin/kubernetes: no next plugin found

```
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by Goend** [comment]
maybe it's my bad,because kubernetes zones  is different from my request,how to set a default nxdomain  responces for  some domain which other plugin cann't give a result .I don’t want this metrics increase
```
coredns_dns_responses_total{plugin="",rcode="SERVFAIL",server="dns://:53",view="",zone="."} 
```
 because it will trigger a prometheus alarm.
I can't use acl all the time because I can't anticipate every possible situation.

**Comment by chrisohaver** [comment]
If you know your service and pod subnets, you can move the Kubernetes plugin into its own server block for the zones cluster.local and the reverse domains (which can be expressed as cidrs for convenience). In the existing root block, you can use the template plugin to respond with NXDOMAIN for all requests. 

another way is to add a forward plugin that forwards to 127.0.0.1 over an alternate port, add a server block that listens on that port, and in that block place a template plugin configured to respond with NXDOMAIN for all requests.

**Comment by Goend** [comment]
> If you know your service and pod subnets, you can move the Kubernetes plugin into its own server block for the zones cluster.local and the reverse domains (which can be expressed as cidrs for convenience). In the existing root block, you can use the template plugin to respond with NXDOMAIN for all requests.
> 
> another way is to add a forward plugin that forwards to 127.0.0.1 over an alternate port, add a server block that listens on that port, and in that block place a template plugin configured to respond with NXDOMAIN for all requests.

Thanks a lot.I will try it,especially the second option.

**Comment by Goend** [comment]
> If you know your service and pod subnets, you can move the Kubernetes plugin into its own server block for the zones cluster.local and the reverse domains (which can be expressed as cidrs for convenience). In the existing root block, you can use the template plugin to respond with NXDOMAIN for all requests.
> 
> another way is to add a forward plugin that forwards to 127.0.0.1 over an alternate port, add a server block that listens on that port, and in that block place a template plugin configured to respond with NXDOMAIN for all requests.
