### ISSUE TITLE
Update Base Image to Debian 12 in Official Docker Image

### ISSUE THREAD

**Issue by Xdynix** [miekg/coredns#6903]
Hello CoreDNS maintainers,

I would like to ask if you could consider updating the base image of the official CoreDNS Docker image to Debian 12. Currently, the image is based on Debian 11, which has reached the end of its support lifecycle. Upgrading to Debian 12 would be beneficial for users who require a more secure image with fewer vulnerabilities, eliminating the need for them to create their own custom Dockerfile for this purpose.

As mentioned in #6649, there is an existing Pull Request #6416 that includes this exact update. It would be greatly appreciated if that PR could be reviewed and merged.

**Comment by SuperQ** [comment]
I think you meant https://github.com/coredns/coredns/pull/6416.

**Comment by Xdynix** [comment]
> I think you meant #6416.

Ah yes you're absolutely right, my finger slipped. 🤦

**Comment by Xdynix** [comment]
Closed with #6968.
