### ISSUE TITLE
Cannot insert kubernetes/client-namespace in regex

### ISSUE THREAD

**Issue by vrbgtrhr** [miekg/coredns#6936]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        metadata
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        rewrite name regex (.+)\.test1\.test2\.com {1}.{kubernetes/client-namespace}.svc.cluster.local
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
```

doing a nslookup from a pod i get:
```
** server can't find <>.test1.test2.com: NXDOMAIN

** server can't find <>.test1.test2.com: NXDOMAIN
```

**Comment by chrisohaver** [comment]
To use `kubernetes/client-namespace` metadata, you must specify `pods verified` in the kubernetes plugin, as per outlined in the the kubernetes plugin docs:

https://github.com/coredns/coredns/tree/master/plugin/kubernetes#metadata

Note that when using `pods verified`, coredns requires signifcantly more memory, and puts significantly more pressure on the K8s API.

**Comment by vrbgtrhr** [comment]
nothing change using `pods verified`

**Comment by chrisohaver** [comment]
> nothing change using `pods verified`

Can you confirm that the other requirement mentioned in the docs is satisfied? You can enable logging to check that source IP matches the client pod IP.

**Comment by vrbgtrhr** [comment]
i get this in teh logs:
```
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:33004->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 test.com. AAAA: read udp 10.42.0.2:39761->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 test.com. A: read udp 10.42.0.2:39737->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 test.com. A: read udp 10.42.0.2:51253->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 test.com. AAAA: read udp 10.42.0.2:36141->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:54698->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:49630->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:40927->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:58009->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:34509->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:43612->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:40284->8.8.8.8:53: i/o timeout
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:41353->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:38852->8.8.8.8:53: i/o timeout
```

**Comment by chrisohaver** [comment]
> i get this in teh logs:
> 
> ```
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:33004->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 test.com. AAAA: read udp 10.42.0.2:39761->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 test.com. A: read udp 10.42.0.2:39737->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 test.com. A: read udp 10.42.0.2:51253->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 test.com. AAAA: read udp 10.42.0.2:36141->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:54698->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:49630->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:40927->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:58009->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:34509->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:43612->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:40284->8.8.8.8:53: i/o timeout
> [WARNING] No files matching import glob pattern: /etc/coredns/custom/*.override
> [WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:41353->8.8.8.8:53: i/o timeout
> [ERROR] plugin/errors: 2 1047883516937311591.5075261204452179579. HINFO: read udp 10.42.0.2:38852->8.8.8.8:53: i/o timeout
> ```

You need to enable logging with the log plugin to see the client queries.

**Comment by vrbgtrhr** [comment]
i get a lot of this:

```
[INFO] 10.42.1.71:49858 - 63654 "AAAA IN mongodb.test1.test2.com.svc.cluster.local. udp 56 false 512" NXDOMAIN qr,aa,rd 149 0.00011523s
[INFO] 10.42.1.71:43044 - 39950 "AAAA IN mongodb.test1.test2.com.cluster.local. udp 52 false 512" NXDOMAIN qr,aa,rd 145 0.000078892s
[INFO] 10.42.1.71:43044 - 29707 "A IN mongodb.test1.test2.com.cluster.local. udp 52 false 512" NXDOMAIN qr,aa,rd 145 0.00011303s
[INFO] 10.42.1.71:45776 - 61028 "A IN mongodb.test1.test2.com. udp 38 false 512" NXDOMAIN qr,aa,rd 131 0.000068737s
[INFO] 10.42.1.71:45776 - 6248 "AAAA IN mongodb.test1.test2.com. udp 38 false 512" NXDOMAIN 
```qr,aa,rd 131 0.000114736s

**Comment by chrisohaver** [comment]
> i get a lot of this:
> 
> ```
> [INFO] 10.42.1.71:49858 - 63654 "AAAA IN mongodb.test1.test2.com.svc.cluster.local. udp 56 false 512" NXDOMAIN qr,aa,rd 149 0.00011523s
> [INFO] 10.42.1.71:43044 - 39950 "AAAA IN mongodb.test1.test2.com.cluster.local. udp 52 false 512" NXDOMAIN qr,aa,rd 145 0.000078892s
> [INFO] 10.42.1.71:43044 - 29707 "A IN mongodb.test1.test2.com.cluster.local. udp 52 false 512" NXDOMAIN qr,aa,rd 145 0.00011303s
> [INFO] 10.42.1.71:45776 - 61028 "A IN mongodb.test1.test2.com. udp 38 false 512" NXDOMAIN qr,aa,rd 131 0.000068737s
> [INFO] 10.42.1.71:45776 - 6248 "AAAA IN mongodb.test1.test2.com. udp 38 false 512" NXDOMAIN 
> ```qr,aa,rd 131 0.000114736s
> ```

That’s normal in Kubernetes.

Did you confirm that the remote ip in the log matches the pod ip of the client?

**Comment by vrbgtrhr** [comment]
if you mean this `10.42.1.71`. yes i confirm

**Comment by vrbgtrhr** [comment]
i found the solution:
`rewrite name regex (.+)\.test1\.test2\.com\.(.+)\.svc\.cluster\.local {1}.{2}.svc.cluster.local`
