### ISSUE TITLE
While load testing coredns and found unbalanced(uneven) traffic across pods.

### ISSUE THREAD

**Issue by YeshuGarg1** [miekg/coredns#6977]
![image](https://github.com/user-attachments/assets/f1b7bc60-7f4f-423f-8643-4c3996d2f038)

As you see above only 4 out of 15pods CPU spiked and rest were idle. Its causing latency as during peak times only few pods are actually in use.

**Comment by SuperQ** [comment]
This does not seem related to CoreDNS. This is a question for your computer platform and load balancing.

**Comment by chrisohaver** [comment]
This question is probably better directed to Kubernetes networking experts.  Kubernetes Service architecture distributes packets to pods. All coredns does is receive the packets it’s receives. 

Some load testing tools tend to construct requests in a way that makes k8s service to pod distribution unbalanced (eg static source port, or persistent connections).

**Comment by YeshuGarg1** [comment]
@chrisohaver I am using perf-tests (https://github.com/kubernetes/perf-tests/blob/master/dns/README.md). Is it the right tool to use? 

If yes, then i can look into the networking part.

**Comment by SuperQ** [comment]
Looking at that perf test, it deploys 4 load testing pods that are single-threaded instances of [dnsperf](https://github.com/DNSPerf/dnsperf). This is probably why your results look the way they do.

I recommend filing an upstream issue with the perf-tests project.

**Comment by YeshuGarg1** [comment]
That makes sense. Request from 4 instances taken by 4 coredns pods.

Q(noob ques)- Isn't k8s service responsible to load balance the requests between pods?

**Comment by SuperQ** [comment]
It is, but like was said above, depending on how the requests are done it can cause the balancing to be ineffective.

This is a problem for the upstream Kubernetes project to solve.
