### ISSUE TITLE
Filter nameserver forwarded to by forward plugin

### ISSUE THREAD

**Issue by jhcook** [miekg/coredns#6978]
**What would you like to be added**:

The ability to filter forward nameservers based on request origin IP address.

**Why is this needed**:

I have clusters distributed across multiple data centers. Each data center has resolvers. There are several third parties that use DNS load balancing with short TTL and results change quite rapidly. 

Due to filtering and TLS forgery detection RFC 6066 (TLS Extensions: Server Name Indication), we need the ability to filter nameserver selection on the requesting workload's IP address. This will solve the problem of DNS result mismatch and TLS connections terminated.

As a practical example, the following snippet would forward requests to 10.0.1.4 from 10.0.3.0/24 and requests to 10.0.2.4 from 10.0.4.0/24. Any requests from other addresses will be forwarded to 10.0.0.4, but a default should not be necessary.

```
. {
    forward . 10.0.1.4:53 {
        match net 10.0.3.0/24
    }
    forward . 10.0.2.4:53 {
        match net 10.0.4.0/24
    }
    forward . 10.0.0.4:53
}
```

I would appreciate if this functionality were added as it would make a lot of sense given these restrictions. And this level of flexibility makes a lot of sense in many situations. There are other limitations in cloud environments this would alleviate.

**Comment by chrisohaver** [comment]
You can achieve this with the _view_ plugin.

**Comment by jhcook** [comment]
Well yeah this seems to be what I'm looking for. I'm sorry for not finding this. It's certainly not a lack of trying!
