### ISSUE TITLE
I have a question about the regex feature.

### ISSUE THREAD

**Issue by donggyu-woo** [miekg/coredns#6984]
Hello All 👋

When enabling logging in coredns, is it possible to define a list of domains that will not be logged based on a REGEX?

**Comment by chrisohaver** [comment]
Not directly. But you can use the view plugin to match those domains in a second server block that doesn’t have the log plugin in it.

**Comment by chrisohaver** [comment]
If you can match the domains without regex, then the view plugin isn’t needed.  You’d  just need the second server block for those domains with log  plugin removed.

**Comment by donggyu-woo** [comment]
Hi, @chrisohaver 

I appreciate your quick answer. I'll take a look at what you've shared. 👍
