### ISSUE TITLE
Config change in 1.11.4?

### ISSUE THREAD

**Issue by defekkt** [miekg/coredns#6990]
My coredns docker stopped working properly and started responding with wrong A records to queries. 
Was there a config change from 1.11.3 to 1.11.4?
It started responding with the querier IP address as A record to *all* queries. 

Tried enabling debug, but did not show additional infos.

**Comment by chrisohaver** [comment]
No intentional config changes in patch releases.

**Comment by chrisohaver** [comment]
Possible that your coredns is not finding its corefile, and is defaulting to the “whoami” plugin when there is no corefile.

**Comment by defekkt** [comment]
there was no change in my config from 1.11.3 to 1.11.4:
Corefile
```
mydomain.com:53 {
    reload 10s
    log
    errors
    debug
    file /etc/coredns/db.mydomain.com
}
```

**Comment by defekkt** [comment]
solved!
Was the docker-compose definition. apparently there was some change there? used to be enough to just have the Corefile in `/home/nonroot/Corefile` but apparently this changed? now I added:
`command: -conf /home/nonroot/Corefile` and it works again.

it would be nice to have some kind of message/output if the Corefile can not be loaded.

**Comment by chrisohaver** [comment]
> it would be nice to have some kind of message/output if the Corefile can not be loaded.

I was also thinking this. It’s an odd default behavior, and IMO warrants a warning in the log that it’s happening.

**Comment by chrisohaver** [comment]
This looks like fallout from the run-as-non-root change. We should put a note of it in the release notes.
